SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
	.string "Hello! I am MR. ICE BEAM.\p"
	.string "Here - have a TM!\n$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
	.string "{PLAYER} received TM24\n"
	.string "from MR. ICE BEAM.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
	.string "You already know, don't you?\n"
	.string "TM24 is THUNDERBOLT.\p"
	.string "I give it in memory of my\n"
	.string "father, Mr. FLAMETHROWER.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "Where do you plan to put this?\n"
    .string "You've no room.$"

