CeladonCity_Condominiums_1F_Text_Meowth::
    .string "MEOWTH: Meow!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "You shouldn't spend all your money\n"
    .string "on drinks.\p"
    .string "Try this instead.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
	.string "After you drink this TOXIC SLUDGE,\n"
	.string "you'll never be thirsty again!$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
	.string "Oh, hello, dearie.\n"
	.string "Was my TOXIC SLUDGE helpful?\p"
	.string "By the way, dear. Are you, by any\n"
	.string "chance, from PALLET TOWN?\p"
	.string "A girl from PALLET TOWN, DAISY,\n"
	.string "she buys TOXIC SLUDGE every day.\p"
	.string "I hear she uses it on the POKeMON\n"
	.string "she treats.$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
	.string "Oh, hello, dearie.\n"
	.string "Was my TOXIC SLUDGE helpful?\p"
	.string "By the way, dear. Are you, by any\n"
	.string "chance, from PALLET TOWN?\p"
	.string "A girl from PALLET TOWN, DAISY,\n"
	.string "she buys TOXIC SLUDGE every day.\p"
	.string "I hear she uses it on the POKeMON\n"
	.string "she treats.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "CLEFAIRY: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "NIDOTRAN♂: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
	.string "There's graffiti on the wall…\p"
	.string "{PLAYER} added a moustache!\n$"

