CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
	.string "Wha?\n"
	.string "This isn't my house!\p"
	.string "Where am I?\n$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFushcia::
	.string "The GYM here in CELADON also\n"
	.string "doubles as our local LGBT Center.\p"
	.string "It's always an affirming and\n"
	.string "uplifting place to be!$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
	.string "I've been seeing some strong\n"
	.string "trainers coming in and out of here.\p"
	.string "I even saw that one guy.\n"
	.string "What's his name?\p"
	.string "Larry? Jerry?\n"
	.string "Something like that.$"

