FushciaCity_Text_DidYouTrySafariGame::
    .string "Did you try the SAFARI GAME?\p"
    .string "There are some rare POKéMON that\n"
    .string "can only be caught there.$"

FushciaCity_Text_SafariZoneZooInFront::
    .string "The SAFARI ZONE has a zoo in front\n"
    .string "of the entrance.\p"
    .string "Out back is the SAFARI GAME for\n"
    .string "catching POKéMON.$"

FushciaCity_Text_WheresSara::
    .string "ERIK: Where's SARA?\n"
    .string "I said I'd meet her here.$"

FushciaCity_Text_ItemBallInThere::
    .string "That item ball in there…\n"
    .string "Were you wanting that?\p"
    .string "Me, too!\n"
    .string "…Huh? That's a POKéMON?$"

FushciaCity_Text_CitySign::
    .string "FUSHCIA CITY\n"
    .string "Behold! It's Passion Pink!$"

FushciaCity_Text_SafariZoneSign::
    .string "POKéMON PARADISE\n"
    .string "SAFARI ZONE$"

FushciaCity_Text_SafariGameSign::
    .string "SAFARI GAME\n"
    .string "POKéMON-U-CATCH!$"

FushciaCity_Text_WardensHomeSign::
    .string "SAFARI ZONE\n"
    .string "WARDEN'S HOME$"

FushciaCity_Text_SafariZoneOfficeSign::
    .string "POKéMON PARADISE!\n"
    .string "Welcome to the SAFARI ZONE!\l"
    .string "SAFARI ZONE OFFICE$"

FushciaCity_Text_GymSign::
    .string "FUSHCIA CITY POKéMON GYM\n"
    .string "LEADER: KOGA\l"
    .string "The Poisonous Ninja Master$"

FushciaCity_Text_ChanseySign::
    .string "Name: CHANSEY\n"
    .string "Catching one is all up to chance.$"

FushciaCity_Text_VoltorbSign::
    .string "Name: VOLTORB\n"
    .string "The very image of a POKé BALL.$"

FushciaCity_Text_KangaskhanSign::
    .string "Name: KANGASKHAN\p"
    .string "A maternal POKéMON that raises its\n"
    .string "young in a pouch on its belly.$"

FushciaCity_Text_SlowpokeSign::
    .string "Name: SLOWPOKE\n"
    .string "Friendly and very slow moving.$"

FushciaCity_Text_LaprasSign::
    .string "Name: LAPRAS\n"
    .string "AKA the king of the seas.$"

FushciaCity_Text_OmanyteSign::
    .string "Name: OMANYTE\n"
    .string "An extremely rare POKéMON that was\l"
    .string "regenerated from a fossil.$"

FushciaCity_Text_KabutoSign::
    .string "Name: KABUTO\n"
    .string "An extremely rare POKéMON that was\l"
    .string "regenerated from a fossil.$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FushciaCity_Text_Ellipsis::
    .string "……$"

Text_SubstituteTeach::
    .string "Aww, I wish I was a KANGASKHAN\n"
    .string "baby.\p"
    .string "I'd love to be a substitute for the\n"
    .string "baby…\p"
    .string "And snuggle in the mother\n"
    .string "KANGASKHAN's belly pouch.\p"
    .string "But only POKéMON can use the\n"
    .string "technique SUBSTITUTE…\p"
    .string "Want me to teach SUBSTITUTE to\n"
    .string "one of your POKéMON?$"

Text_SubstituteDeclined::
    .string "Oh, really?\n"
    .string "SUBSTITUTE seems so fun…$"

Text_SubstituteWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "SUBSTITUTE?$"

Text_SubstituteTaught::
    .string "Boy, what I'd give to crawl inside\n"
    .string "a KANGASKHAN belly pouch…$"

FushciaCity_Text_MyFatherIsGymLeader::
    .string "My father is the GYM LEADER of\n"
    .string "this town.\p"
    .string "I'm training to use POISON POKéMON\n"
    .string "as well as my father.$"

