ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
	.string "Everyone calls me the RUIN MANIAC.\n"
	.string "I don't care what they call me.\p"
	.string "I'll just keep on chipping away at\n"
	.string "the rock wall little by little.\p"
	.string "D'ya know why? I'm a RUIN MANIAC\n"
	.string "who is fascinated by the unknown.\p"
	.string "I'll keep digging, and you keep\n"
	.string "catching POKéMON.\l"
	.string "Such is the way of things.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
	.string "Yay, I dug a tunnel!\n$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
    .string "That's a NUGGET!\p"
    .string "I can't give you any nuggets of\n"
    .string "wisdom, so that'll have to do!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .string "Whoops, your BAG is crammed full!\n"
    .string "I'll give this to you later.$"

