MtMoon_1F_Text_MarcosIntro::
    .string "WHOA!\n"
    .string "You shocked me!\l"
    .string "…Oh, you're just a kid!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "Wow!\n"
    .string "Shocked again!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "Kids like you shouldn't be\n"
    .string "wandering around here in the dark.$"

MtMoon_1F_Text_JoshIntro::
    .string "TENTACOOL stops you from running,\n"
    .string "but…$"

MtMoon_1F_Text_JoshDefeat::
    .string "Losing stinks!\n"
    .string "It's so uncool.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "TENTACOOL stops you from running.\p"
    .string "I think maybe he just wants to\n"
    .string "run too…$"

MtMoon_1F_Text_MiriamIntro::
    .string "Wow! It's way bigger in here than\n"
    .string "I thought!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "Oh!\n"
    .string "I lost it!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "How do you get out of here?\n"
    .string "It's so big, I may get lost.$"

MtMoon_1F_Text_JovanIntro::
    .string "What!?\n"
    .string "This game is awful!$"

MtMoon_1F_Text_JovanDefeat::
    .string "Ass!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "This game fucking sucks!$"

MtMoon_1F_Text_IrisIntro::
    .string "Gah!\n"
    .string "I'm I'm stuck in place!$"

MtMoon_1F_Text_IrisDefeat::
    .string "I lost?$"

MtMoon_1F_Text_IrisPostBattle::
    .string "The TENTACOOL everywhere are\n"
    .string "stopping me from running.\l"
    .string "Now everyone can look at me!$"

MtMoon_1F_Text_KentIntro::
    .string "Suspicious layers are in the cave.\n"
    .string "What about you?$"

MtMoon_1F_Text_KentDefeat::
    .string "You got me!$"

MtMoon_1F_Text_KentPostBattle::
    .string "Downstairs, there's a bunch of\n"
    .string "lawyers taking a lay of this place.\p"
    .string "Be careful if you have any\n"
    .string "copyrighted material on you!$"

MtMoon_1F_Text_RobbyIntro::
    .string "You need to go through this cave\n"
    .string "to get to CERULEAN CITY.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "I lost.$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "ZUBAT is tough!\n"
    .string "But if you can catch one, you'll\l"
    .string "be able to count on it.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "Beware!\n"
    .string "TENTACOOL is annoying!\p"
    .string "Be sure to have a FLYING-TYPE!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "I hear there's someone in this cave\n"
    .string "with an invincible POKéMON\p"
    .string "It's only vulnerable to moves that\n"
    .string "are SUPER-EFFECTIVE against it.$"
