VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "Won't you admire my PIKACHU's\n"
    .string "adorable tail?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "I wasnted a RAICHU, so my friend\n"
    .string "offered to give me one.\p"
    .string "I'm not sure either of us expected\n"
    .string "what happened next.$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "I found this strange POKéMON out\n"
    .string "in the wild!\p"
    .string "It seems oddly different from other\n"
    .string "POKéMON, though.$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "Oh, dear!\p"
    .string "My SEEL is far more attractive.\n"
    .string "By double, I would say.$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "MEOWTH: Chu! Pikachu!\p"
    .string "MEOWTH is reminiscing about\n"
    .string "its childhood.$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "SEAL: Arf! Arf!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "Welcome to the POKéMON Fan Club!\p"
    .string "This is where we talk about our\n"
    .string "favorite franchise ever!\p"
    .string "Would you like to hear me talk\n"
    .string "about the series I love the most?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "Good!\n"
    .string "Then listen up!\p"
    .string "POKéMON has been going downhill\n"
    .string "ever since Generation 8!\p"
    .string "Those games removed the National\n"
    .string "POKéDEX! I can't believe it!\p"
    .string "Gen 7 was also awful - it was\n"
    .string "nothing but cutscenes!\p"
    .string "Gen 6 was constant nostalgia\n"
    .string "pandering, and they didn't give\l"
    .string "us the Third Version we deserve!\p"
    .string "Gen 5 totally sucked - the new\n"
    .string "POKéMON were awful!\p"
    .string "Gen 4 was extremely slow, and Gen\n"
    .string "3 you couldn't transfer POKéMON!\p"
    .string "Gen 2 also sucked! The level curve\n"
    .string "was awful!\p"
    .string "Anyway, I love the POKéMON series!\p"
    .string "Thanks for listening to me talk\n"
    .string "about my biggest love. Take this!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER} received a BIKE VOUCHER\n"
    .string "from the CHAIRMAN.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "Take that BIKE VOUCHER to the\n"
    .string "BIKE SHOP in CERULEAN CITY.\p"
    .string "Exchange that for a BIKE,\n"
    .string "free of charge!\p"
    .string "Don't worry, I have a POKéMON\n"
    .string "that can fly me anywhere.\p"
    .string "Which POKéMON is it?\n"
    .string "Uhh…\p"
    .string "I'll leave you to discover that\n"
    .string "on your own!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "Oh. Come back when you want to\n"
    .string "hear my story!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "Hello, {PLAYER}!\p"
    .string "Did you come see me about\n"
    .string "POKéMON again?\p"
    .string "No?\n"
    .string "Too bad!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "Make room for this!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "Our CHAIRMAN is very vocal about\n"
    .string "POKéMON.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "Yuck!\n"
    .string "Shouldn't have looked!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "If someone brags, brag right back!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "Our CHAIRMAN really does adore his\n"
    .string "POKéMON.\p"
    .string "But the person who is most liked by\n"
    .string "POKéMON is DAISY, I think.$"
