PokemonLeague_LancesRoom_Text_Intro::
	.string "MAY: Hi, {PLAYER}, long time no see!\p"
	.string "While I was searching for other\n"
	.string "POKéMON, my POKéMON grew stronger.\p"
	.string "So…\n"
	.string "How about a little battle?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LancesRoom_Text_RematchIntro::
    .string "Ah!\n"
    .string "So, you've returned, {PLAYER}!\p"
    .string "I lead the ELITE FOUR.\p"
    .string "You can call me LANCE the dragon\n"
    .string "TRAINER.\p"
    .string "You know that dragons are\n"
    .string "mythical POKéMON.\p"
    .string "They're hard to catch and raise,\n"
    .string "but their powers are superior.\p"
    .string "They're virtually indestructible.\n"
    .string "There's no being clever with them.\p"
    .string "Well, are you ready to lose?\p"
    .string "Your LEAGUE challenge ends with\n"
    .string "me, {PLAYER}!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LancesRoom_Text_Defeat::
	.string "Yikes!\n"
	.string "You're better than I expected!$"

PokemonLeague_LancesRoom_Text_PostBattle::
	.string "MAY: I know it's a little silly\n"
	.string "coming from me, but I think you\l"
	.string "should train a lot harder.\p"
	.string "I mean, your STARTER isn't even\n"
	.string "fully evolved yet!\l"
	.string "Could you imagine?$"

