PewterCity_Museum_1F_Text_Its50YForChildsTicket::
    .string "Yes, yes.\n"
    .string "It's ¥10,000 for a child's ticket.\p"
    .string "Would you like to come in?$"

PewterCity_Museum_1F_Text_ComeAgain::
    .string "Gotta keep up with inflation!$"

PewterCity_Museum_1F_Text_Right50YThankYou::
    .string "Oh, whoops.\p"
    .string "I think I added a few 0's to\n"
    .string "that price tag by accident.\l"
    .string "Com on in!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .string "You don't have enough money.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .string "Please enjoy yourself.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
    .string "Y'know I only ever wanted\n"
    .string "to be a gardener.\p"
    .string "I guess this is just what that\n"
    .string "entails nowadays.$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
    .string "AMBER contains the genetic matter\n"
    .string "of ancient POKéMON.\p"
    .string "There's a LAB somewhere trying to\n"
    .string "resurrect POKéMON from AMBER.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
    .string "AMBER is actually sap, that gooey\n"
    .string "stuff that oozes from trees.\p"
    .string "The ancient sap fossilized over\n"
    .string "time to become rock-hard AMBER.$"

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround::
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .string "KABUTOPS, eh?\p"
    .string "I hear scientists are working on a\n"
    .string "mechanical POKéMON just like it.$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .string "A lovely piece of AMBER!\n"
    .string "I'm sure they won't mind...$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
    .string "{PLAYER}  stole the OLD AMBER\n"
    .string "from the display!$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .string "Ssh!\n"
    .string "Get the OLD AMBER checked!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .string "You don't have space for this.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .string "We have two fossils of rare,\n"
    .string "prehistoric POKéMON on exhibit.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .string "There is a beautiful piece of\n"
    .string "AMBER in a clear gold color.$"

PewterCity_Museum_1F_Text_AerodactylFossil::
    .string "AERODACTYL Fossil\n"
    .string "A primitive and rare POKéMON.$"

PewterCity_Museum_1F_Text_KabutopsFossil::
    .string "KABUTOPS Fossil\n"
    .string "A threat to UU matches.$"

