VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "I'm getting her SPEAROW to fly a\n"
    .string "letter to SAFFRON in the north.$"

VermilionCity_House3_Text_Pidgey::
    .string "SPEAROW: Craaaw!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Dear PIPPI,\n"
    .string "I hope to see you soon.\p"
    .string "Here in VERMILLION, we're\n"
    .string "facing major paper shortages.\p"
    .string "Sadly, I had to write this letter\n"
    .string "on an NES.\p"
    .string "I hope you are doing well!$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "You wanna know how I got a\n"
    .string "SPEAROW?\p"
    .string "I hatched it myself from an egg!$"

