Text_SeismicTossTeach::
    .string "The secrets of space…\n"
    .string "The mysteries of earth…\p"
    .string "There are so many things about\n"
    .string "which we know so little.\p"
    .string "But that should spur us to study\n"
    .string "harder, not toss in the towel.\p"
    .string "The only thing you should toss…\p"
    .string "Well, how about SEISMIC TOSS?\n"
    .string "Should I teach that to a POKéMON?$"

Text_SeismicTossDeclined::
    .string "Is that so?\n"
    .string "I'm sure you'll be back for it.$"

Text_SeismicTossWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "SEISMIC TOSS?$"

Text_SeismicTossTaught::
    .string "I hope you won't toss in the towel.\n"
    .string "Keep it up.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "MOON STONE, huh?\n"
    .string "Those are extremely rare!\p"
    .string "I hear you can't even find them\n"
    .string "in MT. MOON anymore!$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "I remember when they finally\n"
    .string "launched a rocked from the\l"
    .string "MOSSDEEP SPACE CENTER.\p"
    .string "It turns out the WHITE ROCK was the\n"
    .string "key all along!$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "This month, we're running a space\n"
    .string "exhibit.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string "I want a PIKACHU!\n"
    .string "It's so cute!\p"
    .string "I asked my daddy to catch me one!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "Sweetie, we have PIKACHU at home.\p"
    .string "...What do you mean, “EMOLGA isn't\n"
    .string "the same thing?”$"

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "It looks like a space shuttle, but\n"
    .string "it's actually a very fancy toaster.$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "There should be a MOON STONE here,\n"
    .string "but it appears to be missing.$"

