SafariZone_SecretHouse_Text_CongratsYouveWon::
    .string "Ah! Finally!\p"
    .string "You're the first person to reach\n"
    .string "the SECRET HOUSE!\p"
    .string "Although I made a campaign\n"
    .string "for our grand opening,\p"
    .string "I was getting worried that no one\n"
    .string "would win our campaign prize.\p"
    .string "Congratulations!\n"
    .string "You have won!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant::
    .string "{PLAYER} received HM03\n"
    .string "from the attendant!$"

SafariZone_SecretHouse_Text_ExplainSurf::
	.string "When we started the HIDDEN MACHINE\n"
	.string "promotion, almost no one got here.\l"
	.string "I nearly died of boredom!\p"
	.string "So, the higher-ups decided to do a\n"
	.string "bit of… remodeling.\p"
	.string "Now, getting to this here SECRET\n"
	.string "HOUSE is actually very easy!\p"
	.string "Unfortunately, that means now we're\n"
	.string "running short on supplies.\l"
	.string "We didn't really think it through.\p"
	.string "And because of our recent budget\n"
	.string "cuts, we can't even restock!\p"
	.string "Thus!\n"
	.string "Congratulations.\l"
	.string "You get our pity prize instead!\p"
	.string "Hope you have fun with it!\n$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
    .string "You don't have room for this\n"
    .string "fabulous prize!$"
