#ifndef GUARD_CONSTANTS_FAME_CHECKER_H
#define GUARD_CONSTANTS_FAME_CHECKER_H

#define FAMECHECKER_PALLET          0
#define FAMECHECKER_VIRIDIAN        1
#define FAMECHECKER_PEWTER        2
#define FAMECHECKER_MT_MOON        3
#define FAMECHECKER_CERULEAN      4
#define FAMECHECKER_VERMILION        5
#define FAMECHECKER_ROCK_TUNNEL         6
#define FAMECHECKER_LAVENDER      7
#define FAMECHECKER_CELADON       8
#define FAMECHECKER_FUSHCIA      9
#define FAMECHECKER_KANTO_SHORELINE       10
#define FAMECHECKER_SAFFRON      11
#define FAMECHECKER_GREAT_SEA       12
#define FAMECHECKER_GREAT_SEA_NORTH        13
#define FAMECHECKER_GREAT_SEA_WEST      14
#define FAMECHECKER_CINNABAR    15
#define NUM_FAMECHECKER_PERSONS 16

#define FCPICKSTATE_NO_DRAW    0
#define FCPICKSTATE_SILHOUETTE 1
#define FCPICKSTATE_COLORED    2

#endif //GUARD_CONSTANTS_FAME_CHECKER_H
