#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

//Add your mugshot constants here

#define MUGSHOT_CHAPTER1 0
#define MUGSHOT_BIKE_FRAME_1 1
#define MUGSHOT_BIKE_FRAME_2 2
#define MUGSHOT_BIKE_FRAME_3 3
#define MUGSHOT_BIKE_FRAME_4 4



#define MUGSHOT_KENYA_FRAME_1 5
#define MUGSHOT_KENYA_FRAME_2 6
#define MUGSHOT_KENYA_FRAME_3 7
#define MUGSHOT_KENYA_FRAME_4 8
#define MUGSHOT_KENYA_FRAME_5 9
#define MUGSHOT_KENYA_FRAME_6 10
#define MUGSHOT_KENYA_FRAME_7 11
#define MUGSHOT_KENYA_FRAME_8 12
#define MUGSHOT_KENYA_FRAME_9 13
#define MUGSHOT_KENYA_FRAME_10 14
#define MUGSHOT_KENYA_FRAME_11 15
#define MUGSHOT_KENYA_FRAME_12 16
#define MUGSHOT_KENYA_FRAME_13 17
#define MUGSHOT_KENYA_FRAME_14 18
#define MUGSHOT_KENYA_FRAME_15 19

#define MUGSHOT_CHAPTER7 20
#define MUGSHOT_CHAPTER7_2 21

#define MUGSHOT_BIKE_FRAME_1_SHINY 22
#define MUGSHOT_BIKE_FRAME_2_SHINY 23
#define MUGSHOT_BIKE_FRAME_3_SHINY 24
#define MUGSHOT_BIKE_FRAME_4_SHINY 25

#endif