#ifndef GUARD_CONSTANTS_ALOLAN_GROWLITHE_H
#define GUARD_CONSTANTS_ALOLAN_GROWLITHE_H

#define ALOLAN_GROWLITHE_VERMILION_CITY   0
#define ALOLAN_GROWLITHE_ONE_ISLAND       1
#define ALOLAN_GROWLITHE_TWO_ISLAND       2
#define ALOLAN_GROWLITHE_THREE_ISLAND     3
#define ALOLAN_GROWLITHE_FOUR_ISLAND      4
#define ALOLAN_GROWLITHE_FIVE_ISLAND      5
#define ALOLAN_GROWLITHE_SIX_ISLAND       6
#define ALOLAN_GROWLITHE_SEVEN_ISLAND     7
#define ALOLAN_GROWLITHE_CINNABAR_ISLAND  8
#define ALOLAN_GROWLITHE_NAVEL_ROCK       9
#define ALOLAN_GROWLITHE_BIRTH_ISLAND    10

#define ALOLAN_GROWLITHE_MORE           254

#endif //GUARD_CONSTANTS_ALOLAN_GROWLITHE_H
