Route23_Text_VictoryRoadGateSign::
    .string "VICTORY ROAD GATE -\n"
    .string "POKéMON LEAGUE$"

Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
	.string "Hi! Remember me?\n"
	.string "I'm one of PROF. OAK's AIDES.\p"
	.string "I was finally able to avoid the\n"
	.string "police on my way here.\p"
	.string "PROF. OAK entrusted me with the\n"
	.string "HM06, ROCK SMASH for you.\p"
	.string "I will give it as a reward if your\n"
	.string "POKéDEX has 151 species caught.\p"
	.string "So, {PLAYER}. Do you have at least\n"
	.string "151 species of POKéMON caught?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "{PLAYER} received HM06\n"
    .string "from the AIDE.$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "HM06 contains the hidden move\n"
    .string "ROCK SMASH.\p"
	.string "ROCK SMASH can break small rocks\n"
	.string "blocking your way.$"

