VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
    .string "Hey, kid!\n"
    .string "I'm the PHISHING GURU!\p"
    .string "Here, I'm doing a free giveaway!\n"
    .string "No strings attached!$"

VermilionCity_House1_Text_TakeThisAndFish::
    .string "Excellent!\n"
    .string "Take it!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
    .string "{PLAYER} received an GOOD ROD from\n"
    .string "the FISHING GURU.$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
    .string "Now if you want, I can actually\n"
    .string "upgrade that GOOD ROD for you!\l"
    .string "I'll give you a fancy SUPER ROD!\p"
    .string "All I need is your date of birth,\n"
    .string "social security, and credit card info!\l"
    .string "How about it?$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
    .string "Oh…\n"
    .string "That's so disappointing…$"

VermilionCity_House1_Text_HowAreTheFishBiting::
    .string "Hello there, {PLAYER}!\p"
    .string "How are the fish biting?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
    .string "Oh, no!\p"
    .string "I had a nice gift for you, but you\n"
    .string "have no room for it!$"

