LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .string "I'm searching for inexpensive copies\n"
    .string "of POKéMON FIRE RED Version.\p"
    .string "Hopefully I can find a good used\n"
    .string "copy here with an intact save file.$"


LavenderTown_Mart_Text_DidYouBuyRevives::
    .string "REVIVES don't work on dead\n"
    .string "POKéMON…$"


LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .string "I was playing POKéMON SILVER when\n"
    .string "suddenly the screen changed to a\l"
    .string "picture of me except I was dead\l"
    .string "and then photorealistic blood\l"
    .string "started to flow out of my…$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "この　あいだ　やまおくで\n"
    .string "きんのたまを　ひろい　ましてね！\p"
    .string "つかえない　しなもの　ですが\n"
    .string "うったら　なんと　5000¥でした$"
