PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .string "This looks like an NES, but it's\n"
    .string "actually a very fancy toaster.$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .string "It's a posted notice…\p"
    .string "If you're confused, ask for HELP!\n"
    .string "Press the L or R Button!\p"
    .string "This is definitely a feature that\n"
    .string "people wanted and will definitely\l"
    .string "not be annoying.$"
    
