gFameCheckerFlavorText_Pallet0:: @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hello, there!\n"
	.string "I am an OAK!$"

gFameCheckerFlavorText_Pallet1:: @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}His name is GARY, not {RIVAL}!\n"
	.string "Haven't you seen the TV show?$"

gFameCheckerFlavorText_Pallet2:: @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This looks like an NES, but it's\n"
	.string "actually a very fancy toaster.$"


gFameCheckerFlavorText_Pallet3:: @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}DAD: {PLAYER}!\n"
	.string "You should take a quick rest.$"

gFameCheckerFlavorText_Pallet4:: @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}That's my GS BALL!\n"
	.string "No, you can't have it.\p"
	.string "It's very important to the plot.\n"
	.string "I need to keep it safe!$"

gFameCheckerFlavorText_Pallet5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It is VERY strongly recommended that\n"
	.string "you complete the POKéDEX!\p"
	.string "Otherwise you'll miss out on\n"
	.string "a lot of the fun!$"

gFameCheckerFlavorText_Viridian0:: @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It appears that this is the\n"
	.string "last POTION in the known universe.\p"
	.string "Uh, I guess you can have it.\n$"

gFameCheckerFlavorText_Viridian1:: @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}…Huh? GARY? Who's that?\p"
	.string "My name is LARRY!\n$"

gFameCheckerFlavorText_Viridian2:: @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TRAINER TIPS!\p"
	.string "Press START to save the game!\n$"

gFameCheckerFlavorText_Viridian3:: @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "And thus, my MELTAN CANDY got\n"
	.string "scattered across all of KANTO!\p"
	.string "Come back to me again once\n"
	.string "you've collected all your BADGES.\l"
	.string "I'll help you narrow your search.$"

gFameCheckerFlavorText_Viridian4:: @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hi!\n"
	.string "Do you have MEWTWO?\p"
	.string "Wanna trade it for my RATTATA?\n$"

gFameCheckerFlavorText_Viridian5:: @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The MR. MIME outside are almost\n"
	.string "impossible to catch!\p"
	.string "Maybe if I had a special POKé Ball\n"
	.string "I could do it…$"

gFameCheckerFlavorText_Pewter0:: @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Helpful advice…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Think outside the box!\p"
	.string "Sometimes, an absurd solution\n"
	.string "might just be what you need.$"


gFameCheckerFlavorText_Pewter1:: @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "I hear if you log onto OAK's PC,\n"
	.string "he'll give some hints on what to do.\p"
	.string "You should try it!\n$"

gFameCheckerFlavorText_Pewter2:: @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}There's supposed to be an extremely\n"
	.string "rare POKéMON in that grass.\p"
	.string "I'd really love to find it, but that\n"
	.string "guy keeps spraying REPEL everywhere!$"
	
gFameCheckerFlavorText_Pewter3:: @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You'd better not be running in\n"
	.string "your normal shoes.\p"
	.string "If you are, I'll have to\n"
	.string "report you to the police!$"

gFameCheckerFlavorText_Pewter4:: @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "MOON STONE, huh?\n"
	.string "Those are extremely rare!\p"
	.string "I hear you can't even find them\n"
	.string "in MT. MOON anymore!$"

gFameCheckerFlavorText_Pewter5:: @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Look at this beautiful piece of\n"
	.string "AMBER we found!\p"
	.string "It's one of our finest specimens.\p"
	.string "…What?\n"
	.string "No, of course you can't have it!\l"
	.string "Why would you think you could?$"

gFameCheckerFlavorText_MtMoon0:: @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We, the DMCA, are copyright\n"
	.string "gangsters!\p"
	.string "We strike fear with our takedown!\n$"


gFameCheckerFlavorText_MtMoon1:: @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am SHORTS!\n"
	.string "I'm comfy and easy to wear!$"


gFameCheckerFlavorText_MtMoon2:: @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}So, wait. If all the TENTACOOL are\n"
	.string "in this cave…\p"
	.string "What does that mean for all the\n"
	.string "WATER routes?$"

gFameCheckerFlavorText_MtMoon3:: @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Excuse me!\n"
	.string "You looked at me, didn't you?\p"
	.string "Yup, you definitely looked\n"
	.string "at me.$"

gFameCheckerFlavorText_MtMoon4:: @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TENTACOOL stops you from running.\p"
	.string "I think maybe he just wants to\n"
	.string "run too…$"

gFameCheckerFlavorText_MtMoon5:: @ 0x81ADCEB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I expected to be able to stop\n"
	.string "you with my invincible KOFFING…\p"
	.string "Surely this will be the only time\n"
	.string "you fight someone with WONDER GUARD.$"

gFameCheckerFlavorText_Cerulean0:: @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where are we?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CERULEAN is known for its competitive\n"
	.string "scene!\p"
	.string "Whether it's battling to the north\n"
	.string "or playing the TCG here in town!$"

gFameCheckerFlavorText_Cerulean1:: @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Have you found any pieces of\n"
	.string "CANDY laying on the ground?\p"
	.string "I think there's one in every\n"
	.string "major area.$"

gFameCheckerFlavorText_Cerulean2:: @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}GARY? LARRY?\n"
	.string "Who's that?\p"
	.string "My name is JERRY!\n"
	.string "What are you talking about?$"

gFameCheckerFlavorText_Cerulean3:: @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where are we?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In order to get through that\n"
	.string "cave, I had to climb a waterfall!\p"
	.string "Maybe it would've been easier if\n"
	.string "I had a POKéMON to help…$"


gFameCheckerFlavorText_Cerulean4:: @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I wanna buy some RARE CANDY to\n"
	.string "help evolve my POKéMON, but I\l"
	.string "need more money!\p"
	.string "Maybe if I visited BILL again…\n$"


gFameCheckerFlavorText_Cerulean5:: @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
    .string "My EKANS evolved right away, but\n"
    .string "my ABRA won't no matter what!\p"
    .string "It seems most POKéMON are hitting\n"
    .string "their final form by Level 20.$"

gFameCheckerFlavorText_Vermilion0:: @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The S.S. ANNE normally arrives\n"
	.string "in VERMILLION around this time.\p"
	.string "It doesn't seem to have made it\n"
	.string "to the harbor, though…$"


gFameCheckerFlavorText_Vermilion1:: @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You wanna know how I got a\n"
	.string "SPEAROW?\p"
	.string "I hatched it myself from an egg!\n$"

gFameCheckerFlavorText_Vermilion2:: @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I gave the guy next door my\n"
	.string "TRAINER ID.\l"
	.string "He said he'd give me a cool prize.\p"
	.string "I think that might've been a bad\n"
	.string "idea…$"


gFameCheckerFlavorText_Vermilion3:: @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I had someone deliver a letter to\n"
	.string "my one friend a while back.\l"
	.string "I think he's in VIRIDIAN still?\p"
	.string "Someone should check on him to see\n"
	.string "if he received it.$"


gFameCheckerFlavorText_Vermilion4:: @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SURGE's POKéMON will destroy you\n"
	.string "if you're not prepared.\p"
	.string "If you want to keep yourself safe,\n"
	.string "you'll need proper eyewear.$"


gFameCheckerFlavorText_Vermilion5:: @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I must've parked my TRUCK somewhere\n"
	.string "in this city...\l"
	.string "Do you have any idea where it is?$"

gFameCheckerFlavorText_RockTunnel0:: @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Wait, wasn't there a POKéMON\n"
	.string "CENTER here a minute ago?\p"
	.string "Darn, that's inconvenient.\n$"


gFameCheckerFlavorText_RockTunnel1:: @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I found my ONIX in a cave, hidden\n"
	.string "on an island far, far away.$"

gFameCheckerFlavorText_RockTunnel2:: @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "If you ever catch a MAGNEMITE, do\n"
	.string "you think you could bring it here?\l"
	.string "That way, we can evolve together!$"


gFameCheckerFlavorText_RockTunnel3:: @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "I'm from the KANTO LIGHTHOUSE\n"
	.string "POWER GRID REPAIR SERVICE.\p"
	.string "I'm sure the folks down at the\n"
	.string "LIGHTHOUSE are back in business!$"

gFameCheckerFlavorText_RockTunnel4:: @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "My name is DAZZLE!\n"
	.string "And I collect STAR PIECES!\p"
	.string "So, guy, if you have any STAR PIECES\n"
	.string "I'll trade you a BADGE for them!$"

gFameCheckerFlavorText_RockTunnel5:: @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "I hear that sometimes when CLEFAIRY\n"
	.string "evolves, its SHADOW comes to life.$"

gFameCheckerFlavorText_Lavender0:: @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where are we?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This town is known as the players'\n"
	.string "grave site.\p"
	.string "Be careful listening to the music!\n$"


gFameCheckerFlavorText_Lavender1:: @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Welcome, young traveler\n"
	.string "I see you have an eye for rarities.\p"
	.string "I offer many wares that those in\n"
	.string "power may find… objectionable.$"


gFameCheckerFlavorText_Lavender2:: @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}HARRY: Yup, my RATICATE sure is\n"
	.string "alive!\p"
	.string "Boy, am I glad that I never went\n"
	.string "on any boats or anything.$"


gFameCheckerFlavorText_Lavender3:: @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Everyone here in school loves\n"
	.string "CUBONE'S mother.\p"
	.string "She comes in sometimes when our\n"
	.string "TEACHER is sick.$"

gFameCheckerFlavorText_Lavender4:: @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MATH CLUB was always CUBONE's\n"
	.string "favorite activity after school.\l"
	.string "I hope his MOTHER is safe up there.$"

gFameCheckerFlavorText_Lavender5:: @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Fill that SOOT SACK with ash and\n"
	.string "bring it to me.\l"
	.string "I'll craft you a present, huff-puff!$"

gFameCheckerFlavorText_Celadon0:: @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where are we?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Oh no!\n"
	.string "Something terrible has happened!\p"
	.string "Someone shoved all of CELADON CITY\n"
	.string "into a RANDOMIZER!$"

gFameCheckerFlavorText_Celadon1:: @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I really like trading, but you can't\n"
	.string "actually do it here in CELADON.\p"
	.string "Right now, the CABLE CLUB is\n"
	.string "replaced by a, erm… GAY-BLE CLUB.$"


gFameCheckerFlavorText_Celadon2:: @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Do you see that guy sitting in\n"
	.string "the corner behind me?\l"
	.string "He's been there for a few months.\p"
	.string "It sounds like he might be counting\n"
	.string "something, I think?$"


gFameCheckerFlavorText_Celadon3:: @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This blasted elevator!\p"
	.string "I was hoping I'd be able to get\n"
	.string "back to the city through it,\l"
	.string "but it's not working!$"


gFameCheckerFlavorText_Celadon4:: @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The BOSS is off on important\n"
	.string "business.\p"
	.string "His POKéMON is fully invincible!\n"
	.string "It has no weakness you can exploit!\p"
	.string "Well, it has no weaknesses here in\n"
	.string "GENERATION 3, at least.$"

gFameCheckerFlavorText_Celadon5:: @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TM30 contains MAGICAL LEAF.\p"
	.string "I'm sure you'll find it very\n"
	.string "useful someday soon!$"

gFameCheckerFlavorText_Fuchsia0:: @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Aight, listen up!\n"
	.string "Here's the perfect SANDWICH:\p"
	.string "A fresh loaf of BREAD!\n"
	.string "Coated in SESAME SEEDS!\p"
	.string "Hearty cuts of MEAT, alongside a\n"
	.string "lovely slice of CHEESE!\p"
	.string "Some LETTUCE that's been very\n"
	.string "freshly CUT!\p"
	.string "And to top it off: Crunchy,\n"
	.string "Flavorful PICKLES!$"

gFameCheckerFlavorText_Fuchsia1:: @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The DMCA are after DRAGONITE.\p"
	.string "If we want to stop them, you'll\n"
	.string "need to find one somewhere.\l"
	.string "It won't be in the SAFARI ZONE.\p"
	.string "Good luck.\n"
	.string "I'm sure you can save us!$"

gFameCheckerFlavorText_Fuchsia2:: @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We found an ITEM here that induced\n"
	.string "an illegal EVOLUTION in DRAGONITE.\p"
	.string "We passed it to our team in the\n"
	.string "CELADON DMCA LAW OFFICES.\l"
	.string "One of our ADMINS is guarding it.$"

gFameCheckerFlavorText_Fuchsia3:: @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ah, confound it!\n"
	.string "I clicked on one of those darned\l"
	.string "pop-up windows.\p"
	.string "Rats, I hope I didn't install a\n"
	.string "virus on my POKéMON again…$"

gFameCheckerFlavorText_Fuchsia4:: @ 0x81AEDAA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}REQUEST NOTICE\p"
    .string "Please find the SAFARI WARDEN's\n"
    .string "lost GOLD TEETH.\l"
    .string "Last seen near CELADON.\p"
    .string "Reward offered!\n"
    .string "Contact: WARDEN$"

gFameCheckerFlavorText_Fuchsia5:: @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Okay, look.\n"
	.string "I know what you're thinking:\p"
	.string "“Isn't that supposed to be an\n"
	.string "HM03 SURF?”\l"
	.string "Yeah, well… funny story about that.$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm sorry, but there's a blackout\n"
	.string "at the LIGHTHOUSE right now.\p"
	.string "I'm sorry, but rules are rules.\n"
	.string "Nobody's allowed to go inside.$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I think the DONUTS are extra good\n"
	.string "if you put them in the toaster first.\l"
	.string "It gets 'em nice and crispy!$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm looking on the seashore for\n"
	.string "things to sell.\l"
	.string "It's fun!$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You give me some POKéMON, doesn't\n"
	.string "matter which.\p"
	.string "Then, I'll tell people that it's\n"
	.string "extremely rare and valuable.\l"
	.string "That way, we get high-value offers!$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Have you come to pray at the\n"
	.string "alter of the LIGHTNING ARCHBIRD?\p"
	.string "They say that one who encounters\n"
	.string "all three is holy and blessed.\l"
	.string "For the GLORY of the SKIES!$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "People often lose things in the\n"
	.string "darkness of the UNDERGROUND PATH.$"

gFameCheckerFlavorText_GreatSeaWest0:: @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "We've been documenting POKéMON\n"
	.string "SIGNS across KANTO.\l"
	.string "There's 7 to see in total.\p"
	.string "I can't wait to learn where they\n"
	.string "all point!$"


gFameCheckerFlavorText_GreatSeaWest1:: @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "This island is great, but I really\n"
	.string "miss being home in JOHTO.\p"
	.string "I'd visit the NATIONAL PARK just\n"
	.string "to relax on the benches all day.\l"
	.string "Ah, if only I could go back…!$"


gFameCheckerFlavorText_GreatSeaWest2:: @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Have you heard of OLD AMBER?\n"
	.string "PEWTER MUSEUM has some.\p"
	.string "In the next room over, they're\n"
	.string "researching it.\l"
	.string "No one's allowed in, though.$"

gFameCheckerFlavorText_GreatSeaWest3:: @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "You're looking for BURN HEAL?\n"
	.string "I don't think they have it here.\p"
	.string "I hear there's an island to the\n"
	.string "NORTHEAST with a marketplace.\l"
	.string "They stock all sorts of things.$"


gFameCheckerFlavorText_GreatSeaWest4:: @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Hi!\n"
	.string "Do you have RAICHU?\p"
	.string "Wnat to trade it for my HAUNTER?\n$"

gFameCheckerFlavorText_GreatSeaWest5:: @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Behind this GYM is a cave.\p"
	.string "This cave is the start to finding\n"
	.string "a BIRD POKéMON spoken in legends.\p"
	.string "Meet with this POKéMON, and I'll\n"
	.string "relent and admit defeat.$"

gFameCheckerFlavorText_GreatSeaEast0:: @ 0x81AF4FD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "A POKéMON is buried deep into\n"
	.string "the ground.\p"
	.string "I wonder where the rest of him\n"
	.string "wound up.$"

gFameCheckerFlavorText_GreatSeaEast1:: @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Have you ever wanted to call your\n"
	.string "opponent a FUCKHEAD?\p"
	.string "Take this!\n$"

gFameCheckerFlavorText_GreatSeaEast2:: @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "One thing I hate about this gym\n"
	.string "is how crowded it gets.\p"
	.string "Everyone's hoping to get their\n"
	.string "turn using the bench press.$"


gFameCheckerFlavorText_GreatSeaEast3:: @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "It's a rock.\p"
	.string "It feels normal to the touch.\n$"


gFameCheckerFlavorText_GreatSeaEast4:: @ 0x81AF758
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Here, you can go on a stroll with\n"
	.string "a cute POKéMON.\p"
	.string "The permitted POKéMON are PIKACHU,\n"
	.string "PACHIRISU, EMOLGA, and TRUBBISH.$"


gFameCheckerFlavorText_GreatSeaEast5:: @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "If we're going to get ourselves\n"
	.string "out of this mess, we need to find\l"
	.string "the rest of my crew.\p"
	.string "Follow along, if you'd like.\n$"

gFameCheckerFlavorText_GreatSeaCenter0:: @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "That guy up there's a real\n"
	.string "jerk!\p"
	.string "He knows how to cross WHIRLPOOLS,\n"
	.string "but he won't teach anyone else!$"

gFameCheckerFlavorText_GreatSeaCenter1:: @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Say, one of our deliverymen got\n"
	.string "stuck in CELADON CITY a while back.\l"
	.string "I hear one of his eggs was ODD?$"

gFameCheckerFlavorText_GreatSeaCenter2:: @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "If you'd like to learn my secret\n"
	.string "moves, fine me under the WATERFALL.\p"
	.string "To enter, you must stand behind the\n"
	.string "falls for 3 Minutes without moving.$"

gFameCheckerFlavorText_GreatSeaCenter3:: @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Hey, hey!\n"
	.string "I'm selling PENCILS!\p"
	.string "A good friend of mine working at\n"
	.string "SILPH CO just placed a huge order.$"

gFameCheckerFlavorText_GreatSeaCenter4:: @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Hey, hey!\n"
	.string "Would you like to buy a HOUSE?\p"
	.string "It's right on the mainland, and\n"
	.string "there's a lovely bench out front!$"


gFameCheckerFlavorText_GreatSeaCenter5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "{BRAILLE_W}\n$"

gFameCheckerFlavorText_GreatBay0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Somehwere in KANTO, there exists\n"
	.string "the ALTAR OF THE MOON.\p"
	.string "Legends say if you bring this\n"
	.string "POKéMON there and hold it up,\l"
	.string "something incredible may happen.$"

gFameCheckerFlavorText_GreatBay1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Ever since the Gen 1 TYPE CHART,\n"
	.string "things have been real rough.\p"
	.string "My BUG-TYPES haven't been able to\n"
	.string "stand up to those POISON-TYPES.\l"
	.string "We're weak to their attacks now!\p"
	.string "I wish there was something we could\n"
	.string "do to turn the tables on them…$"

gFameCheckerFlavorText_GreatBay2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "SAMSON: Hello, there!\n"
	.string "My name is OAK!\p"
	.string "I hope you're having a wonderful\n"
	.string "day on this beautiful island!$"

gFameCheckerFlavorText_GreatBay3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "There was once a POKéMON so greedy\n"
	.string "and powerful, we humans had to\l"
	.string "Seal it away for our own safety.\p"
	.string "Some day, someone may come along\n"
	.string "and Break the Seal themselves…$"

gFameCheckerFlavorText_GreatBay4:: @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Hi, there!\n"
	.string "I'm giving away a free CHANSEY.\l"
	.string "Would you like it?$"

gFameCheckerFlavorText_GreatBay5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "BRENDAN's house\n$"

gFameCheckerFlavorText_Saffron0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "All these staircases were idenitcal\n"
	.string "copies of each other.\p"
	.string "I did this place a favor and\n"
	.string "took them out!$"

gFameCheckerFlavorText_Saffron1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "It's out secret prototype MISTER\n"
	.string "BALL.\p"
	.string "It will catch any MISTER without\n"
	.string "fail.$"

gFameCheckerFlavorText_Saffron2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Feel free to explore the rest of\n"
	.string "this building.\l"
	.string "There's plenty to see!\p"
	.string "Maybe you'll come across our\n"
	.string "facility for POKé BALL development!$"

gFameCheckerFlavorText_Saffron3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "How about this:\n"
	.string "“UNDENIABLE PROOF OF ALIENS!”\l"
	.string "Catchy headline. It's perfect.$"

gFameCheckerFlavorText_Saffron4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Local child COPYCAT still missing\n"
	.string "after DMCA takeover!\p"
	.string "Authorities suspect she's in their\n"
	.string "hideout, still in captivity.$"

gFameCheckerFlavorText_Saffron5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}"
	.string "Sorry, my office is a pig sty…\n"
	.string "And I haven't taken a bath in ages.\p"
	.string "By the way, I'm starving.\n"
	.string "Can I have something to eat?$"


gFameCheckerPersonName_Pallet:: @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where it all began$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: PROF. OAK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Why do POKéMON compete and battle\n"
	.string "so hard for you?\p"
	.string "They do so because they can see\n"
	.string "the love and trust you have\l"
	.string "towards POKéMON.\p"
	.string "Never forget that.$"

gFameCheckerPersonName_Viridian:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hey, what's with that ledge?$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: DAISY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}While I was comfortably enjoying\n"
	.string "my tea breaks, you've grown very\l"
	.string "skilled and powerful.\p"
	.string "I hope you'll remain a good rival\n"
	.string "to my little brother.$"

gFameCheckerPersonName_Pewter:: @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}How do you evolve CATERPIE?$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BROCK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In this big world of ours, there\n"
	.string "must be many tough TRAINERS.\p"
	.string "Let's both keep training and\n"
	.string "making ourselves stronger!$"

gFameCheckerPersonName_MtMoon:: @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Oh no! You can't run!$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MISTY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm going to keep training here at\n"
	.string "this GYM.\p"
	.string "When I get better, I'd love to hit\n"
	.string "the road and travel.$"

gFameCheckerPersonName_Cerulean:: @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The TCG Capital$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LT. SURGE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, kid!\n"
	.string "You electrified me in our battle!\p"
	.string "I didn't know that there were\n"
	.string "gutsy TRAINERS like you.\p"
	.string "It made me change my mind about\n"
	.string "you!$"

gFameCheckerPersonName_Vermilion:: @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}How do you get CUT?$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: ERIKA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am so glad that there are strong\n"
	.string "TRAINERS like you.\p"
	.string "That awareness alone inspires and\n"
	.string "motivates me to try harder.\p"
	.string "Please visit me again.\n"
	.string "Zzz…$"

gFameCheckerPersonName_RockTunnel:: @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gotta turn on the power...$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: KOGA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You and I, we must both set our\n"
	.string "sights higher and work towards\l"
	.string "meeting our challenges.\p"
	.string "Now, I must go train my daughter.$"

gFameCheckerPersonName_Lavender:: @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Copyright Trouble at the school!$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: SABRINA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The love you have towards your\n"
	.string "POKéMON…\p"
	.string "It was a power that was never\n"
	.string "bested by my psychic power.$"

gFameCheckerPersonName_Celadon:: @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}I can't find my house...$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BLAINE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My fire POKéMON!\n"
	.string "They'll become even more powerful!\p"
	.string "And now, a quiz. How many kinds of\n"
	.string "FIRE-type POKéMON are there?$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LORELEI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I needed to thank you for your\n"
	.string "help.\p"
	.string "But that has nothing to do with our\n"
	.string "battles.\p"
	.string "You'd better watch out next time!$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BRUNO\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The super power of your POKéMON\n"
	.string "and you I've experienced myself.\p"
	.string "Next time, maybe I should show you\n"
	.string "how to train yourself.$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: AGATHA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}When you grow older, don't you\n"
	.string "dare go soft like that coot OAK!\p"
	.string "Be like me and keep battling on!$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LANCE$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LANCE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm considering going back to my\n"
	.string "hometown.\p"
	.string "I want to retrain my DRAGON-type\n"
	.string "POKéMON and strengthen them.\p"
	.string "I'd like to invite you to my\n"
	.string "hometown one day.$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BILL\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, there! CELIO had nothing but\n"
	.string "praise for you.\p"
	.string "Hearing that makes me happy.\p"
	.string "When you catch some rare POKéMON,\n"
	.string "come show me, okay? Promise!$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MR. FUJI$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MR. FUJI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Instead of hoping for the happiness\n"
	.string "of just your POKéMON…\p"
	.string "…Can I get you to wish for the\n"
	.string "happiness of all POKéMON?$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: GIOVANNI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}There is nothing that I wish to say\n"
	.string "to you.\p"
	.string "I will concentrate solely on\n"
	.string "bettering myself, and none other.$"

gRumorLogFlavorTextIntoLine1_Pallet0:: @ 0x81B0C45
    .string "Tenured$"

gRumorLogFlavorTextIntoLine1_Pallet1::
    .string "Next-door$"

gRumorLogFlavorTextIntoLine1_Pallet2::
    .string "Bedroom$"

gRumorLogFlavorTextIntoLine1_Pallet3::
    .string "Faithful$"

gRumorLogFlavorTextIntoLine1_Pallet4::
    .string "Meaningful$"

gRumorLogFlavorTextIntoLine1_Pallet5::
    .string "Polite$"

gRumorLogFlavorTextIntoLine1_Viridian0::
    .string "Forlorn$"

gRumorLogFlavorTextIntoLine1_Viridian1::
    .string "Recognizable$"

gRumorLogFlavorTextIntoLine1_Viridian2::
    .string "Pit$"

gRumorLogFlavorTextIntoLine1_Viridian3::
    .string "Candy$"

gRumorLogFlavorTextIntoLine1_Viridian4::
    .string "Ridiculous$"

gRumorLogFlavorTextIntoLine1_Viridian5::
    .string "Rigged$"

gRumorLogFlavorTextIntoLine1_Pewter0::
    .string "Absurdity$"

gRumorLogFlavorTextIntoLine1_Pewter1::
    .string "Digital$"

gRumorLogFlavorTextIntoLine1_Pewter2::
    .string "Garishly$"

gRumorLogFlavorTextIntoLine1_Pewter3::
	.string "Paternal$"

gRumorLogFlavorTextIntoLine1_Pewter4::
    .string "Lunar$"

gRumorLogFlavorTextIntoLine1_Pewter5::
    .string "Austere$"

gRumorLogFlavorTextIntoLine1_MtMoon0::
	.string "Corporate$"

gRumorLogFlavorTextIntoLine1_MtMoon1::
	.string "Loose-Fitting$"

gRumorLogFlavorTextIntoLine1_MtMoon2::
	.string "Aquatic$"

gRumorLogFlavorTextIntoLine1_MtMoon3::
	.string "Severe$"

gRumorLogFlavorTextIntoLine1_MtMoon4::
	.string "Jogging$"

gRumorLogFlavorTextIntoLine1_MtMoon5::
	.string "One-Time$"

gRumorLogFlavorTextIntoLine1_Cerulean0::
	.string "Competitive$"

gRumorLogFlavorTextIntoLine1_Cerulean1::
	.string "Confection$"

gRumorLogFlavorTextIntoLine1_Cerulean2::
	.string "Familiar$"

gRumorLogFlavorTextIntoLine1_Cerulean3::
	.string "Spry$"

gRumorLogFlavorTextIntoLine1_Cerulean4::
	.string "Revenue$"

gRumorLogFlavorTextIntoLine1_Cerulean5::
	.string "Darwinist$"

gRumorLogFlavorTextIntoLine1_Vermilion0::
	.string "Harbor$"

gRumorLogFlavorTextIntoLine1_Vermilion1::
	.string "Amicable$"

gRumorLogFlavorTextIntoLine1_Vermilion2::
	.string "Swindled$"

gRumorLogFlavorTextIntoLine1_Vermilion3::
	.string "Emigrated$"

gRumorLogFlavorTextIntoLine1_Vermilion4::
	.string "Seizure$"

gRumorLogFlavorTextIntoLine1_Vermilion5::
	.string "Disorganized$"

gRumorLogFlavorTextIntoLine1_RockTunnel0::
	.string "Disheartened$"

gRumorLogFlavorTextIntoLine1_RockTunnel1::
	.string "Crystaline$"

gRumorLogFlavorTextIntoLine1_RockTunnel2::
	.string "Magnetic$"

gRumorLogFlavorTextIntoLine1_RockTunnel3::
	.string "Network$"

gRumorLogFlavorTextIntoLine1_RockTunnel4::
	.string "Badge$"

gRumorLogFlavorTextIntoLine1_RockTunnel5::
	.string "Shadow$"

gRumorLogFlavorTextIntoLine1_Lavender0::
	.string "Graveyard$"

gRumorLogFlavorTextIntoLine1_Lavender1::
	.string "Shady$"

gRumorLogFlavorTextIntoLine1_Lavender2::
	.string "Relieved$"

gRumorLogFlavorTextIntoLine1_Lavender3::
	.string "Preschool$"

gRumorLogFlavorTextIntoLine1_Lavender4:: @ idk man
	.string "Math$"

gRumorLogFlavorTextIntoLine1_Lavender5::
	.string "Soot$"

gRumorLogFlavorTextIntoLine1_Celadon0::
	.string "Chaos$"

gRumorLogFlavorTextIntoLine1_Celadon1::
	.string "Troubled$"

gRumorLogFlavorTextIntoLine1_Celadon2::
	.string "Counting$"

gRumorLogFlavorTextIntoLine1_Celadon3::
	.string "Vertical$"

gRumorLogFlavorTextIntoLine1_Celadon4::
	.string "IP$"

gRumorLogFlavorTextIntoLine1_Celadon5::
	.string "Inspiring$"

gRumorLogFlavorTextIntoLine1_Fushcia0::
	.string "Sandwich$"

gRumorLogFlavorTextIntoLine1_Fushcia1::
	.string "Sibling$"

gRumorLogFlavorTextIntoLine1_Fushcia2::
	.string "Infringement$"

gRumorLogFlavorTextIntoLine1_Fushcia3::
	.string "Malware$"

gRumorLogFlavorTextIntoLine1_Fushcia4::
	.string "Molars$"

gRumorLogFlavorTextIntoLine1_Fushcia5::
	.string "Corporate$"

gRumorLogFlavorTextIntoLine1_KantoShoreline0::
	.string "Beacon$"

gRumorLogFlavorTextIntoLine1_KantoShoreline1::
	.string "Glazed$"

gRumorLogFlavorTextIntoLine1_KantoShoreline2::
	.string "Coastal$"

gRumorLogFlavorTextIntoLine1_KantoShoreline3::
	.string "Scheming$"

gRumorLogFlavorTextIntoLine1_KantoShoreline4::
	.string "Zephyr$"

gRumorLogFlavorTextIntoLine1_KantoShoreline5::
	.string "Tunnel$"

gRumorLogFlavorTextIntoLine1_Agatha0::
	.string "Curious$"

gRumorLogFlavorTextIntoLine1_Agatha1::
	.string "Parkside$"

gRumorLogFlavorTextIntoLine1_Agatha2::
	.string "Arboreal$"

gRumorLogFlavorTextIntoLine1_Agatha3::
	.string "Aloe$"

gRumorLogFlavorTextIntoLine1_Agatha4::
	.string "Sinister$"

gRumorLogFlavorTextIntoLine1_Agatha5::
	.string "Conferred$"

gRumorLogFlavorTextIntoLine1_Lance0::
	.string "Withheld$"

gRumorLogFlavorTextIntoLine1_Lance1::
	.string "Shellin' Out$"

gRumorLogFlavorTextIntoLine1_Lance2::
	.string "Stillness$"

gRumorLogFlavorTextIntoLine1_Lance3::
	.string "Graphite$"

gRumorLogFlavorTextIntoLine1_Lance4::
	.string "Dubious$"

gRumorLogFlavorTextIntoLine1_Lance5::
	.string "Tactile$"

gRumorLogFlavorTextIntoLine1_Bill0::
	.string "Bungled$"

gRumorLogFlavorTextIntoLine1_Bill1::
	.string "Mockery$"

gRumorLogFlavorTextIntoLine1_Bill2::
	.string "Workout$"

gRumorLogFlavorTextIntoLine1_Bill3::
	.string "Rock$"

gRumorLogFlavorTextIntoLine1_Bill4::
	.string "Allure$"

gRumorLogFlavorTextIntoLine1_Bill5::
	.string "Patriotic$"

gRumorLogFlavorTextIntoLine1_MrFuji0::
	.string "Lunar$"

gRumorLogFlavorTextIntoLine1_MrFuji1::
	.string "Toxic$"

gRumorLogFlavorTextIntoLine1_MrFuji2::
	.string "Tidal$"

gRumorLogFlavorTextIntoLine1_MrFuji3::
	.string "Pinniped$"

gRumorLogFlavorTextIntoLine1_MrFuji4::
	.string "Consent$"

gRumorLogFlavorTextIntoLine1_MrFuji5::
	.string "Courier$"

gRumorLogFlavorTextIntoLine1_Giovanni0::
	.string "Staircase$"

gRumorLogFlavorTextIntoLine1_Giovanni1::
	.string "Father$"

gRumorLogFlavorTextIntoLine1_Giovanni2::
	.string "Clerical$"

gRumorLogFlavorTextIntoLine1_Giovanni3::
	.string "Extraterrestrial$"

gRumorLogFlavorTextIntoLine1_Giovanni4::
	.string "Missing$"

gRumorLogFlavorTextIntoLine1_Giovanni5::
	.string "Distant$"

gFameCheckerFlavorTextOriginObjectName_Pallet0::
	.string "Timber$"

gFameCheckerFlavorTextOriginObjectName_Pallet1::
	.string "Neighbor$"

gFameCheckerFlavorTextOriginObjectName_Pallet2::
	.string "Breadmaker$"

gFameCheckerFlavorTextOriginObjectName_Pallet3::
	.string "Father$"

gFameCheckerFlavorTextOriginObjectName_Pallet4::
	.string "Macguffin$"

gFameCheckerFlavorTextOriginObjectName_Pallet5::
	.string "Proposal$"

gFameCheckerFlavorTextOriginObjectName_Viridian0::
	.string "Franchiser$"

gFameCheckerFlavorTextOriginObjectName_Viridian1::
	.string "Rando$"

gFameCheckerFlavorTextOriginObjectName_Viridian2::
	.string "Proclamation$"

gFameCheckerFlavorTextOriginObjectName_Viridian3::
	.string "Collector$"

gFameCheckerFlavorTextOriginObjectName_Viridian4::
	.string "Request$"

gFameCheckerFlavorTextOriginObjectName_Viridian5::
	.string "Reunion$"

gFameCheckerFlavorTextOriginObjectName_Pewter0::
	.string "Advisory$"

gFameCheckerFlavorTextOriginObjectName_Pewter1::
	.string "Directions$"

gFameCheckerFlavorTextOriginObjectName_Pewter2::
	.string "Gardening$"

gFameCheckerFlavorTextOriginObjectName_Pewter3::
	.string "Precaution$"

gFameCheckerFlavorTextOriginObjectName_Pewter4::
	.string "Larceny$"

gFameCheckerFlavorTextOriginObjectName_Pewter5::
	.string "Arbor$"

gFameCheckerFlavorTextOriginObjectName_MtMoon0::
	.string "Consortium$"

gFameCheckerFlavorTextOriginObjectName_MtMoon1::
	.string "Legwear$"

gFameCheckerFlavorTextOriginObjectName_MtMoon2::
	.string "Anxiety$"

gFameCheckerFlavorTextOriginObjectName_MtMoon3::
	.string "Scopophobia$"

gFameCheckerFlavorTextOriginObjectName_MtMoon4::
	.string "Jealousy$"

gFameCheckerFlavorTextOriginObjectName_MtMoon5::
	.string "Wonder$"

gFameCheckerFlavorTextOriginObjectName_Cerulean0::
	.string "Community$"

gFameCheckerFlavorTextOriginObjectName_Cerulean1::
	.string "Curator$"

gFameCheckerFlavorTextOriginObjectName_Cerulean2::
	.string "Face$"

gFameCheckerFlavorTextOriginObjectName_Cerulean3::
	.string "Spelunker$"

gFameCheckerFlavorTextOriginObjectName_Cerulean4::
	.string "Recommendation$"

gFameCheckerFlavorTextOriginObjectName_Cerulean5::
	.string "Deviation$"

gFameCheckerFlavorTextOriginObjectName_Vermilion0::
	.string "Historian$"

gFameCheckerFlavorTextOriginObjectName_Vermilion1::
	.string "Aviarist$"

gFameCheckerFlavorTextOriginObjectName_Vermilion2::
	.string "Sweatwear$"

gFameCheckerFlavorTextOriginObjectName_Vermilion3::
	.string "Envoy$"

gFameCheckerFlavorTextOriginObjectName_Vermilion4::
	.string "Sentinel$"

gFameCheckerFlavorTextOriginObjectName_Vermilion5::
	.string "Driver$"

gFameCheckerFlavorTextOriginObjectName_RockTunnel0::
	.string "Denims$"

gFameCheckerFlavorTextOriginObjectName_RockTunnel1::
	.string "Caver$"

gFameCheckerFlavorTextOriginObjectName_RockTunnel2:: @ Unfinished
	.string "Melodrama$"

gFameCheckerFlavorTextOriginObjectName_RockTunnel3:: @ Unfinished
	.string "Neglector$"

gFameCheckerFlavorTextOriginObjectName_RockTunnel4:: @ Unfinished
	.string "Broker$"

gFameCheckerFlavorTextOriginObjectName_RockTunnel5:: @ Unfinished
	.string "Superstition$"

gFameCheckerFlavorTextOriginObjectName_Lavender0::
	.string "Guide$"

gFameCheckerFlavorTextOriginObjectName_Lavender1::
	.string "Salesman$"

gFameCheckerFlavorTextOriginObjectName_Lavender2::
	.string "Ratkeeper$"

gFameCheckerFlavorTextOriginObjectName_Lavender3::
	.string "Pupil$"

gFameCheckerFlavorTextOriginObjectName_Lavender4:: @ Unfinished
	.string "Mentor$"

gFameCheckerFlavorTextOriginObjectName_Lavender5::
	.string "Specialist$"

gFameCheckerFlavorTextOriginObjectName_Celadon0::
	.string "Courier$"

gFameCheckerFlavorTextOriginObjectName_Celadon1::
	.string "Trader$"

gFameCheckerFlavorTextOriginObjectName_Celadon2::
	.string "Continuously$"

gFameCheckerFlavorTextOriginObjectName_Celadon3::
	.string "Vexation$"

gFameCheckerFlavorTextOriginObjectName_Celadon4::
	.string "Inquisitor$"

gFameCheckerFlavorTextOriginObjectName_Celadon5::
	.string "Inclusivity!$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0:: @ Fushcia
	.string "Savant$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "Survivor$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "Informant$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "Maligned$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "Missing$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "Copout$"

gFameCheckerFlavorTextOriginObjectName_Bruno0:: @ Kanto Shoreline
	.string "Blockade$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "Gourmond$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "Capitalist$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "Schmuck$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "Zealot$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "Troubled$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "Cartography$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "Pining$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "Awe$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "Allegation$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "Soliciter$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "Conditionally$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "Wisdom$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "Shells$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "Secret$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "Guru$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "Dwelling$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "Tip$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "Burial$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "Mentor$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "Woes$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "Arbiter$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "Pundit$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "Legends$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "Torment$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "Timber$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "Parable$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "Conundrum$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "Concealment$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "Suppression$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "Fetcher$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "Counsel$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "Evidence$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "Mimic$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "Dinner$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PEWTER GYM\n"
	.string "LEADER BROCK!\p"
	.string "BROCK rarely laughs, but is said to\n"
	.string "be unable to stop if he starts.$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CERULEAN GYM\n"
	.string "LEADER MISTY!\p"
	.string "MISTY is said to worship LORELEI\n"
	.string "of the ELITE FOUR.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: VERMILION GYM\n"
	.string "LEADER LT. SURGE!\p"
	.string "LT. SURGE is rumored to have been\n"
	.string "a pilot while home in America.\p"
	.string "He used the electricity generated\n"
	.string "by POKéMON to power his plane.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CELADON GYM\n"
	.string "LEADER ERIKA!\p"
	.string "Rumor has it that if you peek into\n"
	.string "CELADON GYM, you can often\l"
	.string "see ERIKA snoozing.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: FUSHCIA GYM\n"
	.string "LEADER KOGA!\p"
	.string "KOGA is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his POKéMON to health.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: SAFFRON GYM\n"
	.string "LEADER SABRINA!\p"
	.string "People say that SABRINA can\n"
	.string "communicate with her POKéMON\l"
	.string "during battle without speaking.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CINNABAR GYM\n"
	.string "LEADER BLAINE!\p"
	.string "BLAINE is said to remove his dark\n"
	.string "shades only when he is thinking up\l"
	.string "new quiz questions.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's LORELEI!\p"
	.string "Known for her logical, calculated,\n"
	.string "and cool battling style, LORELEI\l"
	.string "has a surprising secret!$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's BRUNO!\p"
	.string "BRUNO apparently joined the ELITE\n"
	.string "FOUR out of his burning ambition to\l"
	.string "battle the best TRAINERS.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's AGATHA!\p"
	.string "In her youth, AGATHA and PROF.\n"
	.string "OAK were rivals who vied for\l"
	.string "supremacy as TRAINERS.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's LANCE!\p"
	.string "LANCE's grandfather is thought to\n"
	.string "be the elder of a famous clan of\l"
	.string "dragon masters.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PROF. OAK,\n"
	.string "the POKéMON tree!\p"
	.string "PROF. OAK is continuing to grow\n"
	.string "at a rate of one ring per year!$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "This is a POKéMON JOURNAL from\n"
	.string "years ago…\p"
	.string "POKéMON JOURNAL\n"
	.string "CONTEST Special!\p"
	.string "The Spring POKéMON CONTEST's\n"
	.string "Grand Champion is DAISY OAK of\l"
	.string "PALLET TOWN!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "MR. FUJI of POKéMON HOUSE!\p"
	.string "Editor: The shy MR. FUJI turned\n"
	.string "down our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in LAVENDER TOWN.$"
