gFameCheckerFlavorText_Pallet0:: @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hello, there!\n"
	.string "I am an OAK!$"

gFameCheckerFlavorText_Pallet1:: @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}His name is GARY, not {RIVAL}!\n"
	.string "Haven't you seen the TV show?$"

gFameCheckerFlavorText_Pallet2:: @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This looks like an NES, but it's\n"
	.string "actually a very fancy toaster.$"


gFameCheckerFlavorText_Pallet3:: @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}DAD: {PLAYER}!\n"
	.string "You should take a quick rest.$"

gFameCheckerFlavorText_Pallet4:: @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}That's my GS BALL!\n"
	.string "No, you can't have it.\p"
	.string "It's very important to the plot.\n"
	.string "I need to keep it safe!$"

gFameCheckerFlavorText_Pallet5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It is VERY strongly recommended that\n"
	.string "you complete the POKéDEX!\p"
	.string "Otherwise you'll miss out on\n"
	.string "a lot of the fun!$"

gFameCheckerFlavorText_Viridian0:: @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It appears that this is the\n"
	.string "last POTION in the known universe.\p"
	.string "Uh, I guess you can have it.\n$"

gFameCheckerFlavorText_Viridian1:: @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}…Huh? GARY? Who's that?\p"
	.string "My name is LARRY!\n$"

gFameCheckerFlavorText_Viridian2:: @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TRAINER TIPS!\p"
	.string "Press START to save the game!\n$"

gFameCheckerFlavorText_Viridian3:: @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I've been looking around for a\n"
	.string "PIDGEY, but I haven't had any luck.\p"
	.string "Something so strong probably\n"
	.string "wouldn't be on this ROUTE.$"

gFameCheckerFlavorText_Viridian4:: @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hi!\n"
	.string "Do you have MEWTWO?\p"
	.string "Wanna trade it for my RATTATA?\n$"

gFameCheckerFlavorText_Viridian5:: @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The MR. MIME outside are almost\n"
	.string "impossible to catch!\p"
	.string "Maybe if I had a special POKé Ball\n"
	.string "I could do it…$"

gFameCheckerFlavorText_Pewter0:: @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Helpful advice…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Think outside the box!\p"
	.string "Sometimes, an absurd solution\n"
	.string "might just be what you need.$"


gFameCheckerFlavorText_Pewter1:: @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Everyone here's struggling to get a\n"
	.string "BUTTERFREE.\p"
	.string "Not me, though!\n"
	.string "I found a shortcut!$"

gFameCheckerFlavorText_Pewter2:: @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}There's supposed to be an extremely\n"
	.string "rare POKéMON in that grass.\p"
	.string "I'd really love to find it, but that\n"
	.string "guy keeps spraying REPEL everywhere!$"
	
gFameCheckerFlavorText_Pewter3:: @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You'd better not be running in\n"
	.string "your normal shoes.\p"
	.string "If you are, I'll have to\n"
	.string "report you to the police!$"

gFameCheckerFlavorText_Pewter4:: @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}KABUTOPS, eh?\p"
	.string "I hear scientists are working on a\n"
	.string "mechanical POKéMON just like it.$"

gFameCheckerFlavorText_Pewter5:: @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Something to try…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Look at this beautiful piece of\n"
	.string "AMBER we found!\p"
	.string "It's one of our finest specimens.\p"
	.string "…What?\n"
	.string "No, of course you can't have it!\l"
	.string "Why would you think you could?$"

gFameCheckerFlavorText_MtMoon0:: @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We, the DMCA, are copyright\n"
	.string "gangsters!\p"
	.string "We strike fear with our takedown!\n$"


gFameCheckerFlavorText_MtMoon1:: @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am SHORTS!\n"
	.string "I'm comfy and easy to wear!$"


gFameCheckerFlavorText_MtMoon2:: @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}So, wait. If all the TENTACOOL are\n"
	.string "in this cave…\p"
	.string "What does that mean for all the\n"
	.string "WATER routes?$"

gFameCheckerFlavorText_MtMoon3:: @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Excuse me!\n"
	.string "You looked at me, didn't you?\p"
	.string "Yup, you definitely looked\n"
	.string "at me.$"

gFameCheckerFlavorText_MtMoon4:: @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TENTACOOL stops you from running.\p"
	.string "I think maybe he just wants to\n"
	.string "run too…$"

gFameCheckerFlavorText_MtMoon5:: @ 0x81ADCEB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I expected to be able to stop\n"
	.string "you with my invincible KOFFING…\p"
	.string "Surely this will be the only time\n"
	.string "you fight someone with WONDER GUARD.$"

gFameCheckerFlavorText_Cerulean0:: @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where are we?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CERULEAN is known for its competitive\n"
	.string "scene!\p"
	.string "Whether it's battling to the north\n"
	.string "or playing the TCG here in town!$"

gFameCheckerFlavorText_Cerulean1:: @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Have you found any pieces of\n"
	.string "CANDY laying on the ground?\p"
	.string "I think there's one in every\n"
	.string "major area.$"

gFameCheckerFlavorText_Cerulean2:: @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}GARY? LARRY?\n"
	.string "Who's that?\p"
	.string "My name is JERRY!\n"
	.string "What are you talking about?$"

gFameCheckerFlavorText_Cerulean3:: @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where are we?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In order to get through that\n"
	.string "cave, I had to climb a waterfall!\p"
	.string "Maybe it would've been easier if\n"
	.string "I had a POKéMON to help…$"


gFameCheckerFlavorText_Cerulean4:: @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I wanna buy some RARE CANDY to\n"
	.string "help evolve my POKéMON, but I\l"
	.string "need more money!\p"
	.string "Maybe if I visited BILL again…\n$"


gFameCheckerFlavorText_Cerulean5:: @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}If you look behind that cottage,\n"
	.string "you can see a path going north!\p"
	.string "I bet that's where you can catch\n"
	.string "the starters!$"

gFameCheckerFlavorText_Vermilion0:: @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The S.S. ANNE normally arrives\n"
	.string "in VERMILLION around this time.\p"
	.string "It doesn't seem to have made it\n"
	.string "to the harbor, though…$"


gFameCheckerFlavorText_Vermilion1:: @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You wanna know how I got a\n"
	.string "SPEAROW?\p"
	.string "I hatched it myself from an egg!\n$"

gFameCheckerFlavorText_Vermilion2:: @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I gave the guy next door my\n"
	.string "TRAINER ID.\l"
	.string "He said he'd give me a cool prize.\p"
	.string "I think that might've been a bad\n"
	.string "idea…$"


gFameCheckerFlavorText_Vermilion3:: @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I had someone deliver a letter to\n"
	.string "my one friend a while back.\l"
	.string "I think he's in VIRIDIAN still?\p"
	.string "Someone should check on him to see\n"
	.string "if he received it.$"


gFameCheckerFlavorText_Vermilion4:: @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SURGE's POKéMON will destroy you\n"
	.string "if you're not prepared.\p"
	.string "If you want to keep yourself safe,\n"
	.string "you'll need proper eyewear.$"


gFameCheckerFlavorText_Vermilion5:: @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I must've parked my TRUCK somewhere\n"
	.string "in this city...\l"
	.string "Do you have any idea where it is?$"

gFameCheckerFlavorText_RockTunnel0:: @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Wait, wasn't there a POKéMON\n"
	.string "CENTER here a minute ago?\p"
	.string "Darn, that's inconvenient.\n$"


gFameCheckerFlavorText_RockTunnel1:: @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I found my ONIX in a cave, hidden\n"
	.string "on an island far, far away.$"

gFameCheckerFlavorText_RockTunnel2:: @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My father is the GYM LEADER of\n"
	.string "this town.\p"
	.string "I'm training to use POISON POKéMON\n"
	.string "as well as my father.$"


gFameCheckerFlavorText_RockTunnel3:: @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My father is the GYM LEADER of\n"
	.string "this town.\p"
	.string "I'm training to use POISON POKéMON\n"
	.string "as well as my father.$"

gFameCheckerFlavorText_RockTunnel4:: @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}KOGA is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his POKéMON to health.$"

gFameCheckerFlavorText_RockTunnel5:: @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The SAFARI ZONE's huge, wouldn't\n"
	.string "you say?\p"
	.string "FUSHCIA's GYM LEADER, KOGA, \n"
	.string "patrols the grounds every so often.\p"
	.string "Thanks to him, we can play here\n"
	.string "knowing that we're safe.$"

gFameCheckerFlavorText_Lavender0:: @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where are we?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This town is known as the players'\n"
	.string "grave site.\p"
	.string "Be careful listening to the music!\n$"


gFameCheckerFlavorText_Lavender1:: @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I recently moved to this town.\p"
	.string "When I got here, the DMCA forced me\n"
	.string "to take down my fanfic…$"


gFameCheckerFlavorText_Lavender2:: @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Who is this person?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}HARRY: Yup, my RATICATE sure is\n"
	.string "alive!\p"
	.string "Boy, am I glad that I never went\n"
	.string "on any boats or anything.$"


gFameCheckerFlavorText_Lavender3:: @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Everyone here in school loves\n"
	.string "CUBONE'S mother.\p"
	.string "She comes in sometimes when our\n"
	.string "TEACHER is sick.$"

gFameCheckerFlavorText_Lavender4:: @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LAVENDER TOWN\n"
	.string "DANCE THEATER$"

gFameCheckerFlavorText_Lavender5:: @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Beware, fair traveller, as you\n"
	.string "ascend.\p"
	.string "Climbing this tower will face you\n"
	.string "against the greatest fear of any\l"
	.string "fanfiction author.$"

gFameCheckerFlavorText_Celadon0:: @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where are we?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Oh no!\n"
	.string "Something terrible has happened!\p"
	.string "Someone shoved all of CELADON CITY\n"
	.string "into a RANDOMIZER!$"

gFameCheckerFlavorText_Celadon1:: @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I really like trading, but you can't\n"
	.string "actually do it here in CELADON.\p"
	.string "Right now, the CABLE CLUB is\n"
	.string "replaced by a, erm… GAY-BLE CLUB.$"


gFameCheckerFlavorText_Celadon2:: @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This whole ordeal has everone in\n"
	.string "town so lost and confused.\p"
	.string "If only there were some sort of MAP\n"
	.string "that showed the layout of the TOWN.$"


gFameCheckerFlavorText_Celadon3:: @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Looking closer…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This blasted elevator!\p"
	.string "I was hoping I'd be able to get\n"
	.string "back to the city through it,\l"
	.string "but it's not working!$"


gFameCheckerFlavorText_Celadon4:: @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The BOSS is off on important\n"
	.string "business.\p"
	.string "His POKéMON is fully invincible!\n"
	.string "It has no weakness you can exploit!\p"
	.string "Well, it has no weaknesses in THIS\n"
	.string "GENERATION, at least.$"

gFameCheckerFlavorText_Celadon5:: @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}A friendly warning…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TM19 contains MAGICAL LEAF.\p"
	.string "I'm sure you'll find it very\n"
	.string "useful in the near future!$"

gFameCheckerFlavorText_Fuchsia0:: @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}No one can best me when it comes\n"
	.string "to icy POKéMON.$"

gFameCheckerFlavorText_Fuchsia1:: @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}No one can best me when it comes\n"
	.string "to icy POKéMON.$"

gFameCheckerFlavorText_Fuchsia2:: @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where was this person born?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We've had a great and powerful\n"
	.string "TRAINER grow up on this island.\p"
	.string "I bet even you'd know her.\n"
	.string "It's LORELEI of the ELITE FOUR!$"

gFameCheckerFlavorText_Fuchsia3:: @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Known for her logical, calculated,\n"
	.string "and cool battling style, LORELEI\l"
	.string "has a surprising secret!$"

gFameCheckerFlavorText_Fuchsia4:: @ 0x81AEDAA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Did you know that LORELEI has lots\n"
	.string "and lots of stuffed dolls?\p"
	.string "Every time she comes back to\n"
	.string "FOUR ISLAND, her collection grows!$"

gFameCheckerFlavorText_Fuchsia5:: @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The LAPRAS she has, I imagine it\n"
	.string "to be the one she met as a child.\p"
	.string "I believe it was in ICEFALL CAVE\n"
	.string "that she caught it.\p"
	.string "Perhaps that POKéMON has been with\n"
	.string "her ever since.$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am BRUNO of the ELITE FOUR!$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I've lived and trained with my\n"
	.string "fighting POKéMON!$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO apparently joined the ELITE\n"
	.string "FOUR out of his burning ambition to\l"
	.string "battle the best TRAINERS.$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO, who's a senior ahead of me,\n"
	.string "visits the SPA on occasion.\p"
	.string "He comes to rehab injuries, both\n"
	.string "his own and his POKéMON's.$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's one of the ELITE FOUR.\n"
	.string "His name is BRUNO.\p"
	.string "He went away disappointed when he\n"
	.string "found out that they were all sold\l"
	.string "out of Rage Candybars.$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Even BRUNO…\n"
	.string "He trained with a fellow by the\l"
	.string "name of BRAWLY before.$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am AGATHA of the ELITE FOUR.$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AGATHA's GHOST-type POKéMON are\n"
	.string "horrifically terrifying in toughness.$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}That old lady's also got a really\n"
	.string "short fuse, too.\p"
	.string "It doesn't take anything to get\n"
	.string "that scary lady hollering.$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In her youth, AGATHA and PROF.\n"
	.string "OAK were rivals who vied for\l"
	.string "supremacy as TRAINERS.$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear OAK's taken a lot of\n"
	.string "interest in you, child.\p"
	.string "That old duff was once tough and\n"
	.string "handsome.\p"
	.string "But that was decades ago.\n"
	.string "He's a shadow of his former self.$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Take AGATHA, for example.\p"
	.string "She set a record for being the\n"
	.string "oldest-ever ELITE FOUR member.$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I lead the ELITE FOUR.\p"
	.string "You can call me LANCE the dragon\n"
	.string "TRAINER.$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You know that dragons are\n"
	.string "mythical POKéMON.\p"
	.string "They're hard to catch and raise,\n"
	.string "but their powers are superior.\p"
	.string "They're virtually indestructible.\n"
	.string "There's no being clever with them.$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He stands for justice!\n"
	.string "He's cool, and yet passionate!\l"
	.string "He's the greatest, LANCE!$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We have a customer, LANCE, who\n"
	.string "occasionally comes.\p"
	.string "He always buys capes.\p"
	.string "I wonder… Does he have many\n"
	.string "identical capes at home?$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LANCE's grandfather is thought to\n"
	.string "be the elder of a famous clan of\l"
	.string "dragon masters.$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}From what I've heard, LANCE has\n"
	.string "a cousin who's a GYM LEADER\l"
	.string "somewhere far away.$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}After all, BILL's world-famous as a\n"
	.string "POKéMANIAC.\p"
	.string "He invented the POKéMON Storage\n"
	.string "System on PC, too.$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL has lots of POKéMON!\n"
	.string "He collects rare ones, too!$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's my grandson!\p"
	.string "He always liked collecting things,\n"
	.string "even as a child!$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL is a POKéMANIAC, so he loves\n"
	.string "every kind.\p"
	.string "Apparently, the first one he caught\n"
	.string "was an ABRA.$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL's hometown is GOLDENROD CITY,\n"
	.string "where his folks still live.\p"
	.string "I've heard that it's quite the\n"
	.string "festive, bustling city.$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Apparently, BILL simply can't\n"
	.string "stomach milk at all.$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's really kind.\p"
	.string "He looks after abandoned and\n"
	.string "orphaned POKéMON.$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This old guy marched right up to\n"
	.string "our HIDEOUT.\p"
	.string "Then, he starts ranting about how\n"
	.string "TEAM ROCKET's abusing POKéMON.\p"
	.string "So, we're just talking it over as\n"
	.string "adults.$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}POKéMON FAN MAGAZINE\n"
	.string "Monthly Grand Prize Drawing!\p"
	.string "The application form is…\p"
	.string "Gone! It's been clipped out.\n"
	.string "Someone must have applied already.$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear that MR. FUJI's not from\n"
	.string "these parts originally, either.$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It's a photo of BLAINE and\n"
	.string "MR. FUJI.\p"
	.string "They're standing shoulder to\n"
	.string "shoulder with big grins.$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Editor: The shy MR. FUJI turned\n"
	.string "down our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in LAVENDER TOWN.$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET captures POKéMON from\n"
	.string "around the world.\p"
	.string "They're important tools for keeping\n"
	.string "our criminal enterprise going.\p"
	.string "I am the leader, GIOVANNI!$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Those thugs that took over our\n"
	.string "building…\p"
	.string "Their BOSS said he was looking for\n"
	.string "strong POKéMON.$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET's BOSS is terribly\n"
	.string "cruel!\p"
	.string "To him, POKéMON are just tools to\n"
	.string "be used.$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Welcome to my hideout!\p"
	.string "It shall be so until I can restore\n"
	.string "TEAM ROCKET to its former glory.$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Blow me away! GIOVANNI was the\n"
	.string "GYM LEADER of VIRIDIAN?$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You… You're not GIOVANNI's kid,\n"
	.string "are you?\p"
	.string "No, that can't be right.\n"
	.string "GIOVANNI's kid has red hair.$"


gFameCheckerPersonName_Pallet:: @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where it all began$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: PROF. OAK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Why do POKéMON compete and battle\n"
	.string "so hard for you?\p"
	.string "They do so because they can see\n"
	.string "the love and trust you have\l"
	.string "towards POKéMON.\p"
	.string "Never forget that.$"

gFameCheckerPersonName_Viridian:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Hey, what's with that legde?$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: DAISY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}While I was comfortably enjoying\n"
	.string "my tea breaks, you've grown very\l"
	.string "skilled and powerful.\p"
	.string "I hope you'll remain a good rival\n"
	.string "to my little brother.$"

gFameCheckerPersonName_Pewter:: @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}How do you evolve CATERPIE?$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BROCK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In this big world of ours, there\n"
	.string "must be many tough TRAINERS.\p"
	.string "Let's both keep training and\n"
	.string "making ourselves stronger!$"

gFameCheckerPersonName_MtMoon:: @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Oh no! You can't run!$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MISTY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm going to keep training here at\n"
	.string "this GYM.\p"
	.string "When I get better, I'd love to hit\n"
	.string "the road and travel.$"

gFameCheckerPersonName_Cerulean:: @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}The TCG Capital$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LT. SURGE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, kid!\n"
	.string "You electrified me in our battle!\p"
	.string "I didn't know that there were\n"
	.string "gutsy TRAINERS like you.\p"
	.string "It made me change my mind about\n"
	.string "you!$"

gFameCheckerPersonName_Vermilion:: @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}How do you get CUT?$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: ERIKA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am so glad that there are strong\n"
	.string "TRAINERS like you.\p"
	.string "That awareness alone inspires and\n"
	.string "motivates me to try harder.\p"
	.string "Please visit me again.\n"
	.string "Zzz…$"

gFameCheckerPersonName_RockTunnel:: @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Gotta turn on the power...$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: KOGA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You and I, we must both set our\n"
	.string "sights higher and work towards\l"
	.string "meeting our challenges.\p"
	.string "Now, I must go train my daughter.$"

gFameCheckerPersonName_Lavender:: @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Copyright Trouble at the school!$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: SABRINA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The love you have towards your\n"
	.string "POKéMON…\p"
	.string "It was a power that was never\n"
	.string "bested by my psychic power.$"

gFameCheckerPersonName_Celadon:: @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}I can't find my house...$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BLAINE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My fire POKéMON!\n"
	.string "They'll become even more powerful!\p"
	.string "And now, a quiz. How many kinds of\n"
	.string "FIRE-type POKéMON are there?$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LORELEI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I needed to thank you for your\n"
	.string "help.\p"
	.string "But that has nothing to do with our\n"
	.string "battles.\p"
	.string "You'd better watch out next time!$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BRUNO\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The super power of your POKéMON\n"
	.string "and you I've experienced myself.\p"
	.string "Next time, maybe I should show you\n"
	.string "how to train yourself.$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: AGATHA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}When you grow older, don't you\n"
	.string "dare go soft like that coot OAK!\p"
	.string "Be like me and keep battling on!$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LANCE$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LANCE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm considering going back to my\n"
	.string "hometown.\p"
	.string "I want to retrain my DRAGON-type\n"
	.string "POKéMON and strengthen them.\p"
	.string "I'd like to invite you to my\n"
	.string "hometown one day.$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BILL\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, there! CELIO had nothing but\n"
	.string "praise for you.\p"
	.string "Hearing that makes me happy.\p"
	.string "When you catch some rare POKéMON,\n"
	.string "come show me, okay? Promise!$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MR. FUJI$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MR. FUJI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Instead of hoping for the happiness\n"
	.string "of just your POKéMON…\p"
	.string "…Can I get you to wish for the\n"
	.string "happiness of all POKéMON?$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: GIOVANNI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}There is nothing that I wish to say\n"
	.string "to you.\p"
	.string "I will concentrate solely on\n"
	.string "bettering myself, and none other.$"

gRumorLogFlavorTextIntoLine1_Pallet0:: @ 0x81B0C45
    .string "Tenured$"

gRumorLogFlavorTextIntoLine1_Pallet1::
    .string "Next-door$"

gRumorLogFlavorTextIntoLine1_Pallet2::
    .string "Bedroom$"

gRumorLogFlavorTextIntoLine1_Pallet3::
    .string "Loving$"

gRumorLogFlavorTextIntoLine1_Pallet4::
    .string "Meaningful$"

gRumorLogFlavorTextIntoLine1_Pallet5::
    .string "Strongly$"

gRumorLogFlavorTextIntoLine1_Viridian0::
    .string "Forlorn$"

gRumorLogFlavorTextIntoLine1_Viridian1::
    .string "Mysterious$"

gRumorLogFlavorTextIntoLine1_Viridian2::
    .string "Staring into$"

gRumorLogFlavorTextIntoLine1_Viridian3::
    .string "Curious$"

gRumorLogFlavorTextIntoLine1_Viridian4::
    .string "Anxious$"

gRumorLogFlavorTextIntoLine1_Viridian5::
    .string "Family$"

gRumorLogFlavorTextIntoLine1_Pewter0::
    .string "Kind$"

gRumorLogFlavorTextIntoLine1_Pewter1::
    .string "Clever$"

gRumorLogFlavorTextIntoLine1_Pewter2::
    .string "Garishly$"

gRumorLogFlavorTextIntoLine1_Pewter3::
	.string "A Father's$"

gRumorLogFlavorTextIntoLine1_Pewter4::
    .string "Technology is$"

gRumorLogFlavorTextIntoLine1_Pewter5::
    .string "Austere$"

gRumorLogFlavorTextIntoLine1_MtMoon0::
	.string "Corporate$"

gRumorLogFlavorTextIntoLine1_MtMoon1::
	.string "Loose-Fitting$"

gRumorLogFlavorTextIntoLine1_MtMoon2::
	.string "Concerned$"

gRumorLogFlavorTextIntoLine1_MtMoon3::
	.string "Severe$"

gRumorLogFlavorTextIntoLine1_MtMoon4::
	.string "Empathetic$"

gRumorLogFlavorTextIntoLine1_MtMoon5::
	.string "Guarded$"

gRumorLogFlavorTextIntoLine1_Cerulean0::
	.string "Always Vying$"

gRumorLogFlavorTextIntoLine1_Cerulean1::
	.string "Candy$"

gRumorLogFlavorTextIntoLine1_Cerulean2::
	.string "Familiar$"

gRumorLogFlavorTextIntoLine1_Cerulean3::
	.string "Spry$"

gRumorLogFlavorTextIntoLine1_Cerulean4::
	.string "Burgeoning$"

gRumorLogFlavorTextIntoLine1_Cerulean5::
	.string "Wistful$"

gRumorLogFlavorTextIntoLine1_Vermilion0::
	.string "Harbor$"

gRumorLogFlavorTextIntoLine1_Vermilion1::
	.string "Amicable$"

gRumorLogFlavorTextIntoLine1_Vermilion2::
	.string "Swindled$"

gRumorLogFlavorTextIntoLine1_Vermilion3::
	.string "Emigrated$"

gRumorLogFlavorTextIntoLine1_Vermilion4::
	.string "Seizure$"

gRumorLogFlavorTextIntoLine1_Vermilion5::
	.string "Disorganized$"

gRumorLogFlavorTextIntoLine1_RockTunnel0::
	.string "Disheartened$"

gRumorLogFlavorTextIntoLine1_RockTunnel1::
	.string "Crystaline$"

gRumorLogFlavorTextIntoLine1_RockTunnel2::
	.string "FUSHCIA GYM$"

gRumorLogFlavorTextIntoLine1_RockTunnel3::
	.string "FUSHCIA CITY$"

gRumorLogFlavorTextIntoLine1_RockTunnel4::
	.string "FUSHCIA CITY$"

gRumorLogFlavorTextIntoLine1_RockTunnel5::
	.string "SAFARI ZONE$"

gRumorLogFlavorTextIntoLine1_Lavender0::
	.string "Graveyard$"

gRumorLogFlavorTextIntoLine1_Lavender1::
	.string "Copywritten$"

gRumorLogFlavorTextIntoLine1_Lavender2::
	.string "Relieved$"

gRumorLogFlavorTextIntoLine1_Lavender3::
	.string "Preschool$"

gRumorLogFlavorTextIntoLine1_Lavender4::
	.string "SAFFRON CITY$"

gRumorLogFlavorTextIntoLine1_Lavender5::
	.string "Ghostly$"

gRumorLogFlavorTextIntoLine1_Celadon0::
	.string "Chaos$"

gRumorLogFlavorTextIntoLine1_Celadon1::
	.string "Troubled$"

gRumorLogFlavorTextIntoLine1_Celadon2::
	.string "Confused$"

gRumorLogFlavorTextIntoLine1_Celadon3::
	.string "Vertical$"

gRumorLogFlavorTextIntoLine1_Celadon4::
	.string "IP$"

gRumorLogFlavorTextIntoLine1_Celadon5::
	.string "Inspiring$"

gRumorLogFlavorTextIntoLine1_Fushcia0::
	.string "POKéMON LEAGUE$"

gRumorLogFlavorTextIntoLine1_Fushcia1::
	.string "POKéMON LEAGUE$"

gRumorLogFlavorTextIntoLine1_Fushcia2::
	.string "FOUR ISLAND$"

gRumorLogFlavorTextIntoLine1_Fushcia3::
	.string "FIVE ISLAND$"

gRumorLogFlavorTextIntoLine1_Fushcia4::
	.string "FOUR ISLAND$"

gRumorLogFlavorTextIntoLine1_Fushcia5::
	.string "FOUR ISLAND$"

gRumorLogFlavorTextIntoLine1_KantoShoreline0::
	.string "POKéMON LEAGUE$"

gRumorLogFlavorTextIntoLine1_KantoShoreline1::
	.string "POKéMON LEAGUE$"

gRumorLogFlavorTextIntoLine1_KantoShoreline2::
	.string "SAFFRON CITY$"

gRumorLogFlavorTextIntoLine1_KantoShoreline3::
	.string "EMBER SPA$"

gRumorLogFlavorTextIntoLine1_KantoShoreline4::
	.string "TWO ISLAND$"

gRumorLogFlavorTextIntoLine1_KantoShoreline5::
	.string "SEVAULT CANYON$"

gRumorLogFlavorTextIntoLine1_Agatha0::
	.string "POKéMON LEAGUE$"

gRumorLogFlavorTextIntoLine1_Agatha1::
	.string "INDIGO PLATEAU$"

gRumorLogFlavorTextIntoLine1_Agatha2::
	.string "INDIGO PLATEAU$"

gRumorLogFlavorTextIntoLine1_Agatha3::
	.string "SEVEN ISLAND$"

gRumorLogFlavorTextIntoLine1_Agatha4::
	.string "POKéMON LEAGUE$"

gRumorLogFlavorTextIntoLine1_Agatha5::
	.string "SIX ISLAND$"

gRumorLogFlavorTextIntoLine1_Lance0::
	.string "POKéMON LEAGUE$"

gRumorLogFlavorTextIntoLine1_Lance1::
	.string "POKéMON LEAGUE$"

gRumorLogFlavorTextIntoLine1_Lance2::
	.string "SAFFRON CITY$"

gRumorLogFlavorTextIntoLine1_Lance3::
	.string "CELADON DEPT.$"

gRumorLogFlavorTextIntoLine1_Lance4::
	.string "INDIGO PLATEAU$"

gRumorLogFlavorTextIntoLine1_Lance5::
	.string "INDIGO PLATEAU$"

gRumorLogFlavorTextIntoLine1_Bill0::
	.string "CERULEAN CITY$"

gRumorLogFlavorTextIntoLine1_Bill1::
	.string "CERULEAN CITY$"

gRumorLogFlavorTextIntoLine1_Bill2::
	.string "FUSHCIA CITY$"

gRumorLogFlavorTextIntoLine1_Bill3::
	.string "ONE ISLAND$"

gRumorLogFlavorTextIntoLine1_Bill4::
	.string "ONE ISLAND$"

gRumorLogFlavorTextIntoLine1_Bill5::
	.string "ONE ISLAND$"

gRumorLogFlavorTextIntoLine1_MrFuji0::
	.string "LAVENDER TOWN$"

gRumorLogFlavorTextIntoLine1_MrFuji1::
	.string "POKéMON TOWER$"

gRumorLogFlavorTextIntoLine1_MrFuji2::
	.string "LAVENDER TOWN$"

gRumorLogFlavorTextIntoLine1_MrFuji3::
	.string "LAVENDER TOWN$"

gRumorLogFlavorTextIntoLine1_MrFuji4::
	.string "CINNABAR GYM$"

gRumorLogFlavorTextIntoLine1_MrFuji5::
	.string "CINNABAR ISLAND$"

gRumorLogFlavorTextIntoLine1_Giovanni0::
	.string "ROCKET HIDEOUT$"

gRumorLogFlavorTextIntoLine1_Giovanni1::
	.string "SILPH CO.$"

gRumorLogFlavorTextIntoLine1_Giovanni2::
	.string "SILPH CO.$"

gRumorLogFlavorTextIntoLine1_Giovanni3::
	.string "VIRIDIAN GYM$"

gRumorLogFlavorTextIntoLine1_Giovanni4::
	.string "VIRIDIAN GYM$"

gRumorLogFlavorTextIntoLine1_Giovanni5::
	.string "ROCKET WAREHOUSE$"

gFameCheckerFlavorTextOriginObjectName_Pallet0::
	.string "Timber$"

gFameCheckerFlavorTextOriginObjectName_Pallet1::
	.string "Neighbor$"

gFameCheckerFlavorTextOriginObjectName_Pallet2::
	.string "Breadmaker$"

gFameCheckerFlavorTextOriginObjectName_Pallet3::
	.string "Guardian$"

gFameCheckerFlavorTextOriginObjectName_Pallet4::
	.string "Macguffin$"

gFameCheckerFlavorTextOriginObjectName_Pallet5::
	.string "Recommended$"

gFameCheckerFlavorTextOriginObjectName_Viridian0::
	.string "Franchiser$"

gFameCheckerFlavorTextOriginObjectName_Viridian1::
	.string "Stranger$"

gFameCheckerFlavorTextOriginObjectName_Viridian2::
	.string "The Abyss$"

gFameCheckerFlavorTextOriginObjectName_Viridian3::
	.string "Traveler$"

gFameCheckerFlavorTextOriginObjectName_Viridian4::
	.string "Barterer$"

gFameCheckerFlavorTextOriginObjectName_Viridian5::
	.string "Reuinion$"

gFameCheckerFlavorTextOriginObjectName_Pewter0::
	.string "Encouragement$"

gFameCheckerFlavorTextOriginObjectName_Pewter1::
	.string "Rascal$"

gFameCheckerFlavorTextOriginObjectName_Pewter2::
	.string "Gardening$"

gFameCheckerFlavorTextOriginObjectName_Pewter3::
	.string "Warning$"

gFameCheckerFlavorTextOriginObjectName_Pewter4::
	.string "Incredible!$"

gFameCheckerFlavorTextOriginObjectName_Pewter5::
	.string "Arbor$"

gFameCheckerFlavorTextOriginObjectName_MtMoon0::
	.string "Consortium$"

gFameCheckerFlavorTextOriginObjectName_MtMoon1::
	.string "and Breathable$"

gFameCheckerFlavorTextOriginObjectName_MtMoon2::
	.string "Explorer$"

gFameCheckerFlavorTextOriginObjectName_MtMoon3::
	.string "Scopophobia$"

gFameCheckerFlavorTextOriginObjectName_MtMoon4::
	.string "Legwear$"

gFameCheckerFlavorTextOriginObjectName_MtMoon5::
	.string "Wonders$"

gFameCheckerFlavorTextOriginObjectName_Cerulean0::
	.string "to be the Best$"

gFameCheckerFlavorTextOriginObjectName_Cerulean1::
	.string "Collector$"

gFameCheckerFlavorTextOriginObjectName_Cerulean2::
	.string "Face$"

gFameCheckerFlavorTextOriginObjectName_Cerulean3::
	.string "Spelunker$"

gFameCheckerFlavorTextOriginObjectName_Cerulean4::
	.string "Entrepreneur$"

gFameCheckerFlavorTextOriginObjectName_Cerulean5::
	.string "Dreamer$"

gFameCheckerFlavorTextOriginObjectName_Vermilion0::
	.string "Historian$"

gFameCheckerFlavorTextOriginObjectName_Vermilion1::
	.string "Aviarist$"

gFameCheckerFlavorTextOriginObjectName_Vermilion2::
	.string "Sweatwear$"

gFameCheckerFlavorTextOriginObjectName_Vermilion3::
	.string "Envoy$"

gFameCheckerFlavorTextOriginObjectName_Vermilion4::
	.string "Sentinel$"

gFameCheckerFlavorTextOriginObjectName_Vermilion5::
	.string "Driver$"

gFameCheckerFlavorTextOriginObjectName_RockTunnel0::
	.string "Denims$"

gFameCheckerFlavorTextOriginObjectName_RockTunnel1::
	.string "Caver$"

gFameCheckerFlavorTextOriginObjectName_RockTunnel2::
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_RockTunnel3::
	.string "CHARINE$"

gFameCheckerFlavorTextOriginObjectName_RockTunnel4::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_RockTunnel5::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Lavender0::
	.string "Guide$"

gFameCheckerFlavorTextOriginObjectName_Lavender1::
	.string "Creative$"

gFameCheckerFlavorTextOriginObjectName_Lavender2::
	.string "Ratkeeper$"

gFameCheckerFlavorTextOriginObjectName_Lavender3::
	.string "Pupil$"

gFameCheckerFlavorTextOriginObjectName_Lavender4::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lavender5::
	.string "Guide$"

gFameCheckerFlavorTextOriginObjectName_Celadon0::
	.string "Courier$"

gFameCheckerFlavorTextOriginObjectName_Celadon1::
	.string "Trader$"

gFameCheckerFlavorTextOriginObjectName_Celadon2::
	.string "Cartographer$"

gFameCheckerFlavorTextOriginObjectName_Celadon3::
	.string "Vexation$"

gFameCheckerFlavorTextOriginObjectName_Celadon4::
	.string "Inquisitor$"

gFameCheckerFlavorTextOriginObjectName_Celadon5::
	.string "Inclusivity!$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "OLD MAN$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "CRUSHER$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "OLD LADY$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "WOMAN$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "YOUNG MAN$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "LITTLE BOY$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "OLD MAN$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "LITTLE GIRL$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "TEAM ROCKET$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "MAGAZINE$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "PHOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "POKéMON JOURNAL$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "SCIENTIST$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "SCIENTIST$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "MAN$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GIDEON$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PEWTER GYM\n"
	.string "LEADER BROCK!\p"
	.string "BROCK rarely laughs, but is said to\n"
	.string "be unable to stop if he starts.$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CERULEAN GYM\n"
	.string "LEADER MISTY!\p"
	.string "MISTY is said to worship LORELEI\n"
	.string "of the ELITE FOUR.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: VERMILION GYM\n"
	.string "LEADER LT. SURGE!\p"
	.string "LT. SURGE is rumored to have been\n"
	.string "a pilot while home in America.\p"
	.string "He used the electricity generated\n"
	.string "by POKéMON to power his plane.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CELADON GYM\n"
	.string "LEADER ERIKA!\p"
	.string "Rumor has it that if you peek into\n"
	.string "CELADON GYM, you can often\l"
	.string "see ERIKA snoozing.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: FUSHCIA GYM\n"
	.string "LEADER KOGA!\p"
	.string "KOGA is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his POKéMON to health.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: SAFFRON GYM\n"
	.string "LEADER SABRINA!\p"
	.string "People say that SABRINA can\n"
	.string "communicate with her POKéMON\l"
	.string "during battle without speaking.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CINNABAR GYM\n"
	.string "LEADER BLAINE!\p"
	.string "BLAINE is said to remove his dark\n"
	.string "shades only when he is thinking up\l"
	.string "new quiz questions.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's LORELEI!\p"
	.string "Known for her logical, calculated,\n"
	.string "and cool battling style, LORELEI\l"
	.string "has a surprising secret!$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's BRUNO!\p"
	.string "BRUNO apparently joined the ELITE\n"
	.string "FOUR out of his burning ambition to\l"
	.string "battle the best TRAINERS.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's AGATHA!\p"
	.string "In her youth, AGATHA and PROF.\n"
	.string "OAK were rivals who vied for\l"
	.string "supremacy as TRAINERS.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's LANCE!\p"
	.string "LANCE's grandfather is thought to\n"
	.string "be the elder of a famous clan of\l"
	.string "dragon masters.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PROF. OAK,\n"
	.string "the POKéMON tree!\p"
	.string "PROF. OAK is continuing to grow\n"
	.string "at a rate of one ring per year!$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "This is a POKéMON JOURNAL from\n"
	.string "years ago…\p"
	.string "POKéMON JOURNAL\n"
	.string "CONTEST Special!\p"
	.string "The Spring POKéMON CONTEST's\n"
	.string "Grand Champion is DAISY OAK of\l"
	.string "PALLET TOWN!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "MR. FUJI of POKéMON HOUSE!\p"
	.string "Editor: The shy MR. FUJI turned\n"
	.string "down our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in LAVENDER TOWN.$"
