@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "My Secret Life, chapter three.\n"
	.string "\n"
	.string "I was neither a murder suspect, nor\n"
	.string "a target for an international spy\n"
	.string "organization.\n"
	.string "\n"
	.string "But I drove a car down the Jersey\n"
	.string "Turnpike at 80 mph.\n"
	.string "\n"
	.string "\.A police officer pulled me over\n"
	.string "and asked for my driver's license.\n"
	.string "\n"
	.string "He said I was going 20 mph over the\n"
	.string "speed limit. I instantly pointed to\n"
	.string "my wife and said, \qoI'm in a hurry,\n"
	.string "my wife is in labor.\qc\n"
	.string "\n"
	.string "Fortunately, my wife actually had a\n"
	.string "big stomach.\n"
	.string "\n"
	.string "I hoped he'd let me go with this\n"
	.string "excuse.\n"
	.string "\n"
	.string "\qoOh, since it's an emergency, I'll\n"
	.string "lead you to the hospital with my\n"
	.string "police car,\qc he said.\n"
	.string "\n"
	.string "\qoNo, it's not necessary.\qc\n"
	.string "\n"
	.string "\qoWhy not?\qc asked the officer.\n"
	.string "\qoUh\. well\.\qc\n"
	.string "\n"
	.string "\qoLet's get going,\qc said the officer.\n"
	.string "\n"
	.string "\qoNo, no! We can't! This baby is a\n"
	.string "demon child!\qc\n"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "A TOWN MAP.$"

Text_PokeMartShelf::
	.string "Wow!\n"
	.string "Tons of POKéMON stuff!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Dishes and plates are neatly\n"
	.string "lined up.$"

Text_Kitchen::
	.string "It smells delicious!\n"
	.string "Somebody's been cooking here.$"

Text_Dresser::
	.string "It's a nicely made dresser.\n"
	.string "It will hold a lot of stuff.$"

Text_Snacks::
	.string "There's a pile of snacks here.$"

Text_PokemartSign::
	.string "All your item needs fulfilled!\n"
	.string "POKéMON MART$"

Text_PokecenterSign::
	.string "Heal Your POKéMON!\n"
	.string "POKéMON CENTER$"

Text_Indigo_UltimateGoal::
	.string "INDIGO PLATEAU\p"
	.string "The ultimate goal of TRAINERS!\n"
	.string "POKéMON LEAGUE HQ$"

Text_Indigo_HighestAuthority::
	.string "INDIGO PLATEAU\p"
	.string "The highest POKéMON authority!\n"
	.string "POKéMON LEAGUE HQ$"

Text_Food::
	.string "It should be packed with all kinds\n"
	.string "of delicious things to eat.$"

Text_Blueprints::
	.string "It's a blueprint of some sort.\n"
	.string "It's filled with diagrams and text.$"

Text_Painting::
	.string "It's a pretty picture of a POKéMON.\n"
	.string "It looks like it's feeling good.$"

Text_PowerPlantMachine::
	.string "What could this machine be?\n"
	.string "Better not mess around with it!$"

Text_Telephone::
	.string "It's a telephone.\n"
	.string "Better not use it.$"

Text_Computer::
	.string "It's all complicated words and\n"
	.string "numbers that make no sense…$"

Text_AdvertisingPoster::
	.string "It's an advertising poster about\n"
	.string "all kinds of products.$"

Text_TastyFood::
	.string "Oh, that smells tasty!\n"
	.string "It might get the stomach growling!$"

Text_TrashBin::
	.string "Inside this…\n"
	.string "……\p"
	.string "There's nothing here!$"

Text_Cup::
	.string "It's a cup with a POKéMON mark\n"
	.string "on it.$"

Text_PolishedWindow::
	.string "The window is very well polished.$"

Text_BeautifulSkyWindow::
	.string "Outside the window…\p"
	.string "The sky looks fantastically\n"
	.string "beautiful.$"

Text_BlinkingLights::
	.string "Lights in different colors are\n"
	.string "flashing on and off.$"

Text_NeatlyLinedUpTools::
	.string "All sorts of tools are lined up\n"
	.string "neatly.$"

Text_ImpressiveMachine::
	.string "It's a machine of some sort.\n"
	.string "It sure is impressive.$"

Text_VideoGame::
	.string "It's the latest video game!\n"
	.string "It sure looks fun!$"

Text_Burglary::
	.string "There are obvious signs of burglary\n"
	.string "here…$"

Text_PlayerFacingTVScreen::
	.string "There's a POKéMON on TV!\n"
	.string "It looks like it's having fun.$"
