@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "My Secret Life, chapter three.\p"
	.string "I was neither a murder suspect, nor\n"
	.string "a target for an international spy\l"
	.string "organization.\p"
	.string "But I drove a car down the Jersey\n"
	.string "Turnpike at 80 mph.\p"
	.string "…A police officer pulled me over\n"
	.string "and asked for my driver's license.\p"
	.string "He said I was going 20 mph over the\n"
	.string "speed limit. I instantly pointed to\l"
	.string "my wife and said, “I'm in a hurry,\l"
	.string "my wife is in labor.”\p"
	.string "Fortunately, my wife actually had a\n"
	.string "big stomach.\p"
	.string "I hoped he'd let me go with this\n"
	.string "excuse.\p"
	.string "“Oh, since it's an emergency, I'll\n"
	.string "lead you to the hospital with my\l"
	.string "police car,” he said.\p"
	.string "“No, it's not necessary.”\p"
	.string "“Why not?” asked the officer.\n"
	.string "“Uh… well…”\p"
	.string "“Let's get going,” said the officer.\p"
	.string "“No, no! We can't! This baby is a\n"
	.string "demon child!”$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "A TOWN MAP.$"

Text_PokeMartShelf::
	.string "The POTION section is suspiciously\n"
	.string "empty.$"

Text_DishesPlatesNeatlyLinedUp::
	.string "This arranging for mother is\n"
	.string "quite adept!\l"
	.string "Volcano Bakemeat!$"

Text_Kitchen::
	.string "This arranging for mother is\n"
	.string "quite adept!\l"
	.string "Volcano Bakemeat!$"

Text_Dresser::
	.string "Twelve identical copies of your\n"
	.string "favorite shirt.$"

Text_Snacks::
	.string "There's a pile of snacks here.$"

Text_PokemartSign::
	.string "All your item needs fulfilled!\n"
	.string "POKéMON MART$"

Text_PokecenterSign::
	.string "Heal Your POKéMON!\n"
	.string "POKéMON CENTER$"

Text_Indigo_UltimateGoal::
	.string "INDIGO PLATEAU\p"
	.string "The ultimate goal of TRAINERS!\n"
	.string "POKéMON LEAGUE HQ$"

Text_Indigo_HighestAuthority::
	.string "INDIGO PLATEAU\p"
	.string "The highest POKéMON authority!\n"
	.string "POKéMON LEAGUE HQ$"

Text_Food::
	.string "It should be packed with all kinds\n"
	.string "of delicious things to eat.$"

Text_Blueprints::
	.string "It's a blueprint of some sort.\n"
	.string "It's filled with diagrams and text.$"

Text_Painting::
	.string "It's a pretty picture of a POKéMON.\n"
	.string "It looks like it's feeling good.$"

Text_PowerPlantMachine::
	.string "It appears to be a hobbyist\n"
	.string "nuclear reactor.$"

Text_Telephone::
	.string "It's a telephone.\n"
	.string "Better not use it.$"

Text_Computer::
	.string "It's all complicated words and\n"
	.string "numbers that make no sense…$"

Text_AdvertisingPoster::
	.string "It's an advertising poster about\n"
	.string "all kinds of products.$"

Text_TastyFood::
	.string "Oh, that smells tasty!\n"
	.string "It might get the stomach growling!$"

Text_TrashBin::
	.string "Inside this…\n"
	.string "……\p"
	.string "There's nothing here!$"

Text_Cup::
	.string "It's a cup with a POKéMON mark\n"
	.string "on it.$"

Text_PolishedWindow::
	.string "The window is very well polished.$"

Text_BeautifulSkyWindow::
	.string "Outside the window…\p"
	.string "The sky looks fantastically\n"
	.string "beautiful.$"

Text_BlinkingLights::
	.string "Oh no!\n"
	.string "The patient is flatlining!$"

Text_NeatlyLinedUpTools::
	.string "The wall is painted over to give\n"
	.string "the appearance of merchandise.$"

Text_ImpressiveMachine::
	.string "It's a machine of some sort.\n"
	.string "It sure is impressive.$"

Text_VideoGame::
	.string "It's the latest video game!\n"
	.string "It sure looks fun!$"

Text_Burglary::
	.string "There are obvious signs of burglary\n"
	.string "here…$"

Text_PlayerFacingTVScreen::
	.string "Wasn't this episode banned in this\n"
	.string "country?$"
