gOtherText_NewName::
    .string "NEW NAME$"

gNameChoice_Green::
    .string " $"

gNameChoice_Red::
    .string " $"

gNameChoice_Leaf::
    .string " $"

gNameChoice_Fire::
    .string " $"

gNameChoice_Gar::
    .string " $"

gNameChoice_Gary::
    .string "GARY$"

gNameChoice_Kaz::
    .string " $"

gNameChoice_Toru::
    .string " $"

gNameChoice_Ash::
    .string " $"

gNameChoice_Kene::
    .string " $"

gNameChoice_Geki::
    .string " $"

gNameChoice_Jak::
    .string " $"

gNameChoice_Janne::
    .string " $"

gNameChoice_Jonn::
    .string " $"

gNameChoice_Kamon::
    .string " $"

gNameChoice_Karl::
    .string " $"

gNameChoice_Taylor::
    .string " $"

gNameChoice_Oscar::
    .string " $"

gNameChoice_Hiro::
    .string " $"

gNameChoice_Max::
    .string " $"

gNameChoice_Jon::
    .string " $"

gNameChoice_Ralph::
    .string " $"

gNameChoice_Kay::
    .string " $"

gNameChoice_Tosh::
    .string " $"

gNameChoice_Roak::
    .string " $"

gNameChoice_Omi::
    .string " $"

gNameChoice_Jodi::
    .string " $"

gNameChoice_Amanda::
    .string " $"

gNameChoice_Hillary::
    .string " $"

gNameChoice_Makey::
    .string " $"

gNameChoice_Michi::
    .string " $"

gNameChoice_Paula::
    .string " $"

gNameChoice_June::
    .string " $"

gNameChoice_Cassie::
    .string " $"

gNameChoice_Rey::
    .string " $"

gNameChoice_Seda::
    .string " $"

gNameChoice_Kiko::
    .string " $"

gNameChoice_Mina::
    .string " $"

gNameChoice_Norie::
    .string " $"

gNameChoice_Sai::
    .string " $"

gNameChoice_Momo::
    .string " $"

gNameChoice_Suzi::
    .string " $"

gControlsGuide_Text_Intro::
    .string "The various shortcuts will be explained in\n"
    .string "the order of their importance.$"

gControlsGuide_Text_DPad::
    .string "Speeds up the game.\n"
    .string "Will be very useful for grinding.$"

gControlsGuide_Text_AButton::
    .string "Creates a savestate which\n"
    .string "you can later load.$"

gControlsGuide_Text_BButton::
    .string "Loads a savestate.\n"
    .string "Or was it the other way around?$"

gControlsGuide_Text_StartButton::
    .string "This key combination will enter\n"
    .string "developer mode.$"

gControlsGuide_Text_SelectButton::
    .string "Enables Sticky Keys on Windows.$"

gControlsGuide_Text_LRButtons::
    .string "Performing this input will throw\n"
    .string "a Hadoken.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Now tell me.\n"
    .string "What sprite do you want?$"

gPikachuIntro_Text_Page1::
    .string "Hi! This is a stupid hack that I made\n"
    .string "to enjoy with my friends. The best way\n"
    .string "to play is with a group of people!\n"
    .string "\n"
    .string "There's a lot of stupid stuff,\n"
    .string "but mostly it's tons of fun.\n"
    .string "I highly recommend completing\n"
    .string "the POKéDEX as you play!$"

gPikachuIntro_Text_Page2::
    .string "This hack will require a decent amount\n"
    .string "of prior knowledge on the POKéMON\n"
    .string "series to be fully enjoyed.\n"
    .string "\n"
    .string "It's like 30% puzzles,\n"
    .string "30% trivia, 30% comedy\n"
    .string "and 10% complete nonsense.$"

gPikachuIntro_Text_Page3::
    .string "Savestate frequently!\n"
    .string "There is a lot in this hack\n"
    .string "that will be completely unfair.\n"
    .string "\n"
    .string "The point of it isn't to provide\n"
    .string "a challenge, but to enjoy\n"
    .string "the absurdity of it.\n"
    .string "Have fun!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Hello, there!\n"
    .string "I am an OAK!\p"
    .string "Welcome to this stupid ROMhack!\p$"

gOakSpeech_Text_ThisWorld::
    .string "This world…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…is inhabited far and wide by\n"
    .string "creatures called POKéMON.\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\p"
    .string "As for myself…\p"
    .string "I am a tree.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "This is my grandson.\p"
    .string "He's been your rival since 1996!\p"
    .string "…Erm, what was his name now?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Was it LARRY? No…\n"
    .string "Perhaps JERRY? Hmm, not quite…$"

gOakSpeech_Text_ConfirmRivalName::
    .string "…Er, it's {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "Wait, {RIVAL}?\n"
    .string "That can't be right!\p"
    .string "His name is GARY, not {RIVAL}.\n"
    .string "Haven't you seen the TV show?\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "A world of stupidity and nonsense\n"
    .string "awaits! Let's go!$"
