Text_MayIHelpYou::
	.string "Hi, there!\n"
	.string "May I help you?$"

Text_FillOutQuestionnaire::
	.string "MYSTERY GIFT is not supported\n"
	.string "in this ROMhack. Sorry!\l"
	.string "Fill the questionnaire out anyway?$"

Text_QuestionnaireThankYou::
	.string "Thank you for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "This questionnaire loves you.$"

Text_YouKnowThoseWords::
	.string "Oh, uh...\n"
	.string "Hi!\l"
	.string "Why'd you do that?\p"
	.string "I literally just told you that\n"
	.string "MYSTERY GIFT isn't in this hack.\p"
	.string "Sigh...\n"
	.string "Fine.\l"
	.string "Here's the your menu option.$"

Text_YouCanAccessMysteryGift::
	.string "Once you save your game, you can\n"
	.string "see a reflection of your true self.$"

Text_ThankYouForAccessingMysteryGift::
	.string "Thank you for accessing the\n"
	.string "MYSTERY GIFT System.$"
