PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_HaHa::
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"


PokedexRating_Text_HintVictini::
	.string "Have you been to the mysterious\n"
	.string "ZERO ISLAND?\p"
	.string "The three pillars there seem to be\n"
	.string "pointing to artifices elsewhere.$"

PokedexRating_Text_HintBulbasaur::
	.string "SECRET GARDEN has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintCharmander::
	.string "Hey! How did you get here without\n"
	.string "your starter POKéMON?$"

PokedexRating_Text_HintCharmeleon::
	.string "Your CHARMANDER can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintCharizard::
	.string "Your CHARMELEON can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintSquirtle::
	.string "Oh wow!\n"
	.string "Your CHARIZARD sure evolved early!\p"
	.string "I wonder if there's a reason for\n"
	.string "that…$"

PokedexRating_Text_HintIvysaur::
	.string "Oh? It seems that your STARTER\n"
	.string "is ready to evolve again!\p"
	.string "I wonder why…\n$"

PokedexRating_Text_HintHitmonchin::
	.string "You found a PERSIAN by fishing in\n"
	.string "the VIRIDIAN GYM statues?\l"
	.string "Incredible!\p"
	.string "So wait, what about the other\n"
	.string "GYMS' statues?$"

PokedexRating_Text_HintCaterpie::
	.string "VIRIDIAN FOREST has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintMetapod::
	.string "VIRIDIAN FOREST has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintButterfree::
	.string "CATERPIE doesn't seem to evolve\n"
	.string "until a much higher level.\p"
	.string "I think trying to evolve it directly\n"
	.string "is a lost cause.\p"
	.string "Perhaps there's a different way to\n"
	.string "get to BUTTERFREE…$"

PokedexRating_Text_HintWeedle::
	.string "VIRIDIAN CITY has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintKakuna::
	.string "If you look at the POKéDEX listing,\n"
	.string "an icon will appear by species\l"
	.string "you're able to obtain.\p"
	.string "Keep an eye on the list to know\n"
	.string "what you should have!\p"
	.string "It seems like your WEEDLE can\n"
	.string "still evolve.\l"
	.string "Try leveling it up!$"

PokedexRating_Text_HintCombee::
	.string "If you look at the POKéDEX listing,\n"
	.string "an icon will appear by species\l"
	.string "you're able to obtain.\p"
	.string "Keep an eye on the list to know\n"
	.string "what you should have!\p"
	.string "It seems like your KAKUNA can\n"
	.string "still evolve.\l"
	.string "Try leveling it up!$"

PokedexRating_Text_HintPidgey::
	.string "Placeholder!$"

PokedexRating_Text_HintPidgeotto::
	.string "ROUTE 3 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintPidgeot::
	.string "Your PIDGEOTTO can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintRattata::
	.string "ROUTE 1 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintRaticate::
	.string "Placeholder!$"

PokedexRating_Text_HintEkans::
	.string "ROUTE 3 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintArbok::
	.string "Your EKANS can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintSeviper::
	.string "Your EKANS sure evolved early!\n"
	.string "I wonder if there's a reason…$"

PokedexRating_Text_HintPhione::
	.string "I heard there was an EGG deliveryman\n"
	.string "in CELADON who got himself stuck.\p"
	.string "Were you able to talk with him?$"

PokedexRating_Text_HintRaichu::
	.string "There was a girl on ROUTE 5 offering\n"
	.string "to trade her RAICHU for a MEOWTH.\p"
	.string "That deal seems too good to be true.\n"
	.string "You should take it while you can!$"

PokedexRating_Text_HintMeowth::
	.string "ROUTE 4 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintPersian::
	.string "There was a man in VIRIDIAN GYM\n"
	.string "trying to fish something up.\p"
	.string "Maybe he was on to something…\n"
	.string "Have you tried doing that too?$"

PokedexRating_Text_HintSandshrew::
	.string "ROUTE 3 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintSandslash::
	.string "Your SANDSHREW can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintNidoranf::
	.string "ROUTE 22 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintNidorina::
	.string "Your NIDOTRAN♀ can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintNidoqueen::
	.string "The CELADON DEPT STORE sells\n"
	.string "evolution stones.\p"
	.string "One stone resembles something very\n"
	.string "important to one of your POKéMON!$"

PokedexRating_Text_HintNidoranm::
	.string "ROUTE 22 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintNidorino::
	.string "Your NIDOTRAN♂ can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintNidoking::
	.string "The CELADON DEPT STORE sells\n"
	.string "evolution stones.\p"
	.string "One stone resembles something very\n"
	.string "important to one of your POKéMON!$"

PokedexRating_Text_HintClefairy::
	.string "MT MOON has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintClefable::
	.string "Your CLEFAIRY can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintGengar::
	.string "They say something strange can\n"
	.string "happen when CLEFABLE evolves.\p"
	.string "Perhaps you could look into that?\n$"

PokedexRating_Text_HintVulpix::
	.string "ROUTE 8 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintNinetales::
	.string "Your VULPIX can't use a FIRE STONE?\n"
	.string "How odd!\p"
	.string "Maybe something has changed about\n"
	.string "it that might give you a clue.$"

PokedexRating_Text_HintJigglypuff::
	.string "ROUTE 4 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintVenonat::
	.string "You found a PERSIAN by fishing in\n"
	.string "the VIRIDIAN GYM statues?\l"
	.string "Incredible!\p"
	.string "So wait, what about the other\n"
	.string "GYMS' statues?$"

PokedexRating_Text_HintZubat::
	.string "Placeholder!$"

PokedexRating_Text_HintWoobat::
	.string "When you released ZUBAT across the\n"
	.string "waters, they were locked in a cave.\p"
	.string "What did that inscription read?\n"
	.string "What do you have that might match?$"

	
PokedexRating_Text_HintOddish::
	.string "The MUSHROOM MANIAC on TWO ISLAND\n"
	.string "wants to know how his good friend\l"
	.string "the BERRY POWDER MAN is?\p"
	.string "Hmm…\n"
	.string "Can't say I've ever heard of him.\p"
	.string "Maybe use some external help to\n"
	.string "find where he's supposed to be?$"

	
PokedexRating_Text_HintGimmighoul::
	.string "The reward from the SAFARI ZONE\n"
	.string "was quite underwhelming!\p"
	.string "Maybe there's still something you\n"
	.string "can do with it…$"

PokedexRating_Text_HintGholdengo::
	.string "Your GIMMIGHOUL can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintParas::
	.string "MT MOON has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintParasect::
	.string "It seems that PARAS now harnesses\n"
	.string "the power of the SUN!\p"
	.string "Perhaps there's a way to focus that\n"
	.string "power further?$"

PokedexRating_Text_HintJirachi::
	.string "In the CELADON CITY GAME STORE,\n"
	.string "there was a man counting something.\p"
	.string "I wonder what he was doing!\n$"

PokedexRating_Text_HintDiglett::
	.string "DIGLETTS' CAVE has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintDigletts::
	.string "Your DIGLETT can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintGolduck::
	.string "One path in CELADON CITY led to a\n"
	.string "strange, faraway land.\p"
	.string "Was there someone there you could\n"
	.string "talk to?$"

PokedexRating_Text_HintPsyduck::
	.string "Your PSYDUCK can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintMankey::
	.string "ROUTE 22 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintPrimeape::
	.string "Your MANKEY can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintCubone::
	.string "ROUTE 11 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintMarowak::
	.string "Your CUBONE can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintPoliwag::
	.string "Now that you've found a FISHING\n"
	.string "ROD, you should try using it!$"

PokedexRating_Text_HintTentaquil::
	.string "Your POLIWAG can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintAbra::
	.string "ROUTE 24 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintMissingno::
	.string "Placeholder!$"

PokedexRating_Text_HintKangaskhan::
	.string "There was a poor POKéMON in the\n"
	.string "SAFARI ZONE imprisoned by the DMCA.\p"
	.string "Maybe now you can help it!\n"
	.string "What did that TM say?$"
	
PokedexRating_Text_HintAlakazam::
	.string "Placeholder!$"

PokedexRating_Text_HintPlugOink::
	.string "Looking for sandwich ingredients,\n"
	.string "you say?\l"
	.string "How tricky!\p"
	.string "Wasn't there a trainer near\n"
	.string "FUSHCIA who wanted to trade?$"

PokedexRating_Text_HintMachoke::
	.string "Have you talked to everyone in\n"
	.string "FUSHCIA CITY?\p"
	.string "That's a good way to find new\n"
	.string "POKéMON!$"

PokedexRating_Text_HintMachamp::
	.string "You're looking for your last\n"
	.string "evolutions?\l"
	.string "Good luck!\p"
	.string "Remember to keep a close eye on\n"
	.string "your POKéDEX.\l"
	.string "It may have useful information.$"

PokedexRating_Text_HintSlowpoke::
	.string "Have you talked to everyone in\n"
	.string "FUSHCIA CITY?\p"
	.string "That's a good way to find new\n"
	.string "POKéMON!$"

PokedexRating_Text_HintGyarados::
	.string "A man in the POKéMON CENTER before\n"
	.string "MT MOON was selling something.\p"
	.string "It was a very good deal.\n"
	.string "You should take it!$"

PokedexRating_Text_HintMagikarp::
	.string "Your GYARADOS can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintBellsprout::
	.string "ROUTE 24 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintCherubi::
	.string "Your BELLSPROUT can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintTentacool::
	.string "MT MOON has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintToedscool::
	.string "I heard my AIDE delivered RUNNING\n"
	.string "SHOES, but you didn't need them.\p"
	.string "Maybe you could try giving them to\n"
	.string "a POKéMON instead!$"

PokedexRating_Text_HintGeodude::
	.string "You found a PERSIAN by fishing in\n"
	.string "the VIRIDIAN GYM statues?\l"
	.string "Incredible!\p"
	.string "So wait, what about the other\n"
	.string "GYMS' statues?$"

PokedexRating_Text_HintGraveler::
	.string "Your GEODUDE can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintGolem::
	.string "You're looking for your last\n"
	.string "evolutions?\l"
	.string "Good luck!\p"
	.string "Remember to keep a close eye on\n"
	.string "your POKéDEX.\l"
	.string "It may have useful information.$"


PokedexRating_Text_HintDitto::
	.string "Now that you have SURF, you can\n"
	.string "explore many places you couldn't!\p"
	.string "Wasn't there someone looking for\n"
	.string "their TRUCK in VERMILION CITY?$"

PokedexRating_Text_HintUnown::
	.string "Oh no! A man on ROUTE 11 says that\n"
	.string "his daughter got lost in the woods!\p"
	.string "Maybe you could go find her for him?\n$"

PokedexRating_Text_HintMagnemite::
	.string "THIRTY EIGHT ISLAND has a wild"
	.string "POKéMON you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintMagnalone::
	.string "Placeholder!$"

PokedexRating_Text_HintDoduo::
	.string "ROUTE 7 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintHitmonchan::
	.string "Your DODUO can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintSeal::
	.string "MINNESOTA has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintPinsir::
	.string "There's a BUG CATCHING CONTEST in\n"
	.string "JOHTO?\p"
	.string "Why don't you try looking in the\n"
	.string "grass there… … …Wha-\l"
	.string "Hey!$"


PokedexRating_Text_HintGrimer::
	.string "A BUG CATCHER in PEWTER CITY was\n"
	.string "spraying REPEL in the grass.\p"
	.string "Maybe there's a different way to\n"
	.string "make a wild POKéMON appear…$"

PokedexRating_Text_HintMuk::
	.string "An alien appeared and gave you a\n"
	.string "MOON STONE?\p"
	.string "I bet if you read your POKéDEX\n"
	.string "carefully, you could figure out\l"
	.string "what to use it on.$"


PokedexRating_Text_HintShellder::
	.string "I hear if you comb the beach,\n"
	.string "you can find many valuables.\p"
	.string "You should see if you can find\n"
	.string "anything on ROUTE 15!$"

PokedexRating_Text_HintSlowbro::
	.string "I think someone in CELADON\n"
	.string "mentioned evolving a SLOWBRO.\p"
	.string "I wonder what evolved into\n"
	.string "it?$"

PokedexRating_Text_HintCastform::
	.string "It looks like you've found all the\n"
	.string "POKéMON SIGNS across KANTO!\l"
	.string "Well done!\p"
	.string "Go back to the POKéMON ISLAND LAB\n"
	.string "and see what they'll tell us.$"

PokedexRating_Text_HintHaunter::
	.string "There was a woman in CINNABAR who\n"
	.string "wanted to trade for a RAICHU.\p"
	.string "I wonder where you might find one\n"
	.string "you can keep.$"

PokedexRating_Text_HintCloyster::
	.string "The CAVE OF ORIGIN has a POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintOnix::
	.string "The CAVE OF ORIGIN has a POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"


PokedexRating_Text_HintPorygon::
	.string "The SLOT MACHINES at the GAME CORNER\n"
	.string "are all broken!\p"
	.string "Maybe there's another way to find\n"
	.string "the COINS to buy a PORYGON…$"

PokedexRating_Text_HintPorygonZ::
	.string "Oh dear, {PLAYER}…\n"
	.string "I think your TRAINER ID got leaked.\l"
	.string "It's showing up everywhere online.\p"
	.string "I hope those PC WALLPAPERS you\n"
	.string "foolishly installed were worth it!$"

PokedexRating_Text_HintKrabby::
	.string "I hear that all evolutionary trees\n"
	.string "will eventually converge.\p"
	.string "Whatever POKéMON awaits at the end\n"
	.string "must be the ultimate form of life!$"

PokedexRating_Text_HintVoltorb::
	.string "ROUTE 10 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintJiglypuffAbove::
	.string "Your VOLTORB can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintExeggcute::
	.string "ROUTE 5 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintExeggutor::
	.string "A man on ROUTE 8 said he evolved his\n"
	.string "EXEGGCUTE wrong.\p"
	.string "No wonder he wasn't able to find\n"
	.string "CUT!$"

PokedexRating_Text_HintSpearow::
	.string "Wild SPEAROW have mysteriously\n"
	.string "vanished from KANTO.\p"
	.string "I hear that someone in VERMILLION\n"
	.string "was able to get one another way…$"

PokedexRating_Text_HintKenya::
	.string "The guard on ROUTE 11 mentioned a\n"
	.string "friend waiting for him in VIRIDIAN.\p"
	.string "Maybe you should go check on him?\n$"

PokedexRating_Text_HintFarfetchd::
	.string "There's a girl in VERMILLION CITY\n"
	.string "who's offering a trade.\p"
	.string "You should talk to her!\n$"

PokedexRating_Text_HintGolurk::
	.string "ROUTE 16 has a wild POKéMON\n"
	.string "you never caught.\l"
	.string "Be sure to go back for it!$"

PokedexRating_Text_HintBidoof::
	.string "There's an NPC in SILPH CO. you\n"
	.string "forgot to talk to.$"


PokedexRating_Text_HintSmeargle::
	.string "The yellow trees on FOUR ISLAND\n"
	.string "seemed mighty suspicious.\l"
	.string "I wonder what they're hiding.\p"
	.string "By the way, have you looked at your\n"
	.string "POKéMON's abilities?$"


PokedexRating_Text_HintTangela::
	.string "You found a PERSIAN by fishing in\n"
	.string "the VIRIDIAN GYM statues?\l"
	.string "Incredible!\p"
	.string "So wait, what about the other\n"
	.string "GYMS' statues?$"

PokedexRating_Text_HintTrubbish_Trash::
	.string "The older HAIRCUT brother says\n"
	.string "he's looking for a challenge.\p"
	.string "What POKéMON have you caught with\n"
	.string "extraordinarily unruly hair?$"

PokedexRating_Text_HintAmpharos_Mega::
	.string "You turned the POWER PLANT back\n"
	.string "on?\l"
	.string "Wonderful!\p"
	.string "That means the KANTO LIGHTHOUSE\n"
	.string "should be back in service!$"

PokedexRating_Text_HintAmpharos::
	.string "People often do things in the\n"
	.string "darkness of the UNDERGROUND PATH.$"

PokedexRating_Text_HintAmoongus::
	.string "KURT from SILPH CO. makes such\n"
	.string "wonderful POKé BALLS.\p"
	.string "Say, wasn't there something a bit\n"
	.string "suspicious in his collection?$"


PokedexRating_Text_HintRhydon::
	.string "You found a PERSIAN by fishing in\n"
	.string "the VIRIDIAN GYM statues?\l"
	.string "Incredible!\p"
	.string "So wait, what about the other\n"
	.string "GYMS' statues?$"

PokedexRating_Text_HintChansey::
	.string "Why, it seems you can finally\n"
	.string "employ the letter Y in names again!\l"
	.string "Yay!\p"
	.string "Didn't someone ask if you wanted\n"
	.string "a POKéMON?$"

PokedexRating_Text_HintHorsea::
	.string "Your POKéDEX has many valuable\n"
	.string "features.\p"
	.string "Did you know you can check the\n"
	.string "AREA where a POKéMON can be found?\l"
	.string "Be sure to check it often!$"

PokedexRating_Text_HintDragonite::
	.string "Your POKéDEX has many valuable\n"
	.string "features.\p"
	.string "Did you know you can check the\n"
	.string "AREA where a POKéMON can be found?\l"
	.string "Be sure to check it often!$"

PokedexRating_Text_HintYoshi::
	.string "The DMCA said they'd kept an ITEM\n"
	.string "that induced an illegal evolution.\p"
	.string "I'd bet that SUPER SCOPE of\n"
	.string "yours would fit the bill.\l"
	.string "Maybe it'll chase them out!$"

PokedexRating_Text_HintZygarde::
	.string "AMITY SQUARE on FOUR ISLAND has\n"
	.string "some particularly strict rules.\l"
	.string "Only certain POKéMON can enter!\p"
	.string "But wait, what was the list again?\n$"


PokedexRating_Text_HintMelmanure::
	.string "Placeholder!$"

PokedexRating_Text_HintEternatus::
	.string "With FLY, you can truly travel\n"
	.string "anywhere in KANTO in an instant!\p"
	.string "Have you looked carefully at the\n"
	.string "map when you do this?\l"
	.string "There might be somewhere to check.$"

PokedexRating_Text_HintStarmie::
	.string "You found a PERSIAN by fishing in\n"
	.string "the VIRIDIAN GYM statues?\l"
	.string "Incredible!\p"
	.string "So wait, what about the other\n"
	.string "GYMS' statues?$"

PokedexRating_Text_HintMrMime::
	.string "The SILPH CO President was quite\n"
	.string "generous to give you…\l"
	.string "Huh?$"


PokedexRating_Text_HintJynx::
	.string "There was a man in CERULEAN offering\n"
	.string "a trade.\l"
	.string "You should take it!$"

PokedexRating_Text_HintTauros::
	.string "Have you talked to everyone in\n"
	.string "FUSHCIA CITY?\p"
	.string "That's a good way to find new\n"
	.string "POKéMON!$"

PokedexRating_Text_HintScyther::
	.string "A trainer in CERULEAN GYM says he\n"
	.string "can give you a strong card.\p"
	.string "Open up a space in your deck so you\n"
	.string "can take it!$"

PokedexRating_Text_HintPikablu::
	.string "Placeholder!$"

PokedexRating_Text_HintLuvdisc::
	.string "Placeholder!$"

PokedexRating_Text_HintAlomomola::
	.string "Placeholder!$"

PokedexRating_Text_HintAlcreamie::
	.string "The CREAM DROP you were given seems\n"
	.string "to have a mind of its own.\p"
	.string "How might you induce it to change\n"
	.string "in some way?$"


PokedexRating_Text_HintEevee::
	.string "You seriously didn't steal that\n"
	.string "man's EEVEE?\p"
	.string "I mean, I commend your integrity but\n"
	.string "come on…$"

PokedexRating_Text_HintSylveon::
	.string "The CELADON DEPT STORE sells\n"
	.string "evolution stones.\p"
	.string "You have an EEVEE, right?\n"
	.string "Maybe you should use one on it!$"

PokedexRating_Text_HintLatias::
	.string "That cool floaty rock you found\n"
	.string "seems to induce EVOLUTION!\p"
	.string "If you look carefully at it, it\n"
	.string "should seem familiar.\p"
	.string "What POKéMON normally holds it?\n"
	.string "Your POKéDEX might give a clue.$"

PokedexRating_Text_HintSolaceon::
	.string "The top of the cliff on FOUR ISLAND\n"
	.string "had a very peculiar layout.\p"
	.string "What POKéMON could be found in\n"
	.string "the grass there?\l"
	.string "What might that ROCK be suggesting?$"

PokedexRating_Text_HintHoopa::
	.string "There's legends of a POKéMON so\n"
	.string "powerful, it had to be Sealed away.\p"
	.string "Maybe if you were to destroy the\n"
	.string "Seal, it would be released.$"

PokedexRating_Text_HintMimikyu::
	.string "The COPYCAT household in SAFFRON\n"
	.string "is going through some troubles.\p"
	.string "Say, have you looked through your\n"
	.string "items lately?$"


PokedexRating_Text_HintOmanyte::
	.string "ROUTE 9 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintTyranastar::
	.string "Wasn't there a man in the POWER\n"
	.string "PLANT who was waiting for a third\l"
	.string "MAGNEMITE?\p"
	.string "You should bring yours over!\n$"

	
PokedexRating_Text_HintBuzzwole::
	.string "Scientists found a sample of OLD\n"
	.string "AMBER at the PEWTER MUSEUM?\l"
	.string "How exciting!\p"
	.string "Of course they won't simply let\n"
	.string "you take it.\p"
	.string "…Why do I get the feeling you'll\n"
	.string "do something…{PAUSE 30} unethical to get it?$"


PokedexRating_Text_HintArticuno::
	.string "To get into ONE ISLAND, you'll need\n"
	.string "a POKéMON to cross the WHIRLPOOLS.\p"
	.string "Wasn't there a man who figured out\n"
	.string "how to do that?\p"
	.string "Maybe you can trick him and learn\n"
	.string "the secret yourself?$"

PokedexRating_Text_HintVaporeon::
	.string "MOLTRES evolved into FLAREON with\n"
	.string "just a FIRE STONE?\l"
	.string "Quite intriguing!\p"
	.string "You'd think a WATER STONE would\n"
	.string "work on ARTICUNO, but that doesn't\l"
	.string "seem to be the case.\p"
	.string "Wait, is VAPOREON even in your\n"
	.string "POKéDEX at all?\l"
	.string "I wonder why not…$"

PokedexRating_Text_HintZapdos::
	.string "At last, you've completed your\n"
	.string "GYM BADGE journey!\p"
	.string "Now all that's left is to travel\n"
	.string "to the INDIGO PLATEAU!$"

PokedexRating_Text_HintJolteon::
	.string "If you look around the LEGENDARY\n"
	.string "BIRDS in your POKéDEX, something\l"
	.string "seems out of place.\p"
	.string "I wonder why it's like that.\n$"

PokedexRating_Text_HintMoltres::
	.string "You said a volcano spontaneously\n"
	.string "appeared on CINNABAR ISLAND?\l"
	.string "Fascinating!\p"
	.string "Be sure to explore the area\n"
	.string "carefully.$"

PokedexRating_Text_HintFlareon::
	.string "ZAPDOS evolved into JOLTEON right\n"
	.string "away, but it seems MOLTRES isn't\l"
	.string "going to be so simple.\p"
	.string "You're saying the POKéDEX implies\n"
	.string "it'll turn into FLAREON?\l"
	.string "I wonder what else we could try…$"


PokedexRating_Text_HintGoldeen::
	.string "You were given a GOLDEN ROD on\n"
	.string "THIRTY EIGHT ISLAND?\p"
	.string "I wonder what POKéMON it might\n"
	.string "fish up!$"


PokedexRating_Text_HintSeaking::
	.string "Your GOLDEEN can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintGun::
	.string "People often lose things in the\n"
	.string "shortness of the UNDERGROUND PATH.$"

PokedexRating_Text_HintArcanine::
	.string "I hear there's a legendary POKéMON\n"
	.string "hiding deep within CERULEAN CAVE.\p"
	.string "Now that you have a POKéMON that\n"
	.string "can climb WATERFALLS, have a look!$"
	
PokedexRating_Text_HintPokemonGun::
	.string "Placeholder!$"

PokedexRating_Text_HintOrthworm::
	.string "That stubborn NEBBY just won't\n"
	.string "stay in your BAG, will he?\p"
	.string "Take a look around the area you're\n"
	.string "trying to move him to, and look at\l"
	.string "where he's coming from.\p"
	.string "Think carefull about all of your\n"
	.string "options!$"


PokedexRating_Text_HintDachsbun::
	.string "You bought a DONUT at the AMERICAN\n"
	.string "BAKERY earlier, didn't you?\l"
	.string "Sounds delicious!\p"
	.string "It's probably gone cold by now.\n"
	.string "Perhaps you could warm it up?$"


PokedexRating_Text_HintMewtwo::
	.string "Placeholder!$"

PokedexRating_Text_HintVenusaur::
	.string "Your BULBASAUR can still evolve.\n"
	.string "Try leveling it up!$"

