PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_HaHa::
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"


PokedexRating_Text_HintVictini::
	.string "Placeholder!$"

PokedexRating_Text_HintBulbasaur::
	.string "SECRET GARDEN has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintCharmander::
	.string "Hey! How did you get here without\n"
	.string "your starter POKéMON?$"

PokedexRating_Text_HintCharmeleon::
	.string "Your CHARMANDER can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintCharizard::
	.string "Your CHARMELEON can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintSquirtle::
	.string "Oh wow!\n"
	.string "Your CHARIZARD sure evolved early!\p"
	.string "I wonder if there's a reason for\n"
	.string "that\l"
	.string "…$"

PokedexRating_Text_HintIvysaur::
	.string "Your SQUIRTLE can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintHitmonchin::
	.string "Placeholder!$"

PokedexRating_Text_HintCaterpie::
	.string "VIRIDIAN FOREST has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintMetapod::
	.string "VIRIDIAN FOREST has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintButterfree::
	.string "CATERPIE doesn't seem to evolve\n"
	.string "until a much higher level.\p"
	.string "I think trying to evolve it directly\n"
	.string "is a lost cause.\p"
	.string "Perhaps there's a different way to\n"
	.string "get to BUTTERFREE…$"

PokedexRating_Text_HintWeedle::
	.string "VIRIDIAN CITY has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintKakuna::
	.string "Your WEEDLE can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintCombee::
	.string "Your KAKUNA can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintPidgey::
	.string "Placeholder!$"

PokedexRating_Text_HintPidgeotto::
	.string "ROUTE 3 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintPidgeot::
	.string "Your PIDGEOTTO can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintRattata::
	.string "ROUTE 1 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintRaticate::
	.string "Placeholder!$"

PokedexRating_Text_HintEkans::
	.string "ROUTE 3 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintArbok::
	.string "Your EKANS can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintSeviper::
	.string "Your EKANS sure evolved early!\n"
	.string "I wonder if there's a reason…$"

PokedexRating_Text_HintPhione::
	.string "I heard there was an EGG deliveryman\n"
	.string "in CELADON who got himself stuck.\p"
	.string "Were you able to talk with him?$"

PokedexRating_Text_HintRaichu::
	.string "There was a girl on ROUTE 5 offering\n"
	.string "to trade her RAICHU for a MEOWTH.\p"
	.string "That deal seems too good to be true.\n"
	.string "You should take it while you can!$"

PokedexRating_Text_HintMeowth::
	.string "ROUTE 4 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintPersian::
	.string "There was a man in VIRIDIAN GYM\n"
	.string "trying to fish something up.\p"
	.string "Maybe he was on to something…\n"
	.string "Have you tried doing that too?$"

PokedexRating_Text_HintSandshrew::
	.string "ROUTE 3 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintSandslash::
	.string "Your SANDSHREW can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintNidoranf::
	.string "ROUTE 22 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintNidorina::
	.string "Your NIDOTRAN♀ can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintNidoqueen::
	.string "The CELADON DEPT STORE sells\n"
	.string "evolution stones.\p"
	.string "One stone resembles something very\n"
	.string "important to one of your POKéMON!$"

PokedexRating_Text_HintNidoranm::
	.string "ROUTE 22 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintNidorino::
	.string "Your NIDOTRAN♂ can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintNidoking::
	.string "The CELADON DEPT STORE sells\n"
	.string "evolution stones.\p"
	.string "One stone resembles something very\n"
	.string "important to one of your POKéMON!$"

PokedexRating_Text_HintClefairy::
	.string "MT MOON has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintClefable::
	.string "Your CLEFAIRY can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintGengar::
	.string "They say something strange can\n"
	.string "happen when CLEFABLE evolves.\p"
	.string "Perhaps you could look into that?\n$"

PokedexRating_Text_HintVulpix::
	.string "ROUTE 8 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintNinetales::
	.string "Your VULPIX can't use a FIRE STONE?\n"
	.string "How odd!\p"
	.string "Maybe something has changed about\n"
	.string "it that might give you a clue.$"

PokedexRating_Text_HintJigglypuff::
	.string "ROUTE 4 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintVenonat::
	.string "There was a man in VIRIDIAN GYM\n"
	.string "trying to fish something up.\p"
	.string "Have you tried that in FUCHSIA CITY?\n$"

PokedexRating_Text_HintZubat::
	.string "Placeholder!$"

PokedexRating_Text_HintGolbat::
	.string "Placeholder!$"

PokedexRating_Text_HintOddish::
	.string "Placeholder!$"

PokedexRating_Text_HintGimmighoul::
	.string "The reward from the SAFARI ZONE\n"
	.string "was quite underwhelming!\p"
	.string "Maybe there's still something you\n"
	.string "can do with it…$"

PokedexRating_Text_HintGholdengo::
	.string "Your GIMMIGHOUL can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintParas::
	.string "MT MOON has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintParasect::
	.string "It seems that PARAS now harnesses\n"
	.string "the power of the SUN!\p"
	.string "Perhaps there's a way to focus that\n"
	.string "power further?$"

PokedexRating_Text_HintJirachi::
	.string "In the CELADON CITY GAME STORE,\n"
	.string "there was a man counting something.\p"
	.string "I wonder what he was doing!\n$"

PokedexRating_Text_HintDiglett::
	.string "DIGLETTS' CAVE has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintDigletts::
	.string "Your DIGLETT can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintPsyduck::
	.string "One path in CELADON CITY led to a\n"
	.string "strange, faraway land.\p"
	.string "Was there someone there you could\n"
	.string "talk to?$"

PokedexRating_Text_HintGolduck::
	.string "Your PSYDUCK can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintMankey::
	.string "ROUTE 22 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintPrimeape::
	.string "Your MANKEY can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintCubone::
	.string "ROUTE 11 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintMarowak::
	.string "Your CUBONE can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintPoliwag::
	.string "Now that you've found a FISHING\n"
	.string "ROD, you should try using it!$"

PokedexRating_Text_HintTentaquil::
	.string "Your POLIWAG can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintAbra::
	.string "ROUTE 24 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintMissingno::
	.string "Placeholder!$"

PokedexRating_Text_HintKangaskhan::
	.string "There was a poor POKéMON in the\n"
	.string "SAFARI ZONE locked away by the DMCA.\p"
	.string "Maybe now you can go back and help\n"
	.string "it!$"

PokedexRating_Text_HintAlakazam::
	.string "Placeholder!$"

PokedexRating_Text_HintPlugOink::
	.string "Placeholder!$"

PokedexRating_Text_HintMachoke::
	.string "Placeholder!$"

PokedexRating_Text_HintMachamp::
	.string "Placeholder!$"

PokedexRating_Text_HintSlowpoke::
	.string "Placeholder!$"

PokedexRating_Text_HintGyarados::
	.string "A man in the POKéMON CENTER before\n"
	.string "MT MOON was selling something.\p"
	.string "It was a very good deal.\n"
	.string "You should take it!$"

PokedexRating_Text_HintMagikarp::
	.string "Your GYARADOS can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintBellsprout::
	.string "ROUTE 24 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintCherubi::
	.string "Your BELLSPROUT can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintTentacool::
	.string "MT MOON has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintToedscool::
	.string "I hear my AIDE delivered the RUNNING\n"
	.string "SHOES, but you didn't need them.\p"
	.string "Maybe you could try giving them to\n"
	.string "a POKéMON instead!$"

PokedexRating_Text_HintGeodude::
	.string "Placeholder!$"

PokedexRating_Text_HintGraveler::
	.string "Your GEODUDE can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintGolem::
	.string "Placeholder!$"

PokedexRating_Text_HintDitto::
	.string "Placeholder!$"

PokedexRating_Text_HintUnown::
	.string "Oh no! A man on ROUTE 11 says that\n"
	.string "his daughter got lost in the woods!\p"
	.string "Maybe you could go find her for him?\n$"

PokedexRating_Text_HintMagnemite::
	.string "THIRTY EIGHT ISLAND has a wild"
	.string "POKéMON you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintMagnalone::
	.string "Placeholder!$"

PokedexRating_Text_HintDoduo::
	.string "ROUTE 7 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintHitmonchan::
	.string "Your DODUO can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintSeal::
	.string "MINNESOTA has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintPinsir::
	.string "Placeholder!$"

PokedexRating_Text_HintGrimer::
	.string "A BUG CATCHER in PEWTER CITY was\n"
	.string "spraying REPEL in the grass.\p"
	.string "Maybe there's a different way to\n"
	.string "make a wild POKéMON appear…$"

PokedexRating_Text_HintMuk::
	.string "Placeholder!$"

PokedexRating_Text_HintShellder::
	.string "Placeholder!$"

PokedexRating_Text_HintSlowbro::
	.string "Placeholder!$"

PokedexRating_Text_HintCastform::
	.string "Placeholder!$"

PokedexRating_Text_HintHaunter::
	.string "Good job on catching a RAICHU for\n"
	.string "yourself!\p"
	.string "Wasn't there a woman somewhere who\n"
	.string "wanted to trade for one?$"

PokedexRating_Text_HintCloyster::
	.string "The CAVE OF ORIGIN has a POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintOnix::
	.string "The CAVE OF ORIGIN has a POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"


PokedexRating_Text_HintPorygon::
	.string "The SLOT MACHINES at the GAME CORNER\n"
	.string "are all broken!\p"
	.string "Maybe there's another way to find\n"
	.string "the COINS to buy a PORYGON…$"

PokedexRating_Text_HintPorygonZ::
	.string "The PC WALLPAPERS you foolishly\n"
	.string "installed are rife with viruses.\p"
	.string "Hopefully they don't infect any of\n"
	.string "your POKéMON!$"

PokedexRating_Text_HintKrabby::
	.string "I hear that all evolutionary trees\n"
	.string "will eventually converge.\p"
	.string "Whatever POKéMON awaits at the end\n"
	.string "must be the ultimate form of life!$"

PokedexRating_Text_HintVoltorb::
	.string "ROUTE 10 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintJiglypuffAbove::
	.string "Your VOLTORB can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintExeggcute::
	.string "ROUTE 5 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintExeggutor::
	.string "A man on ROUTE 8 said he evolved his\n"
	.string "EXEGGCUTE wrong.\p"
	.string "No wonder he wasn't able to find\n"
	.string "CUT!$"

PokedexRating_Text_HintSpearow::
	.string "Wild SPEAROW have mysteriously\n"
	.string "vanished from KANTO.\p"
	.string "I hear that someone in VERMILLION\n"
	.string "was able to get one another way…$"

PokedexRating_Text_HintKenya::
	.string "The guard on ROUTE 11 mentioned a\n"
	.string "friend waiting for him in VIRIDIAN.\p"
	.string "Maybe you should go check on him?\n$"

PokedexRating_Text_HintFarfetchd::
	.string "There's a girl in VERMILLION CITY\n"
	.string "who's offering a trade.\p"
	.string "You should talk to her!\n$"

PokedexRating_Text_HintGolurk::
	.string "Placeholder!$"

PokedexRating_Text_HintBidoof::
	.string "Placeholder!$"

PokedexRating_Text_HintSmeargle::
	.string "Placeholder!$"

PokedexRating_Text_HintTangela::
	.string "Placeholder!$"

PokedexRating_Text_HintTrubbish_Trash::
	.string "Placeholder!$"

PokedexRating_Text_HintAmpharos_Mega::
	.string "Placeholder!$"

PokedexRating_Text_HintAmpharos::
	.string "Placeholder!$"

PokedexRating_Text_HintAmoongus::
	.string "Placeholder!$"

PokedexRating_Text_HintRhydon::
	.string "Placeholder!$"

PokedexRating_Text_HintChansey::
	.string "Placeholder!$"

PokedexRating_Text_HintHorsea::
	.string "The SAFARI WARDEN wanted you to find\n"
	.string "a DRAGONITE.\p"
	.string "There must be a tool to figure out\n"
	.string "which POKéMON evolves into it…$"

PokedexRating_Text_HintDragonite::
	.string "Your HORSEA can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintYoshi::
	.string "Placeholder!$"

PokedexRating_Text_HintZygarde::
	.string "Placeholder!$"

PokedexRating_Text_HintMelmanure::
	.string "Placeholder!$"

PokedexRating_Text_HintEternatus::
	.string "Placeholder!$"

PokedexRating_Text_HintStarmie::
	.string "Placeholder!$"

PokedexRating_Text_HintMrMime::
	.string "Placeholder!$"

PokedexRating_Text_HintJynx::
	.string "There was a man in CERULEAN offering\n"
	.string "a trade.\l"
	.string "You should take it!$"

PokedexRating_Text_HintTauros::
	.string "Placeholder!$"

PokedexRating_Text_HintScyther::
	.string "A trainer in CERULEAN GYM says he\n"
	.string "can give you a strong card.\p"
	.string "Open up a space in your deck so you\n"
	.string "can take it!$"

PokedexRating_Text_HintPikablu::
	.string "Placeholder!$"

PokedexRating_Text_HintLuvdisc::
	.string "Placeholder!$"

PokedexRating_Text_HintAlomomola::
	.string "Placeholder!$"

PokedexRating_Text_HintAlcreamie::
	.string "Placeholder!$"

PokedexRating_Text_HintEevee::
	.string "You seriously didn't steal that\n"
	.string "man's EEVEE?\p"
	.string "I mean, I commend your integrity but\n"
	.string "come on…$"

PokedexRating_Text_HintSylveon::
	.string "The CELADON DEPT STORE sells\n"
	.string "evolution stones.\p"
	.string "You have an EEVEE, right?\n"
	.string "Maybe you should use one on it!$"

PokedexRating_Text_HintLatias::
	.string "Placeholder!$"

PokedexRating_Text_HintLumineon::
	.string "Placeholder!$"

PokedexRating_Text_HintGenesect::
	.string "Placeholder!$"

PokedexRating_Text_HintKabutops::
	.string "Placeholder!$"

PokedexRating_Text_HintOmanyte::
	.string "ROUTE 9 has a wild POKéMON\n"
	.string "you never caught.\p"
	.string "Be sure to go back for it!\n$"

PokedexRating_Text_HintTyranastar::
	.string "Placeholder!$"

PokedexRating_Text_HintYanmega::
	.string "Placeholder!$"

PokedexRating_Text_HintArticuno::
	.string "Placeholder!$"

PokedexRating_Text_HintVaporeon::
	.string "Placeholder!$"

PokedexRating_Text_HintZapdos::
	.string "Placeholder!$"

PokedexRating_Text_HintJolteon::
	.string "Placeholder!$"

PokedexRating_Text_HintMoltres::
	.string "Placeholder!$"

PokedexRating_Text_HintFlareon::
	.string "Placeholder!$"

PokedexRating_Text_HintGoldeen::
	.string "Placeholder!$"

PokedexRating_Text_HintSeaking::
	.string "Your GOLDEEN can still evolve.\n"
	.string "Try leveling it up!$"

PokedexRating_Text_HintGun::
	.string "Placeholder!$"

PokedexRating_Text_HintArcanine::
	.string "Placeholder!$"

PokedexRating_Text_HintPokemonGun::
	.string "Placeholder!$"

PokedexRating_Text_HintOrthworm::
	.string "Placeholder!$"

PokedexRating_Text_HintDachsbun::
	.string "Placeholder!$"


PokedexRating_Text_HintMewtwo::
	.string "Placeholder!$"

PokedexRating_Text_HintVenusaur::
	.string "Placeholder!$"

