Text_FirstShouldRestoreMonsHealth::
	.string "First, you should restore your\n"
	.string "POKéMON to full health.$"

Text_MonsHealedShouldBuyPotions::
	.string "All right, all right.\n"
	.string "There you go.\l"
	.string "Your POKéMON are all healed.\p"
	.string "Sheesh, you didn't need to ask\n"
	.string "so many times.\l"
	.string "I would've done it eventually...\p"
	.string "This POTION shortage is really\n"
	.string "making our job much harder...\p"
	.string "Anyway, good luck!\n"
	.string "I wanna see your POKéMON in pain!$"

Text_MonsHealed::
	.string "Your POKéMON have been healed\n"
	.string "to perfect health.\p"
	.string "We hope you excel!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "DAD: {PLAYER}!\n"
	.string "Uh, wow!\p"
	.string "Did you really just die on the\n"
	.string "first ROUTE of the game?\p"
	.string "Good job.$"

Text_MomExplainHPGetPotions::
	.string "DAD: Hmm, so you're saying it\n"
	.string "wasn't your fault?\p"
	.string "The RATTATAS are just OP?\n"
	.string "SCRATCH was being inconsistent?\p"
	.string "Sounds like a skill issue to me.$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} panicked and lost ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} whited out!$"

Text_WhitedOut::
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} whited out!$"
