FushciaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
	.string "What, you don't believe that\n"
	.string "SLOWPOKETAIL price is gonna spike?\p"
	.string "C'mon, man! We don't need that kind\n"
	.string "of talk here.\l"
	.string "We need to put our full faith in it!\p"
	.string "How else are we supposed to convince\n"
	.string "other people to buy it?$"

FushciaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
	.string "Yo, dude!\n"
	.string "Have you heard of SLOWPOKETAIL?\p"
	.string "It's the hottest new thing!\n"
	.string "Everyone's investing into it.\p"
	.string "Next thing you know, the value's\n"
	.string "gonna spike and we'll all be rich!$"

FushciaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
	.string "How do you actually make money off\n"
	.string "SLOWPOKETAIL?\l"
	.string "Easy!\p"
	.string "All you do is buy a bunch now and\n"
	.string "hope that later, others believe\l"
	.string "they're actually worth something!$"

FushciaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "WARDEN SLOWPOKE is running a\n"
    .string "promotion campaign right now.\p"
    .string "Try to get to the farthest corner\n"
    .string "of the SAFARI ZONE.\p"
    .string "If you can make it, you'll win a\n"
    .string "very convenient prize.$"

