FushciaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .string "We nicknamed the WARDEN\n"
    .string "“SLOWPOKE.”\p"
    .string "You know, he has that vacant look\n"
    .string "like a SLOWPOKE.$"

FushciaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
	.string "Yo, dude!\n"
	.string "Have you heard of SLOWPOKETAIL?\p"
	.string "It's the hottest new thing!\n"
	.string "Everyone's inveting into it.\p"
	.string "Next thing you know, the value's\n"
	.string "gonna spike and we'll all be rich!$"

FushciaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .string "WARDEN SLOWPOKE came in, but\n"
    .string "I couldn't understand him.\p"
    .string "I think he's got a speech problem!$"

FushciaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .string "WARDEN SLOWPOKE is running a\n"
    .string "promotion campaign right now.\p"
    .string "Try to get to the farthest corner\n"
    .string "of the SAFARI ZONE.\p"
    .string "If you can make it, you'll win a\n"
    .string "very convenient prize.$"

