LavenderTown_Text_DoYouBelieveInGhosts::
    .string "I played a haunted game yesterday.\p"
    .string "Do you believe me?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Really, you do?\p"
    .string "It told me the next person who\n"
    .string "talked to me would die.\l"
    .string "Hahaha!\p"
    .string "If you want to be spared, share this\n"
    .string "story in 3 other ROMhacks!$"


LavenderTown_Text_JustImaginingWhiteHand::
    .string "Haha, I wouldn't either.\p"
    .string "It told me the next person who\n"
    .string "talked to me would die.\l"
    .string "Hahaha!\p"
    .string "If you want to be spared, share this\n"
    .string "story in 3 other ROMhacks!$"


LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "This town is known as the players'\n"
    .string "grave site.\p"
    .string "Be careful listening to the music!$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "I bought a game from a yard sale\n"
    .string "the other day.\p"
    .string "I think something's wrong with\n"
    .string "it...$"


LavenderTown_Text_TownSign::
    .string "LAVENDER TOWN\n"
    .string "Don't listen to this music!\p"
    .string "RECOMMENDED POKéDEX COMPLETION: 55$"

LavenderTown_Text_SilphScopeNotice::
    .string "LAVENDER TOWN\n"
    .string "DANCE THEATER$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "LAVENDER TOWN\n"
    .string "ELEMENTARY SCHOOL$"

LavenderTown_Text_PokemonTowerSign::
    .string "POKéMON TOWER\n"
    .string "A vital fixture of our community.\p"
    .string "NOTICE\p"
    .string "No, POKéMON TOWER will not become\n"
    .string "a RADIO TOWER in 3-4 years.\p"
    .string "I have no idea who started this\n"
    .string "rumor, but it is very disrespectful.$"


LavenderTown_Text_DietDance_Before::
    .string "Oh, no!\n"
    .string "The DANCE THEATER got shut down?\p"
    .string "Where am I supposed to SHAKE IT\n"
    .string "and DO THE DIET DANCE now?$"


LavenderTown_Text_DMCA::
    .string "Stop right there!\p"
    .string "This building right here is the\n"
    .string "LAVENDER TOWN DANCE THEATER.\p"
    .string "They've been putting on shows that\n"
    .string "violate copyright!\l"
    .string "It's shut down until further notice.$"

LavenderTown_Text_MathFail::
    .string "Originally, POKéMON TOWER was\n"
    .string "supposed to be built horizontally.\p"
    .string "However, the engineers who made it\n"
    .string "all failed math.\p"
    .string "This is what we got instead.$"

LavenderTown_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CELADON CITY - LAVENDER TOWN$"

