LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .string "The DMCA will do anything for\n"
    .string "the sake of copyright!\p"
    .string "There is no project too small or\n"
    .string "innocent for them take down!$"


LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .string "CUBONE'S MOTHER used to volunteer\n"
    .string "at the local ELEMENTARY SCHOOL.\p"
    .string "No one's seen her in a while,\n"
    .string "though...$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .string "You know how the CUBONE species\n"
    .string "wears skulls, right?\p"
    .string "People will pay a lot for one.$"

LavenderTown_PokemonCenter_1F_Text_Alphabet::
    .string "Q, R, S…\n"
    .string "T, U, V…\p"
    .string "W, X, and… Z!\n"
    .string "Yay, I did it!$"

LavenderTown_PokemonCenter_1F_Text_Riddle::
.string "Two tails weave,\n"
.string "one truth they hold.\p"
.string "Across the void,\n"
.string "secrets unfold.$"

LavenderTown_PokemonCenter_1F_Text_Plasto::
    .string "PLASTO: …What?$"
