Route7_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CELADON CITY - LAVENDER TOWN$"

Route7_Text_AtNightBefore::
	.string "Look! I found these cool POKéMON\n"
	.string "in the grass here!$"

Route7_Text_AtNightDefeat::
	.string "Oh, no!\n"
	.string "I looked so hard for these!$"

Route7_Text_AtNightAfter::
	.string "I'm so glad this game has DARK-types\n"
	.string "available!\p"
	.string "…Huh? How did I find them?\p"
	.string "Easy! I just had to come here at\n"
	.string "night!$"