Route12_Text_MonSprawledOutInSlumber::
    .string "A POKéMON is sprawled out in\n"
    .string "a deep and comfortable slumber.$"

Text_SnorlaxWokeUp::
    .string "SNORLAX woke up!\p"
    .string "It attacked in a grumpy rage!$"

Text_SnorlaxReturnedToMountains::
    .string "SNORLAX calmed down.\n"
    .string "It gave a huge yawn…\l"
    .string "And returned to the mountains.$"

Text_WantToUsePokeFlute::
    .string "Want to use the POKé FLUTE?$"

Text_PlayedPokeFlute::
    .string "{PLAYER} played the POKé FLUTE.$"

Route12_Text_NedIntro::
    .string "Yeah!\n"
    .string "I got a bite here!$"

Route12_Text_NedDefeat::
    .string "Tch!\n"
    .string "Just a small fry…$"

Route12_Text_NedPostBattle::
    .string "Hang on!\n"
    .string "My line's snagged!$"

Route12_Text_ChipIntro::
    .string "Be patient.\n"
    .string "Fishing is a waiting game.$"

Route12_Text_ChipDefeat::
    .string "That one got away!$"

Route12_Text_ChipPostBattle::
    .string "With a better ROD, I could catch\n"
    .string "better POKéMON…$"

Route12_Text_JustinIntro::
    .string "I'm searching for a MOON STONE.\n"
    .string "Have you found one?$"

Route12_Text_JustinDefeat::
    .string "Oww!$"

Route12_Text_JustinPostBattle::
    .string "I could have made my POKéMON\n"
    .string "evolve with a MOON STONE.\p"
    .string "I would have won then, I bet.$"

Route12_Text_LucaIntro::
    .string "Electricity is my specialty.\p"
    .string "I don't know a thing about POKéMON\n"
    .string "of the sea, though.$"

Route12_Text_LucaDefeat::
    .string "Unplugged!$"

Route12_Text_LucaPostBattle::
    .string "Water conducts electricity, so you\n"
    .string "should zap sea POKéMON.$"

Route12_Text_HankIntro::
    .string "The FISHING FOOL versus POKéMON\n"
    .string "KID!$"

Route12_Text_HankDefeat::
    .string "Touch too much!$"

Route12_Text_HankPostBattle::
    .string "I guess you get to be good at\n"
    .string "what you like.\p"
    .string "Well, you beat me at POKéMON,\n"
    .string "but you can't top me at fishing.$"

Route12_Text_ElliotIntro::
    .string "I love fishing, don't get me wrong.\p"
    .string "But it'd be best if I also had more\n"
    .string "work.$"

Route12_Text_ElliotDefeat::
    .string "It's not easy…$"

Route12_Text_ElliotPostBattle::
    .string "It's all right.\n"
    .string "Losing doesn't bug me anymore.$"

Route12_Text_AndrewIntro::
    .string "What's catching?\p"
    .string "You never know what you could\n"
    .string "catch!$"

Route12_Text_AndrewDefeat::
    .string "Lost it!$"

Route12_Text_AndrewPostBattle::
    .string "What, MAGIKARP?\p"
    .string "I catch them all the time, sure.\n"
    .string "But, boy are they wimpy.$"

Route12_Text_RouteSign::
    .string "ROUTE 12 \n"
    .string "North to LAVENDER$"

Route12_Text_SportfishingArea::
    .string "SPORTFISHING AREA$"

Route12_Text_JesIntro::
	.string "JAN: KIRI, here we go!\n"
	.string "I think we got it set up right!\p"
	.string "KIRI: I dunno, JAN...\n"
	.string "I think the ITEMS are wrong.$"

Route12_Text_JesDefeat::
	.string "JAN: Eeeeh!\n"
	.string "No fair!$"

Route12_Text_JesPostBattle::
	.string "JAN: KIRI, don't cry.\n"
	.string "We'll get it next time!$"

Route12_Text_JesNotEnoughMons::
	.string "JAN: Okay, KIRI!\n"
	.string "We got this!\p"
	.string "Next time we're in a DOUBLE BATTLE,\n"
	.string "let's pull it off!$"

Route12_Text_GiaIntro::
	.string "JAN: KIRI, here we go!\n"
	.string "I think we got it set up right!\p"
	.string "KIRI: I dunno, JAN...\n"
	.string "I think the ITEMS are wrong.$"

Route12_Text_GiaDefeat::
	.string "JAN: Eeeeh!\n"
	.string "No fair!$"

Route12_Text_GiaPostBattle::
	.string "KIRI: Hey JAN, I think we need to\n"
	.string "look it up again.\p"
	.string "I don't think we did it right…\n$"

Route12_Text_GiaNotEnoughMons::
	.string "KIRI: Me and JAN have something\n"
	.string "really cool to try!\l"
	.string "But…\p"
	.string "I think we need to be in a DOUBLE\n"
	.string "BATTLE to do it…$"
