SaffronCity_Gym_Text_SabrinaIntro::
	.string "Grraaaah!\n"
	.string "This is unacceptable!!\p"
	.string "How could I, BRUNO of the ELITE\n"
	.string "FOUR, be demoted from my position?\l"
	.string "And to a lowly GYM LEADER, no less!\p"
	.string "Grr… Challenger!\n"
	.string "I will prove my place at the top!\p"
	.string "You'll never defeat my unbeatable\n"
	.string "team!\l"
	.string "Wanna know why?\p"
	.string "All my POKéMON…{PAUSE 30} are immune\n"
	.string "to PHYSICAL damage!!!\p"
	.string "Come!\n"
	.string "Let's battle!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
	.string "What!?\n"
	.string "You've done that puzzle before!?$"

SaffronCity_Gym_Text_SabrinaPostBattle::
	.string "Maybe…{PAUSE 30}\n"
	.string "Maybe I am a nerd.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
	.string "Hmph. Fine.\p"
	.string "Take this TM, then.\n$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER} received TM34 from\n"
    .string "the big NERD.$"

SaffronCity_Gym_Text_ExplainTM04::
	.string "TM39 contains…{PAUSE 30} BIDE.\p"
	.string "It is a move that definitely\n"
	.string "exists.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "Your BAG is full of other items.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "SABRINA is far younger than I,\n"
    .string "but she has earned my respect.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "Not good enough!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "In a battle of equals, the one\n"
    .string "with the stronger will wins.\p"
    .string "If you wish to beat SABRINA, focus\n"
    .string "and will yourself to victory.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "Does our unseen power scare you?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "I never foresaw this!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "PSYCHIC POKéMON fear only ghosts\n"
    .string "and bugs!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "POKéMON take on the appearance of\n"
    .string "their TRAINERS.\p"
    .string "Your POKéMON must be tough, then!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "I knew it!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "I have much to learn still…\p"
    .string "I must master PSYCHIC and teach it\n"
    .string "to my POKéMON…$"

SaffronCity_Gym_Text_TyronIntro::
    .string "You understand, don't you?\p"
    .string "That power alone isn't enough to\n"
    .string "win in the world of POKéMON?$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "I don't believe this!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "SABRINA just wiped out the KARATE\n"
    .string "MASTER next door.$"

SaffronCity_Gym_Text_TashaIntro::
    .string "You and I, our POKéMON shall\n"
    .string "battle!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "I lost after all!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "I knew that this was going to take\n"
    .string "place.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "SABRINA is young, but she's also\n"
    .string "our highly skilled LEADER.\p"
    .string "You won't reach her easily!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "Ow!\n"
    .string "Down and out!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "There used to be two POKéMON GYMS\n"
    .string "in SAFFRON.\p"
    .string "The FIGHTING DOJO next door lost\n"
    .string "its GYM status, though.\p"
    .string "We simply creamed them when we\n"
    .string "decided to have just one GYM.$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "SAFFRON POKéMON GYM is famous for\n"
    .string "training psychics.\p"
    .string "You want to see SABRINA, don't\n"
    .string "you? I can tell!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "That's right! I used telepathy to\n"
    .string "read your mind!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "SABRINA's POKéMON use psychic\n"
    .string "power instead of force.\p"
    .string "FIGHTING POKéMON are especially\n"
    .string "weak against PSYCHIC POKéMON.\p"
    .string "They'll get destroyed before they\n"
    .string "can even aim a punch!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "Psychic power, huh?\p"
    .string "If I had that, I'd make a bundle\n"
    .string "at the slots!$"

SaffronCity_Gym_Text_GymStatue::
    .string "SAFFRON POKéMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "WINNING TRAINERS:\n"
    .string "GARY, LARRY, JERRY\l"
    .string "HARRY, LARRY$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "SAFFRON POKéMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "WINNING TRAINERS:\n"
    .string "GARY, LARRY, JERRY\l"
    .string "HARRY, LARRY, {PLAYER}$"

