PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .string "Everyone here's struggling to get a\n"
    .string "BUTTERFREE.\p"
    .string "Not me, though!\n"
    .string "I found a shortcut!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .string "Good things can happen if you raise\n"
    .string "POKéMON diligently.\p"
    .string "But something like CATERPIE?\n"
    .string "Nah, not worth it.$"

