VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "Sometimes there are POKéMON that\n"
    .string "are very similar to others.\p"
    .string "The DMCA will claim any that they\n"
    .string "see as infringing on the original.\p"
    .string "They recently stole my DEDENNE.\p"
    .string "That's the sort of horrid people\n"
    .string "they are, the DMCA.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "I must'vs parked my TRUCK somewhere\n"
    .string "in this city...\l"
    .string "Do you have any idea where it is?"

