CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
	.string "Hi, I'm CELIA!\n"
	.string "I designed all the puzzles.\p"
	.string "I hope they've been fun and\n"
	.string "satisfying!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
	.string "Hello, there!\n"
	.string "I'm CELIA!\p"
	.string "I made most of the custom art\n"
	.string "and music!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
	.string "I'm CELIA, the writer for this\n"
	.string "hack.\p"
	.string "Thanks for reading my dialogue!\n$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
	.string "Hi!\n"
	.string "I'm CELIA, the creator!\l"
	.string "Thanks for playing my hack!\p"
	.string "I hope you've been filling up\n"
	.string "your POKéDEX!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "Wow! Excellent!\n"
    .string "You completed your POKéDEX!\l"
    .string "Congratulations!\l"
    .string "…$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
 	.string "It's the design document.\n"
	.string "It shows all the puzzles!\p"
	.string "Ohhh, so THAT'S why nothing learns\n"
	.string "FIRE-TYPE moves!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
	.string "It's all the art in the game.\n"
	.string "Eww, that's ugly!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
	.string "It's the script!\p"
	.string "…\p"
	.string "WOAH!\n"
	.string "You can't put that in a kids' game!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "CELIA's Development Room$"

