SilphCo_7F_Text_HaveMonForSavingUs::
	.string "Thank you for saving us from the\n"
	.string "DMCA!\p"
	.string "Here, I have a gift for you.\n$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "{PLAYER} obtained a BIDOOF from\n"
    .string "the SILPH employee!$"

SilphCo_7F_Text_ExplainLapras::
    .string "This BIDOOF is a very special\n"
	.string "POKéMON.\p"
	.string "It's designed to be compatible\n"
	.string "with any HM you want to teach it.$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "TEAM ROCKET's BOSS went to the\n"
    .string "boardroom!\p"
    .string "Is our PRESIDENT okay?\n"
    .string "I'm worried.$"

SilphCo_7F_Text_OhNo::
    .string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
    .string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "TEAM ROCKET was after the MASTER\n"
    .string "BALL, which catches any POKéMON.$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "We canceled the MASTER BALL\n"
    .string "project because of TEAM ROCKET.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "It would be bad if TEAM ROCKET\n"
    .string "took over SILPH or our POKéMON.$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "Wow!\p"
    .string "You chased off TEAM ROCKET all by\n"
    .string "yourself?$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "You!\n"
    .string "It's really dangerous here!\p"
    .string "You came to save me?\n"
    .string "You can't!$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "Thank you so much!$"

SilphCo_7F_Text_Grunt3Intro::
    .string "Uh-oh!\n"
    .string "I smell a little mouse!$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "Lights out!$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "You won't find my BOSS by just\n"
    .string "scurrying around!$"

SilphCo_7F_Text_JoshuaIntro::
    .string "Heheh!\p"
    .string "You mistook me for a SILPH worker?$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "I'm done!$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "Despite your age, you are a\n"
    .string "skilled TRAINER!$"

SilphCo_7F_Text_Grunt1Intro::
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "Aack!\n"
    .string "Brothers, I lost!$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "Doesn't matter.\n"
    .string "My brothers will repay the favor!$"

SilphCo_7F_Text_Grunt2Intro::
    .string "A child intruder?\n"
    .string "That must be you!$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "Fine!\n"
    .string "I lost!$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "Go on home before my BOSS gets\n"
    .string "ticked off!$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "LARRY: What kept you, {PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
	.string "i'm larry\n$"

SilphCo_7F_Text_RivalDefeat::
	.string "no puzzle\n$"

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}“おまえなあ‥\p"
    .string "こんな　うでまえじゃ\n"
    .string "まだまだ‥\l"
    .string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle::
	.string "Oh no.\n"
	.string "Looks like I lost.\p"
	.string "…\p"
	.string "{PAUSE 30}See ya later.\n$"

SilphCo_7F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "7F$"

