RocketHideout_B1F_Text_Grunt1Intro::
    .string "Who are you?\n"
    .string "How did you get here?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "Oww!\n"
    .string "Beaten!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "Blast it… You're dissing TEAM\n"
    .string "ROCKET, aren't you?$"

RocketHideout_B1F_Text_Grunt2Intro::
	.string "JESSIE: Blast it all!\p"
	.string "How could the nefarious TEAM\n"
	.string "ROCKET be captured like this?$"

RocketHideout_B1F_Text_Grunt2Defeat::
	.string "No!\n"
	.string "We're blasting off again!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
	.string "JESSIE: Oh JAMES…\n"
	.string "What are we to do?\p"
	.string "I've scoured this whole hack top\n"
	.string "to bottom and I haven't seen\l"
	.string "PIKACHU anywhere!$"

RocketHideout_B1F_Text_Grunt3Intro::
	.string "Are you lost, you offbrand\n"
	.string "mouse?$"

RocketHideout_B1F_Text_Grunt3Defeat::
	.string "No!\n"
	.string "They've entered Public Domain!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
	.string "My rats are in public domain…\n"
	.string "There's nothing I can do!$"

RocketHideout_B1F_Text_Grunt4Intro::
	.string "Grrah!\n"
	.string "Another one?\p"
	.string "So many civilians have been breaking\n"
	.string "into our LAW OFFICES recently!$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "This won't do!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
	.string "I'm going to find out where all of\n"
	.string "you are coming from, and then I'll\l"
	.string "sue harder than you could believe!$"

RocketHideout_B1F_Text_Grunt5Intro::
	.string "We caught some troublemakers\n"
	.string "sneaking around.\p"
	.string "Their disguises were a clear\n"
	.string "violation of copyright!$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "Why…?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
	.string "Uh-oh, that ruckus somehow opened\n"
	.string "the door!\p"
	.string "This is extraordinarily convenient\n"
	.string "for you!$"

