RocketHideout_B4F_Text_GiovanniIntro::
    .string "So! I must say, I am impressed you\n"
    .string "got here.\p"
    .string "TEAM ROCKET captures POKéMON from\n"
    .string "around the world.\p"
    .string "They're important tools for keeping\n"
    .string "our criminal enterprise going.\p"
    .string "I am the leader, GIOVANNI!\p"
    .string "For your insolence, you will feel a\n"
    .string "world of pain!$"

RocketHideout_B4F_Text_GiovanniDefeat::
    .string "WHAT!\n"
    .string "This can't be!$"

RocketHideout_B4F_Text_GiovanniPostBattle::
    .string "I see that you raise POKéMON with\n"
    .string "utmost care.\p"
    .string "A child like you would never\n"
    .string "understand what I hope to achieve.\p"
    .string "I shall step aside this time!\p"
    .string "I hope we meet again…$"

RocketHideout_B4F_Text_Grunt2Intro::
    .string "I know you!\n"
    .string "You ruined our plans at MT. MOON!$"

RocketHideout_B4F_Text_Grunt2Defeat::
    .string "Burned again!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
    .string "Do you have something against TEAM\n"
    .string "ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro::
    .string "How can you not see the beauty of\n"
    .string "our evil?$"

RocketHideout_B4F_Text_Grunt3Defeat::
    .string "Ayaya!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
    .string "BOSS!\n"
    .string "I'm sorry I failed you!$"

RocketHideout_B4F_Text_Grunt1Intro::
	.string "Who has the LIFT KEY?\n"
	.string "It definitely isn't me!\p"
	.string "No siree!\p"
	.string "I, Mr. BUTTERFINGERS DMCA, am\n"
	.string "definitely not holding the LIFT KEY.$"

RocketHideout_B4F_Text_Grunt1Defeat::
    .string "No!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
	.string "Oh, no!\n"
	.string "“BUTTERFINGERS” is copyrighted!$"

DMCA_LawOffices_PetrelIntro::
	.string "What...?\n"
	.string "Who are you?\p"
	.string "My name is PETREL.\n"
	.string "I'm an admin of the DMCA!\p"
	.string "How dare you tresspass in our\n"
	.string "LAW OFFICES!$"

DMCA_LawOffices_PetrelDefeat::
	.string "Ayaya!\n"
	.string "My POKéMON were all copies!$"

DMCA_LawOffices_PetrelAfter::
	.string "Grr…\p"
	.string "The SCOPE on the table there was a\n"
	.string "clear copy of the NES ZAPPER.\l"
	.string "How dare you take it!\p"
	.string "The BOSS is off on important\n"
	.string "business too...\p"
	.string "No matter!\n"
	.string "You won't be able to take him down!\p"
	.string "His POKéMON is fully invincible!\n"
	.string "It has no weakness you can exploit!\p"
	.string "Well, it has no weaknesses in THIS\n"
	.string "GENERATION, at least.$"
