SafariZone_North_Text_RestHouse::
    .string "REST HOUSE$"

SafariZone_North_Text_SecretHouseStillAhead::
    .string "TRAINER TIPS\p"
    .string "The SECRET HOUSE is still ahead.$"

SafariZone_North_Text_Area2::
    .string "AREA 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
    .string "TRAINER TIPS\p"
    .string "POKéMON hide in tall grass.\p"
    .string "Zigzag through grassy areas to\n"
    .string "flush them out.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
	.string "Please keep a safe distance from\n"
	.string "the DEATH SPIRAL at all times.\p"
	.string "SAFARI ZONE, LLC. will not\n"
	.string "compensate you for any appendages\l"
	.string "lost via DEATH SPIRAL incidents.$"

