CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .string "Those miserable DMCA!\p"
    .string "Look what they've done to my\n"
    .string "house!\p"
    .string "I was inspired by a TM to teach\n"
    .string "POKéMON how to throw rocks!\p"
    .string "I was going to use it on a\n"
    .string "GEODUDE or an ONIX…\p"
    .string "Now I'm gonna get sued!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "I figure what's lost is lost.\p"
    .string "I decided to teach DIGLETT how to\n"
    .string "DIG without a TM.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
    .string "The DMCA barged in and claimed\n"
    .string "a TM I created for fun with my\l"
    .string "friends!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "TEAM ROCKET left a way out!$"

