CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .string "Those miserable DMCAs!\p"
    .string "Look what they've done to my house!\p"
    .string "I was inspired by a TM to teach\n"
    .string "POKéMON how to throw rocks.\p"
    .string "I was going to use it on a\n"
    .string "GEODUDE or an ONIX…\p"
    .string "Now I'm gonna get sued!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "I figure what's lost is lost.\p"
	.string "Maybe I'll go to BROCK and he'll\n"
	.string "give me the original TM instead.\p"
	.string "…What?\n"
	.string "It isn't ROCK TOMB in this hack?\p"
	.string "Darn.\n$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
	.string "The DMCA barged in and claimed a\n"
	.string "TM I made for fun with my friends…$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "The DMCA left a way out!$"

