CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .string "Those miserable DMCAs!\p"
    .string "Look what they've done to my\n"
    .string "house!\p"
    .string "I was inspired by a TM to teach\n"
    .string "POKéMON how to throw rocks!\p"
    .string "I was going to use it on a\n"
    .string "GEODUDE or an ONIX…\p"
    .string "Now I'm gonna get sued!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "I figure what's lost is lost.\p"
    .string "Maybe I can go back to BROCK and\n"
    .string "he'll give me the original TM\l"
    .string "instead…\p"
    .string "…What?\n"
    .string "That's been changed in this hack too?\p"
    .string "Darn.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
    .string "The DMCA barged in and claimed\n"
    .string "a TM I created for fun with my\l"
    .string "friends!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "The DMCA left a way out!$"

