LavenderTown_House1_Text_Cubone::
    .string "CUBONE: Hello there!\n"
    .string "My name is CUBONE.\p"
    .string "It's my mom specifically that\n"
    .string "everyone's talking about.\p"
    .string "...What, did you think it was all\n"
    .string "CUBONES everywhere whose moms died?\l"
    .string "Ha!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "The DMCA is horrible!\p"
    .string "So many of us here in town are\n"
    .string "just trying to write stories.\p"
    .string "But they keep sending us takedown\n"
    .string "notices!$"
    
LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "The ghost of POKéMON TOWER is\n"
    .string "gone!\p"
    .string "Someone must have soothed its\n"
    .string "restless spirit!$"

