PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "You're completing the POKéDEX?\n"
    .string "Good luck!\p"
    .string "You can save yourself some grinding\n"
    .string "by catching evolved POKéMON in the\l"
    .string "wild$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "A POKéMON becomes easier to \n"
    .string "catch if it has a status problem.\p"
    .string "Sleep, poison, burn, or paralysis…\n"
    .string "Those are all effective.\p"
    .string "But catching POKéMON is never\n"
    .string "a sure thing!$"

