PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
	.string "You're completing the POKéDEX?\n"
	.string "Good luck!\p"
	.string "I hear if you log on to OAK's PC,\n"
	.string "he'll give some hints on what to do.\l"
	.string "You should try it!$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "A POKéMON becomes easier to \n"
    .string "catch if it has a status problem.\p"
    .string "Sleep, poison, burn, or paralysis…\n"
    .string "Those are all effective.\p"
    .string "But catching POKéMON is never\n"
    .string "a sure thing!$"

