CeladonCity_Gym_Text_ErikaIntro::
.string "Hello. I'm the president of\n"
.string "the CELADON CITY LGBT CLUB.\p"
.string "In here, all are welcome regardless\l"
.string "of orientation or gender identity.\p"
.string "In addition, I am also the LEADER\l"
.string "of CELADON GYM.\p"
.string "I'll show you the strength of a\l"
.string "proud and united community!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "Oh!\n"
    .string "I concede defeat.\l"
    .string "You are remarkably strong.\p"
    .string "I must confer on you the\n"
    .string "RAINBOWBADGE.$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "{PLAYER}...\n"
    .string "Thank you so much, again.\p"
    .string "You truly showed what it means\l"
    .string "to be an ally to our community.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "The RAINBOWBADGE will make\n"
    .string "POKéMON up to Lv. 50 obey.\p"
    .string "It also allows POKéMON to use\n"
    .string "STRENGTH in and out of battle.\p"
    .string "Please also take this with you.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "{PLAYER} received TM19\n"
    .string "from ERIKA.$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "TM19 contains MAGICAL LEAF.\p"
    .string "It's a move that I absolutely\l"
    .string "love to use!\p"
    .string "There aren't many POKéMON that\l"
    .string "can use it, but keep it in mind!\p"
    .string "I'm sure you'll find it very\l"
    .string "useful in the near future!$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "You should make room for this.$"

CeladonCity_Gym_Text_KayIntro::
    .string "In this GYM, all women are\n"
    .string "welcome - trans and cis!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "Ah!\n"
    .string "Nice shot!$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "The community in this GYM makes me\n"
    .string "feel safe and secure!\p"
    .string "I don't even care that everyone\l"
    .string "can look at me!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "Male or female, it doesn't matter\n"
    .string "to me.\p"
    .string "I love the person, not the gender.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "Oh!\n"
    .string "Beaten!$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "Be free to live and love whoever\n"
    .string "you desire!$"

CeladonCity_Gym_Text_TinaIntro::
    .string "My girlfriend is so pretty!$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "You're an eye-opener!$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "Just look at ERIKA!\n"
    .string "She's so pretty!\p"
    .string "I love her so much!$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "I love who I am!\n"
    .string "No one can ever take that from me!$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "No!$"

CeladonCity_Gym_Text_TamiaPostBattle::
.string "Since becoming true to myself,\n"
.string "living life has felt so free!\l"
.string "I think I'm going to celebrate!\p"
.string "Maybe I could buy my NIDOs\n"
.string "a present from the DEPT STORE…$"

CeladonCity_Gym_Text_LisaIntro::
    .string "Grumble grumble…\p"
    .string "I hate all these gay people!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "Oh!$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "Grumble grumble…$"

CeladonCity_Gym_Text_LoriIntro::
    .string "Pleased to meet you.\n"
    .string "Want to destroy capitalism?$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "Oh!\n"
    .string "Splendid!$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "Come, comrade! The liberation of\n"
    .string "the working class is upon us!\p"
    .string "All marginalized persons must\l"
    .string "find solidarity in the revolution!$"

CeladonCity_Gym_Text_MaryIntro::
    .string "Gender is a performance, and I'm\n"
    .string "a star!$"

CeladonCity_Gym_Text_MaryDefeat::
.string "My makeup!$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "You should come out to our show!\n"
    .string "We have it every week!\p"
    .string "Our gorgeous queens put on a\l"
    .string "lovely performance!$"

CeladonCity_Gym_Text_GymStatue::
    .string "CELADON POKéMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "CELADON POKéMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

