Route6_NorthEntrance_Text_ThirstyOnGuardDuty::
    .string "I'm on guard duty.\n"
    .string "Gee, I'm thirsty, though!\p"
    .string "Oh, wait there, the road's closed.$"

Route6_NorthEntrance_Text_ThatTeaLooksTasty::
	.string "I'm on guard duty.\n"
	.string "Gee, I'm thirsty, though!\p"
	.string "Wait, that TOXIC SLUDGE…\n$"

Route6_NorthEntrance_Text_ThanksIllShareTeaWithGuards::
	.string "Huh?\n"
	.string "What are you doing with that?!\p"
	.string "Wait!!\p"
	.string "No! No!\n"
	.string "Stop!\p"
	.string "Aaaaaah!!!\n$"

Route6_NorthEntrance_Text_HiHowsItGoing::
    .string "Hi, how's it going?$"

