CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "That BILL!\p"
    .string "I heard that he'll do whatever it\n"
    .string "takes to get rare POKéMON.\p"
    .string "He's not above doing all sorts\n"
    .string "of things, I've heard.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "Evolutions have seemed a tad\n"
    .string "strange as of late.\p"
    .string "My EKANS evolved right away, but\n"
    .string "my ABRA won't no matter what!\p"
    .string "It seems most POKéMON are hitting\n"
    .string "their final form by Level 20.$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "BILL has lots of POKéMON!\n"
    .string "He collects rare ones, too!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
	.string "Have you gone to see BILL yet?\p"
	.string "Getting to draw 2 cards is so\n"
	.string "strong!$"

