CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .string "That BILL!\p"
    .string "I heard that he'll do whatever it\n"
    .string "takes to get rare POKéMON.\p"
    .string "He's not above doing all sorts\n"
    .string "of things, I've heard.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .string "Evolutions have seemed a tad\n"
    .string "strange as of late.\p"
    .string "My EKANS evolved right away, but\n"
    .string "my ABRA won't no matter what!\p"
    .string "It seems most POKéMON are hitting\n"
    .string "their final form by Level 20.$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .string "BILL has lots of POKéMON!\n"
    .string "He collects rare ones, too!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .string "Why don't you go upstairs and try\n"
    .string "trading POKéMON with your friends?\p"
    .string "You could get a lot more variety\n"
    .string "by trading.\p"
    .string "The POKéMON you get in trades grow\n"
    .string "quickly, too.$"

