TwoIsland_Text_IslandSign::
    .string "TWO ISLAND\n"
    .string "Boon Island for Two$"

TwoIsland_Text_JoyfulGameCornerSign::
    .string "Skip & Chomp!\n"
    .string "Joyful GAME CORNER$"

TwoIsland_Text_DangerFastCurrent::
    .string "DANGER! FAST CURRENT!\n"
    .string "Fishing and surfing prohibited!$"

TwoIsland_Text_WelcomeToShopMerchandiseLimited::
    .string "Oh!\n"
    .string "Hello, welcome to my shop!\p"
    .string "We've only opened up recently.\p"
    .string "Our merchandise is limited, but I\n"
    .string "hope we can serve your needs.$"

TwoIsland_Text_AddedMerchandiseForLostelle::
    .string "I can't tell you how grateful I am\n"
    .string "for your rescue of LOSTELLE.\p"
    .string "Thanks to your feat, the people of\n"
    .string "THREE ISLAND have changed their\l"
    .string "attitudes about KANTO people.\p"
    .string "And, I'm from KANTO, you see.\p"
    .string "The people of THREE ISLAND\n"
    .string "helped me add to my merchandise.$"

TwoIsland_Text_HopeYouGiveItYourBest::
    .string "Hi! I'm giving it my best here.\n"
    .string "I hope you do too, {PLAYER}.$"

TwoIsland_Text_BringingItemsFromDistantLands::
    .string "Oh, hello, {PLAYER}!\n"
    .string "Welcome!\p"
    .string "I've started bringing in items from\n"
    .string "distant lands.\p"
    .string "I've got some rare items in, too.\n"
    .string "Please have a look!$"

TwoIsland_Text_FellowMovedFromCeladonCity::
    .string "That fellow there, he moved here\n"
    .string "from CELADON CITY.\p"
    .string "He started up a shop with his\n"
    .string "younger brother.\p"
    .string "You have to wonder if he knew what\n"
    .string "he was getting into.$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner::
    .string "The shopkeeper's brother took\n"
    .string "a job at the GAME CORNER.\p"
    .string "He's trying to pull together money\n"
    .string "so they can buy more merchandise.$"

TwoIsland_Text_BrunoCameToIslandWhileBack::
    .string "Listen, listen.\n"
    .string "Did you know?\p"
    .string "A famous TRAINER came to the\n"
    .string "ISLAND a little while back.\p"
    .string "He's one of the ELITE FOUR.\n"
    .string "His name is BRUNO.\p"
    .string "He went away disappointed when he\n"
    .string "found out that they were all sold\l"
    .string "out of Rage Candybars.$"

TwoIsland_Text_BuyRareItemsHere::
    .string "The discerning TRAINER knows to\n"
    .string "buy rare items here!$"

TwoIsland_Text_OldWomanLivesOutOnCape::
    .string "There's an old woman who lives in\n"
    .string "a cottage out on the cape.\p"
    .string "She gives the eye to POKéMON.\n"
    .string "It's a bit unnerving.$"

TwoIsland_Text_HaveYouTriedJumpingGame::
    .string "Boing! Boing!\n"
    .string "Have you tried the jumping game?\p"
    .string "The POKéMON you can enter…\n"
    .string "Boing!\p"
    .string "Some go boing!\p"
    .string "And some go boooooooing!\p"
    .string "Did you know that?\n"
    .string "Boing!$"

Text_SecretLifeMother3::
	.string "My Secret Life, Mother Three.\p"
	.string "I was neither a murder suspect, nor\n"
	.string "a target for an international spy\l"
	.string "organization.\p"
	.string "But I drove a car down the Jersey\n"
	.string "Turnpike at 80 mph.\p"
	.string "…A police officer pulled me over\n"
	.string "and asked for my driver's license.\p"
	.string "He said I was going 20 mph over the\n"
	.string "speed limit. I instantly pointed to\l"
	.string "my wife and said, “I'm in a hurry,\l"
	.string "my wife is in labor.”\p"
	.string "Fortunately, my wife actually had a\n"
	.string "big stomach.\p"
	.string "I hoped he'd let me go with this\n"
	.string "excuse.\p"
	.string "“Oh, since it's an emergency, I'll\n"
	.string "lead you to the hospital with my\l"
	.string "police car,” he said.\p"
	.string "“No, it's not necessary.”\p"
	.string "“Why not?” asked the officer.\n"
	.string "“Uh… well…”\p"
	.string "“Let's get going,” said the officer.\p"
	.string "“No, no! We can't! This baby is a\n"
	.string "demon child!”$"
