CableClub_OnTransition::
	end

CableClub_EventScript_HideOrShowMysteryGiftMan::
	return

EventScript_HideMysteryGiftMan::
	return

CableClub_EventScript_MysteryGiftMan::

@ Unused
EventScript_MysteryGiftThankYou::
	end

CableClub_OnWarp::
	.2byte 0

EventScript_CheckTurnAttendant::
EventScript_CheckTurnAttendantEnd:
	end

CableClub_OnLoad::
	end

EventScript_OnLoadFromColosseum::
	end

EventScript_OnLoadFromTradeCenter::
	end

EventScript_OnLoadFromUnionRoom::
	end

EventScript_OnLoadFromBerryCrush::
	end

EventScript_OnLoadFromGameCorner::
	end

CableClub_OnFrame::
	.2byte 0

CableClub_EventScript_ExitLinkRoom::
	end

CableClub_EventScript_ExitMinigameRoom::
	end

CableClub_EventScript_CloseLinkAndExitLinkRoom::
	return

CableClub_EventScript_ExitTradeCenter::
	end

CableClub_EventScript_PlayerExitTradeCenter::
	return

CableClub_EventScript_ExitUnionRoom::
	end

CableClub_EventScript_PlayerExitUnionRoom::
	return

CableClub_EventScript_TrainerCardDataOverwritten::
	return

CableClub_EventScript_PlayerExitLinkRoom::
	return

CableClub_EventScript_Tutorial::
	end

Movement_PlayerApproachCounter:

CableClub_EventScript_WelcomeToCableClub::
	end

CableClub_EventScript_UnusedWelcomeToCableClub::
	end

CableClub_EventScript_SelectCableClubRoom::
	end

CableClub_EventScript_Colosseum::
	end

CableClub_EventScript_SelectBattleMode::
	end

CableClub_EventScript_BattleModeInfo::
	end

CableClub_EventScript_SingleBattleMode::
	end

CableClub_EventScript_DoubleBattleMode::
	end

CableClub_EventScript_NeedTwoMonsForDoubleBattle::
	end

CableClub_EventScript_MultiBattleMode::
	end

CableClub_EventScript_TryEnterColosseum::
	end

CableClub_EventScript_EnterColosseum::
	end

@ Unused
CableClub_EventScript_PlayerApproachLinkRoomRight::
	return

CableClub_EventScript_WarpTo4PColosseum::
	end

CableClub_EventScript_AbortLinkIncorrectNumberOfBattlers::
	end

CableClub_EventScript_AbortLinkNeedFourPlayers::
	end

CableClub_EventScript_AbortLinkWrongNumberForDoubleBattle::
	end

CableClub_EventScript_AbortLinkWrongNumberForSingleBattle::
	end

CableClub_EventScript_ConfirmNumberAndRestart::
	release
	end

CableClub_EventScript_TradeCenter::
	end

CableClub_EventScript_EnterTradeCenter::
	end

CableClub_EventScript_CheckPartyTradeRequirements::
	return

CableClub_EventScript_NeedTwoMonsToTrade::
	return

CableClub_EventScript_CantTradeEnigmaBerry::
	return

@ Record Corner is nopped in FRLG
CableClub_EventScript_RecordCorner::
	end

CableClub_EventScript_AbortLinkPlayerNotReady::
	end

CableClub_EventScript_AbortLinkOtherTrainerNotReady::
	end

CableClub_EventScript_AbortLinkConnectionError::
	end

CableClub_EventScript_AbortLinkSomeoneNotReady::
	end

CableClub_EventScript_AbortLinkDifferentSelections::
	end

CableClub_EventScript_AbortLink::
	end

CableClub_EventScript_AbortMinigame::
	end

@ Unused
CableClub_EventScript_CableClubWarp::
	end

CableClub_EventScript_AbortLinkIncorrectNumberOfParticipants::
	end

CableClub_EventScript_AbortLinkPlayerHasBadEgg::
	end

CableClub_EventScript_WirelessClubAdjustements::
	end

CableClub_EventScript_NotReadyYet::
	end

Movement_AttendantFaceDown::

@ Unused
Movement_AttendantFaceRight::

Movement_AttendantFaceLeft::

Movement_PlayerExitLinkRoom::

Movement_PlayerApproachLinkRoomRight::

Movement_PlayerApproachLinkRoomLeft::

Movement_PlayerEnterLinkRoom::

@ Unused
Movement_PlayerFaceAttendantLeft::

Movement_PlayerFaceAttendantRight::

Movement_PlayerEnterMinigameRoom::

CableClub_EventScript_ShowBattleRecords::
	end

BattleColosseum_2P_EventScript_PlayerSpot0::
	end

BattleColosseum_2P_EventScript_PlayerSpot1::
	end

BattleColosseum_4P_EventScript_PlayerSpot0::
	end

BattleColosseum_4P_EventScript_PlayerSpot1::
	end

BattleColosseum_4P_EventScript_PlayerSpot2::
	end

BattleColosseum_4P_EventScript_PlayerSpot3::
	end

BattleColosseum_4P_EventScript_CancelSpotTrigger::
	end

TradeCenter_EventScript_Chair0::
	end

TradeCenter_EventScript_Chair1::
	end

@ Unused
TradeCenter_EventScript_Chair2::
	end

@ Unused
TradeCenter_EventScript_Chair3::
	end

@ Nop in FRLG
@ Separate labels to match GetDirectionForEventScript
RecordCorner_EventScript_Spot0::
RecordCorner_EventScript_Spot1::
RecordCorner_EventScript_Spot2::
RecordCorner_EventScript_Spot3::
	end

CableClub_EventScript_ReadTrainerCard::
	end

CableClub_EventScript_ReadTrainerCardColored::
	end

CableClub_EventScript_TooBusyToNotice::
	end

BattleColosseum_2P_EventScript_Attendant::
	end

TradeCenter_EventScript_Attendant::
	end

@ Nop in FRLG
RecordCorner_EventScript_Attendant::
	end

TradeCenter_ConfirmLeaveRoom::
	end

TradeCenter_TerminateLink::
	end

CableClub_EventScript_DoLinkRoomExit::
	end

CableClub_EventScript_UnionRoomAttendant::
	end

CableClub_EventScript_AskEnterUnionRoom::
	end

CableClub_EventScript_UnionRoomInfo::
	end

CableClub_EventScript_EnterUnionRoom::
	end

CableClub_EventScript_CheckPartyUnionRoomRequirements::
	return

CableClub_EventScript_NeedTwoMonsForUnionRoom::
	end

CableClub_EventScript_NoEnigmaBerryInUnionRoom::
	end

CableClub_EventScript_UnionRoomAdapterNotConnected::
	return

CableClub_EventScript_WirelessClubAttendant::
	return

CableClub_EventScript_DontAskAboutLinking::
	return

CableClub_EventScript_DirectCornerAttendant::
	end

CableClub_EventScript_DirectCornerSelectService::
	end

CableClub_EventScript_DirectCornerNoBerry::
	end

CableClub_EventScript_WirelessTrade::
	end

CableClub_EventScript_WirelessBattleSelect::
	end

CableClub_EventScript_WirelessSingleBattle::
	end

CableClub_EventScript_WirelessDoubleBattle::
	end

CableClub_EventScript_TwoMonsNeededForWirelessDoubleBattle::
	end

CableClub_EventScript_WirelessMultiBattle::
	end

CableClub_EventScript_WirelessBattleInfo::
	end

CableClub_EventScript_WirelessBerryCrush::
	end

CableClub_EventScript_NeedBerryForBerryCrush::
	end

CableClub_EventScript_SaveAndChooseLinkLeader::
	end

CableClub_EventScript_ChooseLinkLeaderFrom2::
	end

CableClub_EventScript_TryLeadGroup2Players::
	return

CableClub_EventScript_TryJoinGroup2Players::
	return

CableClub_EventScript_ChooseLinkLeaderFrom4::
	end

CableClub_EventScript_TryLeadGroup4Players::
	return

CableClub_EventScript_TryJoinGroup4Players::
	return

CableClub_EventScript_ChooseLinkLeader::
	end

CableClub_EventScript_TryLeadGroupXPlayers::
	return

CableClub_EventScript_TryJoinGroupXPlayers::
	return

CableClub_EventScript_TryBecomeLinkLeader::
	return

CableClub_EventScript_TryJoinLinkGroup::
	return

CableClub_EventScript_EnterWirelessLinkRoom::
	end

CableClub_EventScript_ShowWirelessCommunicationScreen::
	end

CableClub_EventScript_AdapterNotConnected::
	end

CableClub_EventScript_OpenUnionRoomBarrier::
	return

CableClub_EventScript_CloseUnionRoomBarrier::
	return

CableClub_EventScript_OpenDirectCornerBarrier::
	return

CableClub_EventScript_CloseDirectCornerBarrier::
	return

CableClub_EventScript_OpenGameCornerBarrier::
	return

CableClub_EventScript_CloseGameCornerBarrier::
	return

CableClub_OnResume::
	end

JoyfulGameCorner_EventScript_InfoMan2::
	end

CableClub_EventScript_PokemonJumpInfo::
	end

CableClub_EventScript_DodrioBerryPickingInfo::
	end

CableClub_EventScript_MinigameInfoExit::
	end

JoyfulGameCorner_EventScript_MinigameAttendant::
	end

CableClub_EventScript_PlayPokemonJump::
	end

CableClub_EventScript_PlayDodrioBerryPicking::
	end

CableClub_EventScript_ChooseLinkLeaderMinigame::
	end

CableClub_EventScript_TryBecomeMinigameLinkLeader::
	return

CableClub_EventScript_TryJoinMinigameLinkGroup::
	return

CableClub_EventScript_EnterMinigame::
	end

CableClub_EventScript_AdapterNotConnectedMinigame::
	end

CableClub_EventScript_NoEligiblePkmn::
	end

CableClub_EventScript_ExplainPokemonJumpRequirements::
	return

CableClub_EventScript_ExplainDodrioBerryPickingRequirements::
	return

TwoIsland_JoyfulGameCorner_EventScript_ShowPokemonJumpRecords::
	end

TwoIsland_JoyfulGameCorner_EventScript_ShowDodrioBerryPickingRecords::
	end

CableClub_Text_WelcomeWhichCableClubService::
	.string "Welcome to the POKéMON CABLE\n"
	.string "CLUB.\p"
	.string "Which of our services do you wish\n"
	.string "to use?$"

CableClub_Text_WhichService::
	.string "Which of our services do you wish\n"
	.string "to use?$"

CableClub_Text_TradeMonsUsingLinkCable::
	.string "Trade POKéMON with another player\n"
	.string "using a GBA Game Link cable.$"

CableClub_Text_BattleUsingLinkCable::
	.string "You may battle another TRAINER\n"
	.string "using a GBA Game Link cable.$"

@ Unused, translated in Emerald
CableClub_Text_CloseThisMenu::
	.string "おわります$"

CableClub_Text_NeedTwoMonsForDoubleBattle::
	.string "For a DOUBLE BATTLE, you must\n"
	.string "have at least two POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade::
	.string "For trading, you must have at\n"
	.string "least two POKéMON with you.$"

CableClub_Text_CantTradeEnigmaBerry::
	.string "A POKéMON holding the {STR_VAR_1}\n"
	.string "BERRY can't be traded.$"

CableClub_Text_PleaseWaitBCancel::
	.string "Please wait.\n"
	.string "… … B Button: Cancel$"

CableClub_Text_WhenAllPlayersReadyAConfirmBCancel::
	.string "When all players are ready…\n"
	.string "A Button: Confirm\l"
	.string "B Button: Cancel$"

CableClub_Text_StartLinkWithXPlayersAConfirmBCancel::
	.string "Start link with {STR_VAR_1} players.\n"
	.string "A Button: Confirm\l"
	.string "B Button: Cancel$"

CableClub_Text_AwaitingLinkupBCancel::
	.string "Awaiting linkup…\n"
	.string "… … B Button: Cancel$"

@ Unused, translated in Emerald
CableClub_Text_OkayToSaveProgress::
	.string "はじめる　まえに　レポートを\n"
	.string "かきますが　よろしいですか？$"

CableClub_Text_PleaseEnter::
	.string "Please enter.$"

CableClub_Text_DirectYouToYourRoom::
	.string "I'll direct you to your room now.$"

CableClub_Text_SomeoneIsNotReadyToLink::
	.string "Someone is not ready to link.\p"
	.string "Please come back after everyone\n"
	.string "has made preparations.$"

CableClub_Text_LinkErrorPleaseReset::
	.string "Sorry, we have a link error…\n"
	.string "Please reset and try again.$"

CableClub_Text_PlayersMadeDifferentSelections::
	.string "The link partners appear to have\n"
	.string "made different selections.$"

CableClub_Text_PleaseVisitAgain::
	.string "Please do visit again.$"

CableClub_Text_IncorrectNumberOfParticipants::
	.string "The number of participants is\n"
	.string "incorrect.$"

CableClub_Text_CantSingleBattleWithXPlayers::
	.string "The SINGLE BATTLE Mode can't be\n"
	.string "played by {STR_VAR_1} players.$"

CableClub_Text_CantDoubleBattleWithXPlayers::
	.string "The DOUBLE BATTLE Mode can't be\n"
	.string "played by {STR_VAR_1} players.$"

CableClub_Text_NeedFourPlayers::
	.string "There must be four players to play\n"
	.string "this Battle Mode.$"

CableClub_Text_PleaseConfirmNumberAndRestart::
	.string "Please confirm the number of\n"
	.string "players and start again.$"

Text_TerminateLinkIfYouLeaveRoom::
	.string "The link will be terminated if you\n"
	.string "leave the room. Is that okay?$"

Text_TerminateLinkConfirmation::
	.string "Terminating link…\n"
	.string "You will be escorted out of\l"
	.string "the room. Please wait.$"

Text_TrainerTooBusyToNotice::
	.string "This TRAINER is too busy to\n"
	.string "notice…$"

Text_LookedAtPlayersTrainerCard::
	.string "Score! Got to look at {STR_VAR_1}'s\n"
	.string "TRAINER CARD!$"

Text_LookedAtPlayersTrainerCardColored::
	.string "Score! Got to look at {STR_VAR_1}'s\n"
	.string "TRAINER CARD!\p"
	.string "It's a {STR_VAR_2} card!$"

Text_TakeSeatStartBattle::
	.string "Please take your seat and start\n"
	.string "your battle.$"

Text_TakeSeatStartTrade::
	.string "Please take your seat and start\n"
	.string "your trade.$"

@ Unused, leftover from RS
RecordCorner_Text_ThanksForComing::
	.string "ごりよう　ありがとう　ございました$"

CableClub_Text_TrainerCardDataOverwritten::
	.string "The TRAINER CARD data will\n"
	.string "be overwritten.$"

CableClub_Text_HopeToSeeYouAgain::
	.string "I hope to see you again!$"

CableClub_Text_NotSetUpForFarAwayRegion::
	.string "I'm awfully sorry.\p"
	.string "We're not set up to conduct trades\n"
	.string "with TRAINERS far away in another\l"
	.string "region yet…$"

CableClub_Text_OtherTrainerNotReady::
	.string "The other TRAINER is not ready.$"

CableClub_Text_YouHaveAMonThatCantBeTaken::
	.string "You have at least one POKéMON\n"
	.string "that can't be taken.$"

CableClub_Text_AdapterNotConnected::
	.string "The Wireless Adapter is not\n"
	.string "connected properly.$"

CableClub_Text_ParticipantsStepUpToCounter::
	.string "Participants are asked to step up\n"
	.string "to the reception counter.$"

@ Unused, translated in Emerald
CableClub_Text_Hello::
	.string "こんにちは！$"

@ Unused, translated in Emerald
CableClub_Text_PleaseWait::
	.string "しょうしょう　おまちください$"

CableClub_Text_YouMayTradeHere::
	.string "You may trade your POKéMON here\n"
	.string "with another TRAINER.$"

CableClub_Text_YouMayBattleHere::
	.string "You may battle with your friends\n"
	.string "here.$"

CableClub_Text_CanMakeBerryPowder::
	.string "Two to five TRAINERS can make\n"
	.string "BERRY POWDER together.$"

@ Unused, Record Mix nopped
CableClub_Text_CanMixRecords::
	.string "ワイヤレス　クラブでの\n"
	.string "あそびかたを　せつめいします$"

CableClub_Text_CancelSelectedItem::
	.string "Cancels the selected MENU item.$"

@ Unused, translated in Emerald
CableClub_Text_WhichBattleMode::
	.string "どちらの　しょうぶに　しますか？$"

@ Unused, translated in Emerald
CableClub_Text_ReturnsToPreviousStep::
	.string "ひとつ　まえに　もどります$"

CableClub_Text_NeedBerryForBerryCrush::
	.string "To use the BERRY CRUSH service,\n"
	.string "you must have at least one BERRY.$"

CableClub_Text_NeedTwoMonsForUnionRoom::
	.string "To enter the UNION ROOM, you must\n"
	.string "have at least two POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom::
	.string "No POKéMON holding the {STR_VAR_1}\n"
	.string "BERRY may enter the UNION ROOM.$"

CableClub_Text_UnionRoomAdapterNotConnected::
	.string "This is the POKéMON WIRELESS CLUB\n"
	.string "UNION ROOM.\p"
	.string "Unfortunately, your Wireless\n"
	.string "Adapter is not connected properly.\p"
	.string "Please do come again.$"

@ Unused, translated in Emerald
CableClub_Text_OhExcuseMe::
	.string "あ‥‥\n"
	.string "おきゃくさま！$"

Text_PlayerIsPlayingRightNowGoForIt::
	.string "It appears as if {STR_VAR_1} is playing\n"
	.string "right now.\l"
	.string "Go for it!$"

Text_DescribeWhichGame::
	.string "I can explain game rules to you,\n"
	.string "if you'd like.\p"
	.string "Which game should I describe?$"

Text_PokemonJumpInfo::
	.string "“POKéMON JUMP”\p"
	.string "Make your POKéMON skip the\n"
	.string "VINE WHIP rope with the A Button.\p"
	.string "Only mini POKéMON around 28 inches\n"
	.string "or less may participate.\p"
	.string "POKéMON that only swim, burrow, or\n"
	.string "fly are not good at jumping.\p"
	.string "As a result, those POKéMON may not\n"
	.string "participate.\p"
	.string "Good things happen if everyone\n"
	.string "jumps in time.$"

Text_DodrioBerryPickingInfo::
	.string "“DODRIO BERRY-PICKING”\p"
	.string "Command DODRIO's three heads to\n"
	.string "catch falling BERRIES.\p"
	.string "Press right, up, or left on the\n"
	.string "{PLUS} Control Pad to move the heads.\p"
	.string "To play this game, you must have\n"
	.string "a DODRIO.$"

Text_TalkToManToPlay::
	.string "If you want to play a game,\n"
	.string "please tell the man beside me.$"

Text_WelcomeCanYouWait::
	.string "Hi, welcome!\n"
	.string "You can play games over the\l"
	.string "Wireless Communication System.\p"
	.string "Can you wait just a little bit?$"

CableClub_Text_ComeAgain::
	.string "All right, come again!$"

Text_AdapterNotConnectedMinigame::
	.string "The Wireless Adapter isn't\n"
	.string "connected.\p"
	.string "Come back when it's hooked up!$"

Text_PlayWhichGame::
	.string "All right, which game did you want\n"
	.string "to play?$"

Text_EnterWhichPokemon::
	.string "Which POKéMON would you like to\n"
	.string "enter?$"

Text_AllGoodToGo::
	.string "Okay, you're all good to go.\n"
	.string "Don't let the others beat you!$"

@ Unused, translated in Emerald
Text_LeavingDoComeAgain::
	.string "きょうは　けえるのか？\n"
	.string "またこいよ！$"

EventScript_ExplainPokemonJumpRequirements::
	.string "It doesn't look like you have any\n"
	.string "POKéMON that you can enter…\p"
	.string "Would you like me to explain what\n"
	.string "kinds of POKéMON can enter?$"

Text_ShortJumpingPokemonAllowed::
	.string "“POKéMON JUMP” is open to POKéMON\n"
	.string "around 28 inches or less.\p"
	.string "What you can't enter are those\n"
	.string "POKéMON that can't jump.\p"
	.string "You know, like POKéMON that only\n"
	.string "swim, burrow, or fly.\p"
	.string "That's all you need to know.$"

Text_OnlyDodrioAllowed::
	.string "“DODRIO BERRY-PICKING”…\n"
	.string "Well, the name says it all.\p"
	.string "You have to have a DODRIO to play\n"
	.string "this game.$"

@ Unused, translated in Emerald
Text_RetryFromStartPlease::
	.string "もういちど　はじめから\n"
	.string "やりなおして　みて　くれ$"

CableClub_Text_WelcomeWhichDirectCornerRoom::
	.string "Welcome to the POKéMON WIRELESS\n"
	.string "CLUB DIRECT CORNER.\p"
	.string "You may interact directly with\n"
	.string "your friends here.\p"
	.string "Which room would you like to\n"
	.string "enter?$"

CableClub_Text_TradePokemon::
	.string "Would you like to trade POKéMON?$"

CableClub_Text_PlayWhichBattleMode::
	.string "Which Battle Mode would you like\n"
	.string "to play?$"

CableClub_Text_UseBerryCrush::
	.string "Would you like to use the\n"
	.string "BERRY CRUSH System?$"

CableClub_Text_ExplainBattleModes::
	.string "There are three Battle Modes.\p"
	.string "SINGLE BATTLE is for two TRAINERS\n"
	.string "with one or more POKéMON each.\p"
	.string "Each TRAINER can have one POKéMON\n"
	.string "in battle at a time.\p"
	.string "DOUBLE BATTLE is for two TRAINERS\n"
	.string "with two or more POKéMON each.\p"
	.string "Each TRAINER will send out two\n"
	.string "POKéMON in battle at a time.\p"
	.string "MULTI BATTLE is for four TRAINERS\n"
	.string "with one or more POKéMON each.\p"
	.string "Each TRAINER can have one POKéMON\n"
	.string "in battle at a time.$"

CableClub_Text_ChooseGroupLeaderOfTwo::
	.string "Please decide which of you two\n"
	.string "will become the LEADER.\p"
	.string "The other player must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeaderOfFour::
	.string "Please decide which of you four\n"
	.string "will become the GROUP LEADER.\p"
	.string "The other players must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeader::
	.string "Please decide which of you will\n"
	.string "become the GROUP LEADER.\p"
	.string "The other players must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_WelcomeUnionRoomEnter::
	.string "Welcome to the POKéMON WIRELESS\n"
	.string "CLUB UNION ROOM.\p"
	.string "You may interact directly with\n"
	.string "other TRAINERS here, some of\l"
	.string "whom you may not even know.\p"
	.string "Would you like to enter the ROOM?$"

CableClub_Text_UnionRoomInfo::
	.string "The TRAINERS in the UNION ROOM\n"
	.string "will be those players around you\l"
	.string "who have also entered the ROOM.\p"
	.string "You may do all sorts of things\n"
	.string "here, such as exchanging greetings.\p"
	.string "You may enter two POKéMON up to\n"
	.string "Lv. 30 for a one-on-one battle.\p"
	.string "You may take part in a chat with\n"
	.string "two to five people.\p"
	.string "Or, you may register a POKéMON for\n"
	.string "trade.\p"
	.string "Would you like to enter the ROOM?$"

CableClub_Text_EnjoyUnionRoom::
	.string "I hope you enjoy your time in\n"
	.string "the UNION ROOM.$"

CableClub_Text_FirstTimeRightThisWay::
	.string "TEALA: Hi there, dumbass.\n"
	.string "Don't go out of bounds.$"

CableClub_Text_ExplainWirelessClubFirstTime::
	.string "On the top floor, there are two\n"
	.string "rooms.\p"
	.string "First, the room on the left.\n"
	.string "It's the UNION ROOM.\p"
	.string "You may link up with TRAINERS\n"
	.string "around you who have also entered\l"
	.string "the UNION ROOM.\p"
	.string "With them, you may do things like\n"
	.string "chat, battle, and trade.\p"
	.string "Second, the room on the right is\n"
	.string "the DIRECT CORNER.\p"
	.string "You may trade or battle POKéMON\n"
	.string "with your friends in this room.\p"
	.string "If the Wireless Adapter isn't\n"
	.string "connected, you may still link up\l"
	.string "using a GBA Game Link cable.\p"
	.string "If that is the case, you must go\n"
	.string "to the DIRECT CORNER.\p"
	.string "I hope you enjoy the Wireless \n"
	.string "Communication System.$"

CableClub_Text_AskAboutLinking::
	.string "Hello, {PLAYER}!\p"
	.string "It's me, TEALA, the POKéMON\n"
	.string "CENTER 2F attendant.\p"
	.string "Is there something you needed to\n"
	.string "ask me about linking?$"

CableClub_Text_ExplainWirelessClub::
	.string "Let me explain how the POKéMON\n"
	.string "WIRELESS CLUB works.\p"
	.string "On this, the top floor, there are\n"
	.string "two rooms.\p"
	.string "First, the room on the left.\n"
	.string "It's the UNION ROOM.\p"
	.string "You may link up with TRAINERS\n"
	.string "around you who have also entered\l"
	.string "the UNION ROOM.\p"
	.string "With them, you may do things like\n"
	.string "chat, battle, and trade.\p"
	.string "Second, the room on the right is\n"
	.string "the DIRECT CORNER.\p"
	.string "You may trade or battle POKéMON\n"
	.string "with your friends in this room.\p"
	.string "Sometimes, you may not be able to\n"
	.string "find your friends in the UNION ROOM\l"
	.string "or the DIRECT CORNER.\p"
	.string "In that case, please move closer\n"
	.string "to your friends.\p"
	.string "If the Wireless Adapter isn't\n"
	.string "connected, you may still link up\l"
	.string "using a GBA Game Link cable.\p"
	.string "If that is the case, you must go\n"
	.string "to the DIRECT CORNER.\p"
	.string "I hope you enjoy the Wireless \n"
	.string "Communication System.$"

CableClub_Text_HopeYouEnjoyWirelessSystem::
	.string "I hope you enjoy the Wireless\n"
	.string "Communication System.$"
