ViridianCity_School_EventScript_PokemonJournal::
	lock
	faceplayer
	famechecker FAMECHECKER_PALLET, 3
	famechecker FAMECHECKER_VIRIDIAN, 3
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureProfOak
	release
	end

EventScript_PokemonJournalUnused1::
	lock
	faceplayer
	famechecker FAMECHECKER_VIRIDIAN, 1
	famechecker FAMECHECKER_PALLET, 4
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureProfOak
	release
	end

EventScript_PokemonJournalUnused2::
	lock
	faceplayer
	famechecker FAMECHECKER_VIRIDIAN, 4
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureProfOak
	release
	end

FourIsland_PokemonCenter_1F_EventScript_PokemonJournal::
	lockall
	famechecker FAMECHECKER_VIRIDIAN, 5
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureDaisyOak
	releaseall
	end

Route4_EventScript_Boy::
	lock
	faceplayer
	famechecker FAMECHECKER_PEWTER, 3
	msgbox Route4_Text_PeopleLikeAndRespectBrock
	release
	end

MtMoon_1F_EventScript_BaldingMan::
	lock
	faceplayer
	famechecker FAMECHECKER_PEWTER, 4
	msgbox MtMoon_1F_Text_BrockHelpsExcavateFossils
	release
	end

PewterCity_Museum_1F_EventScript_PokemonJournalBrock::
	lockall
	famechecker FAMECHECKER_PEWTER, 5
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureBrock
	releaseall
	end

Route20_EventScript_Camper::
	lock
	faceplayer
	famechecker FAMECHECKER_MT_MOON, 3
	msgbox Route20_Text_MistyTrainsHere
	release
	end

Route25_EventScript_Beauty::
	lock
	faceplayer
	famechecker FAMECHECKER_MT_MOON, 4
	msgbox Route25_Text_MistyHighHopesAboutThisPlace
	release
	end

CeruleanCity_PokemonCenter_1F_EventScript_PokemonJournalMisty::
	lock
	faceplayer
	famechecker FAMECHECKER_MT_MOON, 5
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureMisty
	release
	end

VermilionCity_PokemonCenter_1F_EventScript_PokemonJournalLtSurge::
	lockall
	famechecker FAMECHECKER_CERULEAN, 5
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureLtSurge
	releaseall
	end

CeladonCity_Condominiums_2F_EventScript_PokemonJournalErika::
	lock
	faceplayer
	famechecker FAMECHECKER_VERMILION, 5
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureErika
	release
	end

FushciaCity_WardensHouse_EventScript_PokemonJournalKoga::
	lock
	faceplayer
	famechecker FAMECHECKER_ROCK_TUNNEL, 4
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureKoga
	release
	end

SafariZone_North_RestHouse_EventScript_BaldingMan::
	lock
	faceplayer
	famechecker FAMECHECKER_ROCK_TUNNEL, 5
	msgbox SafariZone_West_Text_KogaPatrolsSafariEverySoOften
	release
	end

SaffronCity_PokemonCenter_1F_EventScript_PokemonJournalSabrina::
	lock
	faceplayer
	famechecker FAMECHECKER_LAVENDER, 4
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureSabrina
	release
	end

CinnabarIsland_Gym_EventScript_BlaineFujiPhoto::
	lockall
	famechecker FAMECHECKER_CELADON, 4
	famechecker FAMECHECKER_GREAT_SEA_WEST, 4
	msgbox CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji
	releaseall
	end

FiveIsland_ResortGorgeous_House_EventScript_PokemonJournal::
	lockall
	famechecker FAMECHECKER_CELADON, 5
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureBlaine
	releaseall
	end

FourIsland_Mart_EventScript_OldMan::
	lock
	faceplayer
	famechecker FAMECHECKER_FUSHCIA, 2
	msgbox FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland
	release
	end

FiveIsland_PokemonCenter_1F_EventScript_PokemonJournal::
	lock
	faceplayer
	famechecker FAMECHECKER_FUSHCIA, 3
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureLorelei
	release
	end

SaffronCity_PokemonTrainerFanClub_EventScript_PokemonJournalBruno::
	lock
	faceplayer
	famechecker FAMECHECKER_KANTO_SHORELINE, 2
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureBruno
	release
	end

SevenIsland_SevaultCanyon_EventScript_BlackBelt::
	lock
	faceplayer
	famechecker FAMECHECKER_KANTO_SHORELINE, 5
	msgbox SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly
	release
	end

IndigoPlateau_PokemonCenter_1F_EventScript_BlackBelt::
	lock
	faceplayer
	famechecker FAMECHECKER_SAFFRON, 1
	famechecker FAMECHECKER_SAFFRON, 2
	msgbox IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs
	release
	end

SevenIsland_PokemonCenter_1F_EventScript_PokemonJournal::
	lock
	faceplayer
	famechecker FAMECHECKER_SAFFRON, 3
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureAgatha
	release
	end

SixIsland_Mart_EventScript_OldWoman::
	lock
	faceplayer
	famechecker FAMECHECKER_SAFFRON, 5
	msgbox SixIsland_Mart_Text_AgathaOldestEverEliteFourMember
	release
	end

EventScript_LanceUnused::
	lock
	faceplayer
	famechecker FAMECHECKER_GREAT_SEA, 0
	msgbox gFameCheckerFlavorText_Lance0
	release
	end

SaffronCity_EventScript_BattleGirlUnused::
	lock
	faceplayer
	famechecker FAMECHECKER_GREAT_SEA, 1
	msgbox SaffronCity_Text_HowCanClubNotRecognizeLance
	release
	end

SaffronCity_EventScript_BattleGirl::
	lock
	faceplayer
	famechecker FAMECHECKER_GREAT_SEA, 2
	msgbox SaffronCity_Text_HowCanClubNotRecognizeLance
	release
	end

CeladonCity_DepartmentStore_2F_EventScript_Woman::
	lock
	faceplayer
	famechecker FAMECHECKER_GREAT_SEA, 3
	msgbox CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes
	release
	end

IndigoPlateau_PokemonCenter_1F_EventScript_PokemonJournal::
	lock
	faceplayer
	famechecker FAMECHECKER_GREAT_SEA, 4
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureLance
	release
	end

IndigoPlateau_PokemonCenter_1F_EventScript_CooltrainerM::
	lock
	faceplayer
	famechecker FAMECHECKER_GREAT_SEA, 5
	msgbox IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway
	release
	end

LavenderTown_PokemonCenter_1F_EventScript_BaldingMan::
	lock
	faceplayer
	famechecker FAMECHECKER_GREAT_SEA_WEST, 3
	msgbox LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere
	release
	end

CinnabarIsland_PokemonCenter_1F_EventScript_PokemonJournalMrFuji::
	lock
	faceplayer
	famechecker FAMECHECKER_GREAT_SEA_WEST, 5
	textcolor NPC_TEXT_COLOR_NEUTRAL
	msgbox PokemonJournal_Text_SpecialFeatureMrFuji
	release
	end

SilphCo_5F_EventScript_Scientist::
	lock
	faceplayer
	famechecker FAMECHECKER_CINNABAR, 1
	msgbox SilphCo_5F_Text_RocketBossLookingForStrongMons
	release
	end

SilphCo_8F_EventScript_Scientist::
	lock
	faceplayer
	famechecker FAMECHECKER_CINNABAR, 2
	msgbox SilphCo_8F_Text_ToRocketBossMonsAreTools
	release
	end
