Route6_Text_RickyIntro::
    .string "Whipster…\p"
    .string "This POKéMON leaked early!\n"
    .string "It's gonna be in the new game!\p"
    .string "…Huh? Hey, stop eavesdropping!$"

Route6_Text_RickyDefeat::
    .string "I just can't win!$"

Route6_Text_RickyPostBattle::
    .string "Whisper…\n"
    .string "Whisper…$"

Route6_Text_NancyIntro::
    .string "Whipster…\p"
    .string "Did you hear? LUVDISC is gonna\n"
    .string "be able to evolve!$"

Route6_Text_NancyDefeat::
    .string "Ugh!\n"
    .string "I hate losing.$"

Route6_Text_NancyPostBattle::
    .string "Whipster…\p"
    .string "…Oh? ALOMOMOLA is showing up in\n"
    .string "your POKéDEX?\l"
    .string "I wonder why.$"

Route6_Text_KeigoIntro::
    .string "I'm supposed to have a BUTTERFREE,\n"
    .string "but…\p"
    .string "I think I'm doing something wrong.$"

Route6_Text_KeigoDefeat::
    .string "You're too good!\n"

Route6_Text_KeigoPostBattle::
    .string "Are my POKéMON WEAK?\n"
    .string "Or, am I just bad?\l"
    .string "Which do you think?\l"

Route6_Text_JeffIntro::
    .string "POKéMON just hasn't been the same\n"
    .string "since Generation 1.\p"
    .string "As far as I'm concerned, the\n"
    .string "original 151 are the only real ones.$"

Route6_Text_JeffDefeat::
    .string "This stinks…$"

Route6_Text_JeffPostBattle::
    .string "I'm a very proud member of the\n"
    .string "POKéMON FAN CLUB!\p"
    .string "You should visit them in VERMILLION!$"

Route6_Text_IsabelleIntro::
    .string "I don't like that guy over there…\p"
    .string "I think there were lots of good\n"
    .string "POKéMON after Gen 1!$"


Route6_Text_IsabelleDefeat::
    .string "Things just didn't work…$"

Route6_Text_IsabellePostBattle::
    .string "I grew up with Gen 5, so those are\n"
    .string "my favorites!\p"
    .string "But I don't like anything after the\n"
    .string "original 649!$"

Route6_Text_ElijahIntro::
    .string "Have you heard of specially-colored\n"
    .string "POKéMON?\p"
    .string "I hear they're super rare!$"

Route6_Text_ElijahDefeat::
    .string "No!\n"
    .string "You're kidding!$"

Route6_Text_ElijahPostBattle::
    .string "I used to have another BUTTERFREE\n"
    .string "too!\p"
    .string "Sadly, he got hit by a bus.$"

Route6_Text_UndergroundPathSign::
    .string "ROUTE 6\p"
    .string "NEW WILD POKéMON:\n"
    .string "Same as ROUTE 5, idk$"

