ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "I'm sure nobody will install a\n"
    .string "virus on one!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "There's a POKéMON CENTER in every\n"
    .string "town ahead.\p"
    .string "…Well, most of the, anyway.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "The POKéMON world has universal\n"
    .string "healthcare for animals, yet America\l"
    .string "still can't figure it out for humans.$"

