Route3_Text_TunnelFromCeruleanTiring::
	.string "Whew… I better take a rest…\n"
	.string "Groan…\p"
	.string "I took the treck all the way through\n"
	.string "the UNDERGROUND PATH to VERMILLION\l"
	.string "and then into DIGLETTS' CAVE over\l"
	.string "to ROUTE 2, up through PEWTER and\l"
	.string "now onto ROUTE 3.\p"
	.string "It was one heck of a journey, but\n"
	.string "alas!\l"
	.string "I had to get back from CERULEAN.\p"
	.string "Too bad there's no other way here!\n"
	.string "Darn ledges…$"

Route3_Text_ColtonIntro::
    .string "Hey!\n"
    .string "I saw you in PETALBURG WOODS!$"

Route3_Text_ColtonDefeat::
    .string "Wait, was that you?$"

Route3_Text_ColtonPostBattle::
    .string "Oh, maybe it was SANTALUNE FOREST\n"
    .string "I saw you in?$"

Route3_Text_BenIntro::
    .string "I am SHORTS!\n"
    .string "I'm comfy and easy to wear!$"

Route3_Text_BenDefeat::
    .string "I don't believe it!$"

Route3_Text_BenPostBattle::
    .string "I am SHORTS\p"
    .string "Put me on please!$"

Route3_Text_JaniceIntro::
    .string "Excuse me!\n"
    .string "You looked at me, didn't you?\p"
    .string "Yup, you definitely looked\n"
    .string "at me.\p"
    .string "That certainly is what just\n"
    .string "happened.$"

Route3_Text_JaniceDefeat::
    .string "You're mean!\n"
    .string "Stop looking at me!$"

Route3_Text_JanicePostBattle::
    .string "Excuse me!\n"
    .string "don'How DARE you have eyes!$"

Route3_Text_GregIntro::
    .string "Are you a TRAINER?\n"
    .string "Let's get with it right away!$"

Route3_Text_GregDefeat::
    .string "If I had new POKéMON, I would've\n"
    .string "won!$"

Route3_Text_GregPostBattle::
    .string "If a POKéMON BOX on the PC gets\n"
    .string "full, just switch to another BOX.$"

Route3_Text_SallyIntro::
    .string "That look you gave me…\n"
    .string "It was.\p"
    .string "Yup.\n"
    .string "There definitely was a look.$"

Route3_Text_SallyDefeat::
    .string "Be nice!$"

Route3_Text_SallyPostBattle::
    .string "You can avoid battles by not\n"
    .string "letting TRAINERS see you.$"

Route3_Text_CalvinIntro::
    .string "Hey! I'm the other shorts kid!\n"
    .string "No one seems to remember me though…$"

Route3_Text_CalvinDefeat::
    .string "Lost!\n"
    .string "Lost! Lost!$"

Route3_Text_CalvinPostBattle::
    .string "I always wear shorts, even in\n"
    .string "winter. That's my policy.$"

Route3_Text_JamesIntro::
    .string "I'll battle you with the POKéMON\n"
    .string "I just caught.$"

Route3_Text_JamesDefeat::
    .string "Done like dinner!$"

Route3_Text_JamesPostBattle::
    .string "Trained POKéMON are stronger than\n"
    .string "the wild ones.$"

Route3_Text_RobinIntro::
	.string "I caught my son a few random\n"
	.string "birds in the grass here.\p"
	.string "I hear they decided to give him the\n"
	.string "keys to a GYM?$"

Route3_Text_RobinDefeat::
	.string "Clipped with a jolt of electricity!\n$"

Route3_Text_RobinPostBattle::
	.string "My son was playing in the cave up\n"
	.string "ahead earlier.\p"
	.string "I think he dropped his favorite\n"
	.string "TM on the ground somewhere.$"

Route3_Text_RouteSign::
    .string "ROUTE 3\n"
    .string "NEW WILD POKéMON: 1\l"
    .string "NEW SMASH BROS CHARACTERS: 1$"
