ViridianForest_Text_FriendsItchingToBattle::
    .string "Did you know you can't encounter\n"
    .string "POKéMON in tiles that have flowers?$"

ViridianForest_Text_RickIntro::
    .string "Hey! You have POKéMON!\n"
    .string "Come on!\l"
    .string "Let's battle 'em!$"

ViridianForest_Text_RickDefeat::
    .string "No!\n"
    .string "CATERPIE is unable to modify the\l"
    .string "existing ROM to create unintended\l"
    .string "behavior!$"

ViridianForest_Text_RickPostBattle::
    .string "You heard what I said.$"

ViridianForest_Text_DougIntro::
    .string "Yo!\n"
    .string "I like jam!$"

ViridianForest_Text_DougDefeat::
    .string "Huh?\n"
    .string "I ran out of POKéMON!$"

ViridianForest_Text_DougPostBattle::
    .string "Man, I thought I was so strong!\p"
    .string "I beat this one guy more than\n"
    .string "300 times in a row once!$"

ViridianForest_Text_SammyIntro::
	.string "Hey, you!\n"
	.string "One day, I'm gonna be just like\l"
	.string "BROCK!\p"
	.string "Check out the super strong\n"
	.string "SANDSHREW I trained!$"

ViridianForest_Text_SammyDefeat::
    .string "I give!\n"
    .string "You're good at this!$"

ViridianForest_Text_SammyPostBattle::
	.string "I trained my SANDSHREW by chucking\n"
	.string "him into that pond over there.\p"
	.string "I hear that BROCK's ONIX is also\n"
	.string "immune to WATER attacks!$"

ViridianForest_Text_AnthonyIntro::
    .string "I might be little, but I'm the \n"
    .string "POKéMON 10U champion!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Oh, boo.\n"
    .string "Nothing went right.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "Huh? DITTO isn't showing up in\n"
    .string "your POKéDEX?$"

ViridianForest_Text_CharlieIntro::
    .string "Did you know that POKéMON evolve?\p"
    .string "That's why my parents didn't let\n"
    .string "me play it!$"

ViridianForest_Text_CharlieDefeat::
    .string "Oops.\n"
    .string "I misclicked.$"

ViridianForest_Text_CharliePostBattle::
    .string "BUG POKéMON evolve quickly.\p"
    .string "Well, except for CATERPIE.$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "I was throwing POKé BALLS to\n"
    .string "catch POKéMON, and I ran out.\p"
	.string "Thankfully, POKéBALLs are always\n"
	.string "guaranteed to work!\l"
	.string "(…mostly.)$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
	.string "TRAINER TIPS\p"
	.string "No, there is no sign here.\p"
	.string "Thank you for remembering that\n"
	.string "there should be one, though!$"

ViridianForest_Text_UseAntidoteForPoison::
	.string "TRAINER TIPS\p"
	.string "Use RARE CANDYS!\p"
	.string "They're plentiful and will save\n"
	.string "you time.$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "For bugs, use POISON!\p"
    .string "This message brought to you by\n"
    .string "the RBY type chart!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "TRAINER TIPS\p"
    .string "Contact PROF. OAK via a PC to\n"
    .string "get your POKéDEX evaluated!…\p"
    .string "(Seriously, has anyone ever\n"
    .string "actually done this?)$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "VIRIDIAN FOREST\p"
    .string "NEW WILD POKéMON: 2$"

ViridianForest_Text_LeavingViridianForest::
    .string "LEAVING VIRIDIAN FOREST\n"
    .string "PEWTER CITY AHEAD$"

