ViridianForest_Text_FriendsItchingToBattle::
    .string "Did you know you can't encounter\n"
    .string "POKéMON in tiles that have flowers?$"

ViridianForest_Text_RickIntro::
    .string "Hey! You have POKéMON!\n"
    .string "Come on!\l"
    .string "Let's battle 'em!$"

ViridianForest_Text_RickDefeat::
    .string "No!\n"
    .string "CATERPIE is unable to modify the\l"
    .string "existing ROM to create unintended\l"
    .string "behavior!$"

ViridianForest_Text_RickPostBattle::
    .string "CATERPIE is unable to modify the\l"
    .string "existing ROM to create unintended\l"
    .string "behavior!$"

ViridianForest_Text_DougIntro::
    .string "Yo!\n"
    .string "I like jam!$"

ViridianForest_Text_DougDefeat::
    .string "Huh?\n"
    .string "I ran out of POKéMON!$"

ViridianForest_Text_DougPostBattle::
    .string "Man, I thought I was so strong!\p"
    .string "I beat this one guy more than\n"
    .string "300 times in a row once!$"

ViridianForest_Text_SammyIntro::
    .string "Hey, wait up!\n"
    .string "What's the hurry? Why the rush?$"

ViridianForest_Text_SammyDefeat::
    .string "I give!\n"
    .string "You're good at this!$"

ViridianForest_Text_SammyPostBattle::
    .string "Sometimes, you can find stuff on\n"
    .string "the ground.\p"
    .string "I'm looking for the stuff I\n"
    .string "dropped. Can you help me?$"

ViridianForest_Text_AnthonyIntro::
    .string "I might be little, but I'm the \n"
    .string "POKéMON 10U champion!$"

ViridianForest_Text_AnthonyDefeat::
    .string "Oh, boo.\n"
    .string "Nothing went right.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "Huh? DITTO isn't showing up in\n"
    .string "your POKéDEX?$"

ViridianForest_Text_CharlieIntro::
    .string "Did you know that POKéMON evolve?\p"
    .string "That's why my parents didn't let\n"
    .string "me play it!$"

ViridianForest_Text_CharlieDefeat::
    .string "Oh!\n"
    .string "I lost!$"

ViridianForest_Text_CharliePostBattle::
    .string "BUG POKéMON evolve quickly.\p"
    .string "Well, except for CATERPIE.$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "I was throwing POKé BALLS to\n"
    .string "catch POKéMON, and I ran out.\p"
    .string "Thankfully, catch rates are all\n"
    .string "set to the maximum!\l"
    .string "(...mostly.)$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "TRAINER TIPS\p"
    .string "If your POKéMON are weak and you\n"
    .string "want to avoid battles, stay away\l"
    .string "from grassy areas!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "For poison, use ANTIDOTE!\n"
    .string "Get it at POKéMON MARTS!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "For bugs, use POISON\p"
    .string "This message brought to you by\n"
    .string "the RBY type chart!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "TRAINER TIPS\p"
    .string "Contact PROF. OAK via a PC to\n"
    .string "get your POKéDEX evaluated!…\p"
    .string "(Seriously, has anyone ever\n"
    .string "actually done this?)$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "VIRIDIAN FOREST\p"
    .string "NEW WILD POKéMON: 2$"

ViridianForest_Text_LeavingViridianForest::
    .string "LEAVING VIRIDIAN FOREST\n"
    .string "PEWTER CITY AHEAD$"

