MtMoon_B2F_Text_MiguelIntro::
    .string "Hey, stop!\p"
    .string "I found these fossils!\n"
    .string "They're both mine!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "Okay!\n"
    .string "I'll share!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "What?! I thought my KOFFING was\n"
    .string "invincible!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "All right.\n"
    .string "Phew!\p"
    .string "This is the one I wanted anyway.$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "I expected to be able to stop\n"
    .string "you with my invincible KOFFING…\p"
    .string "Surely this will be the only time\n"
    .string "you fight someone with WONDER GUARD.$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "We, the DMCA, shall find the\n"
    .string "fossils!\p"
    .string "Copyright claiming them will\n"
    .string "earn us huge riches!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "Urgh!\n"
    .string "Now I'm mad!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "Fossils are illegal copies of\n"
    .string "living things!$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "We, the DMCA, are copyright\n"
    .string "gangsters!\l"
    .string "We strike fear with our takedown!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "I blew it!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "Copyright law is the foundation\n"
    .string "of society!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "There's lots of content to claim\n"
    .string "gere, kid!\p"
    .string "We're the DMCA, and we don't"
    .string "take kindly to being messed with!\p"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "So, you are good…$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "You made me mad!\n"
    .string "The DMCA will blacklist you!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "Hey, kid!\p"
    .string "You better not be hosting any\n"
    .string "copyrighted content!\p"
    .string "It could be bad news!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "Blast it!\n"
    .string "My rat was bigger than yours!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "Grr!\p"
    .string "I won't let your rat evolve -\n"
    .string "then it'd be the same as mine!\l"
    .string "That's illegal!$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "Do you want the SAIL FOSSIL?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "Do you want the JAW FOSSIL?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "Hey wait!\p"
    .string "That one's my favorite!\n"
    .string "You can't have it!\p"
    .string "Take the other one!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "Obtained the JAW FOSSIL!$"

