Route22_Text_EarlyRivalIntro::
	.string "LARRY: Hey! {PLAYER}!\p"
	.string "You're off to the POKéMON LEAGUE?\n"
	.string "Forget about it!\p"
	.string "You probably don't have any\n"
	.string "BADGES, do you?\p"
	.string "The guard won't let you through\n"
	.string "without them.\p"
	.string "By the way, did your POKéMON get\n"
	.string "any stronger?$"

Route22_Text_EarlyRivalDefeat::
	.string "Awww!\n"
	.string "You just lucked with that FOCUS SASH!$"

Route22_Text_EarlyRivalPostBattle::
	.string "LARRY: I thought for sure that\n"
	.string "my ZAPDOS could beat you!\l"
	.string "Stupid rat!\p"
	.string "…Huh? GARY? Who's that?\p"
	.string "My name is LARRY!$"

Route22_Text_LarryVictory::
	.string "LARRY: Yeah!\n"
	.string "Am I great or what?$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
	.string "MARY: Heyyyy!\n"
	.string "You must be {PLAYER}!\p"
	.string "You've collected all your badges?\n"
	.string "That's certainly something.\p"
	.string "I guess I have to whip you, then!\n"
	.string "Come on!$"

Route22_Text_LateRivalDefeat::
	.string "What!?\n"
	.string "How'd you do that?$"

	
Route22_Text_LateRivalPostBattle::
	.string "MARY: I thought for sure my unholy\n"
	.string "amalgom could beat you!\l"
	.string "Stupid rat!\p"
	.string "Well anyway, that's all from me.\n"
	.string "Hope you do well!\l"
	.string "Taste ya later!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign::
	.string "POKéMON LEAGUE\n"
	.string "Front Gate$"

