SilphCo_11F_Text_ThanksForSavingMeDearBoy::
	.string "PRESIDENT: Oh, is the board meeting\n"
	.string "over?\l"
	.string "I was getting bored anyway.\p"
	.string "Oh, did you think I was threatened?\n"
	.string "Ohoho, how silly!\p"
	.string "That man was going to make me lots\n"
	.string "of money!\l"
	.string "I really like money.\p"
	.string "But here, have a nice trinket.\n"
	.string "We had some extras in production.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
	.string "PRESIDENT: Oh, is the board meeting\n"
	.string "over?\l"
	.string "I was getting bored anyway.\p"
	.string "Oh, did you think I was threatened?\n"
	.string "Ohoho, how silly!\p"
	.string "That man was going to make me lots\n"
	.string "of money!\l"
	.string "I really like money.\p"
	.string "But here, have a nice trinket.\n"
	.string "We had some extras in production.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "{PLAYER} obtained a MISTER BALL\n"
    .string "from the PRESIDENT!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "PRESIDENT: You can't buy that\n"
    .string "anywhere.\p"
    .string "It's our secret prototype MISTER\n"
    .string "BALL.\p"
    .string "It will catch any MISTER without\n"
	.string "fail!$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "You have no room for this.$"

SilphCo_11F_Text_ThanksForRescuingUs::
	.string "SECRETARY: Now that our meeting is\n"
	.string "finished, I can get back to work.\p"
	.string "Feel free to explore the rest of\n"
	.string "the building.\l"
	.string "There's plenty to see!\p"
	.string "Maybe you'll come across our\n"
	.string "facility for POKé BALL development!$"

SilphCo_11F_Text_GiovanniIntro::
    .string "Ah, {PLAYER}!\n"
    .string "So we meet again!\p"
    .string "The PRESIDENT and I are discussing\n"
    .string "a vital business proposition.\p"
    .string "Keep your nose out of grown-up\n"
    .string "matters…\p"
    .string "Or, experience a world of pain!$"

SilphCo_11F_Text_GiovanniDefeat::
	.string "Arrgh!!\n"
	.string "You copied me!$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "Blast it all!\n"
    .string "You ruined our plans for SILPH!\p"
    .string "But, TEAM ROCKET will never fall!\p"
    .string "{PLAYER}! Never forget that all\n"
    .string "POKéMON exist for TEAM ROCKET!\p"
    .string "I must go, but I shall return!$"

SilphCo_11F_Text_Grunt2Intro::
    .string "Stop right there!\n"
    .string "Don't you move!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "Don't…\n"
    .string "Please!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "So, you want to see my BOSS?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "Halt! Do you have an appointment\n"
    .string "with my BOSS?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "Gaah!\n"
    .string "Demolished!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Watch your step…\n"
    .string "My BOSS likes his POKéMON tough!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "The monitor has POKéMON on it!$"

SilphCo_11F_Text_FloorSign::
    .string "SILPH CO. HEAD OFFICE\n"
    .string "11F$"

