FushciaCity_Text_DidYouTrySafariGame::
    .string "Did you try the SAFARI GAME?\p"
    .string "There are some rare POKéMON that\n"
    .string "can only be caught there.$"

FushciaCity_Text_SafariZoneZooInFront::
    .string "The SAFARI ZONE has a zoo in front\n"
    .string "of the entrance.\p"
    .string "Out back is the SAFARI GAME for\n"
    .string "catching POKéMON.$"

FushciaCity_Text_WheresSara::
    .string "ERIK: Where's SARA?\n"
    .string "I said I'd meet her here.$"

FushciaCity_Text_ItemBallInThere::
    .string "That item ball in there…\n"
    .string "Were you wanting that?\p"
    .string "Me, too!\n"
    .string "…Huh? That's a POKéMON?$"

FushciaCity_Text_CitySign::
	.string "FUSHCIA CITY\n"
	.string "We spelled the name wrong\l"
	.string "on accident!$"

FushciaCity_Text_SafariZoneSign::
    .string "POKéMON PARADISE\n"
    .string "SAFARI ZONE$"

FushciaCity_Text_SafariGameSign::
    .string "SAFARI GAME\n"
    .string "POKéMON-U-CATCH!$"

FushciaCity_Text_WardensHomeSign::
    .string "SAFARI ZONE\n"
    .string "WARDEN'S HOME$"

FushciaCity_Text_SafariZoneOfficeSign::
    .string "POKéMON PARADISE!\n"
    .string "Welcome to the SAFARI ZONE!\l"
    .string "SAFARI ZONE OFFICE$"

FushciaCity_Text_GymSign::
    .string "FUSHCIA CITY POKéMON GYM\n"
    .string "LEADER: KOGA\l"
    .string "The Poisonous Ninja Master$"

FushciaCity_Text_ChanseySign::
    .string "Name: CHANSEY\n"
    .string "Ours ran away.$"

FushciaCity_Text_VoltorbSign::
	.string "Name: FUCKING FUCK$"

FushciaCity_Text_VolrorbContinued::
	.string "…What?\n"
	.string "POKéMON say their names, right?$"

FushciaCity_Text_KangaskhanSign::
	.string "Name: SKITTY\n"
	.string "She's currently single and looking!$"

FushciaCity_Text_SlowpokeSign::
    .string "Name: MR. MIME\n"
    .string "Friendly and very fast moving.$"

FushciaCity_Text_LaprasSign::
	.string "Name: WAILORD\n"
	.string "Currently seeking a girlfriend!$"

FushciaCity_Text_OmanyteSign::
	.string "Name: BOUFFALANT\n"
	.string "Did you know?\p"
	.string "UNOVA BOUFFALANT whom UNOVA\n"
	.string "BOUFFALANT bully themselves bully\l"
	.string "UNOVA BOUFFALANT!$"

FushciaCity_Text_KabutoSign::
	.string "Name: BOUFFALANT\n"
	.string "Did you know?\p"
	.string "UNOVA BOUFFALANT whom UNOVA\n"
	.string "BOUFFALANT bully themselves bully\l"
	.string "UNOVA BOUFFALANT!$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FushciaCity_Text_Ellipsis::
    .string "……$"

Text_SubstituteTeach::
    .string "Aww, I wish I was a KANGASKHAN\n"
    .string "baby.\p"
    .string "I'd love to be a substitute for the\n"
    .string "baby…\p"
    .string "And snuggle in the mother\n"
    .string "KANGASKHAN's belly pouch.\p"
    .string "But only POKéMON can use the\n"
    .string "technique SUBSTITUTE…\p"
    .string "Want me to teach SUBSTITUTE to\n"
    .string "one of your POKéMON?$"

Text_SubstituteDeclined::
    .string "Oh, really?\n"
    .string "SUBSTITUTE seems so fun…$"

Text_SubstituteWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "SUBSTITUTE?$"

Text_SubstituteTaught::
    .string "Boy, what I'd give to crawl inside\n"
    .string "a KANGASKHAN belly pouch…$"

FushciaCity_Text_MyFatherIsGymLeader::
    .string "My father is the GYM LEADER of\n"
    .string "this town.\p"
    .string "I'm training to use POISON POKéMON\n"
    .string "as well as my father.$"

