PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .string "What!?\p"
    .string "They think MT. MOON is copyright\n"
    .string "infringement?\p"
    .string "Huh?\p"
    .string "I'm on the phone!\n"
    .string "Scram!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .string "JIGGLYPUFF: Puu pupuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .string "Yawn!\p"
    .string "When JIGGLYPUFF plays, spectators\n"
    .string "get bored…\p"
    .string "…Me, too…\n"
    .string "Snore…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .string "I really want a PIKACHU, so I'm\n"
    .string "trading my CLEFAIRY for one.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
	.string "I'm evolving my CATERPIE to fight\n"
	.string "BROCK!\p"
	.string "I'm already LEVEL 70, but I still\n"
	.string "have a long way to go!$"
