RocketHideout_B2F_Text_GruntIntro::
	.string "Wahaha!\n"
	.string "Welcome!\p"
	.string "This is the DMCA's law office!\n$"

RocketHideout_B2F_Text_GruntDefeat::
    .string "I surrender!$"

RocketHideout_B2F_Text_GruntPostBattle::
	.string "No, this is not a ripoff of any\n"
	.string "other evil lair!\p"
	.string "All similarities to other locations,\n"
	.string "real or fictional, are coincidental!$"

