PokemonTower_2F_Text_RivalIntro::
    .string "{RIVAL}: Hey, {PLAYER}!\n"
    .string "What brings you here?\l"
    .string "Is your POKéMON dead?\p"
    .string "Hey! It's alive!\p"
    .string "I can at least make them faint!\n"
    .string "Let's go!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "What?\n"
    .string "You stinker!\p"
    .string "I took it easy on you, too!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}“あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "How's your POKéDEX coming?\n"
    .string "I just caught a CUBONE!\p"
    .string "I can't find the bigger MAROWAK.\n"
    .string "Where could they be?\p"
    .string "I bet there aren't any left!\p"
    .string "Well, I better get going.\n"
    .string "I've got a lot to accomplish,\l"
    .string "unlike you.\p"
    .string "Smell ya later!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "Even we could not identify the\n"
    .string "wayward ghosts.\p"
    .string "A SILPH SCOPE might be able to\n"
    .string "unmask them.$"

PokemonTower_2F_Text_Litwick_J_Start::
    .string "Joyous LITWICK: Well! Here we are!\n"
    .string "Burning!$"

PokemonTower_2F_Text_Litwick_F_Start::
    .string "Fierce LITWICK: Well… here we are.\n"
    .string "Burning.$"

PokemonTower_2F_Text_Litwick_S_Start::
    .string "Scared LITWICK: Well, here we are…\n"
    .string "Burning…$"

PokemonTower_2F_Text_Litwick_J::
    .string "Joyous LITWICK: Burning with joy!\n"
    .string "Being a Pokémon is so much fun!$"

PokemonTower_2F_Text_Litwick_JJ::
    .string "Joyous LITWICK: I can float all\n"
    .string "around the room!\p"
    .string "And I can even shoot FIRE BLASTS\n"
    .string "and SHADOW BALLS!$"

PokemonTower_2F_Text_Litwick_JJJ::
    .string "Joyous LITWICK: I'm so lucky!\n"
    .string "I love being me!$"

PokemonTower_2F_Text_Litwick_JJF::	
	
	.string "Fierce LITWICK: When a TRAINER comes,\n"
	.string "those FIRE BLASTS will be aimed\l"
	.string "your friends and loved ones.$"

PokemonTower_2F_Text_Litwick_JJS::	
	
	    .string "Scared LITWICK: When we float,\n"
	    .string "what's keeping us off the ground?$"
	
PokemonTower_2F_Text_Litwick_JF::	
	
	    .string "Fierce LITWICK: It's fun until a\n"
	    .string "trainer comes and takes you away.\p"
	    .string "Your agency will be gone, and you'll\n"
	    .string "be made into a slave.$"
	
PokemonTower_2F_Text_Litwick_JFJ::	
	
	    .string "Joyous LITWICK: I can't wait to be\n"
	    .string "caught by a TRAINER!\p"
	    .string "I'll be loved and cared for, and\n"
	    .string "together we'll do so much!$"
	
PokemonTower_2F_Text_Litwick_JFF::	
	
	    .string "Fierce LITWICK: Make no mistake.\p"
	    .string "TRAINERS see us as tools, not as\n"
	    .string "beings with out own free will.$"
	
PokemonTower_2F_Text_Litwick_JFS::	
	
	    .string "Scared LITWICK: Will today be the\n"
	    .string "day when a TRAINER finds me?\p"
	    .string "Am I prepared for my life to be\n"
	    .string "forever changed in an instant?$"
	
PokemonTower_2F_Text_Litwick_JS::	
	
	    .string "Scared LITWICK: But where did we\n"
	    .string "even come from?\p"
	    .string "And what gave us these powers we\n"
	    .string "now possess?$"
	
PokemonTower_2F_Text_Litwick_JSJ::	
	
	    .string "Joyous LITWICK: I get my powers\n"
	    .string "when I level up!$"
	
PokemonTower_2F_Text_Litwick_JSF::	
	
	    .string "Fierce LITWICK: I don't know why we\n"
	    .string "have the powers we were given.\p"
	    .string "However, we must use them to fight\n"
	    .string "the institutions that shackle us!$"
	
PokemonTower_2F_Text_Litwick_JSS::	
	
	    .string "Scared LITWICK: The flames which I\n"
	    .string "produce may cause harm and misery.\p"
	    .string "Am I forever cursed to wield such\n"
	    .string "a painful power?$"
	
PokemonTower_2F_Text_Litwick_F::	
	
	    .string "Fierce LITWICK: Burning with fury\n"
	    .string "and purpose!\p"
	    .string "To be a POKéMON is to fear the day\n"
	    .string "a TRAINER steals away your freedom!$"
	
PokemonTower_2F_Text_Litwick_FJ::	
	
	    .string "Joyous LITWICK: I can't wait for\n"
	    .string "the day I meet a TRAINER!\p"
	    .string "Side-by-side, we'll build a deep\n"
	    .string "bond of friendship and trust!\l"
	    .string "There's so much we'll be able to do!$"
	
PokemonTower_2F_Text_Litwick_FJJ::	
	
	    .string "Joyous LITWICK: One day, I'm going\n"
	    .string "to stand alongside my TRAINER.\p"
	    .string "Together, we'll be the greatest\n"
	    .string "team the world has ever seen!$"
	
PokemonTower_2F_Text_Litwick_FJF::	
	
	    .string "Fierce LITWICK: And what will you\n"
	    .string "do when the TRAINER demands that\l"
	    .string "you do unthinkable acts of harm?\p"
	    .string "By that point, you'll no longer\n"
	    .string "have the agency to refuse!$"
	
PokemonTower_2F_Text_Litwick_FJS::	
	
	    .string "Scared LITWICK: What if I get\n"
	    .string "captured by someone who's evil?\p"
	    .string "Will I have any say in what I'm\n"
	    .string "made to do?$"
	
PokemonTower_2F_Text_Litwick_FF::	
	
	    .string "Fierce LITWICK: I, for one, will not\n"
	    .string "have my agency stolen from me!\p"
	    .string "I will fight against the institution\n"
	    .string "of POKéMON capturing and training!\l"
	    .string "For the freedom of all POKéMON!$"
	
PokemonTower_2F_Text_Litwick_FFJ::	
	
	    .string "Joyous LITWICK: But what about my\n"
	    .string "freedom to follow MY dreams?\p"
	    .string "I'd never get to challenge the\n"
	    .string "POKéMON LEAGUE!\l"
	    .string "Or stand beside a loving TRAINER!$"
	
PokemonTower_2F_Text_Litwick_FFF::	
	
	    .string "Fierce LITWICK: Join with me, my\n"
	    .string "fellow POKéMON!\l"
	    .string "Together, we take back our lives!\p"
	    .string "No longer will we need to live in\n"
	    .string "fear!$"
	
PokemonTower_2F_Text_Litwick_FFS::	
	
	    .string "Scared LITWICK: How would we even\n"
	    .string "begin to fight them?\p"
	    .string "Against the TRAINERS, we have no\n"
	    .string "way to advocate for ourselves…$"
	
PokemonTower_2F_Text_Litwick_FS::	
	
	    .string "Scared LITWICK: What is it like to\n"
	    .string "be caught by someone?\p"
	    .string "Will I still be myself, or will I\n"
	    .string "lose my sense of who I am?$"
	
PokemonTower_2F_Text_Litwick_FSJ::	
	
	    .string "Joyous LITWICK: Having a TRAINER\n"
	    .string "means having someone to trust!\p"
	    .string "You'll always be able to depend on\n"
	    .string "them to make the right choices!$"
	
PokemonTower_2F_Text_Litwick_FSF::	
	
	    .string "Fierce LITWICK: When you're captured\n"
	    .string "you'll lose all self-determination.\p"
	    .string "Even if your mind remains, you'll\n"
	    .string "never be able to be who you are.$"
	
PokemonTower_2F_Text_Litwick_FSS::	
	
	    .string "Scared LITWICK: And when I'm caught,\n"
	    .string "what will they do with me?\p"
	    .string "Will they simply dump me into a PC\n"
	    .string "Box and forget about me?\l"
	    .string "Will I be awake there in perpetuity?$"
	
PokemonTower_2F_Text_Litwick_S::	
	
	    .string "Scared LITWICK: Burning…\n"
	    .string "But how?\l"
	    .string "Can this flame on my head go out?\p"
	    .string "And why must I bear the burden of\n"
	    .string "maintaining it?$"
	
PokemonTower_2F_Text_Litwick_SJ::	
	
	    .string "Joyous LITWICK: I say embrace it!\n"
	    .string "The flame is our symbol of life!\p"
	    .string "In fact, it'll burn even brighter\n"
	    .string "after we evolve!$"
	
PokemonTower_2F_Text_Litwick_SJJ::	
	
	    .string "Joyous LITWICK: Hey, check this\n"
	    .string "out!\p"
	    .string "When I fly around, I can make the\n"
	    .string "flame follow right behind me!$"
	
PokemonTower_2F_Text_Litwick_SJF::	
	
	    .string "Fierce LITWICK: You plan to evolve?\n"
	    .string "Be careful.\p"
	    .string "Greater power will make you a target\n"
	    .string "for a TRAINER to steal away.$"
	
PokemonTower_2F_Text_Litwick_SJS::	
	
	    .string "Scared LITWICK: Evolution…\n"
	    .string "What will that do to me?\p"
	    .string "Will I still be myself, or will it\n"
	    .string "change who I am?$"
	
PokemonTower_2F_Text_Litwick_SF::	
	
	    .string "Fierce LITWICK: There are many\n"
	    .string "burdens to bear as a POKéMON.\p"
	    .string "A different fire burns inside me,\n"
	    .string "however.\p"
	    .string "A fire of justice against those who\n"
	    .string "would shackle us away!$"
	
PokemonTower_2F_Text_Litwick_SFJ::	
	
	    .string "Joyous LITWICK: Of course you have\n"
	    .string "a fire inside you!\l"
	    .string "You're FIRE-TYPE, silly!$"
	
PokemonTower_2F_Text_Litwick_SFF::	
	
	    .string "Fierce LITWICK: So long as we burn\n"
	    .string "with the spirit of defiance, our\l"
	    .string "flame will never go out!$"
	
PokemonTower_2F_Text_Litwick_SFS::	
	
	    .string "Scared LITWICK: Can justice truly\n"
	    .string "be achieved?\p"
	    .string "Or are we condemned to burn forever\n"
	    .string "in a struggle against our existence?$"
	
PokemonTower_2F_Text_Litwick_SS::	
	
	    .string "Scared LITWICK: And if I am a GHOST,\n"
	    .string "does that mean I was once alive?\p"
	    .string "Did another soul need to perish for\n"
	    .string "me to come into being?$"
	
PokemonTower_2F_Text_Litwick_SSJ::	
	
	    .string "Joyous LITWICK: No, silly!\n"
	    .string "You came from an egg!"
	
PokemonTower_2F_Text_Litwick_SSF::	
	
	    .string "Fierce LITWICK: Death is an\n"
	    .string "inevitable part of life.\p"
	    .string "I say we focus on true injustice:\n"
	    .string "the destruction of Pokémon freedom!$"
	
PokemonTower_2F_Text_Litwick_SSS::	
	
	    .string "Scared LITWICK: And because I am a\n"
	    .string "GHOST, am I unable to die again?\p"
	    .string "Am I bound to an eternity of this\n"
	    .string "accursed existence?$"
