CeruleanCity_Gym_Text_MistyIntro::
    .string "Hi, you're a new face!\p"
    .string "Only those TRAINERS who have a\n"
    .string "strong win condition can win at.\l"
    .string "our events!\p"
    .string "Let me show you what got my cards\n"
    .string "banned!$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "TM18 teaches RAIN DANCE.\p"
    .string "Use it to attach ENERGY faster!\p"
    .string "Anyway, if you wanna get out,\n"
    .string "just use RETREAT again!\p"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "The WATER MEDAL makes all\n"
    .string "POKéMON up to Lv. 30 obey.\p"
    .string "That includes even outsiders you\n"
    .string "got in trades.\p"
    .string "There's more. You can now use CUT\n"
    .string "anytime, even out of battle.\p"
    .string "You can CUT down small trees to\n"
    .string "open new pathways.\p"
    .string "You can also have my favorite TM.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER} received TM18\n"
    .string "from MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "You better make room for this!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Wow!\n"
    .string "You're too much!\p"
    .string "All right!\p"
    .string "You can have the WATER MEDAL to\n"
    .string "show you beat me.$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "What? You?\n"
    .string "I'm more than good enough for you!\p"
    .string "MISTY won't have to be bothered.$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "You overwhelmed me!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "You have to face other TRAINERS\n"
    .string "to see how good you really are.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "Splash!\p"
    .string "I'm first up!\n"
    .string "Let's do it!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "That can't be!$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "MISTY is a TRAINER who's going to\n"
    .string "keep improving.\p"
    .string "She won't lose to someone like you!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "This CLUB is run by POKéMON\n"
    .string "TCG players!\p"
    .string "MISTY's waiting for you in the\n"
    .string "back room.\l"
    .string "You gotta find a way to get to her!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "You beat MISTY!\n"
    .string "See, what'd I tell ya?\p"
    .string "You and me, kid, we make a pretty\n"
    .string "darn-good team!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "CERULEAN POKéMON CLUB\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
    .string "GARY, LARRY, JERRY$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "CERULEAN POKéMON CLUB\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
    .string "GARY, LARRY, JERRY, {PLAYER}$"

