Text_DreamEaterTeach::
    .string "Yawn!\n"
    .string "I'm always so sleepy.\p"
    .string "My friend sent me some MAIL, but\n"
    .string "he left his POKéMON with me.\p"
    .string "I'm not a trainer, so I'm not sure\n"
    .string "what to do with it.\p"
    .string "Here - why don't you take it?$"

Text_DreamEaterDeclined::
    .string "Y'know now that I think about it,\n"
    .string "POKéMON MAIL really isn't a very\l"
    .string "efficient delivery service.\p"
    .string "Oh well, back to sleep.\p"
    .string "Yawn…$"

Text_DreamEaterWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "DREAM EATER?$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "I…can't eat…anymore…$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "A bunch of trees grew in front\n"
    .string "of BORKC's GYM!\p"
    .string "You'd need to be able to Walk\n"
    .string "Through Walls to challenge him!$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "There aren't many serious POKéMON\n"
    .string "TRAINERS here.\p"
    .string "They're all like BUG CATCHERS,\n"
    .string "you know, just hobbyists.\p"
    .string "But PEWTER GYM's BROCK isn't like\n"
    .string "that, not one bit.$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "Did you check out the MUSEUM?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "Weren't those fossils from MT. MOON\n"
    .string "amazing?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "Really?\n"
    .string "You absolutely have to go!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "Oh shoot.\p"
    .string "I think I missed.$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Psssst!\n"
    .string "Do you know what I'm doing?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "That's right!\n"
    .string "It's hard work!\p"
    .string "You'd better not try to make any\n"
    .string "POKéMON appear some other way!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "I'm spraying REPEL to keep wild\n"
    .string "POKéMON out of my garden!\p"
    .string "You'd better not try to make any\n"
    .string "appear some other way!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "You're a TRAINER, right?\p"
    .string "BROCK's looking for new\n"
    .string "challengers. Follow me!$"

PewterCity_Text_GoTakeOnBrock::
    .string "If you have the right stuff,\n"
    .string "go take on BROCK!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "TRAINER TIPS\p"
    .string "Think outside the box!\p"
    .string "Sometimes, an absurd solution\n"
    .string "might just be what you need.$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "NOTICE!\p"
    .string "Thieves have been illegally editing\n"
    .string "POKéMON games for fun!\p"
    .string "We at the DMCA take these matters\n"
    .string "very seriously!$"

PewterCity_Text_MuseumOfScience::
    .string "PEWTER MUSEUM OF SCIENCE$"

PewterCity_Text_GymSign::
    .string "PEWTER CITY POKéMON GYM\n"
    .string "LEADER: BROCK\l"
    .string "The longest GYM in KANTO!\p"
    .string "RECOMMENDED LEVEL: 10$"

PewterCity_Text_CitySign::
    .string "PEWTER CITY\n"
    .string "NEW WILD POKéMON: 1\p"
    .string "RECOMMENDED POKéDEX COMPLETION: 12\p"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "I'm glad I caught up to you.\n"
    .string "I'm PROF. OAK's AIDE.\p"
    .string "I've supposed to give you the\n"
    .string "RUNNING SHOES.\p"
    .string "…What's that?\p"
    .string "You can already run without\n"
    .string "needing a specific kind of shoe?\p"
    .string "…Well that's awkward.\p"
    .string "I guess you can take these\n"
    .string "anyway. Here!\p"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} received the\n"
    .string "RUNNING SHOES from the AIDE.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} switched shoes with the\n"
    .string "RUNNING SHOES.$"

PewterCity_Text_ExplainRunningShoes::
    .string "Perfectly sized for both humans\n"
    .string "and POKéMON!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "OAK made me hike all the way\n"
    .string "here for nothing…\p"
    .string "Guess I better make the trek\n"
    .string "back.\p"
    .string "Uhhhh bye!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "There's a letter attached…\p"
    .string "{PLAYER},\p"
    .string "You'd better not be running in\n"
    .string "your normal shoes.\p"
    .string "If you are, I'll have to\n"
    .string "report you to the police!\p"
    .string "Love, Dad$"

