PokemonTower_3F_Text_HopeIntro::
	.string "Give… me…\n"
	.string "your… blood…$"

PokemonTower_3F_Text_HopeDefeat::
	.string "Please!\n$"

PokemonTower_3F_Text_HopePostBattle::
	.string "Please give me your blood.\n"
	.string "I need a transfusion.\p"
	.string "It keeps leaking out of my eyes!$"

PokemonTower_3F_Text_CarlyIntro::
	.string "H U R R Y …\p"
	.string "G O . B A C K …$"

PokemonTower_3F_Text_CarlyDefeat::
	.string "R E M E M B E R   T O    D R I N K \n"
	.string "Y O U R   O V A L T I N E …$"

PokemonTower_3F_Text_CarlyPostBattle::
	.string "The DMCA does not approve of our\n"
	.string "fanfics…$"

PokemonTower_3F_Text_PatriciaIntro::
	.string "… … …\n"
	.string "My POKéMON are dead.\p"
	.string "And it's all their fault.\n$"

PokemonTower_3F_Text_PatriciaDefeat::
	.string "Damn it!\n"
	.string "Why didn't you hold?$"

PokemonTower_3F_Text_PatriciaPostBattle::
	.string "Another wipe…\n"
	.string "Time to start a new attempt.$"

