Route25_Text_JoeyIntro::
    .string "Local TRAINERS come here to\n"
    .string "practice.$"

Route25_Text_JoeyDefeat::
    .string "You're decent.$"

Route25_Text_JoeyPostBattle::
    .string "All POKéMON have weaknesses.\n"
    .string "Even the strongest ones.\p"
    .string "That's why it's best to raise\n"
    .string "POKéMON of different types.$"

Route25_Text_DanIntro::
    .string "Dad took me to a great party on\n"
    .string "the S.S. ANNE at VERMILION CITY.$"

Route25_Text_DanDefeat::
	.string "On the S.S. ANNE, I was worn by\n"
	.string "TRAINERS from around the world!$"

Route25_Text_DanPostBattle::
    .string "On the S.S. ANNE, I was worn by\n"
    .string "TRAINERS from around the world!$"

Route25_Text_FlintIntro::
    .string "GSC is NOT all stall!\p"
    .string "Here, I'll prove it!$"

Route25_Text_FlintDefeat::
    .string "Aww, darn…$"

Route25_Text_FlintPostBattle::
    .string "Battles only last 57 turns on\n"
    .string "average!\p"
    .string "I don't know what new gen players\n"
    .string "are talking about!\p"

Route25_Text_KelseyIntro::
	.string "Hi!\n"
	.string "Welcome to SMOGON.COM!\p"
	.string "We're the premier source for\n"
	.string "competitive Singles POKéMON!$"

Route25_Text_KelseyDefeat::
    .string "My conditioning isn't the best…$"

Route25_Text_KelseyPostBattle::
	.string "Now, let me tell you about my\n"
	.string "favorite films this year…$"

Route25_Text_ChadIntro::
    .string "…$"

Route25_Text_ChadDefeat::
	.string "Unfortunate doesn't begin to\n"
	.string "describe my series.\p"
	.string "This game rewards blind luck and\n"
	.string "nothing else, I am beyond convinced\l"
	.string "at this point.\p"
	.string "My preparation was superior, my play\n"
	.string "was superior, and I lost, so I don't\l"
	.string "see a reason to continue engaging in\l"
	.string "an activity where what is within my\l"
	.string "control is overwhelmingly outweighed\l"
	.string "by what is not.\p"
	.string "I am done with competitive POKéMON,\n"
	.string "and you won't get a fond farewell.$"

Route25_Text_ChadPostBattle::
	.string "From this moment on, nothing you say\n"
	.string "matters to me.\p"
	.string "The foulest insults you hurl with\n"
	.string "intent to wound will calmly settle\l"
	.string "at the earth before my feet, and the\l"
	.string "venom you spit will bring all the\l"
	.string "pain of a warm summer breeze.\p"
	.string "You are less than anything you can\n"
	.string "conceive, while I carry on, brimming\l"
	.string "with joy distilled from detachment.$"

Route25_Text_HaleyIntro::
	.string "I don't understand those people\n"
	.string "over there.\p"
	.string "Why don't they just win with their\n"
	.string "favorites like I do?$"

Route25_Text_HaleyDefeat::
	.string "Hey, no fair!\n"
	.string "Stop cheating!$"

Route25_Text_HaleyPostBattle::
	.string "Good POKéMON…\n"
	.string "Bad POKéMON…\p"
	.string "Clearly there is no difference\n"
	.string "between the two!\p"
	.string "I'm sure I know better than people\n"
	.string "who actually go to tournaments!$"

Route25_Text_FranklinIntro::
    .string "Hi.\p"
    .string "I am NOB.$"

Route25_Text_FranklinDefeat::
    .string "You done got me, and real good,\p"
    .string "too!$"

Route25_Text_FranklinPostBattle::
    .string "See ya around!$"

Route25_Text_NobIntro::
    .string "Hi.\p"
    .string "I am NOB.$"

Route25_Text_NobDefeat::
    .string "You done got me, and real good,\n"
    .string "too!$"

Route25_Text_NobPostBattle::
	.string "See ya next gen!\n$"

Route25_Text_WayneIntro::
    .string "You're going to see BILL?\n"
    .string "First, we battle!$"

Route25_Text_WayneDefeat::
    .string "You're something.$"

Route25_Text_WaynePostBattle::
    .string "The trail below is a shortcut to\n"
    .string "CERULEAN CITY.$"

Route25_Text_SeaCottageSign::
    .string "SEA COTTAGE\n"
    .string "BILL lives here!$"

Route25_Text_MistyHighHopesAboutThisPlace::
    .string "If you look behind that cottage,\n"
    .string "you can see a path going north!\p"
    .string "I bet that's where you can catch\n"
    .string "the starters!$"

Route25_Text_AreYouHereAlone::
    .string "I heard from my cousin that\n"
    .string "somewhere around here, you can\l"
    .string "catch something super rare!\p"
    .string "I bet if I look hard enough, I'll\n"
    .string "finally find a PIKABLU!$"

