Route25_Text_JoeyIntro::
    .string "Local TRAINERS come here to\n"
    .string "practice.$"

Route25_Text_JoeyDefeat::
    .string "You're decent.$"

Route25_Text_JoeyPostBattle::
    .string "All POKéMON have weaknesses.\n"
    .string "Even the strongest ones.\p"
    .string "That's why it's best to raise\n"
    .string "POKéMON of different types.$"

Route25_Text_DanIntro::
    .string "Dad took me to a great party on\n"
    .string "the S.S. ANNE at VERMILION CITY.$"

Route25_Text_DanDefeat::
    .string "I'm not mad!$"

Route25_Text_DanPostBattle::
    .string "On the S.S. ANNE, I was worn by\n"
    .string "TRAINERS from around the world!$"

Route25_Text_FlintIntro::
    .string "GSC is NOT all stall!\p"
    .string "Here, I'll prove it!$"

Route25_Text_FlintDefeat::
    .string "Aww, darn…$"

Route25_Text_FlintPostBattle::
    .string "Battles only last 57 turns on\n"
    .string "average!\p"
    .string "I don't know what new gen players\n"
    .string "are talking about!\p"

Route25_Text_KelseyIntro::
    .string "Hi!\n"
    .string "My boyfriend is cool!$"

Route25_Text_KelseyDefeat::
    .string "My conditioning isn't the best…$"

Route25_Text_KelseyPostBattle::
    .string "I wish my boyfriend was as good\n"
    .string "as you.$"

Route25_Text_ChadIntro::
    .string "I had this feeling…\n"
    .string "I knew I had to battle you!$"

Route25_Text_ChadDefeat::
    .string "I knew I'd lose, too!$"

Route25_Text_ChadPostBattle::
    .string "If your POKéMON gets confused,\n"
    .string "switch it out.\p"
    .string "That's a good tactic.$"

Route25_Text_HaleyIntro::
    .string "My friend has many cute POKéMON.\n"
    .string "I'm so jealous!$"

Route25_Text_HaleyDefeat::
    .string "I'm not so jealous!$"

Route25_Text_HaleyPostBattle::
    .string "You came from MT. MOON?\n"
    .string "May I have a CLEFAIRY?$"

Route25_Text_FranklinIntro::
    .string "Hi.\p"
    .string "I am NOB.$"

Route25_Text_FranklinDefeat::
    .string "You done got me, and real good,\p"
    .string "too!$"

Route25_Text_FranklinPostBattle::
    .string "See ya around!$"

Route25_Text_NobIntro::
    .string "I'm off to see a POKéMANIAC's\n"
    .string "collection at the cape.$"

Route25_Text_NobDefeat::
    .string "You done got me, and real good,\n"
    .string "too!$"

Route25_Text_NobPostBattle::
    .string "The POKéMANIAC sure lives up to\n"
    .string "his name.\p"
    .string "His collection includes many rare\n"
    .string "species of POKéMON.$"

Route25_Text_WayneIntro::
    .string "You're going to see BILL?\n"
    .string "First, we battle!$"

Route25_Text_WayneDefeat::
    .string "You're something.$"

Route25_Text_WaynePostBattle::
    .string "The trail below is a shortcut to\n"
    .string "CERULEAN CITY.$"

Route25_Text_SeaCottageSign::
    .string "SEA COTTAGE\n"
    .string "BILL lives here!$"

Route25_Text_MistyHighHopesAboutThisPlace::
    .string "If you look behind that cottage,\n"
    .string "you can see a path going north!\p"
    .string "I bet that's where you can catch\n"
    .string "the starters!$"

Route25_Text_AreYouHereAlone::
    .string "I heard from my cousin that\n"
    .string "somewhere around here, you can\l"
    .string "catch something super rare!\p"
    .string "I bet if I look hard enough, I'll\n"
    .string "finally find a PIKABLU!$"

