@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
    .string "{PLAYER}{KUN}の　バッグ\n"
    .string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .string "I had a really good nickname ready\n"
    .string "for my DROWZEE.\p"
    .string "Unfortunately, the NAME RATER came\n"
    .string "by and told me that NYQUIL is a\l"
    .string "registered trademark.\p"
    .string "He forced me to change it.$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
    .string "Ever since I moved to KANTO, I've\n"
    .string "been keeping up with my friends\l"
    .string "from JOHTO via MAIL.\p"
    .string "I had someone deliver a ltter to\n"
    .string "my one friend a while back.\l"
    .string "I think he's in VIRIDIAN still?\p"
    .string "Someone should check on him to see\n"
    .string "if he recieved it.$"

Route11_EastEntrance_1F_Text_GotKenya::
    .string "...\n"
    .string "...Oh!\l"
    .string "You've been to see him?\p"
    .string "I hope he's doing well!$"

