Route9_Text_AliciaIntro::
    .string "You have POKéMON with you!\n"
    .string "You're mine!$"

Route9_Text_AliciaDefeat::
    .string "You deceived me…$"

Route9_Text_AliciaPostBattle::
    .string "The tunnel coming up is pitch-black\n"
    .string "inside.\p"
    .string "You'll need FLASH to get through\n"
    .string "there.$"

Route9_Text_ChrisIntro::
	.string "Haha, yeah!\n"
	.string "Let's go, LazorGator!$"

Route9_Text_ChrisDefeat::
    .string "Out like a light!$"

Route9_Text_ChrisPostBattle::
	.string "What?\p"
	.string "You're telling me you don't\n"
	.string "remember LazorGator at all?$"

Route9_Text_DrewIntro::
	.string "Check out this hole I dug!\n$"

Route9_Text_DrewDefeat::
    .string "Can't measure up…$"

Route9_Text_DrewPostBattle::
	.string "My rat loves digging tunnels\n"
	.string "like this!\p"
	.string "They always take me where I need to\n"
	.string "go!$"

Route9_Text_CaitlinIntro::
	.string "Stop right there!\p"
	.string "You don't get to go any further!\n$"

Route9_Text_CaitlinDefeat::
	.string "START9!\n$"

Route9_Text_CaitlinPostBattle::
	.string "START9!\p"
	.string "START9!\p"
	.string "Why are you still moving?\n"
	.string "I said START9!$"

Route9_Text_JeremyIntro::
    .string "Bwahaha!\n"
    .string "Great! I was bored, eh!$"

Route9_Text_JeremyDefeat::
    .string "Keep it coming, eh!\p"
    .string "Oh wait.\n"
    .string "I'm out of POKéMON!$"

Route9_Text_JeremyPostBattle::
    .string "You sure had guts standing up to\n"
    .string "me there, eh?$"

Route9_Text_BriceIntro::
	.string "This terrain is nothing!\p"
	.string "My bike can handle anything!\n$"

Route9_Text_BriceDefeat::
	.string "No!\n"
	.string "My All-Terrain VENOMOTH!$"

Route9_Text_BricePostBattle::
	.string "What a shame...\p"
	.string "I wiped the floor with the guy on\n"
	.string "the other side of the ROUTE.$"

Route9_Text_BrentIntro::
	.string "Hahaha!\p"
	.string "Fear my DRAGONS!\n$"

Route9_Text_BrentDefeat::
    .string "WHAT?\p"
    .string "What a total waste of time!$"

Route9_Text_BrentPostBattle::
	.string "I don't understand!\n"
	.string "My moves were SUPER-EFFECTIVE!$"

Route9_Text_AlanIntro::
    .string "Hahahaha!\n"
    .string "Bring it on!$"

Route9_Text_AlanDefeat::
    .string "Hahahaha!\n"
    .string "You beat me fair!$"

Route9_Text_AlanPostBattle::
    .string "Hahahaha!\n"
    .string "Us hearty guys always laugh!$"

Route9_Text_ConnerIntro::
	.string "Be careful!\p"
	.string "I'm guarding a dangerous monster!\n$"

Route9_Text_ConnerDefeat::
	.string "Oh, darn.\n"
	.string "It's just like that SUNDAY.$"

Route9_Text_ConnerPostBattle::
	.string "It was a trick!\n"
	.string "They deceived me!$"

Route9_Text_RouteSign::
    .string "ROUTE 9\n"
    .string "CERULEAN CITY - ROCK TUNNEL$"

