CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "I wanna buy some RARE CANDY to\n"
    .string "help evolve my POKéMON, but I\l"
    .string "need more money!\p"
    .string "Maybe if I visited BILL again…$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "Do you know about RARE CANDY?\n"
    .string "They sell it in shops.\p"
    .string "It basically lets you bypass\n"
    .string "annoying grinding!$"

