CeladonCity_House1_Text_SlotsReelInTheDough::
	.string "Grr…\p"
	.string "They're trying to pass these two off\n"
	.string "as completely different POKéMON,\l"
	.string "but I know the truth!\p"
	.string "Whoever designed them is in\n"
	.string "big trouble!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "CHIEF!\p"
    .string "We just shipped two thousand\n"
    .string "more POKéMON as slot prizes\l"
    .string "again today!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "Don't touch the poster at the GAME\n"
    .string "CORNER!\p"
    .string "There's no secret switch behind it!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "ぶつだん　だ‥$"
