Route14_Text_CarterIntro::
    .string "You need to use TMs to teach good\n"
    .string "moves to POKéMON.$"

Route14_Text_CarterDefeat::
    .string "Not good enough quite yet.$"

Route14_Text_CarterPostBattle::
    .string "You have some HMs, right? POKéMON\n"
    .string "can't forget those moves easily.$"

Route14_Text_MitchIntro::
    .string "My bird POKéMON should be ready\n"
    .string "for battle.$"

Route14_Text_MitchDefeat::
    .string "Not ready yet!$"

Route14_Text_MitchPostBattle::
    .string "My bird POKéMON need to learn\n"
    .string "better moves.$"

Route14_Text_BeckIntro::
    .string "They have TMs on sale at the\n"
    .string "CELADON DEPT. STORE.\p"
    .string "TMs aren't really rare, but not\n"
    .string "many people have HMs.$"

Route14_Text_BeckDefeat::
    .string "Aww, bummer!$"

Route14_Text_BeckPostBattle::
    .string "Try teaching POKéMON a move that's\n"
    .string "the same type as it.\p"
    .string "That apparently boosts the power\n"
    .string "of the move.$"

Route14_Text_MarlonIntro::
    .string "Have you taught your bird POKéMON\n"
    .string "how to FLY?\p"
    .string "You'll be able to soar with it into\n"
    .string "the sky!$"

Route14_Text_MarlonDefeat::
    .string "Shot down in flames!$"

Route14_Text_MarlonPostBattle::
    .string "Bird POKéMON are my one true love.\n"
    .string "I don't want to raise anything else.$"

Route14_Text_DonaldIntro::
    .string "Have you heard the legend of the\n"
    .string "winged mirages?$"

Route14_Text_DonaldDefeat::
    .string "Why?\n"
    .string "Why'd I lose?$"

Route14_Text_DonaldPostBattle::
    .string "Well, the winged mirages are the\n"
    .string "legendary bird POKéMON.\p"
    .string "There are three of them: ARTICUNO,\n"
    .string "ZAPDOS, and MOLTRES.$"

Route14_Text_BennyIntro::
    .string "I'm not into it, but okay.\n"
    .string "Let's go!$"

Route14_Text_BennyDefeat::
    .string "I knew it!$"

Route14_Text_BennyPostBattle::
    .string "Winning, losing… It's insignificant\n"
    .string "under this huge sky.$"

Route14_Text_LukasIntro::
    .string "C'mon, c'mon.\n"
    .string "Let's go, let's go, let's go!$"

Route14_Text_LukasDefeat::
    .string "Arrg!\n"
    .string "Lost! Get lost!$"

Route14_Text_LukasPostBattle::
    .string "What, what, what?\n"
    .string "What do you want still?$"

Route14_Text_IsaacIntro::
    .string "I need to burn some time.\n"
    .string "Shut up and battle.$"

Route14_Text_IsaacDefeat::
    .string "What?\n"
    .string "You!?$"

Route14_Text_IsaacPostBattle::
    .string "Raising POKéMON is a drag, man.$"

Route14_Text_GeraldIntro::
    .string "We ride out here because of the\n"
    .string "wide-open spaces.$"

Route14_Text_GeraldDefeat::
    .string "Wipeout!$"

Route14_Text_GeraldPostBattle::
    .string "It's cool you made your POKéMON so\n"
    .string "strong.\p"
    .string "Might is right!\n"
    .string "And you know it!$"

Route14_Text_MalikIntro::
    .string "POKéMON battle?\n"
    .string "Cool! Rumble!$"

Route14_Text_MalikDefeat::
    .string "Blown away!$"

Route14_Text_MalikPostBattle::
    .string "You know who'd win, you and me\n"
    .string "one-on-one!$"

Route14_Text_RouteSign::
    .string "ROUTE 14\n"
    .string "West to FUSHCIA CITY$"

Route14_Text_KiriIntro::
    .string "KIRI: JAN, let's try really,\n"
    .string "really hard together.$"

Route14_Text_KiriDefeat::
    .string "KIRI: Whimper…\n"
    .string "We lost, didn't we?$"

Route14_Text_KiriPostBattle::
    .string "KIRI: Did we lose because of me?$"

Route14_Text_KiriNotEnoughMons::
    .string "KIRI: We can battle if you have\n"
    .string "two POKéMON.$"

Route14_Text_JanIntro::
    .string "JAN: KIRI, here we go!\n"
    .string "We have to try hard!$"

Route14_Text_JanDefeat::
    .string "JAN: Eeeeh!\n"
    .string "No fair!$"

Route14_Text_JanPostBattle::
    .string "JAN: KIRI, don't cry!\n"
    .string "We'll just try harder next time.$"

Route14_Text_JanNotEnoughMons::
    .string "JAN: You want to battle?\n"
    .string "You don't have enough POKéMON.$"



Rapper_1_Intro::
	.string "Okay, guys!\n"
	.string "We gotta rap some POKéMON!$"
Rapper_2_Intro::
	.string "You just do the singing.\n$"
Rapper_3_Intro::
	.string "We'll take care of the hard part!\n$"
Rapper_4_Intro::
	.string "Let's get it on!\n$"
Rapper_5_Intro::
	.string "I want to be the best\n"
	.string "there ever was$"
Rapper_6_Intro::
	.string "To beat all the rest, yeah\n"
	.string "that's my cause$"
Rapper_7_Intro::
	.string "Catch 'em, catch'em\n"
	.string "Gotta catch 'em all$"
Rapper_8_Intro::
	.string "POKéMON!\n$"
Rapper_9_Intro::
	.string "I'll search across the land\n$"
Rapper_10_Intro::
	.string "Look far and wide\n$"
Rapper_11_Intro::
	.string "Release from my hand\n$"
Rapper_12_Intro::
	.string "the power that's inside!\n$"
Rapper_13_Intro::
	.string "Catch 'em, catch 'em\n"
	.string "Gotta catch 'em all$"
Rapper_14_Intro::
	.string "Gotta catch 'em all!\n$"
Rapper_15_Intro::
	.string "POKéMON!\n$"
Rapper_16_Intro::
	.string "Gotta catch 'em all\n"
	.string "Gotta catch 'em all$"
Rapper_17_Intro::
	.string "Yeah\n$"
Rapper_18_Intro::
	.string "Gotta catch 'em all\n"
	.string "Gotta catch 'em all$"
Rapper_19_Intro::
	.string "Yeah\n$"
Rapper_20_Intro::
	.string "Gotta catch 'em all\n$"
Rapper_21_Intro::
	.string "POKéMON!\n$"
Rapper_22_Intro::
	.string "Ow!\n$"
Rapper_23_Intro::
	.string "At least one-hundred and fifty\n"
	.string "or more to see!$"
Rapper_24_Intro::
	.string "To be a POKéMON MASTER is my\n"
	.string "destiny!$"
Rapper_25_Intro::
	.string "Woo!\n"
	.string "We're at the halfway point$"
Rapper_26_Intro::
	.string "Doing great so far!\n$"
Rapper_27_Intro::
	.string "We?\n"
	.string "What's all this “we” stuff?$"
Rapper_28_Intro::
	.string "I'm doing all the hard work!\n$"

Rapper_29_Intro::
	.string "Breaktime's over, here we go!\n$"
Rapper_30_Intro::
	.string "Gotta catch 'em all\n"
	.string "Gotta catch 'em all$"
Rapper_31_Intro::
	.string "Yeah\n$"
Rapper_32_Intro::
	.string "Gotta catch 'em all\n"
	.string "Gotta catch 'em all$"
Rapper_33_Intro::
	.string "Yeah\n$"
Rapper_34_Intro::
	.string "At least one-hundred and fifty\n"
	.string "or more to see!$"
Rapper_35_Intro::
	.string "To be a POKéMON MASTER is my\n"
	.string "destiny!$"
Rapper_36_Intro::
	.string "Shake out those lips!$"
Rapper_37_Intro::
	.string "It's down hill from here.\n"
	.string "Just 24 more to go!$"
Rapper_38_Intro::
	.string "Now it gets tricky, so listen\n"
	.string "real good!$"
Rapper_39_Intro::
	.string "We're almost home!\n$"
Rapper_40_Intro::
	.string "That's all, folks!\n$"
