ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Hey!\n"
    .string "Don't read my fanfic!$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Okay!\p"
    .string "Be sure to read what's on the\n"
    .string "blackboard carefully!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "Let's check out the notebook.\p"
    .string "First page…\p"
    .string "Sonic woke up and looked at the\n"
    .string "clock.\p"
    .string "“7:00,”  it said, and Sonic screamed.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Second page…\p"
    .string "“I am late for school! I have to get\n"
    .string "to school now!” said Sonic, jumping.\l"
    .string "out of bed.\p"
    .string "Sonic put his clothes on really fast\n"
    .string "and ran out of his room because he\l"
    .string "is fast.\p"
    .string "“No time for breakfast!” said Sonic\n"
    .string "as he ran past Sonic's Mom.\l"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Third page…\p"
    .string "“You will regret this,” said Sonic's\n"
    .string "Mom, leering at him from the kitchen\l"
    .string "stove, wearing aprons and oven mitts\l"
    .string "on her hands.\p"
    .string "Sonic did not care.\n"
    .string "He was late!\p"
    .string "Sonic ran outside and ran to the\n"
    .string "bus stop where people were getting\l"
    .string "on the bus$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Fourth page…\p"
    .string "“Tails! Knuckles! Wait for me!” said\n"
    .string "Sonic as he ran towards the bus.\p"
    .string "“Hey Knuckles, its' Sonic,” said Tails\n"
    .string "to Knuckles at the bus stop.\p"
    .string "“He is late!” said Knuckles to Tails\n"
    .string "before getting on the bus.\p"
    .string "Sonic ran so fast to the bus and he\n"
    .string "got on the bus after Tails$"

ViridianCity_School_Text_TurnThePage::
    .string "Turn the page?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "GIRL: Hey!\n"
    .string "Don't look at my fanfic!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "The blackboard lists POKéMON\n"
    .string "STATUS problems during battles.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Which topic do you want to read?$"

ViridianCity_School_Text_ExplainSleep::
    .string "A POKéMON can't attack if it's\n"
    .string "asleep.\p"
    .string "POKéMON will stay asleep even\n"
    .string "after battles.\p"
    .string "Use AWAKENING to awaken one\n"
    .string "from sleep.$"

ViridianCity_School_Text_ExplainBurn::
    .string "A burn reduces ATTACK power.\n"
    .string "It also causes ongoing HP loss.\p"
    .string "A burn remains after a battle.\n"
    .string "Use BURN HEAL to cure a burn.$"

ViridianCity_School_Text_ExplainPoison::
    .string "When poisoned, a POKéMON's health\n"
    .string "steadily drops.\p"
    .string "Poison lingers after battles.\n"
    .string "Use an ANTIDOTE to cure poison!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "A frozen POKéMON becomes\n"
    .string "helplessly immobile.\p"
    .string "It stays frozen even after the\n"
    .string "battle ends.\p"
    .string "Use ICE HEAL to thaw out the\n"
    .string "suffering POKéMON.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Paralysis reduces SPEED and may\n"
    .string "prevent the POKéMON from moving.\p"
    .string "Paralysis remains after battles.\n"
    .string "Use PARLYZ HEAL for treatment.$"

