SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
    .string "This ship, she is a luxury liner for\n"
    .string "TRAINERS of the world!\p"
    .string "At every port, we hold parties with\n"
    .string "invited TRAINERS.$"

SSAnne_2F_Corridor_Text_RivalIntro::
	.string "BARRY: Bonjour, {PLAYER}!\n"
	.string "Imagine seeing you here!\p"
	.string "How's your POKéDEX coming along?\n"
	.string "I've already caught 152 kinds!\p"
	.string "Now c'mon!\n"
	.string "Let's battle already!$"

SSAnne_2F_Corridor_Text_RivalDefeat::
	.string "Humph!\n"
	.string "I don't have time for this!$"

SSAnne_2F_Corridor_Text_RivalVictory::
    .string "{PLAYER}‥！\n"
    .string "ふなよい　してるのか！\p"
    .string "もっと　からだ\n"
    .string "きたえた　ほうが　いいぜ！$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
	.string "BARRY: This ship was supposed to\n"
	.string "be going to VERMILION CITY.\p"
	.string "I heard the CAPTAIN has tons of\n"
	.string "experience out at SEA.\l"
	.string "I wonder why he crashed…\p"
	.string "Anyway, I gotta go.\n"
	.string "Bump into ya later!$"

