Route10_Text_MarkIntro::
    .string "Wow, you came all the way here?\n"
    .string "Maybe you're a POKéMANIAC, too?\l"
    .string "Want to see my collection?$"

Route10_Text_MarkDefeat::
    .string "Humph.\n"
    .string "I'm not angry!$"

Route10_Text_MarkPostBattle::
    .string "I have more rare POKéMON at home!$"

Route10_Text_ClarkIntro::
	.string "Uh hmm.\p"
	.string "I feel like we skipped something.\n$"

Route10_Text_ClarkDefeat::
		.string "What could it have been…?\n$"

Route10_Text_ClarkPostBattle::
	.string "Hmm, yes there was definitely\n"
	.string "something we're missing.\p"
	.string "Oh well, I'm sure it wasn't\n"
	.string "important.$"

Route10_Text_HermanIntro::
	.string "A bunch of my friends are hanging\n"
	.string "out in that cave.\p"
	.string "I was supposed to join them, but…\n$"

Route10_Text_HermanDefeat::
    .string "Oh, no!\n"
    .string "My POKéMON!$"

Route10_Text_HermanPostBattle::
	.string "We were going to hold a convention,\n"
	.string "but we were all thrown out.\p"
	.string "Most of us relocated into that cave,\n"
	.string "and we were having a great time.\p"
	.string "Unfortunately due to the rules on\n"
	.string "POKéCOMMUNITY, we can't actually\l"
	.string "show what they're doing in there.$"

Route10_Text_HeidiIntro::
	.string "Oh boy, ROCK TUNNEL!\n"
	.string "I can't wait!\p"
	.string "That's everyone's favorite part\n"
	.string "of any KANTO game!$"

Route10_Text_HeidiDefeat::
    .string "Ohh!$"

Route10_Text_HeidiPostBattle::
	.string "What's that? You don't even have\n"
	.string "FLASH yet?\p"
	.string "I feel like the creator was a bit\n"
	.string "too obvious about that one.$"

Route10_Text_TrentIntro::
	.string "Ah!\n"
	.string "I love my ONIX!\p"
	.string "Where did I find it?\n"
	.string "I'll tell you if you win!$"

Route10_Text_TrentDefeat::
	.string "I'll, I'll tell you!\n$"

Route10_Text_TrentPostBattle::
	.string "I found my ONIX in a cave, hidden\n"
	.string "on an island far, far away.$"

Route10_Text_CarolIntro::
	.string "The POKéMON here in the mountains\n"
	.string "are so chunky…$"

Route10_Text_CarolDefeat::
    .string "I wasn't up for it.$"

Route10_Text_CarolPostBattle::
	.string "The POKéMON here in the mountains\n"
	.string "are so chunky…\p"
	.string "I wish there was a pink POKéMON\n"
	.string "with a floral pattern introduced in\l"
	.string "Generation V (POKéMON Black Version\l"
	.string "and POKéMON White Version) who is\l"
	.string "pure PSYCHIC-type with the abilities\l"
	.string "FOREWARN and SYNCHRONIZE and is\l"
	.string "themed after dreams and could\l"
	.string "connect to a browser-based\l"
	.string "single-player game on the POKéMON\l"
	.string "Global Link website through which\l"
	.string "players could send their POKéMON\l"
	.string "over the Internet to obtain items\l"
	.string "and meet other POKéMON, which\l"
	.string "themselves would have new abilities\l"
	.string "that are unavailable in the base\l"
	.string "game.\p"
	.string "…\p"
	.string "Yeah, that'd be cool.\n$"

Route10_Text_RockTunnelDetourToLavender::
	.string "ROCK TUNNEL\p"
	.string "The sign has been scribbled over…\p"
	.string "KANTO POKéMANIAC CONVENTION,\n"
	.string "this way!$"

Route10_Text_RockTunnel::
	.string "ROCK TUNNEL\n"
	.string "Vital part of the KANTO experience.$"

Route10_Text_PowerPlant::
    .string "POWER PLANT$"

Route10_Text_LassDefeat::
	.string "Hey!\n"
	.string "Stop looking!$"
