LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .string "I recently moved to this town.\p"
    .string "I hear that MR. FUJI's not from\n"
    .string "these parts originally, either.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .string "Hi!\n"
    .string "I'm SHORTS!\p"
    .string "You should wear me before going\n"
    .string "out for recess!$"


LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .string "MR. FUJI had been praying alone\n"
    .string "for CUBONE's mother.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
.string "I love going to school!\n"
.string "My favorite class is writing.\p"
.string "But! But!\n"
.string "Those DMCA people are meanies!\p"
.string "They took away the story I wrote!\n"
.string "They said it had, um, Copy Rights?\p"
.string "I was gonna read it to the class!\n"
.string "Waaah!$"


LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
.string "Hi, mister!\n"
.string "Can you tell me what 5+7 is?\p"
.string "Our teacher has been gone for a\n"
.string "while, so homework has been hard.\p"
.string "Usually CUBONE'S mother comes in,\n"
.string "but she's missing too...$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .string "NIDORINO: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .string "PSYDUCK: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .string "MR. FUJI: {PLAYER}…\p"
    .string "Your POKéDEX quest is one that\n"
    .string "requires strong dedication.\p"
    .string "Without deep love for POKéMON,\n"
    .string "your quest may fail.\p"
    .string "I'm not sure if this will help you,\n"
    .string "but I'd like you to have it.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .string "{PLAYER} received a POKé FLUTE\n"
    .string "from MR. FUJI.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .string "Upon hearing the POKé FLUTE,\n"
    .string "sleeping POKéMON will spring awake.\p"
    .string "Try using it on POKéMON that are\n"
    .string "sleeping obstacles.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .string "You must make room for this!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .string "MR. FUJI: Has my POKé FLUTE\n"
    .string "helped you?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .string "The book “My Secret Life”\n"
    .string "lies open on the table.\p"
    .string "The pages are turned to Chapter 3.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .string "POKéMON magazines line the shelf.\p"
    .string "POKéMON INSIDER…\p"
    .string "POKéMON FAN…$"

LavenderTown_VolunteerPokemonHouse_Text_OlderGirlBefore::
    .string "Everyone here in school loves\n"
    .string "CUBONE'S mother.\p"
    .string "She comes in sometimes when our\n"
    .string "TEACHER is sick.$"



LavenderTown_VolunteerPokemonHouse_Text_Blackboard::
    .string "The teacher has written out the\n"
    .string "homework for the class.\p"
    .string "“Read pages 15-18 of the book\n"
    .string "My Secret Life.”\p"
    .string "“There will be a quiz on\n"
    .string "Chapter 3 this Friday!”$"
