Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hi!\n"
    .string "I work at a POKéMON MART.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in VIRIDIAN CITY.\p"
    .string "I know, I'll give you a sample.\n"
    .string "Here you go!$"

    .string "Uh, hi!\p"
    .string "I work at a POKé Mart, and I was\n"
    .string "supposed to be handing out free\l"
    .string "POTIONS.\p"
    .string "However, it appears that this is the\n"
    .string "last POTION in the known universe.\p"
    .string "Uh, I guess you can have it.$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Please come see us if you need\n"
    .string "POKé BALLS for catching POKéMON.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's ITEMS POCKET.$"

Route1_Text_CanJumpFromLedges::
    .string "I've been looking around of a\n"
    .string "PIDGEY, but I haven't had any luck.\p"
    .string "Something so strong probably\n"
    .string "wouldn't be on this ROUTE$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "NEW WILD POKéMON: 1$"

Route1_Text_ThePitIntro::
    .string "TRAINER TIPS!\p"
    .string "Press START to save the game!$"

Route1_Text_ThePitDumbass::
    .string "…Dumbass.$"
