Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
	.string "I know the city's messed up, but\n"
	.string "technically this is CYCLING ROAD.\p"
	.string "I know it's strange to hold to my\n"
	.string "duty in a time like this, but\l"
	.string "you still need a BIKE to proceed!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
	.string "The city's messed up, but I still\n"
	.string "won't let anyone pass bikeless.\p"
	.string "Any small act of duty in a time\n"
	.string "like this helps maintain order!$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
    .string "Excuse me!\n"
    .string "Wait up, please!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
	.string "Hmm?\n"
	.string "What's this?\p"
	.string "This isn't the grocery store!\n$"

