CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "There is nothing that I don't know,\n"
    .string "like I wrote on the blackboard.\p"
    .string "I know about the world of POKéMON\n"
    .string "in your GAME BOY ADVANCE!\p"
    .string "Get together with your friends and\n"
    .string "enjoy trading POKéMON!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER} obtained an EEVEE!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "POKéMON Lecture\p"
    .string "Playing with the Wireless Adapter$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "Which heading do you want to read?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "The POKéMON WIRELESS CLUB is\n"
    .string "upstairs at any POKéMON CENTER.\p"
    .string "Visit one to link up with friend(s)\n"
    .string "using your Wireless Adapter.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "To link only with a friend, go to\n"
    .string "the DIRECT CORNER.\p"
    .string "It is the right counter at the\n"
    .string "POKéMON WIRELESS CLUB.\p"
    .string "Go into the TRADE CORNER or the\n"
    .string "COLOSSEUM with your friend.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "To link and communicate with\n"
    .string "anyone, go to the UNION ROOM.\p"
    .string "It is the left counter at the\n"
    .string "POKéMON WIRELESS CLUB.\p"
    .string "Go to the UNION ROOM and enjoy\n"
    .string "meeting other TRAINERS.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "It's a pamphlet on TMs.\p"
    .string "… …\p"
    .string "There are fifty TMs in all.\p"
    .string "There are also seven HMs that\n"
    .string "can be used repeatedly.\p"
    .string "SILPH CO.$"

CeladonCity_EeveeGag_Page1::
	.string "Dear Diary,\p"
	.string "I love my EEVEE.\n"
	.string "I think about it every day.\p"
	.string "Lately, I've been having nightmares\n"
	.string "that someone might steal it…\p"
	.string "I'm sure it can't possibly come\n"
	.string "true, right?$"

CeladonCity_EeveeGag_Page2::
	.string "Dear Diary,\p"
	.string "My worst fears came to pass.\p"
	.string "While I was asleep, a cruel soul\n"
	.string "broke in and stole my EEVEE.\p"
	.string "That's all right. I've been\n"
	.string "preparing for this day to come.\p"
	.string "Thankfully, they were only able to\n"
	.string "steal my backup EEVEE.\l"
	.string "My real EEVEE is still safe.\p"
	.string "Still, I need to be more careful\n"
	.string "going forward...$"

CeladonCity_EeveeGag_Page3::
	.string "Dear Diary,\p"
	.string "The EEVEE-stealing monster struck\n"
	.string "again!\p"
	.string "My true EEVEE is still safe and\n"
	.string "sound, but I need to be careful.\p"
	.string "I've set a trap for them.\n"
	.string "I'm sure this time, we'll be safe.$"

CeladonCity_EeveeGag_KeepReading::
	.string "Keep reading?$"

CeladonCity_EeveeGag_Bribe::
	.string "{PLAYER} accepted the bribe and\n"
	.string "obtained the legally-dubious EEVEE!$"

CeladonCity_EeveeGag_CeliaGives::
	.string "{PLAYER} obtained the EEVEE from\n"
	.string "CELIA!$"
