LavenderTown_House2_Text_WantMeToRateNicknames::
    .string "Wahaha!\n"
    .string "I'm the DMCA's official NAME RATER!\p"
    .string "Want me to tell you if your\n"
    .string "nicknames are legal?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .string "Which POKéMON might be violating\n"
    .string "copyright?$"


LavenderTown_House2_Text_GiveItANicerName::
    .string "{STR_VAR_1}?\p"
    .string "I'm pretty sure that's the name\n"
    .string "of a small corporation in RUSSIA.\p"
    .string "I'm sorry, but you need a new one.$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .string "Phew, that's good news.\p"
    .string "What will you name it instead?$"


LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .string "Done! From now on, this POKéMON\n"
    .string "shall be known as {STR_VAR_1}!\p"
    .string "It's a good thing you changed it\n"
    .string "before we sued you!$"


LavenderTown_House2_Text_ISeeComeVisitAgain::
    .string "Oh?\n"
    .string "You think you're all clear?\p"
    .string "You'd better hope you are!$"


LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .string "…Really?\p"
    .string "I just threatened to sue you, yet you\n"
    .string "decide to give it the same name?\p"
    .string "You've got guts, kid.$"


LavenderTown_House2_Text_TrulyImpeccableName::
    .string "{STR_VAR_1}, is it?\p"
    .string "I think POKéMON might actually be the\n"
    .string "original copyright holder!\p"
    .string "That means {STR_VAR_1}'s name can't\n"
    .string "be changed to maintain the Trademark!\p"
    .string "Don't want it going generic, after all.$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .string "EGGs are actually public domain\n"
    .string "as of 2021!\p"
    .string "No need to worry until it hatches.$"

