Route16_House_Text_FoundMySecretRetreat::
	.string "Ohhh…\n"
	.string "Now I've really done it.\p"
	.string "I committed one of the foulest\n"
	.string "crimes of all:\l"
	.string "Running without RUNNING SHOES!\p"
	.string "…Huh? What's that?\n"
	.string "You're not wearing them either?\p"
	.string "Oh, shoot!\n"
	.string "Good thing you arrived on a BIKE!\l"
	.string "If they saw you, it'd be bad news.\p"
	.string "Quick, take this.\n"
	.string "You gotta get out safely.$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER} received HM02\n"
    .string "from the disgusting criminal.$"

Route16_House_Text_ExplainHM02::
	.string "I went to go for a jog early\n"
	.string "in the morning.\l"
	.string "That's what we'd all do!\p"
	.string "Back home, it was always safe.\n"
	.string "Cops only came out at night.\p"
	.string "Guess it's not the same around\n"
	.string "here…$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "You don't have any room for this.$"

Route16_House_Text_Fearow::
	.string "TENTACOOL:\n"
	.string "… … …\p"
	.string "(uh, what sound does a TENTACOOL\n"
	.string "make?)$"

