Route16_House_Text_FoundMySecretRetreat::
	.string "Oh man, I've really done it now…\p"
	.string "I just wanted to take my early\n"
	.string "morning jog.\l"
	.string "I didn't think anyone could see me…\p"
	.string "Here, take this.\n"
	.string "You need to get out safe.$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER} received HM02\n"
    .string "from the disgusting criminal.$"

Route16_House_Text_ExplainHM02::
	.string "What's that?\n"
	.string "You're not wearing RUNNING SHOES?\p"
	.string "That's some risky business you've\n"
	.string "got going on.\l"
	.string "Don't let them catch you!$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "You don't have any room for this.$"

Route16_House_Text_Fearow::
	.string "TENTACOOL:\n"
	.string "… … …\p"
	.string "(hey, what sound does a TENTACOOL\n"
	.string "make?)$"

