PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "POKéMON TOWER was erected in the\n"
    .string "memory of POKéMON that died.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Did you come to pay respects?\p"
    .string "F$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Did you come to pay respects?\p"
    .string "F\n"


PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "Sniff!\n"
    .string "I miss my CLEFAIRY…\p"
    .string "She's not dead or anything - she\n"
    .string "just moved to VIRIDIAN CITY to\l"
    .string "be a schoolteacher there!$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "I'm burying my beloved GEODUDE.\p"
    .string "I took him to the beach, only to\n"
    .string "realize that he couldn't swim!\p"
    .string "Oh, poor BEN...\n"
    .string "Sniff…$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "I am a MERCHANT.\p"
    .string "Would you like to purchase this\n"
    .string "strange black cartridge?$"


