CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: Yo! {PLAYER}!\p"
    .string "You're still struggling along back\n"
    .string "here?\p"
    .string "I'm doing great! I caught a bunch\n"
    .string "of strong and smart POKéMON!\p"
    .string "Here, let me see what you caught,\n"
    .string "{PLAYER}!$"

CeruleanCity_Text_RivalDefeat::
    .string "Hey!\n"
    .string "Take it easy!\l"
    .string "You won already!$"

CeruleanCity_Text_RivalPostBattle::
    .string "JERRY: Huh?\p"
    .string "GARY? LARRY?\n"
    .string "Who's that?\p"
    .string "My name is Jerry!\n"
    .string "What are you talking about?\p"
    .string "Well, I better get rolling!\n"
    .string "Touch ya later!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "Oh, yeah, right.\p"
    .string "I feel sorry for you.\n"
    .string "No, really!\l"
    .string "The hack creator is really mean.\p"
    .string "You're always struggling to figure\n"
    .string "out what to do.\p"
    .string "Here, GRAMPS gave me this.\n"
    .string "You can have it!$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "A chatty gossip like you…\n"
    .string "That thing's perfect.\p"
    .string "Yes, you are absolutely known\n"
    .string "for being chatty and gossipy.\p"
    .string "All right, this time I really am\n"
    .string "gone. Feel ya!$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
    .string "Hey! Go away!\p"
    .string "This TM contains obvious\n"
    .string "copyrighted material!\p"
    .string "…Huh?\n"
    .string "Me?\p"
    .string "You think I should give it back?\n"
    .string "You'll have to take me to court!$"

CeruleanCity_Text_GruntDefeat::
    .string "DMCA: Okay! Fine!\n"
    .string "I'll drop the charges!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "…Okay.\n"
    .string "Just look at this!\l"
    .string "It's an obvious ripoff!"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "{PLAYER} recovered TM28 from\n"
    .string "the DMCA.$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "Don't teach that to anything or\n"
    .string "we'll sue you!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "Make room for this!\n"
    .string "I can't run until I give it to you!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "You're a TRAINER, too?\p"
    .string "Collecting, battling…\n"
    .string "It's a tough life, isn't it?$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "Did you know that you can CUT down\n"
    .string "small trees?\p"
    .string "Even that small tree in front of\n"
    .string "the shop can be CUT down.\p"
    .string "I think there's a way around it,\n"
    .string "though.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "If that SLOWBRO wasn't there, you\n"
    .string "could CUT down the small tree.\p"
    .string "That way, you could get to the\n"
    .string "other side.\p"
    .string "I think there's a way around it,\n"
    .string "though.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "You're making an encyclopedia on\n"
    .string "POKéMON? That sounds amusing.$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "The people here owned a copyrighted\n"
    .string "TM.\p"
    .string "The DMCA claimed it, and because\n"
    .string "the POLICE FORCE exists only to\l"
    .string "protect and uphold capital,\l"
    .string "we had to let them take it.$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "Okay! SLOWBRO!\n"
    .string "Use MIND GAMES!$"

CeruleanCity_Text_SlowbroPunch::
    .string "SLOWBRO, MIND GAMES!$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "SLOWBRO!\n"
    .string "MIND GAMES, now!$"

CeruleanCity_Text_NoWrong::
    .string "No! That's wrong!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "You can't get SLOWKING in this\n"
    .string "hack, so I'm trying to break the\l"
    .string "TCG with SLOWBRO instead.$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "SLOWBRO took a snooze…$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "SLOWBRO is loafing around…$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "SLOWBRO turned away…$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "SLOWBRO ignored orders…$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "I saw someone with a BICYCLE that\n"
    .string "he got for free!\p"
    .string "When I looked at it, it said:\p"
    .string "RYDEL RYDEL RYDEL RYDEL RYDEL \n"
    .string "RYDEL RYDEL RYDEL RYDEL RYDEL \l"
    .string "RYDEL RYDEL RYDEL RYDEL RYDEL \l"
    .string "RYDEL RYDEL RYDEL RYDEL RYDEL \l"
    .string "RYDEL RYDEL RYDEL RYDEL RYDEL \l"
    .string "RYDEL RYDEL RYDEL RYDEL RYDEL \p"
    .string "I wonder who he bought it from…$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "This is CERULEAN CAVE.\p"
    .string "Horribly strong POKéMON live inside\n"
    .string "there.\p"
    .string "It takes a very special TRAINER to\n"
    .string "be allowed inside there.\p"
    .string "You'd have to be strong enough to\n"
    .string "become the POKéMON LEAGUE\l"
    .string "CHAMPION for starters.\p"
    .string "And, you would have to have\n"
    .string "made a great achievement.$"

CeruleanCity_Text_CitySign::
    .string "CERULEAN CITY\n"
    .string "The Home of Competition\p"
    .string "RECOMMENDED POKéDEX COMPLETION: 30$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "TRAINER TIPS\p"
    .string "A POKéMON can be made to hold\n"
    .string "an item.\p"
    .string "Some items can even be used by\n"
    .string "the holding POKéMON in battle.$"

CeruleanCity_Text_BikeShopSign::
    .string "Grass and caves handled easily!\n"
    .string "BIKE SHOP$"

CeruleanCity_Text_GymSign::
    .string "CERULEAN CITY POKéMON CLUB\n"
    .string "LEADER: MISTY\l"
    .string "The TCG Expert!$"

