FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "There are many POKéMON locked\n"
    .string "away in the pen…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "The pen door is unlocked.\n"
    .string "The POKéMON appear to have fled.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
	.string "Just because I'm small doesn't\n"
	.string "mean you can pick on me!$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "What do you think you're doing?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
	.string "I was recruited to the DMCA after\n"
	.string "I told on my TEACHER in LAVENDER.\p"
	.string "She was doing storytime in class\n"
	.string "with copyright stories!\l"
	.string "They's not allowed!$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "Oh, now your POKéMON look strong.\n"
    .string "You're willing to sell them?\p"
    .string "Oh?\n"
    .string "You wanted to battle?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "Oh, but…\n"
    .string "Too much!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "We can give you a great price.\n"
    .string "Sell us your POKéMON!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
	.string "Grr…\p"
	.string "Every MEGA POKéMON is shaped like\n"
	.string "a letter!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "What do you think you're doing?!$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
	.string "Why are we, the D{PAUSE 20} M{PAUSE 20} C{PAUSE 20} A,{PAUSE 20} allowed\n"
	.string "to exist?\l"
	.string "Pahahah!\p"
	.string "It's hilarious if you honestly\n"
	.string "believe the rules apply to us too!$"

    
FiveIsland_RocketWarehouse_Text_Admin1Intro::
	.string "copyright\n$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "I…\n"
    .string "I'm shattered…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "You're doing things according to\n"
    .string "your beliefs and morals.\p"
    .string "I understand now…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "I've made it so you can come back\n"
    .string "in through there.\p"
    .string "Why don't you go get rested and\n"
    .string "refreshed for what lies ahead?\p"
    .string "The ADMIN after me outranks me\n"
    .string "thoroughly as a TRAINER.\p"
    .string "You'd better steel yourself for one\n"
    .string "harsh challenge.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
	.string "We, the DMCA, are quite merciful!\p"
	.string "We'll let you retain full control\n"
	.string "over everything you make…\l"
	.string "…As long as it belongs to you!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
	.string "Wha-!?\n$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
	.string "Wha-!?\n"
	.string "…{PAUSE 30}Wha.\p"
	.string "See, “Wha” is all I can say.\p"
	.string "“T” belongs to T!\n"
	.string "Such a glyph I shall never use!$"


FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "A report with graphs and text is on\n"
    .string "the PC monitor.\p"
    .string "“The Influence of Magnetic Waves\n"
    .string "on POKéMON Evolution”…\p"
    .string "… … … … … …\p"
    .string "It's too difficult to understand…$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "I almost managed to sell the\n"
    .string "SAPPHIRE for huge money…\p"
    .string "Then, you just had to come along\n"
    .string "and blow the whole deal apart!\p"
    .string "Fufu… Fufufufu…\n"
    .string "There's no forgiveness for you!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "Gah! Darn!\n"
    .string "Darn! Darn!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "If I can't sell it, it's worthless!\n"
    .string "Go ahead, take it!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "What do you want now?\n"
    .string "Go on, get lost, leave me be.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "What, you again?\p"
    .string "You… You're not GIOVANNI's kid,\n"
    .string "are you?\p"
    .string "No, that can't be right!\n"
    .string "GIOVANNI's kid has red hair.\p"
    .string "You don't have any reasons for\n"
    .string "bugging me. Leave me alone!$"

