#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Pound[] = _("Some call it\nan Octothorpe.");
const u8 gMoveDescription_KarateChop[] = _("The foe is attacked\nwith a sharp chop.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_DoubleSlap[] = _("The foe is slapped\nrepeatedly, back\nand forth, two to\nfive times.");
const u8 gMoveDescription_CometPunch[] = _("The foe is hit with\na flurry of punches\nthat strike two to\nfive times.");
const u8 gMoveDescription_MegaPunch[] = _("The foe is slugged\nby a punch thrown\nwith muscle-packed\npower.");
const u8 gMoveDescription_PayDay[] = _("Numerous coins are\nhurled at the foe.\nMoney is earned\nafter battle.");
const u8 gMoveDescription_FirePunch[] = _("The foe is punched\nwith a fiery fist.\nIt may leave the\nfoe with a burn.");
const u8 gMoveDescription_IcePunch[] = _("The foe is punched\nwith an icy fist.\nIt may leave the\nfoe frozen.");
const u8 gMoveDescription_ThunderPunch[] = _("The foe is punched\nwith an electrified\nfist. It may leave\nthe foe paralyzed.");
const u8 gMoveDescription_Scratch[] = _("Hard, pointed, and\nsharp claws rake\nthe foe.");
const u8 gMoveDescription_ViceGrip[] = _("Huge, impressive\npincers grip and\nsqueeze the foe.");
const u8 gMoveDescription_Guillotine[] = _("I only wanted\na little off\nthe top…");
const u8 gMoveDescription_RazorWind[] = _("Blades of wind hit\nthe foe on the 2nd\nturn. It has a high\ncritical-hit ratio.");
const u8 gMoveDescription_SwordsDance[] = _("A frenetic dance of\nfighting. It sharply\nraises the ATTACK\nstat.");
const u8 gMoveDescription_Cut[] = _("A basic attack.\nIt can be used to\ncut down thin trees\nand grass.");
const u8 gMoveDescription_Gust[] = _("Strikes the foe\nwith a gust of wind\nwhipped up by\nwings.");
const u8 gMoveDescription_WingAttack[] = _("The foe is struck\nwith large, imposing\nwings spread wide.");
const u8 gMoveDescription_Whirlwind[] = _("The foe is made to\nswitch out with an\nally. In the wild,\nthe battle ends.");
const u8 gMoveDescription_Fly[] = _("A 2-turn move that\nhits on the 2nd\nturn. Use it to fly\nto any known town.");
const u8 gMoveDescription_Bind[] = _("A long body or\ntentacles are used\nto bind the foe for\ntwo to five turns.");
const u8 gMoveDescription_Slam[] = _("One of the moves\nof all time.");
const u8 gMoveDescription_VineWhip[] = _("The foe is struck\nwith slender, whip-\nlike vines.");
const u8 gMoveDescription_Stomp[] = _("The foe is stomped\nwith a big foot.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_DoubleKick[] = _("A two-part\nattack.\n\nTechnically.");
const u8 gMoveDescription_MegaKick[] = _("The foe is attacked\nby a kick fired\nwith muscle-packed\npower.");
const u8 gMoveDescription_JumpKick[] = _("The user jumps up\nhigh, then kicks.\nIf it misses, the\nuser hurts itself.");
const u8 gMoveDescription_RollingKick[] = _("A quick kick from a\nrolling spin.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_SandAttack[] = _("The user ATTACKS\nusing some SAND.");
const u8 gMoveDescription_Headbutt[] = _("The user sticks its\nhead out and rams.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_HornAttack[] = _("uwu");
const u8 gMoveDescription_FuryAttack[] = _("The foe is jabbed\nrepeatedly with a\nhorn or beak two to\nfive times.");
const u8 gMoveDescription_HornDrill[] = _("The horn is rotated\nlike a drill to ram.\nThe foe will faint\nif it hits.");
const u8 gMoveDescription_Tackle[] = _("A physical attack\nin which the user\ncharges, full body,\ninto the foe.");
const u8 gMoveDescription_BodySlam[] = _("The user drops its\nfull body on the\nfoe. It may leave\nthe foe paralyzed.");
const u8 gMoveDescription_Wrap[] = _("A long body or\nvines are used to\nwrap the foe for\ntwo to five turns.");
const u8 gMoveDescription_TakeDown[] = _("A corporate ploy\nto remove content\nfrom the INTERNET\nfor profits.");
const u8 gMoveDescription_Thrash[] = _("The user thrashes\nabout for two to\nthree turns, then\nbecomes confused.");
const u8 gMoveDescription_DoubleEdge[] = _("A reckless, life-\nrisking tackle that\nalso hurts the user\na little.");
const u8 gMoveDescription_TailWhip[] = _("The user wags its\ntail cutely, making\nthe foe lower its\nATTACK stat.");
const u8 gMoveDescription_PoisonSting[] = _("A POISON attack\nso weak that even\nwith double power\nit's still bad.");
const u8 gMoveDescription_Twineedle[] = _("The foe is stabbed\ntwice with foreleg\nstingers. It may\npoison the foe.");
const u8 gMoveDescription_PinMissile[] = _("Sharp pins are shot\nat the foe and hit\ntwo to five times\nat once.");
const u8 gMoveDescription_Leer[] = _("The foe is given an\nintimidating look\nthat lowers its\nDEFENSE stat.");
const u8 gMoveDescription_Bite[] = _("The user bites with\nvicious fangs.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_Growl[] = _("The user growls in\na cute way, making\nthe foe lower its\nDEFENSE stat.");
const u8 gMoveDescription_Roar[] = _("The foe is made to\nswitch out with an\nally. In the wild,\nthe battle ends.");
const u8 gMoveDescription_Sing[] = _("A soothing song\nin a calming voice\nlulls the foe into\na deep slumber.");
const u8 gMoveDescription_Supersonic[] = _("The user generates\nodd sound waves.\nIt may confuse the\nfoe.");
const u8 gMoveDescription_SonicBoom[] = _("The foe is hit with\na shock wave that\nalways inflicts 20-\nHP damage.");
const u8 gMoveDescription_Disable[] = _("For a few turns,\nit prevents the foe\nfrom using the move\nit last used.");
const u8 gMoveDescription_Acid[] = _("The foe is sprayed\nwith a harsh, hide-\nmelting acid that\nmay lower DEFENSE.");
const u8 gMoveDescription_Ember[] = _("Ah, lovely!\nA FIRE move!");
const u8 gMoveDescription_Flamethrower[] = _("The foe is scorched\nwith intense flames.\nThe foe may suffer\na burn.");
const u8 gMoveDescription_Mist[] = _("The ally party is\nprotected by a\nmist that prevents\nstat reductions.");
const u8 gMoveDescription_WaterGun[] = _("Ah, excellent!\nBROCK should be\nvery easy now!");
const u8 gMoveDescription_HydroPump[] = _("A high volume of\nwater is blasted at\nthe foe under great\npressure.");
const u8 gMoveDescription_Surf[] = _("A big wave crashes\ndown on the foe.\nCan also be used\nfor crossing water.");
const u8 gMoveDescription_IceBeam[] = _("The foe is struck\nwith an icy beam.\nIt may freeze the\nfoe solid.");
const u8 gMoveDescription_Ice[] = _("The foe is blasted\nwith a blizzard.\nIt may freeze the\nfoe solid.");
const u8 gMoveDescription_PsyWind[] = _("A peculiar ray is\nshot at the foe.\nIt may leave the\nfoe confused.");
const u8 gMoveDescription_BubbleBeam[] = _("A spray of bubbles\nstrikes the foe.\nIt may lower the\nfoe's SPEED stat.");
const u8 gMoveDescription_AuroraBeam[] = _("AURORA BEAM?\nAt this time of\nday? In this part\nof KANTO?");
const u8 gMoveDescription_HyperBeam[] = _("A severely damaging\nattack that makes\nthe user rest on\nthe next turn.");
const u8 gMoveDescription_Peck[] = _("The foe is jabbed\nwith a sharply\npointed beak or\nhorn.");
const u8 gMoveDescription_DrillPeck[] = _("A corkscrewing\nattack with the\nsharp beak acting\nas a drill.");
const u8 gMoveDescription_Submission[] = _("The worst best\nmove of all time.");
const u8 gMoveDescription_LowKick[] = _("A low, tripping kick\nthat can cause the\nfoe to flinch.\nJust like Gen 1!");
const u8 gMoveDescription_Counter[] = _("A retaliation move\nthat counters any\nphysical hit with\ndouble the damage.");
const u8 gMoveDescription_SeismicToss[] = _("A gravity-fed throw\nthat causes damage\nmatching the user's\nlevel.");
const u8 gMoveDescription_Strength[] = _("The foe is slugged\nat maximum power.\nCan also be used\nto move boulders.");
const u8 gMoveDescription_Absorb[] = _("An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_MegaDrain[] = _("A tough attack that\ndrains half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_LeechSeed[] = _("A seed is planted\non the foe to steal\nsome HP for the \nuser on every turn.");
const u8 gMoveDescription_Growth[] = _("The user's body is\nforced to grow,\nraising the SP.\nATK stat.");
const u8 gMoveDescription_RazorLeaf[] = _("The foe is hit with\na cutting leaf.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_SolarBeam[] = _("A 2-turn move that\nblasts the foe with\nabsorbed energy in\nthe 2nd turn.");
const u8 gMoveDescription_PoisonPowder[] = _("A cloud of toxic\ndust is scattered.\nIt may poison the\nfoe.");
const u8 gMoveDescription_StunSpore[] = _("Hey, where'd this\n0 come from?");
const u8 gMoveDescription_SleepPowder[] = _("A sleep-inducing\ndust is scattered\nin high volume\naround a foe.");
const u8 gMoveDescription_PetalDance[] = _("The user petal\ndances about for\ntwo to three turns\nand gets confused.");
const u8 gMoveDescription_StringShot[] = _("The foe is bound\nwith strings shot\nfrom the mouth to\nreduce its SPEED.");
const u8 gMoveDescription_DragonRage[] = _("The foe is hit with\na shock wave that\nalways inflicts 4-\nHP damage.");
const u8 gMoveDescription_FireSpin[] = _("The foe is trapped\nin an intense spiral\nof fire that rages\ntwo to five turns.");
const u8 gMoveDescription_ThunderShock[] = _("An electric shock\nattack that may\nalso leave the foe\nparalyzed.");
const u8 gMoveDescription_Thunderbolt[] = _("A strong electrical\nattack that may\nalso leave the foe\nparalyzed.");
const u8 gMoveDescription_ThunderWave[] = _("A weak electric\nshock that is sure\nto cause paralysis\nif it hits.");
const u8 gMoveDescription_Thunder[] = _("A brutal lightning\nattack that may\nalso leave the foe\nparalyzed.");
const u8 gMoveDescription_RockThrow[] = _("The foe is attacked\nwith a shower of\nsmall, easily\nthrown rocks.");
const u8 gMoveDescription_Earthquake[] = _("An earthquake that\nstrikes all POKéMON\nin battle excluding\nthe user.");
const u8 gMoveDescription_Fissure[] = _("The foe is dropped\ninto a fissure.\nThe foe faints if it\nhits.");
const u8 gMoveDescription_Dig[] = _("An attack that hits\non the 2nd turn.\nCan also be used\nto exit dungeons.");
const u8 gMoveDescription_Toxic[] = _("A move that badly\npoisons the foe.\nIts poison damage\nworsens every turn.");
const u8 gMoveDescription_Confusion[] = _("Ah, excellent!\nBROCK should be\nvery easy now!");
const u8 gMoveDescription_PsyBeam[] = _("A strong telekinetic\nattack. It may also\nlower the foe's\nSP. DEF stat.");
const u8 gMoveDescription_Hypnosis[] = _("Hypnotic suggestion\nis used to make the\nfoe fall into a\ndeep sleep.");
const u8 gMoveDescription_Meditate[] = _("The user meditates\nto awaken its power\nand raise its\nATTACK stat.");
const u8 gMoveDescription_Agility[] = _("The user relaxes\nand lightens its\nbody to sharply\nboost its SPEED.");
const u8 gMoveDescription_QuickAttack[] = _("An almost invisibly\nfast attack that\nis certain to strike\nfirst.");
const u8 gMoveDescription_Rage[] = _("An attack that\nbecomes stronger\neach time the user\nis hit in battle.");
const u8 gMoveDescription_Teleport[] = _("The user and\nthe foe get\nTELEPORTED into\na wall somewhere.");
const u8 gMoveDescription_NightShade[] = _("An attack with a\nmirage that inflicts\ndamage matching\nthe user's level.");
const u8 gMoveDescription_Mimic[] = _("The user copies the\nmove last used by\nthe foe for the\nrest of the battle.");
const u8 gMoveDescription_Screech[] = _("An ear-splitting\nscreech is emitted\nto sharply reduce\nthe foe's DEFENSE.");
const u8 gMoveDescription_DoubleTeam[] = _("The user creates\nillusory copies of\nitself to raise its\nevasiveness.");
const u8 gMoveDescription_Recover[] = _("A self-healing move\nthat restores HP by\nup to half of the\nuser's maximum HP.");
const u8 gMoveDescription_Harden[] = _("The user stiffens\nto ATTRACT a mate.");
const u8 gMoveDescription_Minimize[] = _("The user compresses\nall the cells in its\nbody to raise its\nevasiveness.");
const u8 gMoveDescription_Smokescreen[] = _("An obscuring cloud\nof smoke or ink\nreduces the foe's\naccuracy.");
const u8 gMoveDescription_ConfuseRay[] = _("The foe is exposed\nto a sinister ray\nthat triggers\nconfusion.");
const u8 gMoveDescription_Withdraw[] = _("The user withdraws\nits body in its hard\nshell, raising its\nDEFENSE stat.");
const u8 gMoveDescription_DefenseCurl[] = _("The user curls up\nto conceal weak\nspots and raise its\nDEFENSE stat.");
const u8 gMoveDescription_Barrier[] = _("The user creates a\nsturdy wall that\nsharply raises its\nDEFENSE stat.");
const u8 gMoveDescription_LightScreen[] = _("A wall of light\ncuts damage from\nSP. ATK attacks\nfor five turns.");
const u8 gMoveDescription_Haze[] = _("Eliminates all stat\nchanges among all\nPOKéMON engaged in\nbattle.");
const u8 gMoveDescription_Reflect[] = _("A wall of light\ncuts damage from\nphysical attacks\nfor five turns.");
const u8 gMoveDescription_FocusEnergy[] = _("The user takes a\ndeep breath and\nfocuses to quarter\ncritical-hit ratio.");
const u8 gMoveDescription_Bide[] = _("The user endures\nattacks for two\nturns, then strikes\nback double.");
const u8 gMoveDescription_Metronome[] = _("Waggles a finger\nand stimulates the\nbrain into using any\nmove at random.");
const u8 gMoveDescription_MirrorMove[] = _("The user counters\nthe move last used\nby the foe with the\nsame move.");
const u8 gMoveDescription_SelfDestruct[] = _("The user blows up\nto inflict severe\ndamage, even\nmaking itself faint.");
const u8 gMoveDescription_EggBomb[] = _("fucking worthless");
const u8 gMoveDescription_Lick[] = _("The foe is licked\nand hit with a long\ntongue. It may\nalso paralyze.");
const u8 gMoveDescription_Smog[] = _("The foe is attacked\nwith exhaust gases.\nIt may also poison\nthe foe.");
const u8 gMoveDescription_Sludge[] = _("Toxic sludge is\nhurled at the foe.\nIt may poison the\ntarget.");
const u8 gMoveDescription_BoneClub[] = _("The foe is clubbed\nwith a bone held in\nhand. It may make\nthe foe flinch.");
const u8 gMoveDescription_FireBlast[] = _("The foe is hit with\nan intense flame.\nIt may leave the\ntarget with a burn.");
const u8 gMoveDescription_Waterfall[] = _("A powerful charge\nattack. It can also\nbe used to climb\na waterfall.");
const u8 gMoveDescription_Clamp[] = _("The foe is clamped\nand squeezed by\nthe user's shell for\ntwo to five turns.");
const u8 gMoveDescription_Swift[] = _("Star-shaped rays\nthat never miss are\nfired at all foes in\nbattle.");
const u8 gMoveDescription_SkullBash[] = _("The user raises its\nDEFENSE in the 1st\nturn, then attacks\nin the 2nd turn.");
const u8 gMoveDescription_SpikeCannon[] = _("Sharp spikes arev\nfired at the foe to\nstrike two to five\ntimes.");
const u8 gMoveDescription_Constrict[] = _("90% of the time\nit's about as\nuseful as it\nnormally is.");
const u8 gMoveDescription_Amnesia[] = _("I'd like to\nforget about\nthe GEN I\nSPECIAL stat.");
const u8 gMoveDescription_Kinesis[] = _("The user distracts\nthe foe by bending\na spoon. It may\nlower accuracy.");
const u8 gMoveDescription_SoftBoiled[] = _("Heals the user by\nup to half its full\nHP. It can be used\nto heal an ally.");
const u8 gMoveDescription_HiJumpKick[] = _("A strong jumping\nknee kick. If it\nmisses, the user is\nhurt.");
const u8 gMoveDescription_Glare[] = _("The user intimidates\nthe foe with the\ndesign on its belly\nto cause paralysis.");
const u8 gMoveDescription_DreamEater[] = _("Absorbs half the\ndamage it inflicted\non a sleeping foe\nto restore HP.");
const u8 gMoveDescription_PoisonGas[] = _("The foe is sprayed\nwith a cloud of\ntoxic gas that may\npoison the foe.");
const u8 gMoveDescription_Barrage[] = _("The signature move\nof EXEGGCUTE.\nSurely it is not\na waste of space.");
const u8 gMoveDescription_LeechLife[] = _("An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_LovelyKiss[] = _("The user forces a\nkiss on the foe\nwith a scary face\nthat induces sleep.");
const u8 gMoveDescription_SkyAttack[] = _("A 2nd-turn attack\nmove with a high\ncritical-hit ratio.\nThe foe may flinch.");
const u8 gMoveDescription_Transform[] = _("The user transforms\ninto a copy of the\nfoe with even the\nsame move set.");
const u8 gMoveDescription_Bubble[] = _("A spray of bubbles\nhits the foe.\nIt may lower the\nfoe's SPEED stat.");
const u8 gMoveDescription_DizzyPunch[] = _("The user is hit with\na rhythmic punch\nthat may leave it\nconfused.");
const u8 gMoveDescription_Spore[] = _("Oops, dropped a 0\non that Accuracy.");
const u8 gMoveDescription_Flash[] = _("A blast of light\nthat cuts the foe's\naccuracy. It also\nilluminates caves.");
const u8 gMoveDescription_Psywave[] = _("The foe is attacked\nwith an odd, hot\nenergy wave that\nvaries in intensity.");
const u8 gMoveDescription_Splash[] = _("The user just flops\nand splashes around\nwithout having any\neffect.");
const u8 gMoveDescription_AcidArmor[] = _("The user alters its\ncells to liquefy\nitself and sharply\nraise DEFENSE.");
const u8 gMoveDescription_Crabhammer[] = _("A large pincer is\nused to hammer the\nfoe. It has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Explosion[] = _("The user explodes\nto inflict terrible\ndamage even while\nfainting itself.");
const u8 gMoveDescription_FurySwipes[] = _("The foe is raked\nwith sharp claws or\nscythes two to five\ntimes.");
const u8 gMoveDescription_FurrySwipes[] = _("The foe is raked\nwith sharp claws or\nteeth two to five\ntimes.");
const u8 gMoveDescription_Bonemerang[] = _("The user throws a\nbone that hits the\nfoe once, then once\nagain on return.");
const u8 gMoveDescription_Rest[] = _("{PLAYER}\nWhat are you\ndoing out here?");
const u8 gMoveDescription_RockSlide[] = _("Large boulders are\nhurled at the foe.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_HyperFang[] = _("The foe is attacked\nwith sharp fangs.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_Sharpen[] = _("The user reduces\nits polygon count\nto sharpen edges\nand raise ATTACK.");
const u8 gMoveDescription_Conversion[] = _("The user changes\nits type to match\nthe type of one of\nits moves.");
const u8 gMoveDescription_TriAttack[] = _("A simultaneous\n3-beam attack that\nmay paralyze, burn,\nor freeze the foe.");
const u8 gMoveDescription_SuperFang[] = _("The user attacks\nwith sharp fangs\nand halves the\nfoe's HP.");
const u8 gMoveDescription_Slash[] = _("The foe is slashed\nwith claws, etc.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Substitute[] = _("The user creates a\ndecoy using one-\nquarter of its full\nHP.");
const u8 gMoveDescription_Struggle[] = _("An attack that is\nused only if there\nis no PP. It also\nhurts the user.");
const u8 gMoveDescription_Sketch[] = _("This move copies\nthe move last used\nby the foe, then\ndisappears.");
const u8 gMoveDescription_TripleKick[] = _("A 3-kick attack\nthat becomes more\npowerful with each\nsuccessive hit.");
const u8 gMoveDescription_Thief[] = _("An attack that may\ntake the foe's held\nitem if the user\nisn't holding one.");
const u8 gMoveDescription_SpiderWeb[] = _("Ensnares the foe \nwith sticky string\nso it doesn't flee\nor switch out.");
const u8 gMoveDescription_MindReader[] = _("The user predicts\nthe foe's action to\nensure its next\nattack hits.");
const u8 gMoveDescription_Nightmare[] = _("A sleeping foe is\nshown a nightmare\nthat inflicts some\ndamage every turn.");
const u8 gMoveDescription_FlameWheel[] = _("The user makes a\nfiery charge at the\nfoe. It may cause\na burn.");
const u8 gMoveDescription_Snore[] = _("An attack that can\nbe used only while\nasleep. It may\ncause flinching.");
const u8 gMoveDescription_Curse[] = _("A move that works\ndifferently for the\nGHOST-type and all\nthe other types.");
const u8 gMoveDescription_Flail[] = _("A desperate attack\nthat becomes more\npowerful the less\nHP the user has.");
const u8 gMoveDescription_Conversion2[] = _("The user changes\ntype to make itself\nresistant to the\nlast attack it took.");
const u8 gMoveDescription_Aeroblast[] = _("A vortex of air is\nshot at the foe.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_CottonSpore[] = _("Cotton-like spores\ncling to the foe,\nsharply reducing\nits SPEED stat.");
const u8 gMoveDescription_Reversal[] = _("An all-out attack\nthat becomes more\npowerful the less\nHP the user has.");
const u8 gMoveDescription_Spite[] = _("A move that cuts\n2 to 5 PP from the\nmove last used by\nthe foe.");
const u8 gMoveDescription_Freeze[] = _("Blasts the foe with\na snowy gust.\nIt may cause\nfreezing.");
const u8 gMoveDescription_Protect[] = _("Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.");
const u8 gMoveDescription_MachPunch[] = _("A punch thrown at\nblinding speed.\nIt is certain to\nstrike first.");
const u8 gMoveDescription_ScaryFace[] = _("Frightens the foe\nwith a scary face\nto sharply reduce\nits SPEED.");
const u8 gMoveDescription_FaintAttack[] = _("The user FAINTS,\nand then attacks.");
const u8 gMoveDescription_SweetKiss[] = _("The user kisses\nthe foe with sweet\ncuteness that\ncauses confusion.");
const u8 gMoveDescription_BellyDrum[] = _("The user maximizes\nits ATTACK stat at\nthe cost of half\nits full HP.");
const u8 gMoveDescription_SludgeBomb[] = _("Filthy sludge is\nhurled at the foe.\nIt may poison the\ntarget.");
const u8 gMoveDescription_MudSlap[] = _("Mud is hurled in\nthe foe's face to\ninflict damage and\nlower its accuracy.");
const u8 gMoveDescription_Octazooka[] = _("Ink is blasted in\nthe foe's face or\neyes to damage and\nlower accuracy.");
const u8 gMoveDescription_Spikes[] = _("A trap of spikes is\nlaid around the\nfoe's party to hurt\nfoes switching in.");
const u8 gMoveDescription_ZapCannon[] = _("An electric blast is\nfired like a cannon\nto inflict damage\nand paralyze.");
const u8 gMoveDescription_Foresight[] = _("Completely negates\nthe foe's efforts to\nheighten its ability\nto evade.");
const u8 gMoveDescription_DestinyBond[] = _("If the user faints,\nthe foe delivering\nthe final hit also\nfaints.");
const u8 gMoveDescription_PerishSong[] = _("Any battler that\nhears this faints\nin three turns\nunless it switches.");
const u8 gMoveDescription_IcyWind[] = _("A chilling wind is\nused to attack.\nIt also lowers the\nSPEED stat.");
const u8 gMoveDescription_Detect[] = _("Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.");
const u8 gMoveDescription_BoneRush[] = _("The user strikes\nthe foe with a bone\nin hand two to five\ntimes.");
const u8 gMoveDescription_LockOn[] = _("The user locks on\nto the foe, making\nthe next move sure\nto hit.");
const u8 gMoveDescription_Outrage[] = _("The user rampages\nabout for two to\nthree turns, then\nbecomes confused.");
const u8 gMoveDescription_Sandstorm[] = _("A 5-turn sandstorm\nthat damages all\ntypes except ROCK,\nGROUND, and STEEL.");
const u8 gMoveDescription_GigaDrain[] = _("A harsh attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.");
const u8 gMoveDescription_Endure[] = _("The user endures\nany hit with 1 HP\nleft. It may fail if\nused in succession.");
const u8 gMoveDescription_Charm[] = _("The foe is charmed\nby the user's cute\nappeals, sharply\ncutting its ATTACK.");
const u8 gMoveDescription_Rollout[] = _("A 5-turn rolling\nattack that becomes\nstronger each time\nit hits.");
const u8 gMoveDescription_FalseSwipe[] = _("Finish it off\nwith FALSE SWIPE!");
const u8 gMoveDescription_Swagger[] = _("A move that makes\nthe foe confused,\nbut also sharply\nraises its ATTACK.");
const u8 gMoveDescription_MilkDrink[] = _("Heals the user by\nup to half its full\nHP. It can be used\nto heal an ally.");
const u8 gMoveDescription_Spark[] = _("An electrically\ncharged tackle that\nmay also paralyze\nthe foe.");
const u8 gMoveDescription_FuryCutter[] = _("An attack that\ngrows stronger on\neach successive\nhit.");
const u8 gMoveDescription_SteelWing[] = _("The foe is hit with\nwings of steel.\nIt may also raise\nthe user's DEFENSE.");
const u8 gMoveDescription_MeanLook[] = _("The foe is fixed\nwith a mean look\nthat prevents it\nfrom escaping.");
const u8 gMoveDescription_Attract[] = _("The user stiffens\nto ATTRACT a mate.");
const u8 gMoveDescription_SleepTalk[] = _("While asleep, the\nuser randomly uses\none of the moves it\nknows.");
const u8 gMoveDescription_HealBell[] = _("A soothing bell\nchimes to heal the\nstatus problems of\nall allies.");
const u8 gMoveDescription_Return[] = _("This attack move\ngrows more powerful\nthe more the user\nlikes its TRAINER.");
const u8 gMoveDescription_Present[] = _("The foe is given a\nbooby-trapped gift.\nIt restores HP\nsometimes, however.");
const u8 gMoveDescription_Frustration[] = _("This attack move\ngrows more powerful\nthe less the user\nlikes its TRAINER.");
const u8 gMoveDescription_Safeguard[] = _("It protects the\nuser's party from\nall status problems\nfor five turns.");
const u8 gMoveDescription_PainSplit[] = _("The user adds its\nHP to the foe's HP,\nthen equally shares\nthe total HP.");
const u8 gMoveDescription_SacredFire[] = _("A mystical and\npowerful fire\nattack that may\ninflict a burn.");
const u8 gMoveDescription_Magnitude[] = _("A ground-shaking\nattack against all\nstanding POKéMON.\nIts power varies.");
const u8 gMoveDescription_DynamicPunch[] = _("The foe is punched\nwith the user's full\npower. It confuses\nthe foe if it hits.");
const u8 gMoveDescription_Megahorn[] = _("A brutal ramming\nattack delivered\nwith a tough and\nimpressive horn.");
const u8 gMoveDescription_DragonBreath[] = _("No, I'm not\ntalking about\nMY breath.");
const u8 gMoveDescription_BatonPass[] = _("The user switches\nout, passing along\nany stat changes\nto the new battler.");
const u8 gMoveDescription_Encore[] = _("Makes the foe use\nthe move it last\nused repeatedly for\ntwo to six turns.");
const u8 gMoveDescription_Pursuit[] = _("An attack move that\nworks especially\nwell on a foe that\nis switching out.");
const u8 gMoveDescription_RapidSpin[] = _("An attack that\nfrees the user from\nBIND, WRAP, LEECH\nSEED, and SPIKES.");
const u8 gMoveDescription_SweetScent[] = _("Allures the foe to\nreduce evasiveness.\nIt also attracts\nwild POKéMON.");
const u8 gMoveDescription_IronTail[] = _("An attack with a\nsteel-hard tail.\nIt may lower the\nfoe's DEFENSE stat.");
const u8 gMoveDescription_MetalClaw[] = _("Ah, excellent!\nBROCK should be\nvery easy now!");
const u8 gMoveDescription_VitalThrow[] = _("Makes the user\nattack after the\nfoe. In return,\nit will not miss.");
const u8 gMoveDescription_MorningSun[] = _("Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.");
const u8 gMoveDescription_Synthesis[] = _("Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.");
const u8 gMoveDescription_Moonlight[] = _("Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.");
const u8 gMoveDescription_HiddenPower[] = _("An attack that\nvaries in type and\nintensity depending\non the user.");
const u8 gMoveDescription_CrossChop[] = _("The foe is hit with\ndouble chops.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Twister[] = _("A vicious twister\nattacks the foe.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_RainDance[] = _("A heavy rain falls\nfor five turns,\npowering up WATER-\ntype moves.");
const u8 gMoveDescription_SunnyDay[] = _("The sun blazes for\nfive turns, powering\nup FIRE-type\nmoves.");
const u8 gMoveDescription_Crunch[] = _("The foe is crunched\nwith sharp fangs.\nIt may lower the\nfoe's SP. DEF.");
const u8 gMoveDescription_MirrorCoat[] = _("A retaliation move\nthat pays back the\nfoe's special attack\ndouble.");
const u8 gMoveDescription_PsychUp[] = _("The user hypnotizes\nitself into copying\nany stat change\nmade by the foe.");
const u8 gMoveDescription_ExtremeSpeed[] = _("gotta go fast");
const u8 gMoveDescription_AncientPower[] = _("An ancient power is\nused to attack. It\nmay also raise all\nthe user's stats.");
const u8 gMoveDescription_ShadowBall[] = _("A shadowy blob is\nhurled at the foe.\nMay also lower the\nfoe's SP. DEF.");
const u8 gMoveDescription_FutureSight[] = _("Two turns after\nthis move is used,\nthe foe is attacked\npsychically.");
const u8 gMoveDescription_RockSmash[] = _("An attack that may\nalso cut DEFENSE.\nIt can also smash\ncracked boulders.");
const u8 gMoveDescription_Whirlpool[] = _("The foe is trapped\nin a fast, vicious\nwhirlpool for two\nto five turns.");
const u8 gMoveDescription_BeatUp[] = _("All party POKéMON\njoin in the attack.\nThe more allies,\nthe more damage.");
const u8 gMoveDescription_FakeOut[] = _("An attack that hits\nfirst and causes\nflinching. Usable\nonly on 1st turn.");
const u8 gMoveDescription_Uproar[] = _("The user attacks in\nan uproar that\nprevents sleep for\ntwo to five turns.");
const u8 gMoveDescription_Stockpile[] = _("The user charges\nup power for use\nlater. It can be\nused three times.");
const u8 gMoveDescription_SpitUp[] = _("The power built\nusing STOCKPILE is\nreleased at once\nfor attack.");
const u8 gMoveDescription_Swallow[] = _("The energy it built\nusing STOCKPILE is\nabsorbed to restore\nHP.");
const u8 gMoveDescription_HeatWave[] = _("The user exhales a\nheated breath to\nattack. It may also\ninflict a burn.");
const u8 gMoveDescription_Hail[] = _("A hailstorm lasting\nfive turns damages\nall POKéMON except\nthe ICE-type.");
const u8 gMoveDescription_Torment[] = _("It enrages the foe,\nmaking it incapable\nof using the same\nmove successively.");
const u8 gMoveDescription_Flatter[] = _("Flattery is used to\nconfuse the foe,\nbut its SP. ATK\nalso rises.");
const u8 gMoveDescription_WillOWisp[] = _("A sinister, bluish\nwhite flame is shot\nat the foe to\ninflict a burn.");
const u8 gMoveDescription_Memento[] = _("The user faints,\nbut sharply lowers\nthe foe's ATTACK\nand SP. ATK.");
const u8 gMoveDescription_Facade[] = _("An attack that is\nboosted if user is\nburned, poisoned,\nor paralyzed.");
const u8 gMoveDescription_FocusPunch[] = _("An attack that is\nexecuted last.\nThe user flinches\nif hit beforehand.");
const u8 gMoveDescription_SmellingSalt[] = _("Doubly effective on\na paralyzed foe,\nbut it also cures\nthe foe's paralysis.");
const u8 gMoveDescription_FollowMe[] = _("The user draws\nattention to itself,\nmaking foes attack\nonly the user.");
const u8 gMoveDescription_NaturePower[] = _("An attack that\nchanges type\ndepending on the\nuser's location.");
const u8 gMoveDescription_Charge[] = _("The user charges\npower to boost the\nELECTRIC move it\nuses next.");
const u8 gMoveDescription_Taunt[] = _("The foe is taunted\ninto a rage that\nallows it to use\nonly attack moves.");
const u8 gMoveDescription_HelpingHand[] = _("A move that boosts\nthe power of the\nally's attack in a\nbattle.");
const u8 gMoveDescription_Trick[] = _("A move that tricks\nthe foe into\ntrading held items\nwith the user.");
const u8 gMoveDescription_RolePlay[] = _("The user mimics the\nfoe completely and\ncopies the foe's\nability.");
const u8 gMoveDescription_Wish[] = _("A self-healing move\nthat restores half\nthe full HP on the\nnext turn.");
const u8 gMoveDescription_Assist[] = _("The user randomly\npicks and uses a\nmove of an allied\nPOKéMON.");
const u8 gMoveDescription_Ingrain[] = _("The user lays roots\nthat restore HP on\nevery turn.\nIt can't switch out.");
const u8 gMoveDescription_Superpower[] = _("A powerful attack,\nbut it also lowers\nthe user's ATTACK\nand DEFENSE stats.");
const u8 gMoveDescription_MagicCoat[] = _("Reflects back the\nfoe's LEECH SEED\nand any status-\ndamaging move.");
const u8 gMoveDescription_Recycle[] = _("A move that\nrecycles a used\nitem for use once\nmore.");
const u8 gMoveDescription_Revenge[] = _("An attack move that\ngains in intensity if\nthe target has hurt\nthe user.");
const u8 gMoveDescription_BrickBreak[] = _("An attack that also\nbreaks any barrier\nlike LIGHT SCREEN\nand REFLECT.");
const u8 gMoveDescription_Yawn[] = _("A huge yawn lulls\nthe foe into falling\nasleep on the next\nturn.");
const u8 gMoveDescription_KnockOff[] = _("Knocks down the\nfoe's held item to\nprevent its use\nduring the battle.");
const u8 gMoveDescription_Endeavor[] = _("Gains power the\nfewer HP the user\nhas compared with\nthe foe.");
const u8 gMoveDescription_Eruption[] = _("The higher the\nuser's HP, the more\npowerful this\nattack becomes.");
const u8 gMoveDescription_SkillSwap[] = _("The user employs\nits psychic power\nto swap abilities\nwith the foe.");
const u8 gMoveDescription_Imprison[] = _("Prevents foes from\nusing any move\nthat is also known\nby the user.");
const u8 gMoveDescription_Refresh[] = _("A self-healing move\nthat cures the user\nof a poisoning,\nburn, or paralysis.");
const u8 gMoveDescription_Grudge[] = _("If the user faints,\nthis move deletes\nthe PP of the move\nthat finished it.");
const u8 gMoveDescription_Snatch[] = _("Steals the effects\nof the foe's\nhealing or status-\nchanging move.");
const u8 gMoveDescription_SecretPower[] = _("An attack that may\nhave an additional\neffect that varies\nwith the terrain.");
const u8 gMoveDescription_Dive[] = _("The user dives\nunderwater on the\nfirst turn and\nstrikes next turn.");
const u8 gMoveDescription_ArmThrust[] = _("A quick flurry of\nstraight-arm\npunches that hit\ntwo to five times.");
const u8 gMoveDescription_Camouflage[] = _("Alters the user's\ntype depending on\nthe location's\nterrain.");
const u8 gMoveDescription_TailGlow[] = _("The user flashes a\nlight that sharply\nraises its SP. ATK\nstat.");
const u8 gMoveDescription_LusterPurge[] = _("A burst of light\ninjures the foe. It\nmay also lower the\nfoe's SP. DEF.");
const u8 gMoveDescription_MistBall[] = _("A flurry of down\nhits the foe. It\nmay also lower the\nfoe's SP. ATK.");
const u8 gMoveDescription_FeatherDance[] = _("The foe is covered\nwith a mass of down\nthat sharply cuts\nthe ATTACK stat.");
const u8 gMoveDescription_TeeterDance[] = _("A wobbly dance\nthat confuses all\nthe POKéMON in\nbattle.");
const u8 gMoveDescription_BlazeKick[] = _("A fiery kick with a\nhigh critical-hit\nratio. It may also\nburn the foe.");
const u8 gMoveDescription_MudSport[] = _("Weakens ELECTRIC-\ntype attacks while\nthe user is in the\nbattle.");
const u8 gMoveDescription_IceBall[] = _("A 5-turn rolling\nattack that becomes\nstronger each time\nit rolls.");
const u8 gMoveDescription_NeedleArm[] = _("An attack using\nthorny arms.\nIt may make the\nfoe flinch.");
const u8 gMoveDescription_SlackOff[] = _("The user slacks off\nand restores its HP\nby half its full\nHP.");
const u8 gMoveDescription_HyperVoice[] = _("The user lets loose\na horribly loud\nshout with the\npower to damage.");
const u8 gMoveDescription_PoisonFang[] = _("The foe is bitten\nwith toxic fangs.\nIt may also badly\npoison the foe.");
const u8 gMoveDescription_CrushClaw[] = _("The foe is attacked\nwith sharp claws.\nIt may also lower\nthe foe's DEFENSE.");
const u8 gMoveDescription_BlastBurn[] = _("The foe is hit with\na huge explosion.\nThe user can't move\non the next turn.");
const u8 gMoveDescription_HydroCannon[] = _("The foe is hit with\na watery cannon.\nThe user can't move\non the next turn.");
const u8 gMoveDescription_MeteorMash[] = _("The foe is hit with\na hard, fast punch.\nIt may also raise\nthe user's ATTACK.");
const u8 gMoveDescription_Astonish[] = _("An attack using a\nstartling shout.\nIt also may make\nthe foe flinch.");
const u8 gMoveDescription_WeatherBall[] = _("An attack that\nvaries in power and\ntype depending on\nthe weather.");
const u8 gMoveDescription_Aromatherapy[] = _("A soothing scent is\nreleased to heal\nall status problems\nin the user's party.");
const u8 gMoveDescription_FakeTears[] = _("The user feigns\ncrying to sharply\nlower the foe's\nSP. DEF stat.");
const u8 gMoveDescription_AirCutter[] = _("The foe is hit with\nrazor-like wind.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_Overheat[] = _("An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.");
const u8 gMoveDescription_OdorSleuth[] = _("This effect is\ncurrently not\nimplemented.\nStay tuned!");
const u8 gMoveDescription_RockTomb[] = _("A poorly-made\noffbrand version\nof ROCK TOMB.\nCopyright pending");
const u8 gMoveDescription_SilverWind[] = _("The foe is attacked\nwith a silver dust.\nIt may raise all\nthe user's stats.");
const u8 gMoveDescription_MetalSound[] = _("A horrible metallic\nscreech is used to\nsharply lower the\nfoe's SP. DEF.");
const u8 gMoveDescription_GrassWhistle[] = _("A pleasant melody\nis played to lull\nthe foe into a deep\nsleep.");
const u8 gMoveDescription_Tickle[] = _("The foe is made to\nlaugh, reducing its\nATTACK and DEFENSE\nstats.");
const u8 gMoveDescription_CosmicPower[] = _("The user absorbs a\nmystic power to\nraise its DEFENSE\nand SP. DEF.");
const u8 gMoveDescription_WaterSpout[] = _("The higher the\nuser's HP, the more\npowerful this\nattack becomes.");
const u8 gMoveDescription_SignalBeam[] = _("The foe is hit with\na flashing beam\nthat may also\ncause confusion.");
const u8 gMoveDescription_ShadowPunch[] = _("The user throws a\npunch from the\nshadows. It cannot\nbe evaded.");
const u8 gMoveDescription_Extrasensory[] = _("The user attacks\nwith an odd power\nthat may make the\nfoe flinch.");
const u8 gMoveDescription_SkyUppercut[] = _("The user attacks\nwith an uppercut\nthrown skywards\nwith force.");
const u8 gMoveDescription_SandTomb[] = _("The foe is trapped\ninside a painful\nsandstorm for two\nto five turns.");
const u8 gMoveDescription_SheerCold[] = _("The foe is attacked\nwith ultimate cold\nthat causes fainting\nif it hits.");
const u8 gMoveDescription_MuddyWater[] = _("The user attacks\nwith muddy water.\nIt may also lower\nthe foe's accuracy.");
const u8 gMoveDescription_BulletSeed[] = _("The user shoots\nseeds at the foe.\nTwo to five seeds\nare shot at once.");
const u8 gMoveDescription_AerialAce[] = _("An extremely fast\nattack against one\ntarget. It can't be\nevaded.");
const u8 gMoveDescription_IcicleSpear[] = _("Sharp icicles are\nfired at the foe.\nIt strikes two to\nfive times.");
const u8 gMoveDescription_IronDefense[] = _("The user hardens\nits body's surface\nto sharply raise its\nDEFENSE stat.");
const u8 gMoveDescription_Block[] = _("The user blocks the\nfoe's way with arms\nspread wide to\nprevent escape.");
const u8 gMoveDescription_Howl[] = _("The user howls to\nraise its spirit and\nboost its ATTACK\nstat.");
const u8 gMoveDescription_DragonClaw[] = _("Sharp, huge claws\nhook and slash the\nfoe quickly and\nwith great power.");
const u8 gMoveDescription_FrenzyPlant[] = _("The foe is hit with\nan enormous branch.\nThe user can't move\non the next turn.");
const u8 gMoveDescription_BulkUp[] = _("The user bulks up\nits body to boost\nboth its ATTACK and\nDEFENSE stats.");
const u8 gMoveDescription_Bounce[] = _("The user bounces\non the foe on the\n2nd turn. It may\nparalyze the foe.");
const u8 gMoveDescription_MudShot[] = _("The user attacks by\nhurling mud.\nIt also reduces the\nfoe's SPEED.");
const u8 gMoveDescription_PoisonTail[] = _("An attack with a\nhigh critical-hit\nratio. It may also\npoison the foe.");
const u8 gMoveDescription_Covet[] = _("A cutely executed\nattack that also\nsteals the foe's\nhold item.");
const u8 gMoveDescription_VoltTackle[] = _("The user throws an\nelectrified tackle.\nIt hurts the user\na little.");
const u8 gMoveDescription_MagicalLeaf[] = _("The foe is attacked\nwith a strange leaf\nthat cannot be\nevaded.");
const u8 gMoveDescription_WaterSport[] = _("Weakens FIRE-type\nattacks while the\nuser is in the\nbattle.");
const u8 gMoveDescription_CalmMind[] = _("The user focuses\nits mind to raise\nthe SP. ATK and\nSP. DEF stats.");
const u8 gMoveDescription_LeafBlade[] = _("The foe is slashed\nwith a sharp leaf.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_DragonDance[] = _("A mystic, powerful\ndance that boosts\nthe user's ATTACK\nand SPEED stats.");
const u8 gMoveDescription_RockBlast[] = _("The user hurls two\nto five hard rocks\nat the foe to\nattack.");
const u8 gMoveDescription_ShockWave[] = _("A rapid jolt of\nelectricity strikes\nthe foe. It can't\nbe evaded.");
const u8 gMoveDescription_WaterPulse[] = _("An attack with a\npulsing blast of\nwater. It may also\nconfuse the foe.");
const u8 gMoveDescription_DoomDesire[] = _("A move that attacks\nthe foe with a\nblast of light two\nturns after use.");
const u8 gMoveDescription_SlushRush[] = _("An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.");
const u8 gMoveDescription_HeartSwap[] = _("Swaps any stat changes\nwith the foe.");
const u8 gMoveDescription_Retreat[] = _("Switch your active\nPOKéMON with one\nof your benched\nPOKéMON.");
const u8 gMoveDescription_SubstituteTeacher[] = _("The user creates a\ndecoy using one-\nquarter of its full\nHP.");
const u8 gMoveDescription_ConfusionPsyduck[] = _("The user is\nslightly confused\nas to who they're\nsupposed to hit.");



//dummies out for now
const u8 gMoveDescription_Water_Shuriken[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Revival_Blessing[] = _("Revives a fainted\nparty {PKMN} and\nrestores half of\nits HP.");
const u8 gMoveDescription_Tombstoner[] = _("Contained within\nTM28. Lays stones\nthat hurt the foe\nupon switching in.");
const u8 gMoveDescription_Follow_Him[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Spiky_Shield[] = _("Protects the user\nfrom attacks and\ndamages foes who\nmake contact.");
const u8 gMoveDescription_Searing_Shot[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Glaciate[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Victory_Dance[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Fusion_Bolt[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_V_Create[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_L_Create[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_O_Create[] = _("Dummy"); //not used by player, or not accessible until demo 3+ //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Waluigi[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_One_Club[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_One_Claws[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_One_Edge[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Onemerang[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_1der_Room[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Final_Gambit[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Dragon_Ascent[] = _("Ah yes, finally\na strong DRAGON-\nTYPE move!\n…What's that?");
const u8 gMoveDescription_Flying_Claw[] = _("Huge, sharp claws\nhook and slash the\nfoe.\nUh, with FLYING.");
const u8 gMoveDescription_Flying_Dance[] = _("A mystic, powerful\ndance to increase\nATTACK and SPEED.\nFLYING style.");
const u8 gMoveDescription_Fly_O_Meteor[] = _("Comets from the\nsky are summoned\nonto the target.\nUh, they fly.");
const u8 gMoveDescription_Triple_Finish[] = _("You got a\nSMASH BALL!\nTime for your\nFINAL SMASH!");
const u8 gMoveDescription_Celebrate[] = _("yay");
const u8 gMoveDescription_Hurricane[] = _("You should visit\n“Hypothetical\nHurricanes\n.fandom.com”");
const u8 gMoveDescription_Air_Slash[] = _("An extremely fair\nmove, especially\nwhen combined with\nSERENE GRACE.");
const u8 gMoveDescription_The_Bee_Move[] = _("The user raises\nin speed each time\n“BEE” appears\non screen.");
const u8 gMoveDescription_Wumboize[] = _("You had it set to\n“M” for MINIMIZE\nwhen it should've\nbeen set to “W”");
const u8 gMoveDescription_Tailwind[] = _("The user whips up\nwinds that raises\nthe SPEED of all\nparty members.");
const u8 gMoveDescription_Roost[] = _("The user heals\nby deciding to\nstop being a\nFLYING-TYPE.");
const u8 gMoveDescription_Featherdance[] = _("Dummy"); //This was just me being stupid
const u8 gMoveDescription_Primal_Rage[] = _("The user channels\nits rage to deal\na prime number\nof damage.");
const u8 gMoveDescription_Close_Combat[] = _("The user hits the\nfoe from up close.\nAs opposed to doing\nso from afar.");
const u8 gMoveDescription_Rage_Snout[] = _("The user converts\nits rage into\nenergy expressed\nthrough its nose.");
const u8 gMoveDescription_Bulldoze[] = _("The user increases\nproperty value\nby destroying\npeoples' homes.");
const u8 gMoveDescription_Electro_Ball[] = _("The user is able\nto double jump,\nand magnetically\ndraws in rings.");
const u8 gMoveDescription_Flame_Charge[] = _("The user can shoot\nitself through\nthe air to gain\ndistance.");
const u8 gMoveDescription_Bouncy_Bubble[] = _("Protects the user\nand allows them to\nbreathe\nunderwater.");
const u8 gMoveDescription_Collision_Course[] = _("The user gets in a\ncar accident and\ncommits negligent\nmanslaughter.");
const u8 gMoveDescription_Coil[] = _("The user wraps\nitself snug and\ntight, raising\nATK and ACC.");
const u8 gMoveDescription_Rocket_Punch[] = _("The user sends its\nfoe blasting off\nagain!");
const u8 gMoveDescription_Dodge_It[] = _("The user performs\nthe most powerful\ntechnique in the\nPOKéMON anime.");
const u8 gMoveDescription_Nuzzle[] = _("uwu");
const u8 gMoveDescription_Fairy_Tail[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Double_Jump[] = _("Didn't you know?\nTrans girls can\ndouble jump.");
const u8 gMoveDescription_Waterbolt[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Vault_Tackle[] = _("War.\nWar never\nchanges.");
const u8 gMoveDescription_Blu_Flare[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Round[] = _("The user channels\nits shape to\nattack.");
const u8 gMoveDescription_Circle_Throw[] = _("The user throws\nwith all the\npower of being a\ncircle.");
const u8 gMoveDescription_Zen_Headbutt[] = _("The user wills its\nhead onto the\nopponent.");
const u8 gMoveDescription_Aura_Sphere[] = _("The user has a\ncertain aura of\n“sphere” about\nthem.");
const u8 gMoveDescription_Head_Smash[] = _("The user deals\ndamage and gives\nitself a major\nconcussion.");
const u8 gMoveDescription_Head_Charge[] = _("“AFRO SMASH” is\nso much cooler\nof a name.");
const u8 gMoveDescription_Back_Air[] = _("The user protects\nitself with an\nabsolutely\nbullshit hitbox.");
const u8 gMoveDescription_Rest_Hbox[] = _("Better hope it\ndoesn't phantom.");
const u8 gMoveDescription_Pop_Off[] = _("The user gets very\nexcited and causes\nitself to faint.");
const u8 gMoveDescription_Up_Throw[] = _("The user starts a\ncombo, letting its\nREST bypass enemy\nimmunities.");
const u8 gMoveDescription_Up_Dog[] = _("Not much, what's\nup with you?");
const u8 gMoveDescription_Crab_Throw[] = _("The user chucks a\ncrab at the enemy.");
const u8 gMoveDescription_Wall_Of_Pain[] = _("The user is fully\nprotected by a\nbullshit hitbox.");
const u8 gMoveDescription_Secret_Sword[] = _("The user brings\nout the sword that\nit keeps secret\nand attacks.");
const u8 gMoveDescription_Earth_Power[] = _("By your powers\ncombined I am\nCAPTAIN EARTH.\n...wait");
const u8 gMoveDescription_Sacred_Sword[] = _("The user wields\nthe sword which\nit views as sacred\nand attacks.");
const u8 gMoveDescription_Fairy_Fang[] = _("FAIRY-flavored\nFIRE FANG.");
const u8 gMoveDescription_Attack_Order[] = _("The user summons\nreal-life actual\nnormal fucking\nbees to attack.");
const u8 gMoveDescription_Stomping_Tantrum[] = _("The user channels\nthe spirit of a\nwhiny fourteen\nyear old.");
const u8 gMoveDescription_Thundurus_Kick[] = _("Hmm, I feel\nlike that's\nspelled wrong.");
const u8 gMoveDescription_Tornadus_Kick[] = _("Wait, does\nTORNADUS even\nhave feet?");
const u8 gMoveDescription_Take_Heart[] = _("The user steals\nfrom the foe, but\nonly if they have\na HEART SCALE.");
const u8 gMoveDescription_Population_Bomb[] = _("The user chucks\nall of its\nchildren at the\nfoe.");
const u8 gMoveDescription_Daddling_Gleam[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Pay_Dad[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Sunny_Dad[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Liquidadtion[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Chatter[] = _("The user spews\ninane nonsense at\nthe foe, always\nCONFUSING it.");
const u8 gMoveDescription_Fury_Swipe_1[] = _("The user slashes\nonce with a claw.\nThe move is learned\ntwo to five times.");
const u8 gMoveDescription_Fury_Swipe_2[] = _("The user slashes\nonce with a claw.\nThe move is learned\ntwo to five times.");
const u8 gMoveDescription_Fury_Swipe_3[] = _("A critical hit!");
const u8 gMoveDescription_Fury_Swipe_4[] = _("The user slashes\nonce with a claw.\nThe move is learned\ntwo to five times.");
const u8 gMoveDescription_Fury_Swipe_5[] = _("Yes!\nI love it when\nyou get all five\nlearns!");
const u8 gMoveDescription_Struggle_Bug[] = _("The user is\nstruggling while\nbeing a bug.");
const u8 gMoveDescription_X_Scissor[] = _("Between this and\nU-TURN, it seems\nBUG TYPES get all\nthe letter moves.");
const u8 gMoveDescription_Iron_Head[] = _("An extremely fair\nmove, especially\nwhen combined with\nSERENE GRACE.");
const u8 gMoveDescription_Precipice_Blades[] = _("The user brings\nforth the power\nof the drought\nto attack.");
const u8 gMoveDescription_Aqua_Step[] = _("The user performs\nthe traditional\nPaldea Duck Dance\nto raise its speed");
const u8 gMoveDescription_SomeSensory[] = _("The user has just\nenough SENSORY to\nget by.");
const u8 gMoveDescription_NoSensory[] = _("Sorry, we're out\nof SENSORY.");
const u8 gMoveDescription_Healing_Wish[] = _("Unfinished.\nSorry!");
const u8 gMoveDescription_Real_Tears[] = _("Damn bro sorry\nto hear that");
const u8 gMoveDescription_Shadow_Sneak[] = _("The user extends\nits shadow and\nattacks from\nbehind.");
const u8 gMoveDescription_Puke_Blood[] = _("Tbh, that's the\ncorrect response\nto being on 4chan.");
const u8 gMoveDescription_Acid_Spray[] = _("The user spits\nfluid to melt\nthe target. This\nlowers SP. DEF.");
const u8 gMoveDescription_Drill_Run[] = _("Get it?\nCuz it's running?");
const u8 gMoveDescription_Rock_Punch[] = _("Like other ROCK-\nTYPE moves, this\nmove certainly has\nan accuracy.");
const u8 gMoveDescription_Rock_Climb[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Confide[] = _("The user delivers\nbad news to the\nfoe, lowering its\nSP. ATK.");
const u8 gMoveDescription_Dual_Wingbeat[] = _("The user attacks\nwith both of its\nwings, hitting\ntwice.");
const u8 gMoveDescription_Jab[] = _("Perform this\nattack for\none FIGHTING\nENERGY.");
const u8 gMoveDescription_SpecialPunch[] = _("Perform this\nattack for two\nFIGHTING and one\nCOLORLESS ENERGY.");
const u8 gMoveDescription_Psychic_Punch[] = _("A psychic punch\nthat may confuse\nthe target.");
const u8 gMoveDescription_Moongeist_Beam[] = _("The user channels\nthe power of the\nmoon to deliver\nan attack.");
const u8 gMoveDescription_Shell_Smash[] = _("The user smashes\nits shell to\nlighten its body\nand raise stats.");
const u8 gMoveDescription_Psycicle_Spear[] = _("Psychic spears are\nfired at the foe.\nIt strikes two\nto five times.");
const u8 gMoveDescription_Conversion_Z[] = _("Would you like a\nDUBIOUS DISK?");
const u8 gMoveDescription_BoltBeam[] = _("All the coverage\nyou'll ever need,\nall in one place!\nWhat a deal!");
const u8 gMoveDescription_Rounden[] = _("The user shows off\nnew technology by\nsmoothing off its\nrough edges.");
const u8 gMoveDescription_Throat_Chop[] = _("ow");
const u8 gMoveDescription_Dragon_Hammer[] = _("Ah, finally a move\nthat isn't just\nBARRAGE!");
const u8 gMoveDescription_Wood_Hammer[] = _("Okay, so maybe\nthis one won't\njust be BARRAGE\nagain?");
const u8 gMoveDescription_Pickle_Spear[] = _("Lowers the foe's\nPP.\n\niykyk");
const u8 gMoveDescription_Drum_Beating[] = _("The user performs\na traditional\nIsukuti Drumming\npattern.");
const u8 gMoveDescription_Bestow[] = _("The user gives its\nheld item to the\nfoe.\nHow thoughtful!");
const u8 gMoveDescription_Sky_Drop[] = _("The user delivers\naid to the foe\nvia air carrier.");
const u8 gMoveDescription_Delivery[] = _("The user delivers\nits item to the\nfoe, damaging it.");
const u8 gMoveDescription_Automotize[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Hi_Horsepower[] = _("The user attacks\nusing the power it\ngets from being\na horse.");
const u8 gMoveDescription_Heal_Block[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Gulp[] = _("The user eats and\nenemy and spits it\nout at another,\nbypassing PROTECT");
const u8 gMoveDescription_Ground_Pound[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Psystorm[] = _("The foe is blasted\nwith a psychic\nstorm that may\nconfuse it.");
const u8 gMoveDescription_Shadow_Images[] = _("Your opponent\nflips a coin. If\ntails, the attack\ndoes no damage.");
const u8 gMoveDescription_G_Max_Cuddle[] = _("The user channels\nthe G-MAX energy\nin the area to\nperform an attack");
const u8 gMoveDescription_Extreme_Evoboost[] = _("The user pulls\nenergy from its\nheld Z-Crystal to\nboost its power.");
const u8 gMoveDescription_Veevee_Volley[] = _("A move whose\npower increases\nthe more EEVEE\nloves its trainer");
const u8 gMoveDescription_Normally_Normal[] = _("The user uses\nall of its normal\nto attack the foe.");
const u8 gMoveDescription_Moonblast[] = _("Ah excellent, a\nFAIRY-TYPE move!\nI'm sure there's\nno loopholes here");
const u8 gMoveDescription_Mystical_Fire[] = _("Ah excellent, a\nFIRE-TYPE move!\nI'm sure there's\nno loopholes here");
const u8 gMoveDescription_Judgement[] = _("The user attacks\nby being god");
const u8 gMoveDescription_Rage_Powder[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Trick_Room[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Ally_Switch[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Dusk_Ball[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_TM07[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_ZapTap[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_ThunderJolt[] = _("Uh, yeah!\nI'm pretty sure\nthat's what the\nmove is called.");
const u8 gMoveDescription_Lightning[] = _("The user produces\na loud blast of\nthunder.");
const u8 gMoveDescription_WideSlash[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_VacuumCut[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_FocusMiss[] = _("The move misses,\nunless it misses,\nin which case\nit hits.");
const u8 gMoveDescription_TryAttack[] = _("The user tries\nvery hard to\nattack.");
const u8 gMoveDescription_Tax_Fraud[] = _("Dummy");
const u8 gMoveDescription_Pyro_Ball[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Fickle_Beam[] = _("The user attacks\nwith one of its\nheads. Fails if it\ndoesn't have one.");
const u8 gMoveDescription_Leaf_Storm[] = _("A storm of sharp\nleaves is whipped\nup. Lowers the\nuser's SP. ATK.");
const u8 gMoveDescription_Barrage_2[] = _("The signature move\nof EXEGGCUTE.\nSurely it is not\na waste of space.");
const u8 gMoveDescription_Barrage_3[] = _("The signature move\nof EXEGGCUTE.\nSurely it is not\na waste of space.");
const u8 gMoveDescription_Barrage_4[] = _("The signature move\nof EXEGGCUTE.\nSurely it is not\na waste of space.");
const u8 gMoveDescription_Breadbutt[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Butter_Blade[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Pickle_Beam[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Cheese_Dry[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Leaf_Tomato[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_LETTUCE_SNUGGLE[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Meateor_Beam[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Bread_Charge[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Mind_Blown[] = _("The user's head\nfucking explodes.");
const u8 gMoveDescription_Ice_O_Cut[] = _("The user attacks\nwith blades of ice.\nHas a high critical\nhit chance.");
const u8 gMoveDescription_Furry_Swipes[] = _("The user attacks\nthe foe once for\neach member of its\npolycule.");
const u8 gMoveDescription_Fury_Swipe_6[] = _("Aww, I hate when\nI only get two\nlearns…");
const u8 gMoveDescription_follow_mie[] = _("The user draws\nattention to itself,\nmaking foes attack\nonly the user.");
const u8 gMoveDescription_mie_first[] = _("The user cuts\nahead of the foe\nto steal their\nattack.");
const u8 gMoveDescription_mieteor_mash[] = _("The foe is hit with\na hard, fast punch.\nIt may also raise\nthe user's ATTACK.");
const u8 gMoveDescription_mieteor_beam[] = _("The user raises its\nSP. ATK in the 1st\nturn, then attacks\nin the 2nd turn.");
const u8 gMoveDescription_draco_mieteor[] = _("The user summons\nmieteors from the\nsky. This lowers\nthe user's SP. ATK");
const u8 gMoveDescription_mieling_wish[] = _("Unfinished.\nSorry!");
const u8 gMoveDescription_mief[] = _("An attack that may\ntake the foe's held\nitem if the user\nisn't holding one.");
const u8 gMoveDescription_Psycho_Cut[] = _("Dummy"); 
const u8 gMoveDescription_Aqua_Cutter[] = _("Filet-o-Fish");
const u8 gMoveDescription_Bug_Bite[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Quiver_Dance[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_U_Turn[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_First_Impression[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Savage_Spin_Out[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Single_Wingbeat[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_DynamicCrunch[] = _("A fierce bite\nthat always\nlowers DEFENSE\nby two stages.");
const u8 gMoveDescription_MudSpout[] = _("Oops. I hate\nwhen you misspell\nthe move and get\nthe wrong one…");
const u8 gMoveDescription_Foursight[] = _("Using the fource,\nthe user foursees\nthat in four\nturns, 4.");
const u8 gMoveDescription_SteelWang[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_WonderSeed[] = _("Dummy"); //not used by player, or not accessible until demo 3+
const u8 gMoveDescription_Copycat[] = _("The user copies\nthe signature move\nof cats.");
const u8 gMoveDescription_BloodMoon[] = _("Dummy");
const u8 gMoveDescription_EvilMetronome[] = _("The user waggles a\nfinger and uses a\nmove at random.\nBut, like, bad.");
const u8 gMoveDescription_ShadowForce[] = _("Dummy");
const u8 gMoveDescription_dark_pulse[] = _("Dummy");
const u8 gMoveDescription_csr_dummy2[] = _("Dummy");
const u8 gMoveDescription_dragon_pulse[] = _("Dummy");
const u8 gMoveDescription_heal_pulse[] = _("Dummy");
const u8 gMoveDescription_origin_pulse[] = _("Dummy");
const u8 gMoveDescription_WickedTorque[] = _("Dummy");
const u8 gMoveDescription_NoxiousTorque[] = _("Dummy");
const u8 gMoveDescription_MagicalTorque[] = _("Dummy");
const u8 gMoveDescription_CombatTorque[] = _("Dummy");
const u8 gMoveDescription_SparklySwirl[] = _("Dummy");
const u8 gMoveDescription_SyrupBomb[] = _("Dummy");
const u8 gMoveDescription_MakeItRain[] = _("Dummy");
const u8 gMoveDescription_FlashCannon[] = _("Dummy");
const u8 gMoveDescription_BrockTomb[] = _("Dummy");
const u8 gMoveDescription_BrockBlast[] = _("Dummy");
const u8 gMoveDescription_BrockWrecker[] = _("Dummy");
const u8 gMoveDescription_upper_hand[] = _("Dummy");
const u8 gMoveDescription_hornleech[] = _("Dummy");
const u8 gMoveDescription_fishiousrend[] = _("Dummy");
const u8 gMoveDescription_bravebird[] = _("Dummy");
const u8 gMoveDescription_maxairstream[] = _("Dummy");
const u8 gMoveDescription_Steamroller[] = _("Yeah, why would\nsomething like\nthis be BUG type?");
const u8 gMoveDescription_Slash_TCG[] = _("The foe is slashed\nwith claws, etc.\nIt has a high\ncritical-hit ratio.");
const u8 gMoveDescription_SwordsDance_TCG[] = _("A frenetic dance of\nfighting. It sharply\nraises the ATTACK\nstat.");


const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] = {
    [MOVE_POUND         - 1] = gMoveDescription_Pound,
    [MOVE_KARATE_CHOP   - 1] = gMoveDescription_KarateChop,
    [MOVE_DOUBLE_SLAP   - 1] = gMoveDescription_DoubleSlap,
    [MOVE_COMET_PUNCH   - 1] = gMoveDescription_CometPunch,
    [MOVE_MEGA_PUNCH    - 1] = gMoveDescription_MegaPunch,
    [MOVE_PAY_DAY       - 1] = gMoveDescription_PayDay,
    [MOVE_FIRE_PUNCH    - 1] = gMoveDescription_FirePunch,
    [MOVE_ICE_PUNCH     - 1] = gMoveDescription_IcePunch,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_ThunderPunch,
    [MOVE_SCRATCH       - 1] = gMoveDescription_Scratch,
    [MOVE_VICE_GRIP     - 1] = gMoveDescription_ViceGrip,
    [MOVE_GUILLOTINE    - 1] = gMoveDescription_Guillotine,
    [MOVE_RAZOR_WIND    - 1] = gMoveDescription_RazorWind,
    [MOVE_SWORDS_DANCE  - 1] = gMoveDescription_SwordsDance,
    [MOVE_CUT           - 1] = gMoveDescription_Cut,
    [MOVE_GUST          - 1] = gMoveDescription_Gust,
    [MOVE_WING_ATTACK   - 1] = gMoveDescription_WingAttack,
    [MOVE_WHIRLWIND     - 1] = gMoveDescription_Whirlwind,
    [MOVE_FLY           - 1] = gMoveDescription_Fly,
    [MOVE_BIND          - 1] = gMoveDescription_Bind,
    [MOVE_SLAM          - 1] = gMoveDescription_Slam,
    [MOVE_VINE_WHIP     - 1] = gMoveDescription_VineWhip,
    [MOVE_STOMP         - 1] = gMoveDescription_Stomp,
    [MOVE_DOUBLE_KICK   - 1] = gMoveDescription_DoubleKick,
    [MOVE_MEGA_KICK     - 1] = gMoveDescription_MegaKick,
    [MOVE_JUMP_KICK     - 1] = gMoveDescription_JumpKick,
    [MOVE_ROLLING_KICK  - 1] = gMoveDescription_RollingKick,
    [MOVE_SAND_ATTACK   - 1] = gMoveDescription_SandAttack,
    [MOVE_HEADBUTT      - 1] = gMoveDescription_Headbutt,
    [MOVE_HORN_ATTACK   - 1] = gMoveDescription_HornAttack,
    [MOVE_FURY_ATTACK   - 1] = gMoveDescription_FuryAttack,
    [MOVE_HORN_DRILL    - 1] = gMoveDescription_HornDrill,
    [MOVE_TACKLE        - 1] = gMoveDescription_Tackle,
    [MOVE_BODY_SLAM     - 1] = gMoveDescription_BodySlam,
    [MOVE_WRAP          - 1] = gMoveDescription_Wrap,
    [MOVE_TAKE_DOWN     - 1] = gMoveDescription_TakeDown,
    [MOVE_THRASH        - 1] = gMoveDescription_Thrash,
    [MOVE_DOUBLE_EDGE   - 1] = gMoveDescription_DoubleEdge,
    [MOVE_TAIL_WHIP     - 1] = gMoveDescription_TailWhip,
    [MOVE_POISON_STING  - 1] = gMoveDescription_PoisonSting,
    [MOVE_TWINEEDLE     - 1] = gMoveDescription_Twineedle,
    [MOVE_PIN_MISSILE   - 1] = gMoveDescription_PinMissile,
    [MOVE_LEER          - 1] = gMoveDescription_Leer,
    [MOVE_BITE          - 1] = gMoveDescription_Bite,
    [MOVE_GROWL         - 1] = gMoveDescription_Growl,
    [MOVE_ROAR          - 1] = gMoveDescription_Roar,
    [MOVE_SING          - 1] = gMoveDescription_Sing,
    [MOVE_SUPERSONIC    - 1] = gMoveDescription_Supersonic,
    [MOVE_SONIC_BOOM    - 1] = gMoveDescription_SonicBoom,
    [MOVE_DISABLE       - 1] = gMoveDescription_Disable,
    [MOVE_ACID          - 1] = gMoveDescription_Acid,
    [MOVE_EMBER         - 1] = gMoveDescription_Ember,
    [MOVE_FLAMETHROWER  - 1] = gMoveDescription_Flamethrower,
    [MOVE_MIST          - 1] = gMoveDescription_Mist,
    [MOVE_WATER_GUN     - 1] = gMoveDescription_WaterGun,
    [MOVE_HYDRO_PUMP    - 1] = gMoveDescription_HydroPump,
    [MOVE_SURF          - 1] = gMoveDescription_Surf,
    [MOVE_ICEBEAM      - 1] = gMoveDescription_IceBeam,
    [MOVE_ICE      - 1] = gMoveDescription_Ice,
    [MOVE_PSY_WIND       - 1] = gMoveDescription_PsyWind,
    [MOVE_BUBBLE_BEAM   - 1] = gMoveDescription_BubbleBeam,
    [MOVE_AURORA_BEAM   - 1] = gMoveDescription_AuroraBeam,
    [MOVE_HYPER_BEAM    - 1] = gMoveDescription_HyperBeam,
    [MOVE_PECK          - 1] = gMoveDescription_Peck,
    [MOVE_DRILL_PECK    - 1] = gMoveDescription_DrillPeck,
    [MOVE_SUBMISSION    - 1] = gMoveDescription_Submission,
    [MOVE_LOW_KICK      - 1] = gMoveDescription_LowKick,
    [MOVE_COUNTER       - 1] = gMoveDescription_Counter,
    [MOVE_SEISMIC_TOSS  - 1] = gMoveDescription_SeismicToss,
    [MOVE_STRENGTH      - 1] = gMoveDescription_Strength,
    [MOVE_ABSORB        - 1] = gMoveDescription_Absorb,
    [MOVE_MEGA_DRAIN    - 1] = gMoveDescription_MegaDrain,
    [MOVE_LEECH_SEED    - 1] = gMoveDescription_LeechSeed,
    [MOVE_GROWTH        - 1] = gMoveDescription_Growth,
    [MOVE_RAZOR_LEAF    - 1] = gMoveDescription_RazorLeaf,
    [MOVE_SOLAR_BEAM    - 1] = gMoveDescription_SolarBeam,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_PoisonPowder,
    [MOVE_STUN_SPORE    - 1] = gMoveDescription_StunSpore,
    [MOVE_SLEEP_POWDER  - 1] = gMoveDescription_SleepPowder,
    [MOVE_PETAL_DANCE   - 1] = gMoveDescription_PetalDance,
    [MOVE_STRING_SHOT   - 1] = gMoveDescription_StringShot,
    [MOVE_DRAGON_RAGE   - 1] = gMoveDescription_DragonRage,
    [MOVE_FIRE_SPIN     - 1] = gMoveDescription_FireSpin,
    [MOVE_THUNDER_SHOCK - 1] = gMoveDescription_ThunderShock,
    [MOVE_THUNDERBOLT   - 1] = gMoveDescription_Thunderbolt,
    [MOVE_THUNDER_WAVE  - 1] = gMoveDescription_ThunderWave,
    [MOVE_THUNDER       - 1] = gMoveDescription_Thunder,
    [MOVE_ROCK_THROW    - 1] = gMoveDescription_RockThrow,
    [MOVE_EARTHQUAKE    - 1] = gMoveDescription_Earthquake,
    [MOVE_FISSURE       - 1] = gMoveDescription_Fissure,
    [MOVE_DIG           - 1] = gMoveDescription_Dig,
    [MOVE_TOXIC         - 1] = gMoveDescription_Toxic,
    [MOVE_CONFUSION     - 1] = gMoveDescription_Confusion,
    [MOVE_PSY_BEAM       - 1] = gMoveDescription_PsyBeam,
    [MOVE_HYPNOSIS      - 1] = gMoveDescription_Hypnosis,
    [MOVE_MEDITATE      - 1] = gMoveDescription_Meditate,
    [MOVE_AGILITY       - 1] = gMoveDescription_Agility,
    [MOVE_QUICK_ATTACK  - 1] = gMoveDescription_QuickAttack,
    [MOVE_RAGE          - 1] = gMoveDescription_Rage,
    [MOVE_TELEPORT      - 1] = gMoveDescription_Teleport,
    [MOVE_NIGHT_SHADE   - 1] = gMoveDescription_NightShade,
    [MOVE_MIMIC         - 1] = gMoveDescription_Mimic,
    [MOVE_SCREECH       - 1] = gMoveDescription_Screech,
    [MOVE_DOUBLE_TEAM   - 1] = gMoveDescription_DoubleTeam,
    [MOVE_RECOVER       - 1] = gMoveDescription_Recover,
    [MOVE_HARDEN        - 1] = gMoveDescription_Harden,
    [MOVE_MINIMIZE      - 1] = gMoveDescription_Minimize,
    [MOVE_SMOKESCREEN   - 1] = gMoveDescription_Smokescreen,
    [MOVE_CONFUSE_RAY   - 1] = gMoveDescription_ConfuseRay,
    [MOVE_WITHDRAW      - 1] = gMoveDescription_Withdraw,
    [MOVE_DEFENSE_CURL  - 1] = gMoveDescription_DefenseCurl,
    [MOVE_BARRIER       - 1] = gMoveDescription_Barrier,
    [MOVE_LIGHT_SCREEN  - 1] = gMoveDescription_LightScreen,
    [MOVE_HAZE          - 1] = gMoveDescription_Haze,
    [MOVE_REFLECT       - 1] = gMoveDescription_Reflect,
    [MOVE_FOCUS_ENERGY  - 1] = gMoveDescription_FocusEnergy,
    [MOVE_BIDE          - 1] = gMoveDescription_Bide,
    [MOVE_METRONOME     - 1] = gMoveDescription_Metronome,
    [MOVE_MIRROR_MOVE   - 1] = gMoveDescription_MirrorMove,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_SelfDestruct,
    [MOVE_EGG_BOMB      - 1] = gMoveDescription_EggBomb,
    [MOVE_LICK          - 1] = gMoveDescription_Lick,
    [MOVE_SMOG          - 1] = gMoveDescription_Smog,
    [MOVE_SLUDGE        - 1] = gMoveDescription_Sludge,
    [MOVE_BONE_CLUB     - 1] = gMoveDescription_BoneClub,
    [MOVE_FIRE_BLAST    - 1] = gMoveDescription_FireBlast,
    [MOVE_WATERFALL     - 1] = gMoveDescription_Waterfall,
    [MOVE_CLAMP         - 1] = gMoveDescription_Clamp,
    [MOVE_SWIFT         - 1] = gMoveDescription_Swift,
    [MOVE_SKULL_BASH    - 1] = gMoveDescription_SkullBash,
    [MOVE_SPIKE_CANNON  - 1] = gMoveDescription_SpikeCannon,
    [MOVE_CONSTRICT     - 1] = gMoveDescription_Constrict,
    [MOVE_AMNESIA       - 1] = gMoveDescription_Amnesia,
    [MOVE_KINESIS       - 1] = gMoveDescription_Kinesis,
    [MOVE_SOFT_BOILED   - 1] = gMoveDescription_SoftBoiled,
    [MOVE_HI_JUMP_KICK  - 1] = gMoveDescription_HiJumpKick,
    [MOVE_GLARE         - 1] = gMoveDescription_Glare,
    [MOVE_DREAM_EATER   - 1] = gMoveDescription_DreamEater,
    [MOVE_POISON_GAS    - 1] = gMoveDescription_PoisonGas,
    [MOVE_BARRAGE       - 1] = gMoveDescription_Barrage,
    [MOVE_LEECH_LIFE    - 1] = gMoveDescription_LeechLife,
    [MOVE_LOVELY_KISS   - 1] = gMoveDescription_LovelyKiss,
    [MOVE_SKY_ATTACK    - 1] = gMoveDescription_SkyAttack,
    [MOVE_TRANSFORM     - 1] = gMoveDescription_Transform,
    [MOVE_BUBBLE        - 1] = gMoveDescription_Bubble,
    [MOVE_DIZZY_PUNCH   - 1] = gMoveDescription_DizzyPunch,
    [MOVE_SPORE         - 1] = gMoveDescription_Spore,
    [MOVE_FLASH         - 1] = gMoveDescription_Flash,
    [MOVE_PSYWAVE       - 1] = gMoveDescription_Psywave,
    [MOVE_SPLASH        - 1] = gMoveDescription_Splash,
    [MOVE_ACID_ARMOR    - 1] = gMoveDescription_AcidArmor,
    [MOVE_CRABHAMMER    - 1] = gMoveDescription_Crabhammer,
    [MOVE_EXPLOSION     - 1] = gMoveDescription_Explosion,
    [MOVE_EXPLOSION_USELESS     - 1] = gMoveDescription_Explosion,

    [MOVE_FURY_SWIPES   - 1] = gMoveDescription_FurySwipes,
    [MOVE_FURRY_SWIPES   - 1] = gMoveDescription_FurrySwipes,

    [MOVE_BONEMERANG    - 1] = gMoveDescription_Bonemerang,
    [MOVE_REST          - 1] = gMoveDescription_Rest,
    [MOVE_ROCK_SLIDE    - 1] = gMoveDescription_RockSlide,
    [MOVE_HYPER_FANG    - 1] = gMoveDescription_HyperFang,
    [MOVE_SHARPEN       - 1] = gMoveDescription_Sharpen,
    [MOVE_CONVERSION    - 1] = gMoveDescription_Conversion,
    [MOVE_TRI_ATTACK    - 1] = gMoveDescription_TriAttack,
    [MOVE_SUPER_FANG    - 1] = gMoveDescription_SuperFang,
    [MOVE_SLASH         - 1] = gMoveDescription_Slash,
    [MOVE_SUBSTITUTE    - 1] = gMoveDescription_Substitute,
    [MOVE_STRUGGLE      - 1] = gMoveDescription_Struggle,
    [MOVE_SKETCH        - 1] = gMoveDescription_Sketch,
    [MOVE_TRIPLE_KICK   - 1] = gMoveDescription_TripleKick,
    [MOVE_THIEF         - 1] = gMoveDescription_Thief,
    [MOVE_SPIDER_WEB    - 1] = gMoveDescription_SpiderWeb,
    [MOVE_MIND_READER   - 1] = gMoveDescription_MindReader,
    [MOVE_NIGHTMARE     - 1] = gMoveDescription_Nightmare,
    [MOVE_FLAME_WHEEL   - 1] = gMoveDescription_FlameWheel,
    [MOVE_SNORE         - 1] = gMoveDescription_Snore,
    [MOVE_CURSE         - 1] = gMoveDescription_Curse,
    [MOVE_FLAIL         - 1] = gMoveDescription_Flail,
    [MOVE_CONVERSION_2  - 1] = gMoveDescription_Conversion2,
    [MOVE_AEROBLAST     - 1] = gMoveDescription_Aeroblast,
    [MOVE_COTTON_SPORE  - 1] = gMoveDescription_CottonSpore,
    [MOVE_REVERSAL      - 1] = gMoveDescription_Reversal,
    [MOVE_SPITE         - 1] = gMoveDescription_Spite,
    [MOVE_FREEZE   - 1] = gMoveDescription_Freeze,
    [MOVE_PROTECT       - 1] = gMoveDescription_Protect,
    [MOVE_MACH_PUNCH    - 1] = gMoveDescription_MachPunch,
    [MOVE_SCARY_FACE    - 1] = gMoveDescription_ScaryFace,
    [MOVE_FAINT_ATTACK  - 1] = gMoveDescription_FaintAttack,
    [MOVE_SWEET_KISS    - 1] = gMoveDescription_SweetKiss,
    [MOVE_BELLY_DRUM    - 1] = gMoveDescription_BellyDrum,
    [MOVE_SLUDGE_BOMB   - 1] = gMoveDescription_SludgeBomb,
    [MOVE_MUD_SLAP      - 1] = gMoveDescription_MudSlap,
    [MOVE_OCTAZOOKA     - 1] = gMoveDescription_Octazooka,
    [MOVE_SPIKES        - 1] = gMoveDescription_Spikes,
    [MOVE_ZAP_CANNON    - 1] = gMoveDescription_ZapCannon,
    [MOVE_FORESIGHT     - 1] = gMoveDescription_Foresight,
    [MOVE_DESTINY_BOND  - 1] = gMoveDescription_DestinyBond,
    [MOVE_PERISH_SONG   - 1] = gMoveDescription_PerishSong,
    [MOVE_ICY_WIND      - 1] = gMoveDescription_IcyWind,
    [MOVE_DETECT        - 1] = gMoveDescription_Detect,
    [MOVE_BONE_RUSH     - 1] = gMoveDescription_BoneRush,
    [MOVE_LOCK_ON       - 1] = gMoveDescription_LockOn,
    [MOVE_OUTRAGE       - 1] = gMoveDescription_Outrage,
    [MOVE_SANDSTORM     - 1] = gMoveDescription_Sandstorm,
    [MOVE_GIGA_DRAIN    - 1] = gMoveDescription_GigaDrain,
    [MOVE_ENDURE        - 1] = gMoveDescription_Endure,
    [MOVE_CHARM         - 1] = gMoveDescription_Charm,
    [MOVE_ROLLOUT       - 1] = gMoveDescription_Rollout,
    [MOVE_FALSE_SWIPE   - 1] = gMoveDescription_FalseSwipe,
    [MOVE_SWAGGER       - 1] = gMoveDescription_Swagger,
    [MOVE_MILK_DRINK    - 1] = gMoveDescription_MilkDrink,
    [MOVE_SPARK         - 1] = gMoveDescription_Spark,
    [MOVE_FURY_CUTTER   - 1] = gMoveDescription_FuryCutter,
    [MOVE_STEEL_WING    - 1] = gMoveDescription_SteelWing,
    [MOVE_MEAN_LOOK     - 1] = gMoveDescription_MeanLook,
    [MOVE_ATTRACT       - 1] = gMoveDescription_Attract,
    [MOVE_SLEEP_TALK    - 1] = gMoveDescription_SleepTalk,
    [MOVE_HEAL_BELL     - 1] = gMoveDescription_HealBell,
    [MOVE_RETURN        - 1] = gMoveDescription_Return,
    [MOVE_PRESENT       - 1] = gMoveDescription_Present,
    [MOVE_FRUSTRATION   - 1] = gMoveDescription_Frustration,
    [MOVE_SAFEGUARD     - 1] = gMoveDescription_Safeguard,
    [MOVE_PAIN_SPLIT    - 1] = gMoveDescription_PainSplit,
    [MOVE_SACRED_FIRE   - 1] = gMoveDescription_SacredFire,
    [MOVE_MAGNITUDE     - 1] = gMoveDescription_Magnitude,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_DynamicPunch,
    [MOVE_MEGAHORN      - 1] = gMoveDescription_Megahorn,
    [MOVE_DRAGON_BREATH - 1] = gMoveDescription_DragonBreath,
    [MOVE_BATON_PASS    - 1] = gMoveDescription_BatonPass,
    [MOVE_ENCORE        - 1] = gMoveDescription_Encore,
    [MOVE_PURSUIT       - 1] = gMoveDescription_Pursuit,
    [MOVE_RAPID_SPIN    - 1] = gMoveDescription_RapidSpin,
    [MOVE_SWEET_SCENT   - 1] = gMoveDescription_SweetScent,
    [MOVE_IRON_TAIL     - 1] = gMoveDescription_IronTail,
    [MOVE_METAL_CLAW    - 1] = gMoveDescription_MetalClaw,
    [MOVE_VITAL_THROW   - 1] = gMoveDescription_VitalThrow,
    [MOVE_MORNING_SUN   - 1] = gMoveDescription_MorningSun,
    [MOVE_SYNTHESIS     - 1] = gMoveDescription_Synthesis,
    [MOVE_MOONLIGHT     - 1] = gMoveDescription_Moonlight,
    [MOVE_HIDDEN_POWER  - 1] = gMoveDescription_HiddenPower,
    [MOVE_CROSS_CHOP    - 1] = gMoveDescription_CrossChop,
    [MOVE_TWISTER       - 1] = gMoveDescription_Twister,
    [MOVE_RAIN_DANCE    - 1] = gMoveDescription_RainDance,
    [MOVE_SUNNY_DAY     - 1] = gMoveDescription_SunnyDay,
    [MOVE_CRUNCH        - 1] = gMoveDescription_Crunch,
    [MOVE_MIRROR_COAT   - 1] = gMoveDescription_MirrorCoat,
    [MOVE_PSYCH_UP      - 1] = gMoveDescription_PsychUp,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_ExtremeSpeed,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_AncientPower,
    [MOVE_SHADOW_BALL   - 1] = gMoveDescription_ShadowBall,
    [MOVE_FUTURE_SIGHT  - 1] = gMoveDescription_FutureSight,
    [MOVE_ROCK_SMASH    - 1] = gMoveDescription_RockSmash,
    [MOVE_WHIRLPOOL     - 1] = gMoveDescription_Whirlpool,
    [MOVE_BEAT_UP       - 1] = gMoveDescription_BeatUp,
    [MOVE_FAKE_OUT      - 1] = gMoveDescription_FakeOut,
    [MOVE_UPROAR        - 1] = gMoveDescription_Uproar,
    [MOVE_STOCKPILE     - 1] = gMoveDescription_Stockpile,
    [MOVE_SPIT_UP       - 1] = gMoveDescription_SpitUp,
    [MOVE_SWALLOW       - 1] = gMoveDescription_Swallow,
    [MOVE_HEAT_WAVE     - 1] = gMoveDescription_HeatWave,
    [MOVE_HAIL          - 1] = gMoveDescription_Hail,
    [MOVE_TORMENT       - 1] = gMoveDescription_Torment,
    [MOVE_FLATTER       - 1] = gMoveDescription_Flatter,
    [MOVE_WILL_O_WISP   - 1] = gMoveDescription_WillOWisp,
    [MOVE_MEMENTO       - 1] = gMoveDescription_Memento,
    [MOVE_FACADE        - 1] = gMoveDescription_Facade,
    [MOVE_FOCUS_PUNCH   - 1] = gMoveDescription_FocusPunch,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_SmellingSalt,
    [MOVE_FOLLOW_ME     - 1] = gMoveDescription_FollowMe,
    [MOVE_NATURE_POWER  - 1] = gMoveDescription_NaturePower,
    [MOVE_CHARGE        - 1] = gMoveDescription_Charge,
    [MOVE_TAUNT         - 1] = gMoveDescription_Taunt,
    [MOVE_HELPING_HAND  - 1] = gMoveDescription_HelpingHand,
    [MOVE_TRICK         - 1] = gMoveDescription_Trick,
    [MOVE_ROLE_PLAY     - 1] = gMoveDescription_RolePlay,
    [MOVE_WISH          - 1] = gMoveDescription_Wish,
    [MOVE_ASSIST        - 1] = gMoveDescription_Assist,
    [MOVE_INGRAIN       - 1] = gMoveDescription_Ingrain,
    [MOVE_SUPERPOWER    - 1] = gMoveDescription_Superpower,
    [MOVE_MAGIC_COAT    - 1] = gMoveDescription_MagicCoat,
    [MOVE_RECYCLE       - 1] = gMoveDescription_Recycle,
    [MOVE_REVENGE       - 1] = gMoveDescription_Revenge,
    [MOVE_BRICK_BREAK   - 1] = gMoveDescription_BrickBreak,
    [MOVE_YAWN          - 1] = gMoveDescription_Yawn,
    [MOVE_KNOCK_OFF     - 1] = gMoveDescription_KnockOff,
    [MOVE_ENDEAVOR      - 1] = gMoveDescription_Endeavor,
    [MOVE_ERUPTION      - 1] = gMoveDescription_Eruption,
    [MOVE_SKILL_SWAP    - 1] = gMoveDescription_SkillSwap,
    [MOVE_IMPRISON      - 1] = gMoveDescription_Imprison,
    [MOVE_REFRESH       - 1] = gMoveDescription_Refresh,
    [MOVE_GRUDGE        - 1] = gMoveDescription_Grudge,
    [MOVE_SNATCH        - 1] = gMoveDescription_Snatch,
    [MOVE_SECRET_POWER  - 1] = gMoveDescription_SecretPower,
    [MOVE_DIVE          - 1] = gMoveDescription_Dive,
    [MOVE_ARM_THRUST    - 1] = gMoveDescription_ArmThrust,
    [MOVE_CAMOUFLAGE    - 1] = gMoveDescription_Camouflage,
    [MOVE_TAIL_GLOW     - 1] = gMoveDescription_TailGlow,
    [MOVE_LUSTER_PURGE  - 1] = gMoveDescription_LusterPurge,
    [MOVE_MIST_BALL     - 1] = gMoveDescription_MistBall,
    [MOVE_FEATHER_DANCE - 1] = gMoveDescription_FeatherDance,
    [MOVE_TEETER_DANCE  - 1] = gMoveDescription_TeeterDance,
    [MOVE_BLAZE_KICK    - 1] = gMoveDescription_BlazeKick,
    [MOVE_MUD_SPORT     - 1] = gMoveDescription_MudSport,
    [MOVE_ICE_BALL      - 1] = gMoveDescription_IceBall,
    [MOVE_NEEDLE_ARM    - 1] = gMoveDescription_NeedleArm,
    [MOVE_SLACK_OFF     - 1] = gMoveDescription_SlackOff,
    [MOVE_HYPER_VOICE   - 1] = gMoveDescription_HyperVoice,
    [MOVE_POISON_FANG   - 1] = gMoveDescription_PoisonFang,
    [MOVE_CRUSH_CLAW    - 1] = gMoveDescription_CrushClaw,
    [MOVE_BLAST_BURN    - 1] = gMoveDescription_BlastBurn,
    [MOVE_HYDRO_CANNON  - 1] = gMoveDescription_HydroCannon,
    [MOVE_METEOR_MASH   - 1] = gMoveDescription_MeteorMash,
    [MOVE_ASTONISH      - 1] = gMoveDescription_Astonish,
    [MOVE_WEATHER_BALL  - 1] = gMoveDescription_WeatherBall,
    [MOVE_AROMATHERAPY  - 1] = gMoveDescription_Aromatherapy,
    [MOVE_FAKE_TEARS    - 1] = gMoveDescription_FakeTears,
    [MOVE_AIR_CUTTER    - 1] = gMoveDescription_AirCutter,
    [MOVE_OVERHEAT      - 1] = gMoveDescription_Overheat,
    [MOVE_ODOR_SLEUTH   - 1] = gMoveDescription_OdorSleuth,
    [MOVE_ROCK_TOMB     - 1] = gMoveDescription_RockTomb,
    [MOVE_SILVER_WIND   - 1] = gMoveDescription_SilverWind,
    [MOVE_METAL_SOUND   - 1] = gMoveDescription_MetalSound,
    [MOVE_GRASS_WHISTLE - 1] = gMoveDescription_GrassWhistle,
    [MOVE_TICKLE        - 1] = gMoveDescription_Tickle,
    [MOVE_COSMIC_POWER  - 1] = gMoveDescription_CosmicPower,
    [MOVE_WATER_SPOUT   - 1] = gMoveDescription_WaterSpout,
    [MOVE_SIGNAL_BEAM   - 1] = gMoveDescription_SignalBeam,
    [MOVE_SHADOW_PUNCH  - 1] = gMoveDescription_ShadowPunch,
    [MOVE_EXTRASENSORY  - 1] = gMoveDescription_Extrasensory,
    [MOVE_SKY_UPPERCUT  - 1] = gMoveDescription_SkyUppercut,
    [MOVE_SAND_TOMB     - 1] = gMoveDescription_SandTomb,
    [MOVE_SHEER_COLD    - 1] = gMoveDescription_SheerCold,
    [MOVE_MUDDY_WATER   - 1] = gMoveDescription_MuddyWater,
    [MOVE_BULLET_SEED   - 1] = gMoveDescription_BulletSeed,
    [MOVE_AERIAL_ACE    - 1] = gMoveDescription_AerialAce,
    [MOVE_ICICLE_SPEAR  - 1] = gMoveDescription_IcicleSpear,
    [MOVE_IRON_DEFENSE  - 1] = gMoveDescription_IronDefense,
    [MOVE_BLOCK         - 1] = gMoveDescription_Block,
    [MOVE_HOWL          - 1] = gMoveDescription_Howl,
    [MOVE_DRAGON_CLAW   - 1] = gMoveDescription_DragonClaw,
    [MOVE_FRENZY_PLANT  - 1] = gMoveDescription_FrenzyPlant,
    [MOVE_BULK_UP       - 1] = gMoveDescription_BulkUp,
    [MOVE_BOUNCE        - 1] = gMoveDescription_Bounce,
    [MOVE_MUD_SHOT      - 1] = gMoveDescription_MudShot,
    [MOVE_POISON_TAIL   - 1] = gMoveDescription_PoisonTail,
    [MOVE_COVET         - 1] = gMoveDescription_Covet,
    [MOVE_VOLT_TACKLE   - 1] = gMoveDescription_VoltTackle,
    [MOVE_MAGICAL_LEAF  - 1] = gMoveDescription_MagicalLeaf,
    [MOVE_WATER_SPORT   - 1] = gMoveDescription_WaterSport,
    [MOVE_CALM_MIND     - 1] = gMoveDescription_CalmMind,
    [MOVE_LEAF_BLADE    - 1] = gMoveDescription_LeafBlade,
    [MOVE_DRAGON_DANCE  - 1] = gMoveDescription_DragonDance,
    [MOVE_ROCK_BLAST    - 1] = gMoveDescription_RockBlast,
    [MOVE_SHOCK_WAVE    - 1] = gMoveDescription_ShockWave,
    [MOVE_WATER_PULSE   - 1] = gMoveDescription_WaterPulse,
    [MOVE_DOOM_DESIRE   - 1] = gMoveDescription_DoomDesire,
    [MOVE_SLUSH_RUSH  - 1] = gMoveDescription_SlushRush,
    [MOVE_HEART_SWAP    - 1] = gMoveDescription_HeartSwap,
    [MOVE_RETREAT       - 1] = gMoveDescription_Retreat,
    [MOVE_SUBSTITUTE_TEACHER    - 1] = gMoveDescription_SubstituteTeacher,
    [MOVE_WATER_SHURIKEN     -1 ] = gMoveDescription_Water_Shuriken,
    [MOVE_REVIVAL_BLESSING     -1 ] = gMoveDescription_Revival_Blessing,
    [MOVE_TOMBSTONER     -1 ] = gMoveDescription_Tombstoner,
    [MOVE_FOLLOW_HIM     -1 ] = gMoveDescription_Follow_Him,
    [MOVE_SPIKY_SHIELD     -1 ] = gMoveDescription_Spiky_Shield,
    [MOVE_SEARING_SHOT     -1 ] = gMoveDescription_Searing_Shot,
    [MOVE_GLACIATE     -1 ] = gMoveDescription_Glaciate,
    [MOVE_VICTORY_DANCE     -1 ] = gMoveDescription_Victory_Dance,
    [MOVE_FUSION_BOLT     -1 ] = gMoveDescription_Fusion_Bolt,
    [MOVE_V_CREATE     -1 ] = gMoveDescription_V_Create,
    [MOVE_L_CREATE     -1 ] = gMoveDescription_L_Create,
    [MOVE_O_CREATE     -1 ] = gMoveDescription_O_Create,
    [MOVE_WALUIGI     -1 ] = gMoveDescription_Waluigi,
    [MOVE_ONE_CLUB     -1 ] = gMoveDescription_One_Club,
    [MOVE_ONE_CLAWS     -1 ] = gMoveDescription_One_Claws,
    [MOVE_ONE_EDGE     -1 ] = gMoveDescription_One_Edge,
    [MOVE_ONEMERANG     -1 ] = gMoveDescription_Onemerang,
    [MOVE_1DER_ROOM     -1 ] = gMoveDescription_1der_Room,
    [MOVE_FINAL_GAMBIT     -1 ] = gMoveDescription_Final_Gambit,
    [MOVE_DRAGON_ASCENT     -1 ] = gMoveDescription_Dragon_Ascent,
    [MOVE_FLYING_CLAW     -1 ] = gMoveDescription_Flying_Claw,
    [MOVE_FLYING_DANCE     -1 ] = gMoveDescription_Flying_Dance,
    [MOVE_FLY_O_METEOR     -1 ] = gMoveDescription_Fly_O_Meteor,
    [MOVE_TRIPLE_FINISH     -1 ] = gMoveDescription_Triple_Finish,
    [MOVE_CELEBRATE     -1 ] = gMoveDescription_Celebrate,
    [MOVE_HURRICANE     -1 ] = gMoveDescription_Hurricane,
    [MOVE_AIR_SLASH     -1 ] = gMoveDescription_Air_Slash,
    [MOVE_THE_BEE_MOVE     -1 ] = gMoveDescription_The_Bee_Move,
    [MOVE_WUMBOIZE     -1 ] = gMoveDescription_Wumboize,
    [MOVE_TAILWIND     -1 ] = gMoveDescription_Tailwind,
    [MOVE_ROOST     -1 ] = gMoveDescription_Roost,
    [MOVE_CSR_DUMMY     -1 ] = gMoveDescription_Featherdance,
    [MOVE_PRIMAL_RAGE     -1 ] = gMoveDescription_Primal_Rage,
    [MOVE_CLOSE_COMBAT     -1 ] = gMoveDescription_Close_Combat,
    [MOVE_RAGE_SNOUT     -1 ] = gMoveDescription_Rage_Snout,
    [MOVE_BULLDOZE     -1 ] = gMoveDescription_Bulldoze,
    [MOVE_ELECTRO_BALL     -1 ] = gMoveDescription_Electro_Ball,
    [MOVE_FLAME_CHARGE     -1 ] = gMoveDescription_Flame_Charge,
    [MOVE_BOUNCY_BUBBLE     -1 ] = gMoveDescription_Bouncy_Bubble,
    [MOVE_COLLISION_COURSE     -1 ] = gMoveDescription_Collision_Course,
    [MOVE_COIL     -1 ] = gMoveDescription_Coil,
    [MOVE_ROCKET_PUNCH     -1 ] = gMoveDescription_Rocket_Punch,
    [MOVE_DODGE_IT     -1 ] = gMoveDescription_Dodge_It,
    [MOVE_NUZZLE     -1 ] = gMoveDescription_Nuzzle,
    [MOVE_FAIRY_TAIL     -1 ] = gMoveDescription_Fairy_Tail,
    [MOVE_DOUBLE_JUMP     -1 ] = gMoveDescription_Double_Jump,
    [MOVE_WATERBOLT     -1 ] = gMoveDescription_Waterbolt,
    [MOVE_VAULT_TACKLE     -1 ] = gMoveDescription_Vault_Tackle,
    [MOVE_BLU_FLARE     -1 ] = gMoveDescription_Blu_Flare,
    [MOVE_ROUND     -1 ] = gMoveDescription_Round,
    [MOVE_CIRCLE_THROW     -1 ] = gMoveDescription_Circle_Throw,
    [MOVE_CHILL_HEADBUTT     -1 ] = gMoveDescription_Zen_Headbutt,
    [MOVE_AURA_SPHERE     -1 ] = gMoveDescription_Aura_Sphere,
    [MOVE_HEAD_SMASH     -1 ] = gMoveDescription_Head_Smash,
    [MOVE_HEAD_CHARGE     -1 ] = gMoveDescription_Head_Charge,
    [MOVE_BACK_AIR     -1 ] = gMoveDescription_Back_Air,
    [MOVE_REST_HBOX     -1 ] = gMoveDescription_Rest_Hbox,
    [MOVE_POP_OFF     -1 ] = gMoveDescription_Pop_Off,
    [MOVE_UP_THROW     -1 ] = gMoveDescription_Up_Throw,
    [MOVE_UP_DOG     -1 ] = gMoveDescription_Up_Dog,
    [MOVE_CRAB_THROW     -1 ] = gMoveDescription_Crab_Throw,
    [MOVE_WALL_OF_PAIN     -1 ] = gMoveDescription_Wall_Of_Pain,
    [MOVE_SECRET_SWORD     -1 ] = gMoveDescription_Secret_Sword,
    [MOVE_EARTH_POWER     -1 ] = gMoveDescription_Earth_Power,
    [MOVE_SACRED_SWORD     -1 ] = gMoveDescription_Sacred_Sword,
    [MOVE_FAIRY_FANG     -1 ] = gMoveDescription_Fairy_Fang,
    [MOVE_ATTACK_ORDER     -1 ] = gMoveDescription_Attack_Order,
    [MOVE_STOMPING_TANTRUM     -1 ] = gMoveDescription_Stomping_Tantrum,
    [MOVE_THUNDURUS_KICK     -1 ] = gMoveDescription_Thundurus_Kick,
    [MOVE_TORNADUS_KICK     -1 ] = gMoveDescription_Tornadus_Kick,
    [MOVE_TAKE_HEART     -1 ] = gMoveDescription_Take_Heart,
    [MOVE_POPULATION_BOMB     -1 ] = gMoveDescription_Population_Bomb,
    [MOVE_DADDLING_GLEAM     -1 ] = gMoveDescription_Daddling_Gleam,
    [MOVE_PAY_DAD     -1 ] = gMoveDescription_Pay_Dad,
    [MOVE_SUNNY_DAD     -1 ] = gMoveDescription_Sunny_Dad,
    [MOVE_LIQUIDADTION     -1 ] = gMoveDescription_Liquidadtion,
    [MOVE_CHATTER     -1 ] = gMoveDescription_Chatter,
    [MOVE_FURY_SWIPE_1     -1 ] = gMoveDescription_Fury_Swipe_1,
    [MOVE_FURY_SWIPE_2     -1 ] = gMoveDescription_Fury_Swipe_2,
    [MOVE_FURY_SWIPE_3     -1 ] = gMoveDescription_Fury_Swipe_3,
    [MOVE_FURY_SWIPE_4     -1 ] = gMoveDescription_Fury_Swipe_4,
    [MOVE_FURY_SWIPE_5     -1 ] = gMoveDescription_Fury_Swipe_5,
    [MOVE_STRUGGLE_BUG     -1 ] = gMoveDescription_Struggle_Bug,
    [MOVE_X_SCISSOR     -1 ] = gMoveDescription_X_Scissor,
    [MOVE_IRON_HEAD     -1 ] = gMoveDescription_Iron_Head,
    [MOVE_PRECIPICE_BLADES     -1 ] = gMoveDescription_Precipice_Blades,
    [MOVE_AQUA_STEP     -1 ] = gMoveDescription_Aqua_Step,
    [MOVE_SOMESENSORY     -1 ] = gMoveDescription_SomeSensory,
    [MOVE_NOSENSORY     -1 ] = gMoveDescription_NoSensory,
    [MOVE_HEALING_WISH     -1 ] = gMoveDescription_Healing_Wish,
    [MOVE_REAL_TEARS     -1 ] = gMoveDescription_Real_Tears,
    [MOVE_SHADOW_SNEAK     -1 ] = gMoveDescription_Shadow_Sneak,
    [MOVE_PUKE_BLOOD     -1 ] = gMoveDescription_Puke_Blood,
    [MOVE_ACID_SPRAY     -1 ] = gMoveDescription_Acid_Spray,
    [MOVE_DRILL_RUN     -1 ] = gMoveDescription_Drill_Run,
    [MOVE_ROCK_PUNCH     -1 ] = gMoveDescription_Rock_Punch,
    [MOVE_ROCK_CLIMB     -1 ] = gMoveDescription_Rock_Climb,
    [MOVE_CONFIDE     -1 ] = gMoveDescription_Confide,
    [MOVE_DUAL_WINGBEAT     -1 ] = gMoveDescription_Dual_Wingbeat,
    [MOVE_JAB     -1 ] = gMoveDescription_Jab,
    [MOVE_SPECIALPUNCH     -1 ] = gMoveDescription_SpecialPunch,
    [MOVE_PSYCHIC_PUNCH     -1 ] = gMoveDescription_Psychic_Punch,
    [MOVE_MOONGEIST_BEAM     -1 ] = gMoveDescription_Moongeist_Beam,
    [MOVE_SHELL_SMASH     -1 ] = gMoveDescription_Shell_Smash,
    [MOVE_PSYCICLE_SPEAR     -1 ] = gMoveDescription_Psycicle_Spear,
    [MOVE_CONVERSION_Z     -1 ] = gMoveDescription_Conversion_Z,
    [MOVE_BOLTBEAM     -1 ] = gMoveDescription_BoltBeam,
    [MOVE_ROUNDEN     -1 ] = gMoveDescription_Rounden,
    [MOVE_THROAT_CHOP     -1 ] = gMoveDescription_Throat_Chop,
    [MOVE_DRAGON_HAMMER     -1 ] = gMoveDescription_Dragon_Hammer,
    [MOVE_PICKLE_SPEAR     -1 ] = gMoveDescription_Pickle_Spear,
    [MOVE_DRUM_BEATING     -1 ] = gMoveDescription_Drum_Beating,
    [MOVE_BESTOW     -1 ] = gMoveDescription_Bestow,
    [MOVE_SKY_DROP     -1 ] = gMoveDescription_Sky_Drop,
    [MOVE_DELIVERY     -1 ] = gMoveDescription_Delivery,
    [MOVE_AUTOMOTIZE     -1 ] = gMoveDescription_Automotize,
    [MOVE_HI_HORSEPOWER     -1 ] = gMoveDescription_Hi_Horsepower,
    [MOVE_HEAL_BLOCK     -1 ] = gMoveDescription_Heal_Block,
    [MOVE_GULP     -1 ] = gMoveDescription_Gulp,
    [MOVE_GROUND_POUND     -1 ] = gMoveDescription_Ground_Pound,
    [MOVE_PSYSTORM     -1 ] = gMoveDescription_Psystorm,
    [MOVE_SHADOW_IMAGES     -1 ] = gMoveDescription_Shadow_Images,
    [MOVE_G_MAX_CUDDLE     -1 ] = gMoveDescription_G_Max_Cuddle,
    [MOVE_EXTREME_EVOBOOST     -1 ] = gMoveDescription_Extreme_Evoboost,
    [MOVE_VEEVEE_VOLLEY     -1 ] = gMoveDescription_Veevee_Volley,
    [MOVE_NORMALLY_NORMAL     -1 ] = gMoveDescription_Normally_Normal,
    [MOVE_MOONBLAST     -1 ] = gMoveDescription_Moonblast,
    [MOVE_MYSTICAL_FIRE     -1 ] = gMoveDescription_Mystical_Fire,
    [MOVE_JUDGEMENT     -1 ] = gMoveDescription_Judgement,
    [MOVE_RAGE_POWDER     -1 ] = gMoveDescription_Rage_Powder,
    [MOVE_TRICK_ROOM     -1 ] = gMoveDescription_Trick_Room,
    [MOVE_ALLY_SWITCH     -1 ] = gMoveDescription_Ally_Switch,
    [MOVE_DUSK_BALL     -1 ] = gMoveDescription_Dusk_Ball,
    [MOVE_TM07     -1 ] = gMoveDescription_TM07,
    [MOVE_ZAP_TAP     -1 ] = gMoveDescription_ZapTap,
    [MOVE_THUNDERJOLT     -1 ] = gMoveDescription_ThunderJolt,
    [MOVE_LIGHTNING     -1 ] = gMoveDescription_Lightning,
    [MOVE_WIDE_SLASH     -1 ] = gMoveDescription_WideSlash,
    [MOVE_VACUUM_CUT     -1 ] = gMoveDescription_VacuumCut,
    [MOVE_FOCUS_MISS     -1 ] = gMoveDescription_FocusMiss,
    [MOVE_TRY_ATTACK     -1 ] = gMoveDescription_TryAttack,
    [MOVE_TAX_FRAUD     -1 ] = gMoveDescription_Tax_Fraud,
    [MOVE_PYRO_BALL     -1 ] = gMoveDescription_Pyro_Ball,
    [MOVE_FICKLE_BEAM     -1 ] = gMoveDescription_Fickle_Beam,
    [MOVE_LEAF_STORM     -1 ] = gMoveDescription_Leaf_Storm,
    [MOVE_BARRAGE_2     -1 ] = gMoveDescription_Barrage_2,
    [MOVE_BARRAGE_3     -1 ] = gMoveDescription_Barrage_3,
    [MOVE_BARRAGE_4     -1 ] = gMoveDescription_Barrage_4,
    [MOVE_WOOD_HAMMER     -1 ] = gMoveDescription_Wood_Hammer,
    [MOVE_BREADBUTT     -1 ] = gMoveDescription_Breadbutt,
    [MOVE_BUTTER_BLADE     -1 ] = gMoveDescription_Butter_Blade,
    [MOVE_PICKLE_BEAM     -1 ] = gMoveDescription_Pickle_Beam,
    [MOVE_CHEESE_DRY     -1 ] = gMoveDescription_Cheese_Dry,
    [MOVE_LEAF_TOMATO     -1 ] = gMoveDescription_Leaf_Tomato,
    [MOVE_LETTUCE_SNUGGLE     -1 ] = gMoveDescription_LETTUCE_SNUGGLE,
    [MOVE_MEATEOR_BEAM     -1 ] = gMoveDescription_Meateor_Beam,
    [MOVE_BREAD_CHARGE     -1 ] = gMoveDescription_Bread_Charge,
    [MOVE_MIND_BLOWN     -1 ] = gMoveDescription_Mind_Blown,
    [MOVE_GROWL_CHARMANDER     -1 ] = gMoveDescription_Growl,
    [MOVE_ICE_O_CUT     -1 ] = gMoveDescription_Ice_O_Cut,
    [MOVE_FURY_SWIPE_6     -1 ] = gMoveDescription_Fury_Swipe_6,
    [MOVE_FOLLOW_MIE     -1 ] = gMoveDescription_follow_mie,
    [MOVE_MIE_FIRST     -1 ] = gMoveDescription_mie_first,
    [MOVE_MIETEOR_MASH     -1 ] = gMoveDescription_mieteor_mash,
    [MOVE_MIETEOR_BEAM     -1 ] = gMoveDescription_mieteor_beam,
    [MOVE_DRACO_MIETEOR     -1 ] = gMoveDescription_draco_mieteor,
    [MOVE_MIELING_WISH     -1 ] = gMoveDescription_mieling_wish,
    [MOVE_MIEF     -1 ] = gMoveDescription_mief,
    [MOVE_PSYCHO_CUT     -1 ] = gMoveDescription_Psycho_Cut,
    [MOVE_AQUA_CUTTER     -1 ] = gMoveDescription_Aqua_Cutter,
    [MOVE_BUG_BITE     -1 ] = gMoveDescription_Bug_Bite,
    [MOVE_QUIVER_DANCE     -1 ] = gMoveDescription_Quiver_Dance,
    [MOVE_U_TURN     -1 ] = gMoveDescription_U_Turn,
    [MOVE_FIRST_IMPRESSION     -1 ] = gMoveDescription_First_Impression,
    [MOVE_SAVAGE_SPIN_OUT     -1 ] = gMoveDescription_Savage_Spin_Out,
    [MOVE_SINGLE_WINGBEAT     -1 ] = gMoveDescription_Single_Wingbeat,
    [MOVE_CONFUSION_PSYDUCK     -1 ] = gMoveDescription_ConfusionPsyduck,
    [MOVE_DYNAMIC_CRUNCH     -1 ] = gMoveDescription_DynamicCrunch,
    [MOVE_MUD_SPOUT     -1 ] = gMoveDescription_MudSpout,
    [MOVE_FOURSIGHT     -1 ] = gMoveDescription_Foursight,
    [MOVE_STEEL_WANG     -1 ] = gMoveDescription_SteelWang,
    [MOVE_WONDER_SEED     -1 ] = gMoveDescription_WonderSeed,
    [MOVE_COPYCAT     -1 ] = gMoveDescription_Copycat,
    [MOVE_BLOOD_MOON     -1 ] = gMoveDescription_BloodMoon,
    [MOVE_EVIL_METRONOME     -1 ] = gMoveDescription_EvilMetronome,
    [MOVE_SHADOW_FORCE     -1 ] = gMoveDescription_ShadowForce,
    [MOVE_DARK_PULSE     -1 ] = gMoveDescription_dark_pulse,
    [MOVE_CSR_DUMMY_2     -1 ] = gMoveDescription_csr_dummy2,
    [MOVE_DRAGON_PULSE     -1 ] = gMoveDescription_dragon_pulse,
    [MOVE_HEAL_PULSE     -1 ] = gMoveDescription_heal_pulse,
    [MOVE_ORIGIN_PULSE     -1 ] = gMoveDescription_origin_pulse,
    [MOVE_WICKED_TORQUE     -1 ] = gMoveDescription_WickedTorque,
    [MOVE_NOXIOUS_TORQUE     -1 ] = gMoveDescription_NoxiousTorque,
    [MOVE_MAGICAL_TORQUE     -1 ] = gMoveDescription_MagicalTorque,
    [MOVE_COMBAT_TORQUE     -1 ] = gMoveDescription_CombatTorque,
    [MOVE_SPARKLY_SWIRL     -1 ] = gMoveDescription_SparklySwirl,
    [MOVE_SYRUP_BOMB     -1 ] = gMoveDescription_SyrupBomb,
    [MOVE_MAKE_IT_RAIN     -1 ] = gMoveDescription_MakeItRain,
    [MOVE_FLASH_CANNON     -1 ] = gMoveDescription_FlashCannon,
    [MOVE_BROCK_TOMB     -1 ] = gMoveDescription_BrockTomb,
    [MOVE_BROCK_BLAST     -1 ] = gMoveDescription_BrockBlast,
    [MOVE_BROCK_WRECKER     -1 ] = gMoveDescription_BrockWrecker,
    [MOVE_UPPER_HAND     -1 ] = gMoveDescription_upper_hand,
    [MOVE_HORN_LEECH     -1 ] = gMoveDescription_hornleech,
    [MOVE_FISHIOUS_REND     -1 ] = gMoveDescription_fishiousrend,
    [MOVE_BRAVE_BIRD     -1 ] = gMoveDescription_bravebird,
    [MOVE_MAX_AIRSTREAM     -1 ] = gMoveDescription_maxairstream,
    [MOVE_STEAMROLLER     -1 ] = gMoveDescription_Steamroller,
    [MOVE_SLASH_TCG     -1 ] = gMoveDescription_Slash_TCG,
    [MOVE_SWORDSDANCE_TCG     -1 ] = gMoveDescription_SwordsDance_TCG,
};
