CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
	.string "Oh god, please help me.\p"
	.string "I've been stuck in this room for\n"
	.string "ages.\l"
	.string "I just want to see my family…$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
	.string "1F: SERVICE COUNTER\p"
	.string "2F: TRAINER'S MAR-\p"
	.string "The rest has been scribbled over...\p"
	.string "PLEASE GET ME OUT OF HERE\n$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
	.string "Hi!\n"
	.string "I know what you're thinking:\l"
	.string "There should be an elevator here!\p"
	.string "Sadly, I had to remove it cuz it\n"
	.string "kept causing game-breaking bugs.\p"
	.string "Apologies for the inconvenience!\n"
	.string "-CELIA, the creator.$"

