ViridianCity_Text_CanCarryMonsAnywhere::
    .string "Running into a wild RATATTA is\n"
    .string "always scary.\p"
    .string "Even me and my Level 96 DRAGONITE\n"
    .string "still FEAR them.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "This POKéMON GYM is always closed.\p"
    .string "It's always in legal trouble!$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "VIRIDIAN GYM's LEADER returned!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "You want to know about the two\n"
    .string "kinds of caterpillar POKéMON?$"

ViridianCity_Text_OhOkayThen::
    .string "Oh, okay then!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "CATERPIE evlolves into a butterfly,\n"
    .string "and WEEDLE evolves into a bee!$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "Oh, no!\p"
    .string "Grandpa's dead!$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "We just finished holding the funeral\n"
    .string "for grandpa.\p"
    .string "Thankfully, I g ot a new one!$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "There's a dead man in the road.\p"
    .string "You shouldn't disturb the body…$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "A few minutes ago there was\n"
    .string "another old man laying here.\p"
    .string "Unfortunately, he caught a bad\n"
    .string "case of death.\p"
    .string "ok tutorial time$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "Ah, I'm sure taht was helpful\n"
    .string "and informative!\p"
    .string "oh take this too$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "All right, 0x59:mna!\n"
    .string "Now quickly!\l"
    .string "FLY over to CINNABAR ISLAND\P"
    .string "…What's that?\n"
    .string "You can't FLY yet?\p"
    .string "Darn.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Be ready to FLY over to\n"
    .string "CINNABAR ISLAND!\p"
    .string "By the way, I'm sorry that the\n"
    .string "TEACHY TV isn't changed yet.\l"
    .string "It's coming next update.$"


ViridianCity_Text_HowsTeachyTVHelping::
    .string "Be ready to FLY over to\n"
    .string "CINNABAR ISLAND!\p"
    .string "By the way, I'm sorry that the\n"
    .string "TEACHY TV isn't changed yet.\l"
    .string "It's coming next update.$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Hm… You're too busy to not even\n"
    .string "have the time for TEACHY TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"

ViridianCity_Text_CitySign::
    .string "VIRIDIAN CITY \n"
    .string "Zero violations of copyright law!\p"
    .string "Recommended POKéDEX completion: 6$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "VIRIDIAN CITY\n"
    .string "NEW WILD POKéMON: 1$"

ViridianCity_Text_MovesLimitedByPP::
    .string "TRAINER TIPS\p"
    .string "Remember to savestate frequently!\p"
    .string "You might accidentally do something\n"
    .string "Very dumb and softlock yourself!$"

ViridianCity_Text_GymSign::
    .string "VIRIDIAN CITY POKéMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "VIRIDIAN GYM's doors are locked…$"

