PokemonLeague_AgathasRoom_Text_Intro::
	.string "CYNTHIA: Hello.\p"
	.string "There's no need for pleasantries.\n"
	.string "We both know why you're here.\p"
	.string "Are you ready for the challenge\n"
	.string "ahead?\l"
	.string "It'll be your greatest test yet.\p"
	.string "But enough talk.\n"
	.string "I accept your challenge!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro::
    .string "I am AGATHA of the ELITE FOUR.\p"
    .string "You're the child that OAK's taken\n"
    .string "under his wing, aren't you?\p"
    .string "That old duff was once tough and\n"
    .string "handsome.\p"
    .string "But that was decades ago.\n"
    .string "He's a shadow of his former self.\p"
    .string "Now he just wants to fiddle with\n"
    .string "his POKéDEX.\p"
    .string "He's wrong.\n"
    .string "POKéMON are for battling!\p"
    .string "{PLAYER}! I'll show you how a real\n"
    .string "TRAINER battles!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat::
    .string "Oh, my!\n"
    .string "You're something special, child!$"

PokemonLeague_AgathasRoom_Text_PostBattle::
	.string "Well done.\n"
	.string "You've truly proven your wit.\p"
	.string "But don't expect to rest easy.\n"
	.string "There's another challenge ahead.\p"
	.string "In the next room awaits the most\n"
	.string "difficult TRAINER in the entire\l"
	.string "POKéMON franchise!$"

