PokemonLeague_AgathasRoom_Text_Intro::
	.string "CYNTHIA: Hello.\p"
	.string "There's no need for pleasantries.\n"
	.string "We both know why you're here.\p"
	.string "Are you ready for the challenge\n"
	.string "ahead?\l"
	.string "It'll be your greatest test yet.\p"
	.string "But enough talk.\n"
	.string "I accept your challenge!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_RematchIntro::
	.string "CYNTHIA: Hello.\p"
	.string "There's no need for pleasantries.\n"
	.string "We both know why you're here.\p"
	.string "Are you ready for the challenge\n"
	.string "ahead?\l"
	.string "It'll be your greatest test yet.\p"
	.string "But enough talk.\n"
	.string "I accept your challenge!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_AgathasRoom_Text_Defeat::
    .string "Oh, my!\n"
    .string "You're something special, child!$"

PokemonLeague_AgathasRoom_Text_PostBattle::
	.string "Well done.\n"
	.string "You've truly proven your wit.\p"
	.string "But don't expect to rest easy.\n"
	.string "There's another challenge ahead.\p"
	.string "In the next room awaits the most\n"
	.string "difficult TRAINER in the entire\l"
	.string "POKéMON franchise!$"

