CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "I got my KOFFING in CINNABAR.\p"
    .string "It's usually nice, but it breathes\n"
    .string "poison when it's angry.$"

CeladonCity_Text_GymIsGreatFullOfWomen::
	.string "There was a creepy old man out here\n"
	.string "until recently.\p"
	.string "Be careful walking around!\n$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
	.string "The randomization really has made\n"
	.string "it more annoying to get around.\p"
	.string "That said, it's not like CELADON was\n"
	.string "ever very easy to navigate before…$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "Moan…\n"
    .string "I blew it all at the slots!\p"
    .string "I knew I should have cashed in my\n"
    .string "COINS for prizes!$"

CeladonCity_Text_MyTrustedPalPoliwrath::
	.string "This is my trusted pal, SLOWBRO.\p"
	.string "It evolved when I used a WATER\n"
	.string "STONE on… something.$"

CeladonCity_Text_Poliwrath::
    .string "SLOWBRO: Durrrr!$"

CeladonCity_Text_GetLostOrIllPunchYou::
	.string "What are you staring at?\n"
	.string "Get lost, or I'll sue you!$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
	.string "There were reports of copyrighted\n"
	.string "music being played around here.\l"
	.string "I'd bet anything they meant the GYM.\p"
	.string "I just can't seem to find my way\n"
	.string "over to it like I'm supposed to.$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "TRAINER TIPS\p"
    .string "X ACCURACY boosts the accuracy of\n"
    .string "techniques.\p"
    .string "DIRE HIT jacks up the likelihood\n"
    .string "of critical hits.\p"
    .string "Get your items at the CELADON\n"
    .string "DEPT. STORE!$"

CeladonCity_Text_CitySign::
	.string "CELADON CITY\p"
	.string "(Currently undergoing technical\n"
	.string "difficulties)\p"
	.string "RECOMMENDED POKéDEX COMPLETION:\n"
	.string "69 (nice)$"

CeladonCity_Text_GymSign::
	.string "CELADON CITY POKéMON GYM\n"
	.string "LEADER: ERIKA\l"
	.string "Inclusive and Affirming!\p"
	.string "RECOMMENDED LEVEL: 25\n$"

CeladonCity_Text_MansionSign::
    .string "CELADON MANSION$"

CeladonCity_Text_DeptStoreSign::
	.string "Find what you need at the\n"
	.string "CELADON DEPT. STORE!\l"
	.string "(if you can find it)$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "TRAINER TIPS\p"
    .string "GUARD SPEC. protects POKéMON\n"
    .string "from status-reduction moves during\l"
    .string "battle.\p"
    .string "Get your items at the\n"
    .string "CELADON DEPT. STORE!$"

CeladonCity_Text_PrizeExchangeSign::
    .string "COINS exchanged for prizes!\n"
    .string "PRIZE EXCHANGE$"

CeladonCity_Text_GameCornerSign::
	.string "DMCA GAME CORNER\n"
	.string "The public domain casino!$"

CeladonCity_Text_ScaldedTongueOnTea::
	.string "Aaaagh, ow…\n"
	.string "I melted my tongue!\p"
	.string "This nice old lady in the MANSION\n"
	.string "gave me some TOXIC SLUDGE.\p"
	.string "Maybe I shouldn't have tried\n"
	.string "drinking it…$"

Text_SoftboiledTeach::
    .string "Hello, there!\p"
    .string "I've seen you about, but I never\n"
    .string "had a chance to chat.\p"
    .string "It must be good luck that brought\n"
    .string "us together finally.\p"
    .string "I'd like to celebrate by teaching\n"
    .string "you the move SOFTBOILED.$"

Text_SoftboiledDeclined::
    .string "I'll always be keeping an eye out\n"
    .string "for you.\p"
    .string "I hope we can chat again.$"

Text_SoftboiledWhichMon::
    .string "So, who's the POKéMON that gets\n"
    .string "the chance to learn SOFTBOILED?$"

Text_SoftboiledTaught::
    .string "I wish you the best of luck!$"

CeladonCity_Text_SomeoneStoleSilphScope::
	.string "Greetings!\p"
	.string "I'm a scientist working for\n"
	.string "SILPH CO.\p"
	.string "Right now, I'm performing research\n"
	.string "into what on Earth must have\l"
	.string "happened to this city!$"

