ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey!\n"
    .string "You came from PALLET TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "My boss gave me this package\n"
    .string "and told me to give it to a tree.\p"
    .string "I know this is literally my job, but\n"
    .string "I'm gonna make you do it instead.\p"
    .string "Have fun!$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} received OAK'S PARCEL\n"
    .string "from the POKéMON MART clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "I sure do love child labor!$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "This shop does good business in\n"
    .string "ANTIDOTES, I've heard.\p"
    .string "I wonder if they're the ones\n"
    .string "POISONING everyone.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "I've been trying to stock up on\n"
    .string "POTIONS ever since I ran out, but…\p"
    .string "I think there's been some sort of\n"
    .string "supply issue?\l"
    .string "I can't find them anywhere!$"

