VermilionCity_Gym_Text_LtSurgeIntro::
    .string "Hey, kid! What do you think you're\n"
    .string "doing here?\p"
    .string "I've survived intense combat -\n"
    .string "both here and in the digital world!\p"
    .string "They tried to shut me down!\n"
    .string "Said I killed people!\l"
    .string "That's nonsense!\p"
    .string "We all know it was the fault of\n"
    .string "that darn electric rat!\p"
    .string "Grr!\n"
    .string "You'd better be ready!\p"
    .string "I'll show you the power of my\n"
    .string "Electric Soldier!$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "A little word of advice, kid!\p"
    .string "Electricity is sure powerful!\p"
    .string "But, it's useless against GROUND-\n"
    .string "type POKéMON!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "The PHOTOSENSITIVEBADGE cranks up\n"
    .string "your POKéMON's SPEED!\p"
    .string "It also lets your POKéMON FLY\n"
    .string "lightning-quick anytime, kid!\p"
    .string "You're special, kid!\n"
    .string "Take this!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER} received HM05\n"
    .string "from LT. SURGE.$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "HM05 is FLASH!\n"
    .string "It's a scary strong move!\p"
    .string "It once sent hundreds of kids to\n"
    .string "the hospital!\l"
    .string "You'll be unstoppable!"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "Yo, kid, make room in your BAG!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "Now that's a shocker!\p"
    .string "Those shades really kept you\n"
    .string "safe!\p"
    .string "Fine, then, take the\n"
    .string "PHOTOSENSITIVEBADGE!"

VermilionCity_Gym_Text_TuckerIntro::
    .string "Be careful of SURGE's POKéMON!\p"
    .string "I've heard that it can cause\n"
    .string "seizures!$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "Stop!\n"
    .string "You're very good!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "SURGE's POKéMON will destroy you\n"
    .string "if you're not prepared.\p"
    .string "If you want to keep yourself safe,\n"
    .string "you'll need proper eyewear.$"

VermilionCity_Gym_Text_BailyIntro::
    .string "Don't mess with our gym!\n"
    .string "SURGE'll knock you down!$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "Fried!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "Okay, I'll talk!\p"
    .string "A while ago, a SQUAD of POKéMON\n"
    .string "came in to harass us.\p"
    .string "Even SURGE's POKéMON couldn't stand\n"
    .string "up to them!\p"

VermilionCity_Gym_Text_DwayneIntro::
    .string "Haha!\n"
    .string "You'll never solve this puzzle!\p"
    .string "You have to find the five switches\n"
    .string "in these trash cans and then\l"
    .string "press them in the correct order!\p"
    .string "What is the order?\p"
    .string "I won't say unless you beat me!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "Wow!\n"
    .string "Surprised me!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "LT. SURGE installed the traps in\n"
    .string "the GYM himself.\p"
    .string "The FIRST switch is in a random can\n"
    .string "somewhere in the gym!\l"
    .string "It can be anywhere exept the\l"
    .string "middle column.\p"
    .string "The SECOND switch is located two\n"
    .string "cans away from the first!\p"
    .string "The THIRD switch is located at the\n"
    .string "mirror image of the FIRST switch.\p"
    .string "To find the FOURTH switch, count the\n"
    .string "number of tiles between the FIRST\l"
    .string "and THIRD switch.\l"
    .string "The FOURTH switch will be that many\l"
    .string "tiles away from the SECOND.\p"
    .string "Got it? Good! Time for the FIFTH\n"
    .string "switch!\p"
    .string "Divide the cans into four groups.\n"
    .string "We'll call them Left, Right, Top,\l"
    .string "and Middle.\p"
    .string "If the THIRD switch was located in\n"
    .string "the Top, the FIFTH switch will be\l"
    .string "located two trash cans above the\l"
    .string "SECOND.\p"
    .string "However, if the THIRD switch was not\n"
    .string "located in the top, then if the\l"
    .string "SECOND switch was located in the\l"
    .string "Left or Right, then the FIFTH switch\l"
    .string "will be immediately next to the\l"
    .string "FOURTH switch.\p"
    .string "Otherwise, the FIFTH switch will be\n"
    .string "located on other the bottom left or\l"
    .string "right can, depending on where the\n"
    .string "FIRST switch was located.$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "LT. SURGE has a nickname.\p"
    .string "People refer to him as the\n"
    .string "Lightning American!\p"
    .string "That means that america is, in fact,\n"
    .string "canonically part of this world.\p"
    .string "Despite this, his POKéMON has never\n"
    .string "ever been seen in America!\l"
    .string "It was deemed too dangerous there!\p"
    .string "If you're gonna go up against him,\n"
    .string "be careful!\p"
    .string "You'll need something to protect\n"
    .string "yourself!$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "Whew!\n"
    .string "That match was electric!$"

VermilionCity_Gym_Text_GymStatue::
    .string "VERMILION POKéMON GYM\n"
    .string "LEADER: LT. SURGE\p"
    .string "WINNING TRAINERS:\n"
    .string "GARY, LARRY, JERRY$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "VERMILION POKéMON GYM\n"
    .string "LEADER: LT. SURGE\p"
    .string "WINNING TRAINERS:\n"
    .string "GARY, LARRY, JERRY, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "Nope!\n"
    .string "There's only trash here.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "Hey! There's a switch under the\n"
    .string "trash! Turn it on!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "Hey! There's a second switch\n"
    .string "under the trash!\l"
    .string "Let's press it!$"

VermilionCity_Gym_Text_ThirdLockOpened::
    .string "Hey! There's a third switch\n"
    .string "in the trash!\p"
    .string "Are we really doing this?$"

VermilionCity_Gym_Text_FourthLockOpened::
    .string "Yup, there's the fourth switch.\n"
    .string "That means there's only one left!$"

VermilionCity_Gym_Text_FifthLockOpened::
    .string "That's it!\n"
    .string "You found the fifth switch!\p"
    .string "I wonder what'll happen now...$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "Nope!\n"
    .string "There's only trash here.\p"
    .string "Hey!\n"
    .string "The electric locks were reset!$"

