Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze::
    .string "I'm very impressed with the new\n"
    .string "KANTO Lawn Maintenance service!\p"
    .string "It's like there was never grass\n"
    .string "out front at all!$"

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite::
    .string "RATTATA may be small, but don't\n"
    .string "underestimate its wicked ENDEAVOR.\p"
    .string "Have you caught one already?$"

