Route8_Text_AidanIntro::
	.string "Walk in front of the trainer at the\n"
	.string "EXACT time they come on screen?\l"
	.string "What were they thinking!?$"

Route8_Text_AidanDefeat::
	.string "What a shitload of fuck!\n$"

Route8_Text_AidanPostBattle::
	.string "And get this:\n"
	.string "That's the ONLY way to get MEW.\p"
	.string "How the fuck are kids supposed to\n"
	.string "figure that out?\l"
	.string "Especially before the INTERNET!$"

Route8_Text_StanIntro::
    .string "All right!\n"
    .string "Let's play a game!$"

Route8_Text_StanDefeat::
    .string "Drat!\n"
    .string "Came up short!$"

Route8_Text_StanPostBattle::
    .string "Things didn't work today.$"

Route8_Text_GlennIntro::
	.string "Brr...!\n"
	.string "It's cold!\p"
	.string "I sure am glad that I'm pants!\n$"

Route8_Text_GlennDefeat::
	.string "Aah!\n"
	.string "I've been ripped!$"

Route8_Text_GlennPostBattle::
	.string "I'm warm and fuzzy, perfect for\n"
	.string "keeping out that winter chill!$"

Route8_Text_PaigeIntro::
    .string "I like NIDORAN, so I collect them!$"

Route8_Text_PaigeDefeat::
    .string "Why?\n"
    .string "Why??$"

Route8_Text_PaigePostBattle::
    .string "When POKéMON grow up, they get\n"
    .string "ugly! They shouldn't evolve.$"

Route8_Text_LeslieIntro::
    .string "School is fun, but so are POKéMON.$"

Route8_Text_LeslieDefeat::
    .string "You made it clear to me that\n"
    .string "I should stick with school.$"

Route8_Text_LesliePostBattle::
    .string "I was planning on getting some\n"
    .string "fresh air for a change, but…\p"
    .string "We're stuck here because of the\n"
    .string "gates at SAFFRON.$"

Route8_Text_AndreaIntro::
    .string "MEOWTH is so cute, meow, meow,\n"
    .string "meow!$"

Route8_Text_AndreaDefeat::
    .string "Meeeeyow!$"

Route8_Text_AndreaPostBattle::
    .string "I think PIDGEY and RATTATA are\n"
    .string "cute, too!$"

Route8_Text_MeganIntro::
    .string "We must look silly standing here\n"
    .string "like this.$"

Route8_Text_MeganDefeat::
    .string "Look what you did to my poor, cute\n"
    .string "POKéMON!$"

Route8_Text_MeganPostBattle::
    .string "SAFFRON's gatekeeper won't let us\n"
    .string "go through.\p"
    .string "I know he's doing his job, but I\n"
    .string "think he's mean.$"

Route8_Text_RichIntro::
    .string "I'm a rambling, gaming dude!$"

Route8_Text_RichDefeat::
    .string "Missed the big chance!$"

Route8_Text_RichPostBattle::
    .string "Playing games and POKéMON are like\n"
    .string "eating peanuts! I just can't stop!$"

Route8_Text_JuliaIntro::
    .string "What's a cute, round, and fluffy\n"
    .string "POKéMON?$"

Route8_Text_JuliaDefeat::
    .string "Owie!$"

Route8_Text_JuliaPostBattle::
    .string "I read that CLEFAIRY evolves when\n"
    .string "it's exposed to a MOON STONE.\p"
    .string "I read that in a POKéMON JOURNAL.\n"
    .string "I wonder if it's true?$"

Route8_Text_UndergroundPathSign::
    .string "UNDERGROUND PATH\n"
    .string "CELADON CITY - LAVENDER TOWN$"

Route8_Text_EliIntro::
	.string "ELI: I wish that man over there\n"
	.string "would leave us alone…$"

Route8_Text_EliDefeat::
    .string "ELI: But…\n"
    .string "We used our twin power…$"

Route8_Text_EliPostBattle::
    .string "ELI: I caught my POKéMON with\n"
    .string "ANNE!$"

Route8_Text_EliNotEnoughMons::
    .string "ELI: We can't battle if you don't\n"
    .string "have two POKéMON.$"

Route8_Text_AnneIntro::
	.string "ELI: I wish that man over there\n"
	.string "would leave us alone…$"

Route8_Text_AnneDefeat::
    .string "ANNE: Our twin power…$"

Route8_Text_AnnePostBattle::
    .string "ANNE: I'm raising POKéMON with\n"
    .string "ELI.$"

Route8_Text_AnneNotEnoughMons::
    .string "ANNE: Hi, hi! Let's battle!\n"
    .string "But bring two POKéMON.$"

Route8_Text_RicardoIntro::
	.string "UGH.\p"
	.string "NO ONE UNDERSTANDS ME.\n$"

Route8_Text_RicardoDefeat::
	.string "I HATE EVERYTHING.\n$"

Route8_Text_RicardoPostBattle::
	.string "This infinite storm represents my\n"
	.string "unending pain and suffering.$"

Route8_Text_JarenIntro::
	.string "Yo wait, you found CUT?\p"
	.string "Could you help get me out of here?\n$"

Route8_Text_JarenDefeat::
	.string "Aww, man…\n$"

Route8_Text_JarenPostBattle::
	.string "I've been stuck in here for weeks.\p"
	.string "I can't figure out how to get CUT\n"
	.string "in this hack.\l"
	.string "Maybe I evolved my EXEGGCUTE wrong?$"
