CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
	.string "Goodness sakes!\p"
	.string "I'm trying to buy a POKé DOLL\n"
	.string "for my girlfriend, but these\l"
	.string "prices are insane!$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
	.string "Evolutionary stones, huh?\p"
	.string "I get the feeling that they can\n"
	.string "evolve an EEVEE.\p"
	.string "Question is, which one\n"
	.string "will I use?\l"
	.string "FIRE STONE, WATER STONE…$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
	.string "Express yourself with gifts!\n"
	.string "4F: ELEMENTAL STONES\p"
	.string "OUR RECOMMENDATION:\p"
	.string "3 WATER STONES\n"
	.string "1 LEAF STONE\l"
	.string "1 SUN STONE\l"
	.string "3 DAWN STONES$"
