ViridianCity_House_Text_NicknamingIsFun::
    .string "Coming up with nicknames is fun.\p"
    .string "I'm very creative when I do it.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "SHIT, I: My daddy is weird about\n"
    .string "names.\p"
    .string "He insists that it's very clever,\n"
    .string "but everyone makes fun of me…\p"

ViridianCity_House_Text_Speary::
    .string "SPEAROWNOLACTONE: Tetweet!\p"
    .string "SPEAROWNOLACTONE lowered its PP!$"

