name: CI

on:
  push:
    branches:
      - master
      - beta
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERSION: FIRERED
      GAME_LANGUAGE: ENGLISH
      GAME_REVISION: 0
      MODERN: 0
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout agbcc
        uses: actions/checkout@v2
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y build-essential libpng-dev libelf-dev
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: ./agbcc

      - name: Poryscript download
        uses: robinraju/release-downloader@v1
        with:
          repository: 'huderlem/poryscript'
          latest: true
          fileName: 'poryscript-linux.zip'
          extract: true
          out-file-path: 'tools'

      - name: Poryscript install
        run: |
          sudo mv tools/poryscript-linux/poryscript tools/poryscript/
          sudo mv tools/poryscript-linux/font_config.json tools/poryscript/
          sudo chmod +x tools/poryscript/poryscript
          sudo rm -rf tools/poryscript-linux.zip
          sudo rm -rf tools/poryscript-linux

      - name: Build with agbcc
        run: make -j${nproc} -O all
