name: CI

on:
  push:
    branches:
      - beta
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERSION: FIRERED
      GAME_LANGUAGE: ENGLISH
      GAME_REVISION: 0
      MODERN: 0
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout agbcc
        uses: actions/checkout@master
        with:
          path: 'agbcc'
          repository: 'pret/agbcc'

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: ./agbcc

      - name: Poryscript download
        uses: robinraju/release-downloader@v1
        with:
          repository: 'huderlem/poryscript'
          latest: true
          fileName: 'poryscript-linux.zip'
          extract: true
          out-file-path: 'tools'

      - name: Poryscript install
        run: |
          sudo mv tools/poryscript-linux tools/poryscript
          sudo chmod +x tools/poryscript/poryscript

      - name: Build with agbcc
        run: make -j${nproc} -O all
