ThreeIsland_BerryForest_Text_HelpScaryPokemon::
	.string "LOSSELLE: Whimper… Sniff…\n"
	.string "Oh! Please, help!\p"
	.string "A scary POKéMON appeared there\n"
	.string "a little while ago.\p"
	.string "I keep seeing it everywhere.\n"
	.string "It makes LOSSELLE scared.\p"
	.string "I'm too scared to move!\n"
	.string "But I want to go home…$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "Oh! Here it comes again!\n"
    .string "No! Go away! It's scaring me!\p"
    .string "Waaaaaaah!\n"
    .string "I want my daddy!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
	.string "Ohh! That was so scary!\n"
	.string "Thank you!\p"
	.string "Everywhere I go, LOSSELLE sees\n"
	.string "the same patterns…\p"
	.string "They're following me everywhere!\n$"

ThreeIsland_BerryForest_Text_LetsGoHome::
	.string "Okay, LOSSELLE isn't scared\n"
	.string "anymore.\p"
	.string "I'm gonna stay here and play\n"
	.string "some more.\l"
	.string "You can tell my daddy I'm safe.$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "Your BERRY POUCH is full.\n"
    .string "I guess you don't want this.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "Welcome to the BERRY FOREST\p"
    .string "Be friendly and share BERRIES with\n"
    .string "others and POKéMON.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "Beware of wild, BERRY-loving\n"
    .string "POKéMON!$"

