CeladonCity_Hotel_Text_ThisHotelIsForPeople::
	.string "Erm, hello.\n"
	.string "How did you get back here?\p"
	.string "Actually, that doesn't matter.\p"
	.string "Could you please, uh, leave?\n$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .string "I'm on vacation with my brother and\n"
    .string "boyfriend.\p"
    .string "CELADON is such a pretty city!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
	.string "I'm the most tragic NPC in the\n"
	.string "game...$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .string "Yippee! I'm on vacation!\n"
    .string "My sis brought me along! Awesome!$"

